Edit route geometry
HSLdevcom/jore4-ui pull request #102
Opened 2022-02-25 07:26 UTC by eleksi

- Implement editing existing routes' geometry
- Route can be opened in map view and by clicking "Edit" the route can be edited
- A line consisting of "handles" or anchor points will appear in the map. Handles can be moved, deleted and new ones added to shape the route geometry
- Handle deletion works by first selecting a handle or handles by clicking (deselecting by clicking again) and then hitting backspace or delete key. Handles can be deleted as long as there remains at least to handles after deletion
- All stops on the route will be picked to the journey pattern (selection to be implemented later)

Resolves https://github.com/HSLdevcom/jore4/issues/473

2022-02-25 07:44 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @eleksi and @pallost)

___
*[package.json, line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwjmTcSE9RPDtCRBdKA:-MwjmTcT8MEky37EpE57:b-1ch33i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f20898ab23d8c75267b95d001649d62891f2093d/package.json#L27)):*
> ```JSON
>     "@headlessui/react": "^1.0.0",
>     "@hookform/resolvers": "^2.8.3",
>     "@nebula.gl/edit-modes": "^1.0.2-alpha.2",
> ```

let's avoid using alpha versions. Is the version 1.0.1 stable and include everything you need...?
___
*[src/api/routing.ts, line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwjmoh1-B4lLdOyzBUh:-Mwjmoh1-B4lLdOyzBUi:b-twb9vn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f20898ab23d8c75267b95d001649d62891f2093d/src/api/routing.ts#L10)):*
> ```XML
> const getBus = (coordinates: string) => apiClient.get(`/bus/${coordinates}`);
> 
> export interface Geometry {
> ```

there's already a built-in type for this, already available from another package: `GeoJSON.LineString`
___
*[src/components/map/DrawRouteLayer.tsx, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwjn5Rr7cHjWAq5P8vl:-Mwjn5Rr7cHjWAq5P8vm:b-mjkmdy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f20898ab23d8c75267b95d001649d62891f2093d/src/components/map/DrawRouteLayer.tsx#L8)):*
> ```XML
> } from '@nebula.gl/edit-modes';
> import composeRefs from '@seznam/compose-react-refs';
> import { remove } from 'lodash';
> ```

`import remove from 'lodash/remove'`
___
*[src/components/map/DrawRouteLayer.tsx, line 64 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwjn_LX-9AK8OXUaNLs:-Mwjn_LX-9AK8OXUaNLt:b-79gg0b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f20898ab23d8c75267b95d001649d62891f2093d/src/components/map/DrawRouteLayer.tsx#L64)):*
> ```XML
> ): Feature[] => {
>   if (!infraLinks || infraLinks.length === 0) return [];
>   return [
> ```

let's split this function to a few steps:

```
const coordinates = infraLinks.flatMap(...); // no need for `?` assertion as you already have the check above
const features: Feature[] = [mapGeoJSONtoFeature({type: LineString, coordinates})] // we already have a mapping function for wrapping stuff into features
```

maybe you could also consider creating a `mapCoordinatesToLineString` or similar wrapper
___
*[src/components/map/DrawRouteLayer.tsx, line 73 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwjoVfk2J8ee6Dzk1oh:-MwjoVfk2J8ee6Dzk1oi:b-59upho) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f20898ab23d8c75267b95d001649d62891f2093d/src/components/map/DrawRouteLayer.tsx#L73)):*
> ```XML
>           let linkCoordinates = link.shape.coordinates;
> 
>           // Order coordinates properly
> ```

nicely commented!


<!-- Sent from Reviewable.io -->

2022-02-25 08:37 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 0 of 16 files reviewed, 5 unresolved discussions (waiting on @pallost)

___
*[package.json, line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwjmTcSE9RPDtCRBdKA:-MwjqwlMChzLCLEjEuJg:bcbzr9r) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f20898ab23d8c75267b95d001649d62891f2093d/package.json#L27)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's avoid using alpha versions. Is the version 1.0.1 stable and include everything you need...?
</blockquote></details>

Right, earlier non alpha version should have all we need. I just installed the latest and didn't pay attention to it being alpha version.
___
*[src/api/routing.ts, line 10 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwjmoh1-B4lLdOyzBUh:-MwjrWd2AK05Zw9Iwtyu:b-72j678) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f20898ab23d8c75267b95d001649d62891f2093d/src/api/routing.ts#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

there's already a built-in type for this, already available from another package: `GeoJSON.LineString`
</blockquote></details>

This type was already there, but I guess I could use the type provided by the package.
___
*[src/components/map/DrawRouteLayer.tsx, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwjn5Rr7cHjWAq5P8vl:-Mwk0OFP3WSIAg6KvvSL:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f20898ab23d8c75267b95d001649d62891f2093d/src/components/map/DrawRouteLayer.tsx#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`import remove from 'lodash/remove'`
</blockquote></details>

Done.
___
*[src/components/map/DrawRouteLayer.tsx, line 64 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwjn_LX-9AK8OXUaNLs:-Mwk0W53AZMNxWsLp19b:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f20898ab23d8c75267b95d001649d62891f2093d/src/components/map/DrawRouteLayer.tsx#L64)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's split this function to a few steps:

```
const coordinates = infraLinks.flatMap(...); // no need for `?` assertion as you already have the check above
const features: Feature[] = [mapGeoJSONtoFeature({type: LineString, coordinates})] // we already have a mapping function for wrapping stuff into features
```

maybe you could also consider creating a `mapCoordinatesToLineString` or similar wrapper
</blockquote></details>

Done.
___
*[src/components/map/DrawRouteLayer.tsx, line 73 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwjoVfk2J8ee6Dzk1oh:-Mwk0Wa_6edJcR4tc0Rn:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f20898ab23d8c75267b95d001649d62891f2093d/src/components/map/DrawRouteLayer.tsx#L73)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

nicely commented!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-25 11:28 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 0 of 16 files reviewed, 6 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/map/DrawRouteLayer.tsx, line 103 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwka9cE31cysuDAxw5x:-Mwka9cE31cysuDAxw5y:b-btqbdw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/DrawRouteLayer.tsx#L103)):*
> ```XML
>   } = useContext(MapEditorContext);
> 
>   const [features, setFeatures] = useState<LineStringFeature[]>();
> ```

"feature" is a bit too generic term here, let's rather use something else, like "route", "path" or similar
___
*[src/components/map/DrawRouteLayer.tsx, line 104 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwk_k269ZgejUBZ72N4:-Mwk_k269ZgejUBZ72N5:b-g9ril9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/DrawRouteLayer.tsx#L104)):*
> ```XML
> 
>   const [features, setFeatures] = useState<LineStringFeature[]>();
>   const [selectedHandles, setSelectedHandles] = useState<number[]>([]);
> ```

in our terms, these have been "snap points". "Handle" is a quite generic term. You could also use a better typing here... e.g.:
`const [selectedSnapPoints, setSelectedSnapPoints] = useState<Position>([])`
___
*[src/components/map/ModalMap.tsx, line 74 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwkb3jF1HPgtFrZ5f-Y:-Mwkb3jF1HPgtFrZ5f-Z:b-p6x89t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/ModalMap.tsx#L74)):*
> ```XML
>   const onSave = async () => {
>     const {
>       busRoute,
> ```

this function has grown huuuuuge. It's getting quite out of control... Let's refactor it to its own hook! And split into multiple little functions.

Here's an example how I did a hook that can create new bus stop or edit an existing one: https://github.com/HSLdevcom/jore4-ui/blob/fix-bus-stop-editing/src/hooks/useEditStop.ts

with this:
- you can build the data that will be edited/inserted in graphql
- the changes are presented in a way that can be read by the user on the UI later on
- the changes are validated
___
*[src/hooks/useShowRoutesOnModal.ts, line 36 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwkcHWr7_DbYM2XSm0Y:-MwkcHWr7_DbYM2XSm0Z:bexltkg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/hooks/useShowRoutesOnModal.ts#L36)):*
> ```XML
>   const showRoutesOnModal = (routeIds: UUID[]) => {
>     fetchRouteDetails({ route_ids: routeIds }).then((results) => {
>       const routes = mapRoutesDetailsResult(results);
> ```

this function is doing too much, should split the mappings to their own functions
___
*[src/locales/en-US/common.json, line 104 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwkcaFu8XuyC-5UDz4a:-MwkcaFu8XuyC-5UDz4b:be3acg0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/locales/en-US/common.json#L104)):*
> ```JSON
>   "errors": {
>     "saveFailed": "Something went wrong",
>     "leaveMultipleHandles": "Deletion unsuccessful! Please leave at least two points!"
> ```

Isn't it more like: "Cannot delete snap point, should leave at least 2"?


<!-- Sent from Reviewable.io -->

2022-02-25 12:21 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 0 of 16 files reviewed, 7 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/map/DrawRouteLayer.tsx, line 138 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwkoAIh484Z_jtk0qiK:-MwkoAIh484Z_jtk0qiL:bunxdds) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/DrawRouteLayer.tsx#L138)):*
> ```XML
>   >(MapExternalLinkIdsToInfraLinksWithStopsDocument);
> 
>   const onAddRoute = useCallback(
> ```

this name keeps on confusing me... is `onDisplayRoutes` closer to reality...?
___
*[src/hooks/useShowRoutesOnModal.ts, line 35 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwkkBsCAf6NBgwSPNqW:-MwkkBsCAf6NBgwSPNqX:b9ti9sk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/hooks/useShowRoutesOnModal.ts#L35)):*
> ```XML
> 
>   const showRoutesOnModal = (routeIds: UUID[]) => {
>     fetchRouteDetails({ route_ids: routeIds }).then((results) => {
> ```

I just noticed this now: let's use async-await instead of .then()


<!-- Sent from Reviewable.io -->

2022-02-28 08:46 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 0 of 18 files reviewed, 7 unresolved discussions (waiting on @pallost)

___
*[src/components/map/DrawRouteLayer.tsx, line 103 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwka9cE31cysuDAxw5x:-MwzF0eQ68kA2TLXAMAC:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/DrawRouteLayer.tsx#L103)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

"feature" is a bit too generic term here, let's rather use something else, like "route", "path" or similar
</blockquote></details>

Done.
___
*[src/components/map/DrawRouteLayer.tsx, line 104 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwk_k269ZgejUBZ72N4:-MwzEHsJCKpXB1iSXx82:b-5d0by8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/DrawRouteLayer.tsx#L104)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

in our terms, these have been "snap points". "Handle" is a quite generic term. You could also use a better typing here... e.g.:
`const [selectedSnapPoints, setSelectedSnapPoints] = useState<Position>([])`
</blockquote></details>

I don't know what advantage would using Position as a type here bring. We get the selection as index and can easily delete them by index.
___
*[src/components/map/DrawRouteLayer.tsx, line 138 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwkoAIh484Z_jtk0qiK:-MwzE_O61cIaXtmpEeHU:brrkn6n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/DrawRouteLayer.tsx#L138)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this name keeps on confusing me... is `onDisplayRoutes` closer to reality...?
</blockquote></details>

Yes, maybe it should be renamed.
___
*[src/components/map/ModalMap.tsx, line 74 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwkb3jF1HPgtFrZ5f-Y:-MwzRL9T6_ozPTkQJZz4:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/ModalMap.tsx#L74)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this function has grown huuuuuge. It's getting quite out of control... Let's refactor it to its own hook! And split into multiple little functions.

Here's an example how I did a hook that can create new bus stop or edit an existing one: https://github.com/HSLdevcom/jore4-ui/blob/fix-bus-stop-editing/src/hooks/useEditStop.ts

with this:
- you can build the data that will be edited/inserted in graphql
- the changes are presented in a way that can be read by the user on the UI later on
- the changes are validated
</blockquote></details>

Done.
___
*[src/hooks/useShowRoutesOnModal.ts, line 35 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwkkBsCAf6NBgwSPNqW:-MwzSlhM4_viVikvV36P:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/hooks/useShowRoutesOnModal.ts#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I just noticed this now: let's use async-await instead of .then()
</blockquote></details>

Done.
___
*[src/hooks/useShowRoutesOnModal.ts, line 36 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwkcHWr7_DbYM2XSm0Y:-MwzU_aF6LIJLxt6s0M4:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/hooks/useShowRoutesOnModal.ts#L36)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this function is doing too much, should split the mappings to their own functions
</blockquote></details>

Done.
___
*[src/locales/en-US/common.json, line 104 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-MwkcaFu8XuyC-5UDz4a:-MwzV9XdER-SBHNPNgFu:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/locales/en-US/common.json#L104)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Isn't it more like: "Cannot delete snap point, should leave at least 2"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-28 11:41 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 0 of 18 files reviewed, 8 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/context/MapEditorReducer.ts, line 26 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx-7PGR9tKrLND1ZSwZ:-Mx-7PGS38qxB2GETxzv:b-6zo9l3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52e4409f6781d9ca11d405a3fc60096dfc7f6dbf/src/context/MapEditorReducer.ts#L26)):*
> ```XML
>   infraLinksAlongRoute: Map<UUID | null, InfrastructureLinkAlongRoute[]>;
> }
> ```

editedRouteData: {
  id: UUID;
  metadata: RouteFormState;
  stopIds: UUID[];
  infraLinks: InfraLinks[];
}


<!-- Sent from Reviewable.io -->

2022-02-28 11:53 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 0 of 18 files reviewed, 8 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/context/MapEditorReducer.ts, line 26 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx-7PGR9tKrLND1ZSwZ:-Mx-AIdK0NQA5P9HdhFj:b-6ohdp3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52e4409f6781d9ca11d405a3fc60096dfc7f6dbf/src/context/MapEditorReducer.ts#L26)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

editedRouteData: {
  id: UUID;
  metadata: RouteFormState;
  stopIds: UUID[];
  infraLinks: InfraLinks[];
}
</blockquote></details>

infraLinks: UUID[]; ?


<!-- Sent from Reviewable.io -->

2022-03-02 12:49 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 0 of 19 files reviewed, 10 unresolved discussions (waiting on @eleksi and @pallost)

___
*[src/components/map/DrawRouteLayer.tsx, line 88 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9Uje-972QXQoestDg:-Mx9Uje-972QXQoestDh:b-3shc23) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/DrawRouteLayer.tsx#L88)):*
> ```XML
>   });
> 
>   return [mapGeoJSONtoFeature({ type: 'LineString', coordinates })];
> ```

I don't really understand why this function is returning an array. What this function does is that it takes infra links belonging to a *single* route and turn it into an array of coordinates (=a single linestring). The return type should be rather just `:LineStringFeature`

I'd also move this function rather to e.g. `graphql/infrastructureNetwork.ts` for now as it does not strictly belong to route drawing. Or at least to a separate hook
___
*[src/components/map/DrawRouteLayer.tsx, line 91 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9XYO621zA6VZhku4n:-Mx9XYO621zA6VZhku4o:b-ulp6jr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/DrawRouteLayer.tsx#L91)):*
> ```XML
> };
> 
> const mapGraphQLRouteToInfraLinks = (route: RouteRoute) => {
> ```

the opposite of this function is found from `graphql/infrastructureNetwork.ts` I'd move this function there too
___
*[src/components/map/Stops.tsx, line 168 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9eyRH1R6MaKaorzHw:-Mx9eyRH1R6MaKaorzHx:b-fymx1o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/Stops.tsx#L168)):*
> ```XML
>     // If not editing, show stops along all displayed routes
>     const fetchRoutes = async () => {
>       const routeDetailsResults = await fetchRouteDetails({
> ```

this fetchRouteDetails also has a hook version, no need to use the useEffect + useAsyncQuery version. Can't you just use `useGetRouteWithInfrastructureLinks({route_ids: displayedRouteIds})`?
___
*[src/components/map/Stops.tsx, line 175 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9a-tQBuOJK3YVD2Wg:-Mx9a-tQBuOJK3YVD2Wh:b-jta411) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/Stops.tsx#L175)):*
> ```XML
>       const stopIds = routes.flatMap((route) => getRouteStopIds(route));
> 
>       setStopIdsWithingRoute(stopIds);
> ```

typo: setStopIdsWithinRoute
___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 31 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9_WDCA8G8_xWf3aDC:-Mx9_WDCA8G8_xWf3aDD:b-dam23x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/routes-and-lines/EditRoutePage.tsx#L31)):*
> ```XML
> 
> const mapRouteToRouteDetails = (route: RouteRoute) => ({
>   description_i18n: route.description_i18n || '',
> ```

the name of the function is a bit misleading and is missing the type check for the return value.

```
const mapRouteToFormState = (route: RouteRoute) => {
  const formState: FormState = {...};
  return formState;
};
```  
```

___
*[src/context/MapEditorReducer.ts, line 6 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9_6rg26NlAQHVLS7I:-Mx9_6rg26NlAQHVLS7J:b-fjrvdx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/context/MapEditorReducer.ts#L6)):*
> ```XML
> import { InfrastructureLinkAlongRoute } from '../graphql';
> 
> enableMapSet();
> ```

Please put a comment here that what does this do. Is it actually still needed...?
___
*[src/graphql/route.ts, line 187 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9ZafB4s6wCEz2fQgO:-Mx9ZafB4s6wCEz2fQgP:b-v6y5cz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/graphql/route.ts#L187)):*
> ```XML
> 
> const GET_ROUTES_WITH_INFRASTRUCTURE_LINKS = gql`
>   query GetRouteWithInfrastructureLinks($route_ids: [uuid!]) {
> ```

GetRoute*s*WithInfrastructureLinks. Your parameter is an array...
___
*[src/graphql/route.ts, line 251 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9Sk8j7EKfON_tD6uT:-Mx9Sk8j7EKfON_tD6uU:bq6alwn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/graphql/route.ts#L251)):*
> ```XML
> 
> const UPDATE_ROUTE_GEOMETRY = gql`
>   mutation UpdateRouteGeometry(
> ```

wow, this is quite a query... I'm a bit concerned that deleting all infra links and then reinserting the new ones will cause problems in the future. Same with the journey pattern... but we'll fix it later on if that's the case... 
___
*[src/hooks/useEditRouteGeometry.ts, line 21 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9ZGaaANw9qjfB1NkV:-Mx9ZGaaANw9qjfB1NkW:b-8o3ash) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/hooks/useEditRouteGeometry.ts#L21)):*
> ```XML
> 
> export const useEditRouteGeometry = () => {
>   const [insertRouteMutation] = useInsertRouteOneMutation();
> ```

this is much nicer, now that at least the graphql calls are refactored here. It'd be awesome if also the whole business logic from DrawRouteLayer would be shoveled here, because that layer is still super bloated... Well, maybe in the future...
___
*[src/hooks/useEditRouteGeometry.ts, line 75 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9YylyEDOXKv16joJO:-Mx9YylyEDOXKv16joJP:b2ey88z) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/hooks/useEditRouteGeometry.ts#L75)):*
> ```XML
>     finalStopId: UUID,
>   ) => {
>     const variables = mapToVariables({
> ```

should do the type checking here:
```
const variables: UpdateMutationVariables = {route_id:...};
return mapToVariables(variables);
```


<!-- Sent from Reviewable.io -->

2022-03-02 12:49 UTC, jarkkoka reviewed
> Reviewed 1 of 12 files at r1, 3 of 7 files at r3, 1 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 5 of 19 files reviewed, 11 unresolved discussions (waiting on @eleksi, @jarkkoka, and @pallost)

___
*[src/components/map/DrawRouteLayer.tsx, line 103 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwka9cE31cysuDAxw5x:-Mx9eNdR6tNe3pGRmm2E:b-3hi717) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/DrawRouteLayer.tsx#L103)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

BTW, "Feature" has a specific meaning in GeoJSON. When dealing with GeoJSON it is not a generic term.
___
*[src/components/map/DrawRouteLayer.tsx, line 104 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwk_k269ZgejUBZ72N4:-Mx9eiQpBV4nnM8VsBRm:bk7zybr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/DrawRouteLayer.tsx#L104)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I don't know what advantage would using Position as a type here bring. We get the selection as index and can easily delete them by index.
</blockquote></details>

Yeah. It is good to use common vocabulary. "Snap" is commonly used term in map-matching even outside Jore4 context.
___
*[src/components/map/DrawRouteLayer.tsx, line 72 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9dibT9dAGue4gQHf4:-Mx9dibT9dAGue4gQHf5:b-ab4qxh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/DrawRouteLayer.tsx#L72)):*
> ```XML
>     // Order coordinates properly
>     if (linkCoordinates.length > 0 && !link.isTraversalForwards) {
>       linkCoordinates = [...linkCoordinates].reverse();
> ```

Could add TODO comment that reversing LineString could be optimised out since anyway only the first and last coordinate are used (see the next lines in code). `isTraversalForwards` property will then be used in determining how to order first and last coordinate.



_Code quote:_
```XML
linkCoordinates = [...linkCoordinates].reverse();
```


<!-- Sent from Reviewable.io -->

2022-03-02 13:09 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 5 of 19 files reviewed, 13 unresolved discussions (waiting on @eleksi, @jarkkoka, and @pallost)

___
*[src/components/map/DrawRouteLayer.tsx, line 256 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9jXnxAkEy6Vc7aWBV:-Mx9jXnxAkEy6Vc7aWBW:bhxnmqq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/DrawRouteLayer.tsx#L256)):*
> ```XML
> 
>   useEffect(() => {
>     const updateFeatures = async () => {
> ```

instead of using useEffect + fetchRouteDetails, you could just use the original hook version: useGetRoutesWithInfraLinksQuery({editedRouteData.id})
___
*[src/components/map/Stops.tsx, line 45 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9iBqnBBntdN0xNldh:-Mx9iBqnBBntdN0xNldi:b-y8ej8a) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/Stops.tsx#L45)):*
> ```XML
> 
> const getRouteStopIds = (route: RouteRoute) => {
>   return route.route_journey_patterns[0].scheduled_stop_point_in_journey_patterns.map(
> ```

this is fine for now but we (including me :P) should learn to write graphql queries that are actually fetching data that we need. Here you were e.g. fetching all the routes' details and then digging deep into the data structure to get only its stops. Would be much simpler to turn this upside down and fetch scheduled stops points which have a route_id as ...


<!-- Sent from Reviewable.io -->

2022-03-02 14:26 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 5 of 19 files reviewed, 12 unresolved discussions (waiting on @jarkkoka and @pallost)

___
*[src/components/map/DrawRouteLayer.tsx, line 103 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mwka9cE31cysuDAxw5x:-Mx9jYXZ7qgd2e3hpCVE:bdri3iv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b33122e7c04eaae626644e25ed235fcd9bc8f9bc/src/components/map/DrawRouteLayer.tsx#L103)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

BTW, "Feature" has a specific meaning in GeoJSON. When dealing with GeoJSON it is not a generic term.
</blockquote></details>

I already renamed it to routeFeatures, some kind of compromise.
___
*[src/components/map/DrawRouteLayer.tsx, line 72 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9dibT9dAGue4gQHf4:-MxA-ujg1FdeZUou9y6e:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/DrawRouteLayer.tsx#L72)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Could add TODO comment that reversing LineString could be optimised out since anyway only the first and last coordinate are used (see the next lines in code). `isTraversalForwards` property will then be used in determining how to order first and last coordinate.
</blockquote></details>

Done.
___
*[src/components/map/DrawRouteLayer.tsx, line 88 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9Uje-972QXQoestDg:-Mx9hiAuENkFdLBKHKVI:b-ghs9rr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/DrawRouteLayer.tsx#L88)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I don't really understand why this function is returning an array. What this function does is that it takes infra links belonging to a *single* route and turn it into an array of coordinates (=a single linestring). The return type should be rather just `:LineStringFeature`

I'd also move this function rather to e.g. `graphql/infrastructureNetwork.ts` for now as it does not strictly belong to route drawing. Or at least to a separate hook
</blockquote></details>

routeFeatures holds the state of Editor's features. This function pretty much just converts infra links to an array that can be directly given to Editor. Of course we can make this return only a single instance, and then make the result an array, as I have now done.
___
*[src/components/map/DrawRouteLayer.tsx, line 91 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9XYO621zA6VZhku4n:-MxA03ozAkQBk6TwGzCU:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/DrawRouteLayer.tsx#L91)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the opposite of this function is found from `graphql/infrastructureNetwork.ts` I'd move this function there too
</blockquote></details>

Done.
___
*[src/components/map/DrawRouteLayer.tsx, line 256 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9jXnxAkEy6Vc7aWBV:-Mx9pr9z9m3sjAM1NzXW:b6tvtmb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/DrawRouteLayer.tsx#L256)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

instead of using useEffect + fetchRouteDetails, you could just use the original hook version: useGetRoutesWithInfraLinksQuery({editedRouteData.id})
</blockquote></details>

Sure, still getting use to these handy query hooks.
___
*[src/components/map/Stops.tsx, line 45 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9iBqnBBntdN0xNldh:-Mx9p_oqEX278Pf_TxkL:b-gdxwsz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/Stops.tsx#L45)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is fine for now but we (including me :P) should learn to write graphql queries that are actually fetching data that we need. Here you were e.g. fetching all the routes' details and then digging deep into the data structure to get only its stops. Would be much simpler to turn this upside down and fetch scheduled stops points which have a route_id as ...
</blockquote></details>

Good point. It is easy to be lazy and use old queries. I will think about it more in the future.
___
*[src/components/map/Stops.tsx, line 168 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9eyRH1R6MaKaorzHw:-Mx9nkIUAKCDfYbyMjtp:b-80tlqx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/Stops.tsx#L168)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this fetchRouteDetails also has a hook version, no need to use the useEffect + useAsyncQuery version. Can't you just use `useGetRouteWithInfrastructureLinks({route_ids: displayedRouteIds})`?
</blockquote></details>

Sure!
___
*[src/components/routes-and-lines/EditRoutePage.tsx, line 31 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9_WDCA8G8_xWf3aDC:-Mx9oBGKCFJ9U85Zy1z1:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/routes-and-lines/EditRoutePage.tsx#L31)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the name of the function is a bit misleading and is missing the type check for the return value.

```
const mapRouteToFormState = (route: RouteRoute) => {
  const formState: FormState = {...};
  return formState;
};
```  
```

</blockquote></details>

Done.
___
*[src/context/MapEditorReducer.ts, line 6 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9_6rg26NlAQHVLS7I:-Mx9oGX7DvYBnI7ybP0q:b-5d646u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/context/MapEditorReducer.ts#L6)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Please put a comment here that what does this do. Is it actually still needed...?
</blockquote></details>

Good catch, no longer needed after maps were removed.
___
*[src/graphql/route.ts, line 187 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9ZafB4s6wCEz2fQgO:-Mx9oZBn3ulTSqSrOfxs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/graphql/route.ts#L187)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

GetRoute*s*WithInfrastructureLinks. Your parameter is an array...
</blockquote></details>

Done.
___
*[src/graphql/route.ts, line 251 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9Sk8j7EKfON_tD6uT:-Mx9obUa-CpyGbemrNX9:b-3pucn8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/graphql/route.ts#L251)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

wow, this is quite a query... I'm a bit concerned that deleting all infra links and then reinserting the new ones will cause problems in the future. Same with the journey pattern... but we'll fix it later on if that's the case... 
</blockquote></details>

Yes, have to start somewhere.
___
*[src/hooks/useEditRouteGeometry.ts, line 21 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9ZGaaANw9qjfB1NkV:-Mx9oiJb-UTqBK6Ik0gn:bm9zmbr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/hooks/useEditRouteGeometry.ts#L21)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is much nicer, now that at least the graphql calls are refactored  [...]

2022-03-02 15:52 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/102)* status: 4 of 20 files reviewed, 3 unresolved discussions (waiting on @eleksi, @jarkkoka, and @pallost)

___
*[src/components/map/Stops.tsx, line 168 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/102#-Mx9eyRH1R6MaKaorzHw:-MxAK50t3hka_Gq2nREH:b3u94hb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/dc07fefaff835551d599be29722567888ca3b0f6/src/components/map/Stops.tsx#L168)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this does not need to be in useEffect anymore I think
</blockquote></details>

Right, it can be refactored out of useEffect. If it is ok, I will refactor it in a future pr that edits these lines anyway.


<!-- Sent from Reviewable.io -->

2022-03-03 08:08 UTC, merged