Add search functionality
HSLdevcom/jore4-ui pull request #122
Opened 2022-03-22 11:35 UTC by HenrikHartiala

Adds the search functionality with the results page.

New hooks:
- useToggle
- useSearchQueryParser: parses deserializes and validates the query string in to search parameter object
- useSearch: stores the search conditions and handles the tranformation calls from search conditions and filters object in to query parameter string.
- useSearchResults: handles the GraphQL call and filtering for result lines / routes / resultCount

Utils:
- search.ts: has implementation for the query parameter string creator and the GqlFilterObject constructor

Components:
Folderstructure here is:
- routes-and-lines
  - search
    - conditions: Components that are related to search conditions (applies to GQL)
    - filters: Components that are related to live filtering, currently only one live filter (ResultsSelector).
    - results: Components that are related to displaying results

2022-03-22 12:42 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122)* status: 0 of 23 files reviewed, 7 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[src/components/RoutesAndLinesPage.tsx, line 17 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylbmn94VrR1uaeIzV2:-Mylbmn94VrR1uaeIzV3:b-fjbyom) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/RoutesAndLinesPage.tsx#L17)):*
> ```XML
> import { RoutesResultTable } from './routes-and-lines/search/results/RoutesResultTable'; // eslint-disable-line import/no-cycle
> 
> const RouteResults = () => {
> ```

I wouldn't call this RouteResults as these are actually not a result of any search. How about `RouteList` or something similar?
___
*[src/components/RoutesAndLinesPage.tsx, line 26 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylbgSuEatncKhhdpdI:-MylbgSv7yquAAXXpycE:b-jwv0eo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/RoutesAndLinesPage.tsx#L26)):*
> ```XML
> 
>   return (
>     <>
> ```

let's rather wrap this into a `<div>` instead of a fragment
___
*[src/components/RoutesAndLinesPage.tsx, line 30 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylbEAtBJxF8O9jkc9e:-MylbEAtBJxF8O9jkc9f:b-dm220d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/RoutesAndLinesPage.tsx#L30)):*
> ```XML
>         {t('routes.changingRoutes')}
>       </h2>
>       <RoutesResultTable routes={changingRoutes} />
> ```

I think this will cause a linter error as `changingRoutes` is undefined before the response arrives. Should wrap it into `{chagingRoutes && changingRoutes.length > 0 && <RoutesResultTable.../>}`
Same with `ownLines`
___
*[src/components/routes-and-lines/search/CloseButton.tsx, line 3 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylcbjG9tu-PAMbk9n7:-MylcbjG9tu-PAMbk9n8:bld9tp4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/CloseButton.tsx#L3)):*
> ```XML
> import { useTranslation } from 'react-i18next';
> 
> export const CloseButton = ({ onClose }: { onClose: () => void }) => {
> ```

this looks like a more reusable ui component, you could even move it to the `./uiComponents` directory
___
*[src/components/routes-and-lines/search/CloseButton.tsx, line 8 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylcnYW8ly4POF6ZcqI:-MylcnYW8ly4POF6ZcqJ:b-z0oac5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/CloseButton.tsx#L8)):*
> ```XML
>   return (
>     <button
>       className="ml-auto text-base font-bold text-brand"
> ```

this button could/should have an extensible `className` that comes from the components props: `<button className={`${props.className} ml-auto text-base...`}/>` It would allow the user to place this button into a context and set margins for it
___
*[src/components/routes-and-lines/search/CloseButton.tsx, line 8 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myld9MlE_YkMVW8tzdD:-Myld9MlE_YkMVW8tzdE:b-kxra47) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/CloseButton.tsx#L8)):*
> ```XML
>   return (
>     <button
>       className="ml-auto text-base font-bold text-brand"
> ```

`ml-auto` is not a component-specific css attribute, it's context-specific. It should be rather set from the outside: `<CloseButton className="ml-auto" onClose="..."/>`
___
*[src/components/routes-and-lines/search/SearchResultPage.tsx, line 22 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylcCt6BvP0LVN27_qM:-MylcCt72al0tx0Q03Iq:b-fo4cx6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/SearchResultPage.tsx#L22)):*
> ```XML
>       <Row className="h-12">
>         <h1 className="text-2xl font-bold">
>           {t('search.searchResultsTitle')} | {t('routes.routes')}
> ```

this may end up being wrapped wrong thus losing a whitespace. Let's rather build it as a whole template string:
{`${t('search...')} | ${t('routes...')}`}


<!-- Sent from Reviewable.io -->

2022-03-22 13:08 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122)* status: 0 of 23 files reviewed, 19 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[src/components/routes-and-lines/search/conditions/PriorityCondition.tsx, line 34 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyldzDU9Wtyuta_iaGi:-MyldzDU9Wtyuta_iaGj:bjq288i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/PriorityCondition.tsx#L34)):*
> ```XML
>     );
>   };
>   const PriorityStandardButton = () =>
> ```

you could simplify this by receiving priority and label as props:
```
const PriorityButton: React.FC<{priority: Priority, label: string, onClick: () => void}> = ({priority, label, onClick}) => {...}
```

I would also prefer if the component wasn't defined within the other component but nicely separated instead. It's not worth merging these just to save a few onClickPriority calls
___
*[src/components/routes-and-lines/search/conditions/SearchBarContainer.tsx, line 23 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylfUsa-dNkJzExxWy9:-MylfUsa-dNkJzExxWyA:b-je3qus) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchBarContainer.tsx#L23)):*
> ```XML
>   return (
>     <Row className="justify-center bg-background py-4">
>       <Column className=" w-2/4">
> ```

unnecessary whitespace
___
*[src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx, line 17 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylfvDD1KK-NnEVbtcO:-MylfvDD1KK-NnEVbtcP:bjevz71) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx#L17)):*
> ```XML
>         <IconButton
>           onClick={onClick}
>           icon={<FaChevronUp className="text-3xl text-tweaked-brand" />}
> ```

you could have the ternary operator within the icon property instead to have less things copy-pasted:
```
icon={isToggled ? <FaChevronUp ...> : <FaChevronDown>}
```
___
*[src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx, line 18 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylfkwb6yrrNlJ9SZme:-Mylfkwb6yrrNlJ9SZmf:blivsv2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx#L18)):*
> ```XML
>           onClick={onClick}
>           icon={<FaChevronUp className="text-3xl text-tweaked-brand" />}
>           testId="RoutesTableRow::showRoute"
> ```

testId="SearchConditionToggle::toggle"
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 10 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylgi-w9waAZNDrFRKB:-Mylgi-w9waAZNDrFRKC:bt8s0bs) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L10)):*
> ```XML
> import { SearchBarContainer } from './SearchBarContainer';
> 
> const AdvancedSearchContainer: FC = ({ children }) => (
> ```

I wouldn't create a new component for this, it does not seem to add any value. Let's rather have this div inline
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 11 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylgFBK01GG6mre9qUg:-MylgFBK01GG6mre9qUh:biuf7ic) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L11)):*
> ```XML
> 
> const AdvancedSearchContainer: FC = ({ children }) => (
>   <div style={{ borderColor: '#f2f5f7' }} className="border-2 p-10">
> ```

this is called `border-background` in tailwind css I think (because in theme.js this color is called as "background")
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 17 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylgrfr-XjL1QRg9pyM:-Mylgrfr-XjL1QRg9pyN:bdorvx5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L17)):*
> ```XML
> 
> const ActionsContainer: FC = ({ children }) => (
>   <Row className="flex justify-end bg-background py-4">{children}</Row>
> ```

I wouldn't create a new component for this, it does not seem to add any value. Let's rather have this <Row> inline
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 27 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylgvhD-Ts9pgZt_4M2:-MylgvhD-Ts9pgZt_4M3:b7uh0rc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L27)):*
> ```XML
> 
>   return (
>     <Container className="pt-10 pb-10">
> ```

`py-10`
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 28 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylhK550jSTaGSQHJen:-MylhK550jSTaGSQHJeo:bmy7e1y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L28)):*
> ```XML
>   return (
>     <Container className="pt-10 pb-10">
>       <SearchBarContainer
> ```

having this SearchBarContainer as a separate component seems inappropriate. You've passed on lots of values and callbacks from the parent just to make the interaction work. I'd just copy its contents as inline HTML here, it's not that long component to make it worth splitting it as its own
___
*[src/components/routes-and-lines/search/conditions/SearchInput.tsx, line 10 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyliVLEDFjEUoGngOxw:-MyliVLEDFjEUoGngOxx:b-wy4mkp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchInput.tsx#L10)):*
> ```XML
> };
> 
> export const SearchInput = ({
> ```

first I was confused and thought that this was a generic component for handling the search parameters that are text inputs. My bad...

I don't however know how to call this component instead to make its use more clear... `SearchExpression`...?
___
*[src/components/routes-and-lines/search/conditions/SearchInput.tsx, line 26 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myli79B1IofkzzPv-id:-Myli79B1IofkzzPv-ie:baw83q2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchInput.tsx#L26)):*
> ```XML
>       id="label-input"
>       type="text"
>       value={value || ''}
> ```

you don't seem to allow undefined values for this property, so why the `|| ''` fallback? Should you actually make the property more lenient instead with `value?: string;`?
___
*[src/components/routes-and-lines/search/filters/ResultSelector.tsx, line 13 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyljER_E8_EvGm0c7Aa:-MyljER_E8_EvGm0c7Ab:b-4eey3m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/filters/ResultSelector.tsx#L13)):*
> ```XML
>   const getToggleClassName = (selected: boolean) =>
>     selected
>       ? 'mr-2 w-20 !rounded  !px-0 !py-0 !text-sm !font-light'
> ```

you've overridden awfully lots of css attributes for the SimpleButton... just a thought that wouldn't it be easier to just use the `<button>` component instead...?


<!-- Sent from Reviewable.io -->

2022-03-22 13:16 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122)* status: 0 of 23 files reviewed, 24 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[src/components/routes-and-lines/search/SearchResultPage.tsx, line 31 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylkL8R-DFhm1YZmTYz:-MylkL8R-DFhm1YZmTZ-:blt1fh3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/SearchResultPage.tsx#L31)):*
> ```XML
> 
>       <ResultsTableHeader count={resultsCount} />
>       {queryParameters.filter.displayRoutes ? (
> ```

isn't it actually possible to show *both* lines and routes as result? Are you sure it's either-or?
___
*[src/components/routes-and-lines/search/filters/ResultSelector.tsx, line 17 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyljwDg6cQjGuONkMJ9:-MyljwDh07n-hTWttxvL:bgiwdf8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/filters/ResultSelector.tsx#L17)):*
> ```XML
> 
>   return (
>     <>
> ```

this should rather be its own <div> instead of a fragment
___
*[src/components/routes-and-lines/search/results/LinesResultTable.tsx, line 12 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylkepKDKHqsN2201YH:-MylkepKDKHqsN2201YI:b-95hxrd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/results/LinesResultTable.tsx#L12)):*
> ```XML
> }) =>
>   lines && lines.length > 0 ? (
>     <RoutesTable>
> ```

I don't really see a value in moving this to its own component. I'd rather keep it inline, it's only saving you like 3-4 rows. This component currently is just basically mitigating the "is the `lines` variable having any value" validation from the parent to its own component
___
*[src/components/routes-and-lines/search/results/ResultsTableHeader.tsx, line 6 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyllAiP9hIasn9CJ4M6:-MyllAiP9hIasn9CJ4M7:b-42j30p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/results/ResultsTableHeader.tsx#L6)):*
> ```XML
>   const { t } = useTranslation();
>   return (
>     <h1 className="mt-4 mb-4 text-2xl font-bold">
> ```

I don't really see a value in moving this to its own component, would rather keep it inline
___
*[src/components/routes-and-lines/search/results/RoutesResultTable.tsx, line 12 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyllF_eAl-D6saA9Y7t:-MyllF_eAl-D6saA9Y7u:b-h9vxsq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/results/RoutesResultTable.tsx#L12)):*
> ```XML
> }) =>
>   routes && routes.length > 0 ? (
>     <RoutesTable>
> ```

I don't really see a value in moving this to its own component. I'd rather keep it inline, it's only saving you like 3-4 rows. This component currently is just basically mitigating the "is the `routes` variable having any value" validation from the parent to its own component


<!-- Sent from Reviewable.io -->

2022-03-22 13:18 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122)* status: 0 of 23 files reviewed, 34 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @pallost)

___
*[src/hooks/useToggle.ts, line 3 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myll02Q-4rEoEPceLkD:-MylldFe2wt0FHf1_Ff0:b132fll) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/hooks/useToggle.ts#L3)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand purpose of this hook. Why not just use `  const [state, setState] = useState(initialState);`?
</blockquote></details>

If you want to toggle the value you can do this in one line too:
`setState(!state)`


<!-- Sent from Reviewable.io -->

2022-03-22 13:43 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122)* status: 0 of 23 files reviewed, 41 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[src/hooks/useToggle.ts, line 3 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myll02Q-4rEoEPceLkD:-Mylm3Oc1_l7SjwfpE0m:begnhdz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/hooks/useToggle.ts#L3)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If you want to toggle the value you can do this in one line too:
`setState(!state)`
</blockquote></details>

I think he wanted to share this state globally, between the search components...? Anyhow, I'd then just move it to `useSearch`, there's no need to create its own hook
___
*[src/hooks/search/useSearch.ts, line 12 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylmPMzElYcrQe8c8Rd:-MylmPN--ssf7VfGVzrN:b-ajv8dn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/hooks/search/useSearch.ts#L12)):*
> ```XML
> 
> export const useSearch = (): {
>   queryParameters: SearchParameters;
> ```

there's no need to define the return type here
___
*[src/hooks/search/useSearch.ts, line 26 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylmf6M0oBd_-GFYKs4:-Mylmf6M0oBd_-GFYKs5:boc77l0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/hooks/search/useSearch.ts#L26)):*
> ```XML
>   );
> 
>   const setSearchCondition = useCallback(
> ```

why did you use `useCallback` here? (asking, because I have no idea how/when to use it) Is there anything you actually can optimize by memoizing this?
___
*[src/hooks/search/useSearch.ts, line 41 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myln1034H2wpOM5_C10:-Myln1034H2wpOM5_C11:boc77l0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/hooks/search/useSearch.ts#L41)):*
> ```XML
>    */
>   const setFilter = useCallback(
>     (filterName: string, value: boolean) => {
> ```

why did you use `useCallback` here? (asking, because I have no idea how/when to use it) Is there anything you actually can optimize by memoizing this?
___
*[src/hooks/search/useSearch.ts, line 44 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylo9AYDJhzg1NleDQ-:-Mylo9AYDJhzg1NleDQ0:btja0m4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/hooks/search/useSearch.ts#L44)):*
> ```XML
>       const combinedParameters = {
>         ...queryParameters,
>         filter: {
> ```

we've been using `immer` for these kind of merge&set operations in this project: https://immerjs.github.io/immer/ 
but you could also probably use `Object.assign()`
___
*[src/hooks/search/useSearch.ts, line 49 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylpRUEBPJ9vYWmAsnf:-MylpRUEBPJ9vYWmAsng:bvckfih) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/hooks/search/useSearch.ts#L49)):*
> ```XML
>         },
>       };
>       history.push({
> ```

you could simplify this function by just calling setSearchCondition() and then handleSearch() within. Also, `searchConditions` already contains the `queryParameters` so there's no need to deal with that
___
*[src/hooks/search/useSearch.ts, line 63 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MylplOz1G71F0yzsAOv:-MylplOz1G71F0yzsAOw:bv9f25h) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/hooks/search/useSearch.ts#L63)):*
> ```XML
>   const handleSearch = () => {
>     const combinedParameters = {
>       search: { ...searchConditions },
> ```

`searchConditions` should already contain the `queryParameters` as it was used for its default value
___
*[src/hooks/search/useSearchQueryParser.ts, line 18 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylq64M4pRMhT8V3zwg:-Mylq64M4pRMhT8V3zwh:b-com2ty) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/hooks/search/useSearchQueryParser.ts#L18)):*
> ```XML
>  */
> export type SearchParameters = {
>   search: SearchConditions;
> ```

I don't really see a use for handling `displayRoutes` in a different way, it's also just a search parameter even if you don't necessarily need to send it to the backend


<!-- Sent from Reviewable.io -->

2022-03-23 09:35 UTC, tk-vincit requested changes
Generally looking good.

Mentioned also small things as requested as this was your first PR in this project.

Would like to re-review after changes are done.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-:-Myq7BPK1eRVmyD8kSjh:b-v05oka)* status: 0 of 23 files reviewed, 58 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[src/components/RoutesAndLinesPage.tsx, line 17 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MypmvUp6D9j3VO4ShBz:-MypmvUp6D9j3VO4ShC-:b-jvhzj7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/RoutesAndLinesPage.tsx#L17)):*
> ```XML
> import { RoutesResultTable } from './routes-and-lines/search/results/RoutesResultTable'; // eslint-disable-line import/no-cycle
> 
> const RouteResults = () => {
> ```

Should this component definition be on its own file?
___
*[src/components/routes-and-lines/search/CloseButton.tsx, line 8 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myld9MlE_YkMVW8tzdD:-MypnAFQD0Vg2QuKxJss:bjxqk9m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/CloseButton.tsx#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

`ml-auto` is not a component-specific css attribute, it's context-specific. It should be rather set from the outside: `<CloseButton className="ml-auto" onClose="..."/>`
</blockquote></details>

:+1: 
Outer margins should ~always be set _outside_ to the component.
___
*[src/components/routes-and-lines/search/SearchResultPage.tsx, line 24 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MypnaHf2ZNU5wZR0TXZ:-MypnaHf2ZNU5wZR0TX_:b60u27o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/SearchResultPage.tsx#L24)):*
> ```XML
>           {t('search.searchResultsTitle')} | {t('routes.routes')}
>         </h1>
>         <CloseButton onClose={handleClose} />
> ```

Usually buttons receive "onClick" prop.
What does "onClose" even mean in the context of button?
___
*[src/components/routes-and-lines/search/SearchResultPage.tsx, line 27 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mypnvqv-MH5VPIWMMmg:-Mypnvqv-MH5VPIWMMmh:b75dbje) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/SearchResultPage.tsx#L27)):*
> ```XML
>       </Row>
>       <SearchContainer />
> ```

Usually newlines are not used inside jsx
___
*[src/components/routes-and-lines/search/SearchResultPage.tsx, line 34 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MypoQZY9emv6Gpr2ezY:-MypoQZY9emv6Gpr2ezZ:b-koputk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/SearchResultPage.tsx#L34)):*
> ```XML
>         <RoutesResultTable routes={routes} />
>       ) : (
>         <LinesResultTable lines={lines} />
> ```

Just wondering: would you rather call ` const { lines } = useSearchResults();`  inside LinesResultTable keep all related responsibilities in same component? Same for RoutesResultTable,



_Code quote:_
```XML
 const { lines, routes, resultsCount } = useSearchResults();
```
___
*[src/components/routes-and-lines/search/conditions/PriorityCondition.tsx, line 12 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MypozsP69Mizr98SHFq:-MypozsP69Mizr98SHFr:b-biwatf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/PriorityCondition.tsx#L12)):*
> ```XML
> }: {
>   priorities: Priority[];
>   onClick: ValueFn;
> ```

Definition of ValueFn:
```
// copied from HeadlessUI Listbox as it's not exported
export type ValueFn = (...event: ExplicitAny[]) => void;
```

Are you sure you want to use it here?
___
*[src/components/routes-and-lines/search/conditions/PriorityCondition.tsx, line 16 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MypyxlBDycS4_7ryloB:-MypyxlBDycS4_7ryloC:bz49f2g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/PriorityCondition.tsx#L16)):*
> ```XML
>   const { t } = useTranslation();
> 
>   const onClickPriority = (priorityBeingChanged: Priority) => {
> ```

priorityBeingChanged -> newPriority?
___
*[src/components/routes-and-lines/search/conditions/PriorityCondition.tsx, line 34 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyldzDU9Wtyuta_iaGi:-MypzTN33a3e20b8uQCR:br74mvx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/PriorityCondition.tsx#L34)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you could simplify this by receiving priority and label as props:
```
const PriorityButton: React.FC<{priority: Priority, label: string, onClick: () => void}> = ({priority, label, onClick}) => {...}
```

I would also prefer if the component wasn't defined within the other component but nicely separated instead. It's not worth merging these just to save a few onClickPriority calls
</blockquote></details>

I would question a bit if this kind of "priorityButton" is useful abstraction at all.

If you want to avoid defining same button couple of times, how about something like this?

```

  const priorities: { priority: Priority; label: string }[] = [
    {
      priority: Priority.Standard,
      label: t('priority.standard'),
    },
    {
      priority: Priority.Draft,
      label: t('priority.draft'),
    },
  ];

```

and

```
{priorities.map((item) => (
      <SimpleButton
        onClick={() => onClick('priorities', item.priority)}
        inverted={!priorities.includes(item.priority)}
        key={item.priority}
      >
        {item.label}
      </SimpleButton>

)}
```
___
*[src/components/routes-and-lines/search/conditions/PriorityCondition.tsx, line 45 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myq28qN62-PjICxoMAJ:-Myq28qN62-PjICxoMAK:by6zkpa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/PriorityCondition.tsx#L45)):*
> ```XML
>   return (
>     <Column>
>       {/* eslint-disable-next-line jsx-a11y/label-has-associated-control */}
> ```

This eslint comment makes me wonder if <label> is actually correct tag to use here?
___
*[src/components/routes-and-lines/search/conditions/SearchBarContainer.tsx, line 14 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myq2KS29KmoiPl89GGl:-Myq2KS29KmoiPl89GGm:b13yg73) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchBarContainer.tsx#L14)):*
> ```XML
>   onSearch,
> }: {
>   isToggled: boolean;
> ```

What does it mean if SearchBarContainer is "toggled"? Would eg. isEnabled or isCollapsed be more descriptive name? (I have no idea, just wondering)
___
*[src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx, line 9 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myq2kvPAriDzlo8AULf:-Myq2kvPAriDzlo8AULg:b84x5y2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx#L9)):*
> ```XML
>   onClick,
> }: {
>   isToggled: boolean;
> ```

isToggled or isEnabled? 
___
*[src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx, line 13 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myq2vlb5UDuTMWu2SBW:-Myq2vlb5UDuTMWu2SBX:byhkf7j) ([raw file](https://github.com/hsldevco [...]

2022-03-24 11:57 UTC, tk-vincit requested changes
> Reviewed 1 of 20 files at r11.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122)* status: 1 of 33 files reviewed, 61 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, @param, and @tk-vincit)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvmC0y0zUpaK9b1nmU:-MyvmC0z8wDo1s9i83Jt:b-ylsc0z) (no related file):*
Looking better than before!

Starting to rut out of time for today, but re-reviewed almost everything and added some new comments/suggestions.

---
___
*[src/components/RoutesAndLinesPage.tsx, line 8 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvcFt6CU1S2bGfkxmZ:-MyvcFt6CU1S2bGfkxm_:b-3iji9r) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/RoutesAndLinesPage.tsx#L8)):*
> ```XML
> import { Path, routes } from '../routes'; // eslint-disable-line import/no-cycle
> import { SimpleButton } from '../uiComponents';
> import { RoutesAndLinesLists } from './routes-and-lines/RoutesAndLinesLists'; // eslint-disable-line import/no-cycle
> ```

Why there is dependency cycle? I undestand why router and top level page have dependency cycle, but usually parent and children components shouldn't have dependnecy cycles. Couldn't figure out how why there is a cycle in this case by reading the PR so can't suggest solution now...
___
*[src/components/routes-and-lines/LinesList.tsx, line 12 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvdEK0B2Pp5hogNT0n:-MyvdEK0B2Pp5hogNT0o:b-pnqfl0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/LinesList.tsx#L12)):*
> ```XML
> 
> export const LinesList = ({ lines }: Props): JSX.Element => (
>   <Visible visible={!!lines?.length}>
> ```

Thing to consider: is it responsibility of this component to render something or nothing at all depending if `lines` prop is given, or should `lines` prop be required and parent decide if to render this or not? I would vote for the latter.

If you prefer to keep <Visible> tag here, then it could make more sense to query for lines inside this component and not take any props at all.

Same comment for RoutesList component!
___
*[src/components/routes-and-lines/search/ResultsListHeader.tsx, line 3 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myvff9EE0aSLOLKoMW5:-Myvff9EE0aSLOLKoMW6:b-krwux6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/ResultsListHeader.tsx#L3)):*
> ```XML
> import { useTranslation } from 'react-i18next';
> 
> type Props = { count: number };
> ```

I would have called this `resultCont` to keep it more descriptive and avoid renaming of it in this component, but whatever. :)

(Actually I woudn't have made this onw component as now we are creating new file just to save 3 lines (assuming `t` line would fit to one line without renaming), but once again, whatever.

And third minor thing, our convention has been to define props as `interface`s instead of `type`, but that doesn't make ~any difference so for third time, whatever.
___
*[src/components/routes-and-lines/search/SearchResultPage.tsx, line 19 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myvf1R0-DU7aLewGt-i:-Myvf1R0-DU7aLewGt-j:bs6v9hd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/SearchResultPage.tsx#L19)):*
> ```XML
>   return (
>     <Container>
>       <Row className="h-12">
> ```

Do you have to define explicit height ("h-12") to this element? Now this easily breaks if someone modifies contents of this block.
___
*[src/components/routes-and-lines/search/SearchResultPage.tsx, line 25 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvfL5V20DlSBzykZvq:-MyvfL5V20DlSBzykZvr:b-11cbpb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/SearchResultPage.tsx#L25)):*
> ```XML
>         <CloseButton
>           className="ml-auto text-base font-bold text-brand"
>           onClick={handleClose}
> ```

I guess react conventon would be to call this kind of action handler `onClose` - at least if it would have been defined inside this component. Now it seems to come from hook, so this is OK but still something to keep in mind in the future :)
___
*[src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx, line 9 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myq2kvPAriDzlo8AULf:-MyvguPo2Kyzbo21LHHl:b32w1t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx#L9)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I do think that isToggled is better here, since isEnabled would refer to something being enabled/disabled. But here nothing is "disabled". On this component it decides which way the arrow pointing. But maybe isToggled is not the right name either, hmm.
</blockquote></details>

Ok
___
*[src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx, line 21 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myvh-sQ9C97eryix8PH:-Myvh-sQ9C97eryix8PI:b-n6hz4u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx#L21)):*
> ```XML
>           <FaChevronUp className="text-3xl text-tweaked-brand" />
>         ) : (
>           <FaChevronDown className="text-3xl text-tweaked-brand" />
> ```

You could avoid defining same classnames twice to improve maintanability:
```
const iconClassName = "...";
...
className={iconClassName}
```
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 3 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvhKx259P_8Dtu_kMi:-MyvhKx259P_8Dtu_kMj:brv8via) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L3)):*
> ```XML
> import React, { FC } from 'react';
> import { useTranslation } from 'react-i18next';
> import { useSearch } from '../../../../hooks/search';
> ```

This and next hook could and probably should be exposed from `src/hooks/index.ts`
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 11 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvhZ6ODZROUqGLTiqV:-MyvhZ6ODZROUqGLTiqW:bswg06q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L11)):*
> ```XML
> import { SearchExpression } from './SearchExpression';
> 
> const AdvancedSearchContainer: FC = ({ children }): JSX.Element => (
> ```

JSX.Element typing is not needed if this is already typed as React.FC.
Same for also component definitions below.
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 15 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myvj8ZNDPfFXSDB6MLx:-Myvj8ZNDPfFXSDB6MLy:bt6aztv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L15)):*
> ```XML
> );
> 
> const ActionsContainer: FC = ({ children }): JSX.Element => (
> ```

Personally I don't understand why these are defined as individual components as these just wrap single (!) jsx tag and thus make it (imo) more difficult to read what jsx actually says - but if you prefer these I'm ok with these so far.

Just wondering what is the logic to have these as individual components but not having e.g. <Row> around <label> as own component. Or <Row> ar [...]

2022-03-25 14:00 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122)* status: 1 of 33 files reviewed, 61 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, @param, and @tk-vincit)

___
*[src/components/RoutesAndLinesPage.tsx, line 8 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvcFt6CU1S2bGfkxmZ:-Mz-CSsY6K4eXfydTpTB:b-6cep5i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/RoutesAndLinesPage.tsx#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why there is dependency cycle? I undestand why router and top level page have dependency cycle, but usually parent and children components shouldn't have dependnecy cycles. Couldn't figure out how why there is a cycle in this case by reading the PR so can't suggest solution now...
</blockquote></details>

It seems that the dependency cycle comes from (`LineTableRow`), which has 
`import { Path, routes } from '../routes';` for the Link:
`<Link to={routes[Path.lineDetails].getLink(line.line_id)}>`

This is something that already existed, and earlier I quickly checked if there is a way to extract this Link information to somewhere else to cut the dependency cycle, but did not invest much time to it yet. 
___
*[src/components/routes-and-lines/LinesList.tsx, line 12 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvdEK0B2Pp5hogNT0n:-Mz-DrVH87bVKoeQqzWi:bsi7wf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/LinesList.tsx#L12)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Thing to consider: is it responsibility of this component to render something or nothing at all depending if `lines` prop is given, or should `lines` prop be required and parent decide if to render this or not? I would vote for the latter.

If you prefer to keep <Visible> tag here, then it could make more sense to query for lines inside this component and not take any props at all.

Same comment for RoutesList component!
</blockquote></details>

Good point. My mindset was that this was more like parameter validation to prevent errors. But since we already changed the lines / routes to be optional, we can actually remove this Visible component completely.
___
*[src/components/routes-and-lines/search/ResultsListHeader.tsx, line 3 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myvff9EE0aSLOLKoMW5:-Mz-OSjX2BvEvWIVh7HO:b-zhmbq0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/ResultsListHeader.tsx#L3)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I would have called this `resultCont` to keep it more descriptive and avoid renaming of it in this component, but whatever. :)

(Actually I woudn't have made this onw component as now we are creating new file just to save 3 lines (assuming `t` line would fit to one line without renaming), but once again, whatever.

And third minor thing, our convention has been to define props as `interface`s instead of `type`, but that doesn't make ~any difference so for third time, whatever.
</blockquote></details>

Good points, and now I also remember why I did this component. It will have more functionality in the future. (Choose button) and ordering of the table. But then maybe this component is then again named wrong for that purpose, not sure. 

Maybe I'll just remove this component for now and then it can be re-created (with some other name) once the next features will be implemented regarding this header row.
___
*[src/components/routes-and-lines/search/SearchResultPage.tsx, line 19 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myvf1R0-DU7aLewGt-i:-Mz-QKnV4uLouz4mfbnz:b-xdgvze) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/SearchResultPage.tsx#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do you have to define explicit height ("h-12") to this element? Now this easily breaks if someone modifies contents of this block.
</blockquote></details>

Nice catch! Would not like to give explicit heights at all. This height also makes so little difference that I will just remove it.
___
*[src/components/routes-and-lines/search/SearchResultPage.tsx, line 25 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvfL5V20DlSBzykZvq:-Mz-QfCoALWnqeplv7bX:b-eeywll) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/SearchResultPage.tsx#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I guess react conventon would be to call this kind of action handler `onClose` - at least if it would have been defined inside this component. Now it seems to come from hook, so this is OK but still something to keep in mind in the future :)
</blockquote></details>

Noted, thanks!
___
*[src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx, line 21 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myvh-sQ9C97eryix8PH:-Mz-QqqVADfZhzFnSY3f:bsvv7vh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

You could avoid defining same classnames twice to improve maintanability:
```
const iconClassName = "...";
...
className={iconClassName}
```
</blockquote></details>

:+1: Will change
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 3 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvhKx259P_8Dtu_kMi:-Mz-R8YbAHlAJ8OiBtHE:b-ot2uxc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L3)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This and next hook could and probably should be exposed from `src/hooks/index.ts`
</blockquote></details>

Ah, right. I made a index.ts to the search folder. I'll remove that and expose these from the hooks/index.ts :+1: 
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 11 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvhZ6ODZROUqGLTiqV:-Mz-iBp5ElXrNL7ojmDH:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

JSX.Element typing is not needed if this is already typed as React.FC.
Same for also component definitions below.


</blockquote></details>

:+1: 
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 15 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Myvj8ZNDPfFXSDB6MLx:-Mz-j1x450RGpspWvR7z:br5kks2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Personally I don't understand why these are defined as individual components as these just wrap single (!) jsx tag and thus make it (imo) more difficult to read what jsx actually says - but if you prefer these I'm ok with these so far.

Just wondering what is the logic to have these as individual components but not having e.g. <Row> around <label> as own component. Or <Row> around SearchExpression and SearchConditionToggle - why it is not SearchContainer or something like that then? :raised_eyebrow:  
</blo [...]

2022-03-28 09:14 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122)* status: 0 of 35 files reviewed, 56 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, @param, and @tk-vincit)

___
*[src/components/RoutesAndLinesPage.tsx, line 8 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvcFt6CU1S2bGfkxmZ:-MzEfsg86QXuo1dJ3OnG:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/RoutesAndLinesPage.tsx#L8)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

It seems that the dependency cycle comes from (`LineTableRow`), which has 
`import { Path, routes } from '../routes';` for the Link:
`<Link to={routes[Path.lineDetails].getLink(line.line_id)}>`

This is something that already existed, and earlier I quickly checked if there is a way to extract this Link information to somewhere else to cut the dependency cycle, but did not invest much time to it yet. 
</blockquote></details>

OK
___
*[src/components/routes-and-lines/LinesList.tsx, line 12 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvdEK0B2Pp5hogNT0n:-MzEg7QDCLl_gKGJlwSh:b-ouk9fh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/LinesList.tsx#L12)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Good point. My mindset was that this was more like parameter validation to prevent errors. But since we already changed the lines / routes to be optional, we can actually remove this Visible component completely.
</blockquote></details>

Why lines has to be optional?
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 20 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEhhcH9PvpbpcpyG_K:-MzEhhcH9PvpbpcpyG_L:br2mboo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L20)):*
> ```XML
>     <Container className="py-10">
>       <Row className="justify-center bg-background py-4">
>         <Column className="w-2/4">
> ```

Does this need to have explicit width?
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 22 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEhwO-DtnOZ7WJJdc_:-MzEhwO-DtnOZ7WJJdca:b217a1f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L22)):*
> ```XML
>         <Column className="w-2/4">
>           <Row>
>             <label htmlFor="label">{t('search.searchLabel')}</label>
> ```

No 100% sure, but this should probably be right before SearchExpression in DOM. That might affect accessibility and layout in some cases. 
___
*[src/components/routes-and-lines/search/conditions/SearchExpression.tsx, line 10 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEhrNh6WTdN413tBAY:-MzEhrNh6WTdN413tBAZ:brubke6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/components/routes-and-lines/search/conditions/SearchExpression.tsx#L10)):*
> ```XML
> };
> 
> export const SearchExpression = ({
> ```

SearchInput? This seems to return input element.
___
*[src/hooks/useToggle.ts, line 3 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEjAr2B7HygnTlxanE:-MzEjAr2B7HygnTlxanF:b-dgseon) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/hooks/useToggle.ts#L3)):*
> ```XML
> import { useState } from 'react';
> 
> export const useToggle = (initialState = false): [boolean, () => void] => {
> ```

Explicit return value shouldn't be needed as TS should be able to infer this. Also it is IMO usually best to leave it out as it just makes things more complex when refactoring function implementation.
___
*[src/hooks/search/useSearch.ts, line 32 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEjsHB3ii8zEE7_Ilx:-MzEjsHB3ii8zEE7_Ily:bblc2p4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/hooks/search/useSearch.ts#L32)):*
> ```XML
>   const setFilter = (filterName: string, value: boolean) => {
>     const combinedParameters = produce(queryParameters, (draft) => {
>       draft.filter[filterName as keyof FilterConditions] = value;
> ```

You would probably want define this function like: `(filterName: keyof FilterConditions, ...`. Then you would get intellisense to complan if this function is called with incorrect parameters and you also could get rid of this `as` casting.
___
*[src/uiComponents/SimpleSmallButton.tsx, line 10 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEmbw3DZr9GUBq8mJP:-MzEmbw3DZr9GUBq8mJQ:bzifm87) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/uiComponents/SimpleSmallButton.tsx#L10)):*
> ```XML
> 
> const commonClassNames =
>   'mr-2 font-bold rounded-full border w-20 !rounded !text-sm !font-light';
> ```

Why do you need !important classes here?


<!-- Sent from Reviewable.io -->

2022-03-28 13:08 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122)* status: 0 of 35 files reviewed, 56 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, @param, and @tk-vincit)

___
*[-- commits, line 2 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyliVWc-Sm2a45ginOr):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Shouldn't be in its own commit. Now we just introduce unused code to the repository. Should be squashed with the commit where this is actually used.
</blockquote></details>

Done.
___
*[-- commits, line 5 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylig8OBfi9ICteP9bh):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Same.
</blockquote></details>

Done.
___
*[-- commits, line 8 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylik3316_BpGZnzjMu):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Same. Maybe same thing also for the rest of the commits?
</blockquote></details>

Done.
___
*[src/components/routes-and-lines/LinesList.tsx, line 12 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvdEK0B2Pp5hogNT0n:-MzEtb037ZFZP_c6fq1h:bp8glw7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/52dfcfc662e1877d5b1fd6b7e30a6e4e34716efd/src/components/routes-and-lines/LinesList.tsx#L12)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why lines has to be optional?
</blockquote></details>

Well, at least at first it was because the caller (RoutesAndLinesList.tsx) uses this `mapListChangingRoutesResult(changingRoutesResult);` which might return  `RouteRoute[] | undefined`.  This was first typed the same way, but then there was this suggestion to just make it optional.

But now I see that the `mapListOwnLinesResult(ownLinesResult);` is not typed like this. Not sure why routes have been typed to have the possibility to be `undefined`, but lines are not.

So based on this the lines doesn't need to be optional, but routes needs to be, otherwise we get linter error. Not sure if I should change the lines to be mandatory, since routes can't be either. Or is the question actually that why is the mapListchangingRoutesResult typed to have `undefined` as possible result?
___
*[src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx, line 18 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylfkwb6yrrNlJ9SZme:-MzFWVKe1UnCOPlVPeDC:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchConditionsToggle.tsx#L18)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

testId="SearchConditionToggle::toggle"
</blockquote></details>

Done.
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 17 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-Mylgrfr-XjL1QRg9pyM:-MzFWbL7ExtOYlvBPUGu:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a8bc5195578969a24bea4a50ca6e7d0000b93030/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L17)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 20 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEhhcH9PvpbpcpyG_K:-MzExU758tQqlhNAd_L-:bmudgc5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L20)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Does this need to have explicit width?
</blockquote></details>

I'm not sure how to achieve the correct width otherwise.
___
*[src/components/routes-and-lines/search/conditions/SearchContainer.tsx, line 22 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEhwO-DtnOZ7WJJdc_:-MzF4gcLD480vMJHbaHe:b-xo2u2y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/components/routes-and-lines/search/conditions/SearchContainer.tsx#L22)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

No 100% sure, but this should probably be right before SearchExpression in DOM. That might affect accessibility and layout in some cases. 
</blockquote></details>

Hmm, should this element be a header then? Because this was kind of my solution to have the layout here so that the arrow icon is in the right place without setting the icons location explicitly.
___
*[src/components/routes-and-lines/search/conditions/SearchExpression.tsx, line 10 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEhrNh6WTdN413tBAY:-MzF5EN0BIY8h9jlvm9O:bz18567) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/components/routes-and-lines/search/conditions/SearchExpression.tsx#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

SearchInput? This seems to return input element.
</blockquote></details>

This was SearchInput at first, but Tamas suggested SearchExpression and I decided to try it out. Maybe the SearchInput is better. The comment of course is not here anymore because the file is now different. But I'll change this back, I also think that it is clearer.
___
*[src/hooks/useToggle.ts, line 3 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEjAr2B7HygnTlxanE:-MzF63Qw8u_leBQEGYRU:bz2512p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/hooks/useToggle.ts#L3)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Explicit return value shouldn't be needed as TS should be able to infer this. Also it is IMO usually best to leave it out as it just makes things more complex when refactoring function implementation.
</blockquote></details>

Hmm, do you mean the `:[boolean, () => void]`? Because if I remove this, then I get linter error when using this useToggle. It seems to not know the order of these.

`Type 'boolean | (() => void)' is not assignable to type 'boolean'.`
___
*[src/hooks/search/useSearch.ts, line 32 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEjsHB3ii8zEE7_Ilx:-MzF9LU72y5OA39g_xH-:b5bnnt5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/hooks/search/useSearch.ts#L32)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

You would probably want define this function like: `(filterName: keyof FilterConditions, ...`. Then you would get intellisense to complan if this function is called with incorrect parameters and you also could get rid of this `as` casting.
</blockquote></details>

Ahh, perfect. Thanks!
___
*[src/uiComponents/SimpleSmallButton.tsx, line 10 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEmbw3DZr9GUBq8mJP:-MzFULje5o6Yq5TDHI0u:b-puy8rn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/uiComponents/SimpleSmallButton.tsx#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why do you need !important classes here?
</blockquote></details>

The !importants might be remains after some copy-paste (bad habit). Though I already thought I checked that these were all good and removed unnecessary definitions. They do not require !important and there is also an extra "rounded-full". Nice that you spotted this, I need to be sharper with these in the future.


<!-- Sent from Reviewable.io -->

2022-03-30 09:15 UTC, tk-vincit approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/122)* status: 0 of 35 files reviewed, 54 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, @param, and @tk-vincit)

*[a discussion](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MyvmC0y0zUpaK9b1nmU:-MzP5zZj-o0Y7Zou--k7:b47l1fw) (no related file):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Looking better than before!

Starting to rut out of time for today, but re-reviewed almost everything and added some new comments/suggestions.
</blockquote></details>

Great work! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

---
___
*[src/hooks/useToggle.ts, line 3 at r15](https://reviewable.io/reviews/hsldevcom/jore4-ui/122#-MzEjAr2B7HygnTlxanE:-MzP5MYQEUYcwTwI9QE6:bo3tpvb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/216e40551061d832f75ff4e5dca4ce406019157a/src/hooks/useToggle.ts#L3)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, do you mean the `:[boolean, () => void]`? Because if I remove this, then I get linter error when using this useToggle. It seems to not know the order of these.

`Type 'boolean | (() => void)' is not assignable to type 'boolean'.`
</blockquote></details>

Ok, my bad then


<!-- Sent from Reviewable.io -->

2022-03-30 11:23 UTC, merged