Add line drafts page
HSLdevcom/jore4-ui pull request #162
Opened 2022-04-28 06:48 UTC by HenrikHartiala

This PR will:
* Fix <SimpleDropdownMenu>'s menu item from overflowing
* Add LineDraftsPage which will show the list of all drafts of a line.

2022-05-02 09:12 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/162)* status: 0 of 11 files reviewed, 15 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @pallost)

___
*[`src/components/routes-and-lines/line-details/ActionsRow.tsx` line 62 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12vXth4bD-m9OWDuNg:-N12vXth4bD-m9OWDuNh:b-e8zd64) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-details/ActionsRow.tsx#L62)):*
> ```XML
>             className="ml-auto"
>             inverted
>             onClick={() => onClickShowDrafts(line.label)}
> ```

Seems like this should ne `href` and not `onClick` handler. SimpleButton already supports `href` tag.
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12vp_e9qjXd-pshCCV:-N12vp_e9qjXd-pshCCW:b1hfokj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L16)):*
> ```XML
> import { LineDraftTableRow } from './LineDraftTableRow';
> 
> export const LineDraftsPage = () => {
> ```

Should be typed to JSX.Element
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12wELZBILgV4TTJdv1:-N12wELZBILgV4TTJdv2:b-tmu22l) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L21)):*
> ```XML
>   const history = useHistory();
> 
>   const lineDetailsResult = useGetDraftLinesByLabelQuery(
> ```

We should create custom hook for this to avoid writing business logics to UI components



_Code quote:_
```XML
  const lineDetailsResult = useGetDraftLinesByLabelQuery(
    mapToVariables({ label }),
  );

  const lines = mapDraftLinesByLabelResult(lineDetailsResult);
```
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12wTNQB6aPx97BuYIB:-N12wTNQB6aPx97BuYIC:bv81i8v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L27)):*
> ```XML
>   const lines = mapDraftLinesByLabelResult(lineDetailsResult);
> 
>   const handleClose = () => {
> ```

`onClose` would be shorted and more consistent with rest of the codebase
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 35 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12xFRfD-KVVUJkoBTY:-N12xFRg2Sddo_VX1DiT:b-aq10mx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L35)):*
> ```XML
>       <Row>
>         <h1 className="text-2xl font-bold">
>           {`${t('lines.draftsTitle')} | ${t('lines.line')} ${label}`}
> ```

Latter part should be defined like this:
`t('lines.line', { label })}`
You should also refactor translation in common.json to something like this (not exactly like this naturally, see exact examples from common.json):
`  "lines.line": "Line: {{ label }}",`

Seems like you have to also refactor three existing usages of this in our codebase (global search 'lines.line'). Could you please do that in own commit? Thanks!
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 53 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12y17QDaUv7DH6C_n4:-N12y17QDaUv7DH6C_n5:b-fkfbd1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L53)):*
> ```XML
>       ) : (
>         <Row className="py-20">
>           <p className="mx-auto flex text-2xl font-bold">{`${t(
> ```

No need to define translation inside string template (`${}`)



_Code quote:_
```XML
          <p className="mx-auto flex text-2xl font-bold">{`${t(
            'lines.noDrafts',
          )}`}</p>
```
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx` line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12yEi_-lrL6K6eRmaj:-N12yEi_-lrL6K6eRmak:b5201x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx#L4)):*
> ```XML
> 
> export const LineDraftTableHeader = ({
>   className,
> ```

className = ''
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12yYq9CMQROn5t5dvJ:-N12yYq9CMQROn5t5dvK:b5201x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L15)):*
> ```XML
> }
> 
> export const LineDraftTableRow = ({ className, line }: Props): JSX.Element => {
> ```

className = ''
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12yqoPEic3P7xrI8mC:-N12yqoPEic3P7xrI8mD:b-m0uy3p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L25)):*
> ```XML
>     showRoutesOnModal(
>       lineRouteIds,
>       // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
> ```

Please comment why this is safe to do
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 60 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12za_o8naRJXcV1ICg:-N12za_o8naRJXcV1ICh:b-mimrbn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L60)):*
> ```XML
>         <td className={commonClassName}>
>           <SimpleDropdownMenu>
>             <button type="button" onClick={onClickToLineDetails}>
> ```

Seems like this should be `import { Link } from 'react-router-dom';` and not button
___
*[`src/graphql/route.ts` line 257 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N13-NFn77wz4wcoV1Nh:-N13-NFn77wz4wcoV1Ni:buyytyy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/graphql/route.ts#L257)):*
> ```XML
> const GET_DRAFT_LINES_BY_LABEL = gql`
>   query GetDraftLinesByLabel($label: String!) {
>     route_line(where: { label: { _eq: $label }, priority: { _eq: 30 } }) {
> ```

`_eq: 30` is impossible to maintain if enum values of priorities change at some point (and its also impossible to read).

I don't have perfect solution in mind, but if you can't think anything else, refactor this to GET_LINES_BY_LABEL and take priority as param so that it can be defined in js side...
___
*[`src/graphql/route.ts` line 268 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N130dPeA5RX0CpjS00y:-N130dPeA5RX0CpjS00z:b-j7axlo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/graphql/route.ts#L268)):*
> ```XML
> export const mapDraftLinesByLabelResult = (
>   result: GqlQueryResult<GetDraftLinesByLabelQuery>,
> ) => result.data?.route_line as RouteLine[] | undefined;
> ```

Is `| undefined` needed? Not 100% sure, but I assume if `result.data?` is not defined we automatically fallback to undefined.
___
*[`src/locales/fi-FI/common.json` line 195 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1310kXEW654v0hekd1:-N1310kXEW654v0hekd2:b-mxb67j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/locales/fi-FI/common.json#L195)):*
> ```JSON
>   "version": "Versio: {{ version }}",
>   "hide": "Piilota",
>   "validityStart": "Al [...]

2022-05-04 05:58 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/162)* status: 0 of 11 files reviewed, 15 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/line-details/ActionsRow.tsx` line 62 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12vXth4bD-m9OWDuNg:-N18_snk5PSVzLrn15GE:brmux6m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-details/ActionsRow.tsx#L62)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Seems like this should ne `href` and not `onClick` handler. SimpleButton already supports `href` tag.
</blockquote></details>

Check!
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12vp_e9qjXd-pshCCV:-N186yPR3TQF5jLlM-2E:b-l0zo9p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L16)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should be typed to JSX.Element
</blockquote></details>

Btw is this needed for something, or just for readability? At least for me the intellisense already shows that this is JSX.Element when hovering over. I mean it does improve the readability so I'll add it. I will also take a note on this, not the first time you mentioned :D
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12wELZBILgV4TTJdv1:-N18aNzy9bmu6iVgWEPC:b-20ftp1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

We should create custom hook for this to avoid writing business logics to UI components
</blockquote></details>

Great, I'll do that!
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12wTNQB6aPx97BuYIB:-N18RKNh1EQoc7mk-SQp:b3m0pm4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L27)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`onClose` would be shorted and more consistent with rest of the codebase
</blockquote></details>

:+1: I'll take a note on this as well. I'll also move this to the newly created hook.
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 35 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12xFRfD-KVVUJkoBTY:-N19HQ663YFsHa-PC9mo:b-yewqid) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L35)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Latter part should be defined like this:
`t('lines.line', { label })}`
You should also refactor translation in common.json to something like this (not exactly like this naturally, see exact examples from common.json):
`  "lines.line": "Line: {{ label }}",`

Seems like you have to also refactor three existing usages of this in our codebase (global search 'lines.line'). Could you please do that in own commit? Thanks!
</blockquote></details>

Good one, I'll do that!
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 53 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12y17QDaUv7DH6C_n4:-N18Rf3pAMQmJqoClH26:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L53)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

No need to define translation inside string template (`${}`)
</blockquote></details>

:+1: 
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx` line 4 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12yEi_-lrL6K6eRmaj:-N18RiPJ4LejenshPKF1:b-3o76ea) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx#L4)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

className = ''
</blockquote></details>

Thanks, I'll also take a note on this.
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12yYq9CMQROn5t5dvJ:-N19KiAQ3x4cEXOwLbkW:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

className = ''
</blockquote></details>

:+1: 
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12yqoPEic3P7xrI8mC:-N18L-Bn30E55FfYrcMR:b-qajmz8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please comment why this is safe to do
</blockquote></details>

This is actually copypasted code and I personally don't like suppressing eslint warnings, so I might do the necessary checks and remove the eslint-disable completely.
Hmm, now that I look at this, I'm not sure if I understand it completely, because the validity_start can be nullable (as discussed in architecture meeting). So I'm not sure why this warning can be suppressed and I'm not sure how to refactor this correctly.

If we need to refactor the useShowRoutesOnModal to allow validityStart to be nullable, I think that will need its own PR.

Or did I understand this wrong :D ?
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 60 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12za_o8naRJXcV1ICg:-N18Mrlo9eoSdUPqUkVD:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L60)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Seems like this should be `import { Link } from 'react-router-dom';` and not button
</blockquote></details>

:+1: 
___
*[`src/graphql/route.ts` line 257 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N13-NFn77wz4wcoV1Nh:-N18LoOa1RLr6lr4StMr:b-ttjzsf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/graphql/route.ts#L257)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`_eq: 30` is impossible to maintain if enum values of priorities change at some point (and its also impossible to read).

I don't have perfect solution in mind, but if you can't think anything else, refactor this to GET_LINES_BY_LABEL and take priority as param so that it can be defined in js side...
</blockquote></details>

True. I tried a couple of ways, but couldn't find another solution for this. I'll go with your solution, although need to name it to GET_LINES_BY_LABEL_AND_PRIORITY
___
*[`src/graphql/route.ts` line 268 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N130dPeA5RX0CpjS00y:-N18M4c08agWAheTP-OG:bhdcb1c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/graphql/route.ts#L268)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is `| undefined` needed? [...]

2022-05-04 06:38 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/162)* status: 0 of 17 files reviewed, 6 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @pallost)

___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12vp_e9qjXd-pshCCV:-N1CgBSi8w8z_EXV3F_e:b4gw2zz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Btw is this needed for something, or just for readability? At least for me the intellisense already shows that this is JSX.Element when hovering over. I mean it does improve the readability so I'll add it. I will also take a note on this, not the first time you mentioned :D
</blockquote></details>

Unless something is changed, TS compiler won't know this is intented to be react component and not just a regular function unless you define return value. So then we lose type safety and checks related to that on CI side.
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 21 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12wELZBILgV4TTJdv1:-N1Cm8_B5nLqYfII5MnR:b-j81q7u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L21)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Great, I'll do that!
</blockquote></details>

Thanks! Let's continue discussion in new PR regarding new hook.
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 35 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12xFRfD-KVVUJkoBTY:-N1Ch4g-5n6VOCpIwoW8:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L35)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Good one, I'll do that!
</blockquote></details>

Thanks!
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx` line 13 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1CjdH26UOrgML0q2mh:-N1CjdH3CHnjEnwio8WP:byncrrl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d1eab9d62b08eba35438869da61e280e9c99530e/src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx#L13)):*
> ```XML
>     <thead className={`${className} text-left`}>
>       <tr>
>         <th className={commonClassName}>{t('tableHeaders.status')}</th>
> ```

I think this should rather be prefixed with "line.tableHeaders" or "LineTableHeaders" or "LineDraftsTableHeaders" or something like that. It won't make sense to put all headers of all, mostly unrelated tables under same translation prefix in the future.

Sorry that my initial suggestion was ambiguous...
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12yqoPEic3P7xrI8mC:-N1CmTAM3NJ0hXHU9rsB:bi6hnsa) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L25)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This is actually copypasted code and I personally don't like suppressing eslint warnings, so I might do the necessary checks and remove the eslint-disable completely.
Hmm, now that I look at this, I'm not sure if I understand it completely, because the validity_start can be nullable (as discussed in architecture meeting). So I'm not sure why this warning can be suppressed and I'm not sure how to refactor this correctly.

If we need to refactor the useShowRoutesOnModal to allow validityStart to be nullable, I think that will need its own PR.

Or did I understand this wrong :D ?
</blockquote></details>

Maybe we should discuss about this in slack with the team. But OK, if this is copypaste then this might ne non-blocking for this PR, depending on what we decide.
___
*[`src/graphql/route.ts` line 268 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N130dPeA5RX0CpjS00y:-N1CkC6q0BV2TrqnMSOD:b-6xq8g3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/graphql/route.ts#L268)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, I'm not sure either. This undefined typing is used in many of our queries. These gql typings are are not completely clear to me yet.
</blockquote></details>

You could remove it and see what return value intellisense shows for this component. And if you remove it and TS compiler won't give warnings, then it is safe to remove it :shrug: 

Anyway, not a big issue so this is non-blocking thin for this PR.
___
*[`src/hooks/line-drafts/useGetLineDraftDetails.ts` line 21 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1Ckcyz7Va2bu9c2J55:-N1Ckcyz7Va2bu9c2J56:bq8rt56) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d1eab9d62b08eba35438869da61e280e9c99530e/src/hooks/line-drafts/useGetLineDraftDetails.ts#L21)):*
> ```XML
>   };
> 
>   return { lines, onClose };
> ```

Interface of this hook is pretty weird. So this either returns lines or goes back in history..? This mixes up different kind of responsibilities so this should be changed. I don't understand why this is done like this so dont have good suggestions in mind right now, but I suggest we try to re-think this.

Edit: one solution could be just removing "onClose" from here and moving it back to UI component..?
___
*[`src/locales/fi-FI/common.json` line 199 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N131BPi2IyHtokXaHfj:-N1ClcTG2lskpiKZ5H_z:bxntjy0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/locales/fi-FI/common.json#L199)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah, good that you mentioned this, because I was pondering about the same solution.
</blockquote></details>

Let's continue discussion in new thread related to this.
___
*[`src/locales/fi-FI/common.json` line 189 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1CkzsqECwsbpDYHbK1:-N1CkzsqECwsbpDYHbK2:bslkbnv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d1eab9d62b08eba35438869da61e280e9c99530e/src/locales/fi-FI/common.json#L189)):*
> ```JSON
>   },
>   "tableHeaders": {
>     "status": "Status",
> ```

This is not finnish. I think we should check from HSL what is correct term for this.


<!-- Sent from Reviewable.io -->

2022-05-06 07:01 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/162)* status: 0 of 17 files reviewed, 6 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12vp_e9qjXd-pshCCV:-N1N2AJTBHUNibKmuV9D:bkvo41v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L16)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Unless something is changed, TS compiler won't know this is intented to be react component and not just a regular function unless you define return value. So then we lose type safety and checks related to that on CI side.
</blockquote></details>

Ahh, okay. That makes sense. Thanks for the explanation!
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx` line 13 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1CjdH26UOrgML0q2mh:-N1N2cq94wRDd9rtRga-:b-23vi2x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d1eab9d62b08eba35438869da61e280e9c99530e/src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I think this should rather be prefixed with "line.tableHeaders" or "LineTableHeaders" or "LineDraftsTableHeaders" or something like that. It won't make sense to put all headers of all, mostly unrelated tables under same translation prefix in the future.

Sorry that my initial suggestion was ambiguous...
</blockquote></details>

That is true, although I would say that because these are easy to change and we don't exactly know yet how much of which translations are needed, so I think this will find it's shape as we go on. 
For example here I would maybe not use "line.tableHeaders.name" or "line.tableHeaders.edited" because these are most likely (at least I assume) to be used in other places as well other than lines. I'm not even sure if translation for "name" should even be under "tableHeaders".

So all in all I think that these tableHeaders which I added (status, name, edited, editor) are more likely to be common in oppose to being exclusive for lines.
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12yqoPEic3P7xrI8mC:-N1N6Tb65aolIYP_JMSH:b-r1nwme) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Maybe we should discuss about this in slack with the team. But OK, if this is copypaste then this might ne non-blocking for this PR, depending on what we decide.
</blockquote></details>

Check! I can start a thread about this soon
___
*[`src/graphql/route.ts` line 268 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N130dPeA5RX0CpjS00y:-N1N7doI88YMRjyJ2UmN:b-qjrexv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/graphql/route.ts#L268)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

You could remove it and see what return value intellisense shows for this component. And if you remove it and TS compiler won't give warnings, then it is safe to remove it :shrug: 

Anyway, not a big issue so this is non-blocking thin for this PR.
</blockquote></details>

Okay, then it can go :+1: 
___
*[`src/hooks/line-drafts/useGetLineDraftDetails.ts` line 21 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1Ckcyz7Va2bu9c2J55:-N1N83qw4Tz2rnstnQP3:b-4034vm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d1eab9d62b08eba35438869da61e280e9c99530e/src/hooks/line-drafts/useGetLineDraftDetails.ts#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Interface of this hook is pretty weird. So this either returns lines or goes back in history..? This mixes up different kind of responsibilities so this should be changed. I don't understand why this is done like this so dont have good suggestions in mind right now, but I suggest we try to re-think this.

Edit: one solution could be just removing "onClose" from here and moving it back to UI component..?
</blockquote></details>

Yup. I think this was a minor brain fart here. I probably was thinking this hook as the whole logic for the component, but it makes more sense to move onClose back to the UI component. Thanks!
___
*[`src/locales/fi-FI/common.json` line 189 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1CkzsqECwsbpDYHbK1:-N1N8vCRE75WMe5GFqSW:b19fwdv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d1eab9d62b08eba35438869da61e280e9c99530e/src/locales/fi-FI/common.json#L189)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This is not finnish. I think we should check from HSL what is correct term for this.
</blockquote></details>

I followed the figma sketch which used this as the Finnish translation. But for starters I'll ask Juha if this should be something else.


<!-- Sent from Reviewable.io -->

2022-05-06 08:24 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/162)* status: 0 of 17 files reviewed, 6 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`src/locales/fi-FI/common.json` line 189 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1CkzsqECwsbpDYHbK1:-N1NT0TJ1IxYdxpkxjql:bhzif2q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d1eab9d62b08eba35438869da61e280e9c99530e/src/locales/fi-FI/common.json#L189)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I followed the figma sketch which used this as the Finnish translation. But for starters I'll ask Juha if this should be something else.
</blockquote></details>

This is now changed to "Priority"


<!-- Sent from Reviewable.io -->

2022-05-10 05:56 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/162)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @pallost)

___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 19 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1gUQSCEs2UCmgRdNTZ:-N1gUQSCEs2UCmgRdNT_:bgz0d1a) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7067553a9337667f7a419e022b6bf1f506db8dab/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L19)):*
> ```XML
> 
>   const onClose = () => {
>     history.goBack();
> ```

We don't know what is in `history` object so this might redirect user to ambiguous place. See slack discussion about this.
___
*[`src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx` line 13 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1CjdH26UOrgML0q2mh:-N1gVgSh3IGUiSyegOYV:bbyu6hr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d1eab9d62b08eba35438869da61e280e9c99530e/src/components/routes-and-lines/line-drafts/LineDraftsTableHeader.tsx#L13)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

That is true, although I would say that because these are easy to change and we don't exactly know yet how much of which translations are needed, so I think this will find it's shape as we go on. 
For example here I would maybe not use "line.tableHeaders.name" or "line.tableHeaders.edited" because these are most likely (at least I assume) to be used in other places as well other than lines. I'm not even sure if translation for "name" should even be under "tableHeaders".

So all in all I think that these tableHeaders which I added (status, name, edited, editor) are more likely to be common in oppose to being exclusive for lines.
</blockquote></details>

OK, let's go with this for now. 
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12yqoPEic3P7xrI8mC:-N1gW9_s9k__XdDS9TDm:bd0rhpn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L25)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Check! I can start a thread about this soon
</blockquote></details>

If this is something that we have to refactor in the future, could you please create ticket to backlog about it? Or is it done already?
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 41 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1gWODc8c5ubLB103BG:-N1gWODc8c5ubLB103BH:b-gzyyfn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7067553a9337667f7a419e022b6bf1f506db8dab/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L41)):*
> ```XML
>           {mapPriorityToUiName(line.priority)}
>         </td>
>         <td className={commonClassName}>{line.validity_start?.toISODate()}</td>
> ```

Do we really want to show ISO dates to the user? Usually dates are formatted to more human-friendly form. See e.g. `mapToShortDateTime` function, but not 100% sure if we want to use that format or something else.



_Code quote:_
```XML
        <td className={commonClassName}>{line.validity_start?.toISODate()}</td>
        <td className={commonClassName}>{line.validity_end?.toISODate()}</td>
```
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 48 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1gWiUyB_HNXVHRRlu3:-N1gWiUyB_HNXVHRRlu4:biadw51) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7067553a9337667f7a419e022b6bf1f506db8dab/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L48)):*
> ```XML
>         <td className={commonClassName}>!Muokkaaja</td>
>         <td className={commonClassName}>
>           {' '}
> ```

Do we want this kind of magical space or should this be done with margin/padding?



_Code quote:_
```XML
       {' '}
```
___
*[`src/hooks/line-drafts/useGetLineDraftDetails.ts` line 21 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1Ckcyz7Va2bu9c2J55:-N1gX7yv3113ntAdC7Ph:b-26fxd9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/d1eab9d62b08eba35438869da61e280e9c99530e/src/hooks/line-drafts/useGetLineDraftDetails.ts#L21)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yup. I think this was a minor brain fart here. I probably was thinking this hook as the whole logic for the component, but it makes more sense to move onClose back to the UI component. Thanks!
</blockquote></details>

Now this looks nice :)


<!-- Sent from Reviewable.io -->

2022-05-10 14:08 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/162)* status: 0 of 17 files reviewed, 4 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx` line 19 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1gUQSCEs2UCmgRdNTZ:-N1iEiMC8_nvDl_KZePU:b-dtez4w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7067553a9337667f7a419e022b6bf1f506db8dab/src/components/routes-and-lines/line-drafts/LineDraftsPage.tsx#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

We don't know what is in `history` object so this might redirect user to ambiguous place. See slack discussion about this.
</blockquote></details>

added returnTo query parameter and use that one. 
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N12yqoPEic3P7xrI8mC:-N1i0FcIAxRfllW_iuRg:b-ac3xym) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f2ea1ae211ce7f8548b686e93cb95bc742aa4a75/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If this is something that we have to refactor in the future, could you please create ticket to backlog about it? Or is it done already?
</blockquote></details>

Did not add yet. The slack thread was a bit of a stub. But as far as I understand, this will need refactoring so I'll create a ticket about it.
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 41 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1gWODc8c5ubLB103BG:-N1i1qD-5npEGwBTD-GP:b-qttfqq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7067553a9337667f7a419e022b6bf1f506db8dab/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L41)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we really want to show ISO dates to the user? Usually dates are formatted to more human-friendly form. See e.g. `mapToShortDateTime` function, but not 100% sure if we want to use that format or something else.
</blockquote></details>

`mapToShortDate` is the correct one according to figma. Thanks!
___
*[`src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx` line 48 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/162#-N1gWiUyB_HNXVHRRlu3:-N1i-nhe71gfdYkt1jtd:bl8pqyq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/7067553a9337667f7a419e022b6bf1f506db8dab/src/components/routes-and-lines/line-drafts/LineDraftTableRow.tsx#L48)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we want this kind of magical space or should this be done with margin/padding?
</blockquote></details>

Good catch. This must be some save / prettier thing replacing some accidantal whitespace, because I haven't manually added anything like that :D. I'll remove it :+1: 


<!-- Sent from Reviewable.io -->

2022-05-12 07:50 UTC, tk-vincit approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/162)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @eleksi and @pallost)



<!-- Sent from Reviewable.io -->

2022-05-12 09:30 UTC, merged