Add via point modal and via icon
HSLdevcom/jore4-ui pull request #201
Opened 2022-05-27 06:42 UTC by HenrikHartiala

In this PR we add
* Via icon to indicate that a stop is a via point.
* Via modal to add via information to a stop.

I did also recognize a couple of components along the way that could/should be refactored to make them a bit more clear and logic more straight forward, but don't want to expand & prolong this PR anymore. And also it would be beneficial to write tests about them first.

2022-05-27 08:52 UTC, eleksi requested changes
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: all files reviewed, 19 unresolved discussions (waiting on @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/ViaForm.tsx` line 62 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33YJGx2sy_1WttbbqR:-N33YJGy0gvLIeYOPRHR:b-omlsg4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaForm.tsx#L62)):*
> ```XML
>         className={className}
>       >
>         <Row className="mb-5 space-x-10">
> ```

There seems to be 4 very similar of these Row components here. Maybe try to make them more reusable if possible?
___
*[`src/components/routes-and-lines/ViaModal.tsx` line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33Yz6n6jM5fC2nZIKm:-N33Yz6n6jM5fC2nZIKn:b2n0q2h) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaModal.tsx#L13)):*
> ```XML
> }
> 
> const ModalHeader = ({ onClose, heading }: HeaderProps): JSX.Element => {
> ```

This looks a lot like `ModalHeader` in `components/map/Modal.tsx`. Maybe combine them somehow?
___
*[`src/components/routes-and-lines/ViaModal.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33ZBYW0kvNvn81eOVz:-N33ZBYX5Sv6wVkSOuqs:boqqljw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaModal.tsx#L35)):*
> ```XML
>   return (
>     <div
>       className={`fixed top-1/2 left-1/2 z-10 -translate-y-1/2 -translate-x-1/2 overflow-auto overflow-y-auto bg-white  drop-shadow-md ${className}`}
> ```

Double space
___
*[`src/components/routes-and-lines/ViaModal.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33_6dA22Z0LOo19H9M:-N33_6dA22Z0LOo19H9N:bufqnn8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaModal.tsx#L35)):*
> ```XML
>   return (
>     <div
>       className={`fixed top-1/2 left-1/2 z-10 -translate-y-1/2 -translate-x-1/2 overflow-auto overflow-y-auto bg-white  drop-shadow-md ${className}`}
> ```

Are you sure there is no reusable component for this? If this unique kind of modal or should we create another reusable component like `Modal`, or edit it to support this kind of modal as well?
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33_ni1ACIw01CNyo68:-N33_ni1ACIw01CNyo69:b-q2kwt7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L8)):*
> ```XML
> import { useAppDispatch, useEditRouteJourneyPattern } from '../../../hooks';
> import { Row, Visible } from '../../../layoutComponents';
> import { openViaModal } from '../../../redux/slices/modals';
> ```

Put export to `/redux/index.ts` and import slice from `/redux`
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 90 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33cFrX2IAFvsaCfpOt:-N33cFrX2IAFvsaCfpOu:buipd23) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L90)):*
> ```XML
>       <td data-testid="stop-row-name">
>         <span>!Pysäkki X</span>
>         <Visible visible={!!isViaPoint}>
> ```

Is this not boolean? If it is, !! is not needed.
___
*[`src/graphql/route.ts` line 529 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33cvVv9No66zFq5KI9:-N33cvVv9No66zFq5KIA:bhs6c2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/graphql/route.ts#L529)):*
> ```XML
>       where: {
>         scheduled_stop_point_id: { _eq: $scheduled_stop_point_id }
>         journey_pattern_id: { _eq: $journey_pattern_id }
> ```

We have been doing these queries by route_id but I guess this is more future proof way to do it.
___
*[`src/graphql/route.ts` line 571 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33dFt47LvzcBT9EGCY:-N33dFt47LvzcBT9EGCZ:b-d1st12) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/graphql/route.ts#L571)):*
> ```XML
> `;
> 
> const GET_SCHEDULED_STOP_POINT_INFO_FOR_VIA_MODAL = gql`
> ```

I don't think we should bring UI component names to GQL queries. More like `GET_SCHEDULED_STOP_POINT_INFO_WITH_VIA_INFO` or something better.
___
*[`src/graphql/route.ts` line 607 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33dlK8BNpzZOPYIbtb:-N33dlK8BNpzZOPYIbtc:b-w6xagk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/graphql/route.ts#L607)):*
> ```XML
> 
> export const mapGetScheduledStopPointInfoForViaModal = (
>   result: ReturnType<typeof useGetScheduledStopPointInfoForViaModalQuery>,
> ```

If you want, you could also use `GqlQueryResult`. It covers also `ApolloQueryResult`



_Code snippet:_
```XML
GqlQueryResult<GetScheduledStopPointInfoForViaModalQuery>
```
___
*[`src/hooks/line-details/useViaModal.ts` line 10 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33eA7y2mp38tHKjwl4:-N33eA7y2mp38tHKjwl5:bxcn3bj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/hooks/line-details/useViaModal.ts#L10)):*
> ```XML
> import { mapGetScheduledStopPointInfoForViaModal } from '../../graphql';
> import { selectViaModal } from '../../redux';
> import { closeViaModal } from '../../redux/slices/modals';
> ```

Same here, import from `/redux`
___
*[`src/hooks/line-details/useViaModal.ts` line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33eOzL3Ff_IsmRaesZ:-N33eOzM12qkJDBRXZgD:b-340o19) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/hooks/line-details/useViaModal.ts#L18)):*
> ```XML
>   const [updateViaInfo] = usePatchScheduledStopPointViaInfoMutation();
>   const [removeViaInfo] = useRemoveScheduledStopPointViaInfoMutation();
>   const viaModalSelector = useAppSelector(selectViaModal);
> ```

I think this should not be called selector, as it already contains the fields fetched. More like `viaModalData` or something else.
___
*[`src/hooks/line-details/useViaModal.ts` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33eeem4GsRsqcw2IlD:-N33eeem4GsRsqcw2IlE:b3jmmu4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/hooks/line-details/useViaModal.ts#L22)):*
> ```XML
>   const dispatch = useAppDispatch();
> 
>   const result = useGetScheduledStopPointInfoForViaModalQuery({
> ```

Would make it more readable if it was named something like `stopResult`
___
*[`src/hooks/line-details/useViaModal.ts` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33f1RL0lMJ_TUDnWIM:-N33f1RL0lMJ_TUDnWIN:b-w1ntum) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/hooks/line-details/useViaModal.ts#L56)):*
> ```XML
>         },
>       });
>       dispatch(closeViaModal());
> ```

These last two rows of this `onSubmit` function could be outside the hook. Now we are mixing db queries with UI logic, which is not optimal. 

I probably also would then wrap onSubmit in the ui component with try and show error if it failed, success toast if it succeeded.
___
*[`src/hooks/line-details/useViaModal.ts` line 75 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33fYCECEUK2UM7Drnc:-N33fYCECEUK2UM7Drnd:bcdc420) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/hooks/line-details/useViaModal.ts#L75)):* [...]

2022-05-27 10:27 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: all files reviewed, 27 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`src/components/routes-and-lines/ViaForm.tsx` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33yBcR9BI_fgdRfPMV:-N33yBcR9BI_fgdRfPMW:b-f5pc4z) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaForm.tsx#L12)):*
> ```XML
> 
> export const schema = z.object({
>   viaInfo: z.object({
> ```

I'd rather keep the form schema closer to the database schema to help mapping between the values.

```
z.object({
  viaPointName: localizedStringRequired,
  viaPointShortName: localizedStringRequired,
});
```

(and as we discussed, the isViaPoint is a computed value so it shouldn't be part of the form schema)
___
*[`src/components/routes-and-lines/ViaForm.tsx` line 62 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33YJGx2sy_1WttbbqR:-N33ywxq8IO03nMuKAVW:bv9vik4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaForm.tsx#L62)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

There seems to be 4 very similar of these Row components here. Maybe try to make them more reusable if possible?
</blockquote></details>

I actually made a component for this, called StringInput. But it's not yet in main... however, you could steal it for your own PR if you want ;) 

Component: https://github.com/HSLdevcom/jore4-ui/blob/origin-destination-name/src/components/forms/common/StringInput.tsx
Usage sample: https://github.com/HSLdevcom/jore4-ui/blob/origin-destination-name/src/components/forms/route/TerminusNameInputs.tsx
___
*[`src/components/routes-and-lines/line-details/LineDetailsPage.tsx` line 118 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N34-4yIEky5_dNKgD4V:-N33zlBC6jSOEAThMtH-:b-4185u5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/LineDetailsPage.tsx#L118)):*
> ```XML
>   };
> 
>   const isViaModalOpen = useAppSelector(selectViaModal).isOpen;
> ```

just make a separate selector for this ;)
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 113 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N34-nro-jM99HhlPtBt:-N34-nrp-TFfVs4Ad859:b-6eqmn9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L113)):*
> ```XML
>       <td>&nbsp;</td>
>       <td>
>         <SimpleDropdownMenu
> ```

these are getting too tightly coupled. Please extract this as its own component e.g. to the top of this file.

```
const StopDropdown: React.FC = () => {
  ... all event handlers nicely separated from the parent component
  return (
    <SimpleDropdownMenu>...</SimpleDropdownMenu>
  )
}
```
___
*[`src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap` line 478 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N340UBw2TjXv_sIyIQf:-N340UBw2TjXv_sIyIQg:byteljb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap#L478)):*
> ```
>             data-testid="stop-row-validity-period"
>           >
>             Voimassa 1.1.2021 - 13.12.2023
> ```

umm, how did this stop suddenly become part of this route? It smells like this test is failing for a reason. Did the logic somehow change?
___
*[`src/generated/fontello/css/hsl-icons.css` line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N340jyq1NjAXh1fW1U5:-N340jyq1NjAXh1fW1U6:b-8ldwtb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/generated/fontello/css/hsl-icons.css#L3)):*
> ```CSS
> @font-face {
>   font-family: 'hsl-icons';
>   src: url('../font/hsl-icons.eot?14414808');
> ```

could you add a section to the README that how to export icons with fontello and have the circle around them? Thanks!
___
*[`src/graphql/route.ts` line 529 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33cvVv9No66zFq5KI9:-N3411Az6lotyIUwggaX:bkuxyub) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/graphql/route.ts#L529)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

We have been doing these queries by route_id but I guess this is more future proof way to do it.
</blockquote></details>

this table does not have a route_id
___
*[`src/graphql/route.ts` line 592 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N341TB_BkUnlb87Mn3k:-N341TB_BkUnlb87Mn3l:b-xf6qaz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/graphql/route.ts#L592)):*
> ```XML
>           label
>         }
>         scheduled_stop_point_in_journey_patterns {
> ```

umm, why are you interested that
___
*[`src/hooks/line-details/useViaModal.ts` line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N341oTIB0ldB8jftA4u:-N341oTIB0ldB8jftA4v:b-u73am) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/hooks/line-details/useViaModal.ts#L34)):*
> ```XML
>     if (stopInfo) {
>       await updateViaInfo({
>         variables: {
> ```

please use the hook logic flow we've introduced before, in other hooks
1. prepareEdit - validates the form data and generates a change set. The change set should be written in a form that can be presented to the user (so it should contain e.g. the route's and stop's information)
2. mapEditChangesToVariables - maps these changes to the graphql mutation variables
3. editMutation - execute the edit graphql mutation and do all the aftereffects (e.g. removeFromApolloCache)
___
*[`src/hooks/line-details/useViaModal.ts` line 62 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N342Xyj75zExXoupWZS:-N342Xyj75zExXoupWZT:b-nearf0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/hooks/line-details/useViaModal.ts#L62)):*
> ```XML
> 
>   const onRemove = async () => {
>     await removeViaInfo({
> ```

this should be split to those 3 functions I mentioned in my previous comment
___
*[`src/redux/slices/modals.ts` line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33ha-U4Q-hYJdNWgdR:-N33zyXD9Oz0j1Lp6weP:bljvmv4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/redux/slices/modals.ts#L16)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Empty string or just optional field with undefined initial state? We have been using undefined in cases like these.
</blockquote></details>

yes, let's definitely make these undefined, '' is an invalid value for these


<!-- Sent from Reviewable.io -->

2022-05-27 10:35 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: all files reviewed, 28 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`src/hooks/line-details/useViaModal.ts` line 84 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N343yCJBVhl8Jj-H8_E:-N343yCJBVhl8Jj-H8_F:b-wpcoui) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/hooks/line-details/useViaModal.ts#L84)):*
> ```XML
> 
>   const defaultValues = {
>     isViaPoint: stopInfo?.is_via_point,
> ```

This should rather be made into a separate mapping function:
```
mapStopToViaPointInfo = (stop: ScheduledStopPoint) => {
  const viaPointInfo: FormState = {
    viaPointName: ...
    viaPointShortName: ...
  }
}
```
___
*[`src/redux/slices/modals.ts` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33gxNMBTthjtzjshIP:-N343p8u5IX5cpMH9h8b:b-7eflro) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/redux/slices/modals.ts#L22)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

If we have `modals` store, we should probably move `modalMap` store here as well.
</blockquote></details>

maybe at some point... but this is not in scope for this PR


<!-- Sent from Reviewable.io -->

2022-05-29 08:43 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: 17 of 38 files reviewed, 26 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/ViaForm.tsx` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33yBcR9BI_fgdRfPMV:-N34h5oKE0haxFqbMxeY:brwxlu7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaForm.tsx#L12)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd rather keep the form schema closer to the database schema to help mapping between the values.

```
z.object({
  viaPointName: localizedStringRequired,
  viaPointShortName: localizedStringRequired,
});
```

(and as we discussed, the isViaPoint is a computed value so it shouldn't be part of the form schema)
</blockquote></details>

Thanks, I'll fix this. And what comes to the `IsViaPoint`, as it turned out it can't be generated for now, so I guess that can stay.
___
*[`src/components/routes-and-lines/ViaForm.tsx` line 62 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33YJGx2sy_1WttbbqR:-N34hr5J7w9hwtNFyfkE:bokt0br) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaForm.tsx#L62)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I actually made a component for this, called StringInput. But it's not yet in main... however, you could steal it for your own PR if you want ;) 

Component: https://github.com/HSLdevcom/jore4-ui/blob/origin-destination-name/src/components/forms/common/StringInput.tsx
Usage sample: https://github.com/HSLdevcom/jore4-ui/blob/origin-destination-name/src/components/forms/route/TerminusNameInputs.tsx
</blockquote></details>

I'll check If I could use the same StringInput :+1: Thanks!
___
*[`src/components/routes-and-lines/ViaModal.tsx` line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33Yz6n6jM5fC2nZIKm:-N34i6ll15jhuA48uOUb:b-knytwp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaModal.tsx#L13)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This looks a lot like `ModalHeader` in `components/map/Modal.tsx`. Maybe combine them somehow?
</blockquote></details>

Ah nice that you noticed. That was actually the original plan, but forgot in the end. But there could be some more refactor to the `<Modal />` component, but that wont be in this PR.
___
*[`src/components/routes-and-lines/ViaModal.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33_6dA22Z0LOo19H9M:-N34iMYG8nPzf3-x3zQ1:b-2l54go) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaModal.tsx#L35)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Are you sure there is no reusable component for this? If this unique kind of modal or should we create another reusable component like `Modal`, or edit it to support this kind of modal as well?
</blockquote></details>

Yeah, there are couple of different kind of modals, and at least at first I tried to use the Modal we already had, but had some problems with it. Also thought that maybe could be tried to refactor the Modal to be reusable a little bit better, but I've already done many refactors from "under" this PR and because of the timetables decided to leave this one out. There are couple of other components also that should be refactored to be more. I can still check if there is a quick way to edit it, but let's see.
My suggestion: Do the generic modal component in another PR.
___
*[`src/components/routes-and-lines/ViaModal.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33ZBYW0kvNvn81eOVz:-N3Acr5U9Gracc4EJ0RA:b-8fx2u7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaModal.tsx#L35)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Double space
</blockquote></details>

:+1: 
___
*[`src/components/routes-and-lines/line-details/LineDetailsPage.tsx` line 118 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N34-4yIEky5_dNKgD4V:-N34jGLLCdAsqkCJsUjn:b-xoph9v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/LineDetailsPage.tsx#L118)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

just make a separate selector for this ;)
</blockquote></details>

Ah okay! Was not sure which one was the way to go. Thanks!
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33_ni1ACIw01CNyo68:-N3AdcT91qWe4vt7UpN7:b-hay2ib) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L8)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Put export to `/redux/index.ts` and import slice from `/redux`
</blockquote></details>

Thanks! 
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 90 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33cFrX2IAFvsaCfpOt:-N34jgAbAVWsCORtbvxe:b-o4yhlx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L90)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Is this not boolean? If it is, !! is not needed.
</blockquote></details>

Because of this:
`const isViaPoint = scheduledStopPointInJourneyPattern?.is_via_point;` it might be undefined and that is not accepted by the `visible` attribute.
But now that you say, maybe I should tweak the `<Visible>` component to allow undefined and then default it to false.
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 113 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N34-nro-jM99HhlPtBt:-N34krEQAPUXO0QvtD2S:b-8zvqip) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L113)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

these are getting too tightly coupled. Please extract this as its own component e.g. to the top of this file.

```
const StopDropdown: React.FC = () => {
  ... all event handlers nicely separated from the parent component
  return (
    <SimpleDropdownMenu>...</SimpleDropdownMenu>
  )
}
```
</blockquote></details>

I nearly already extracted this to own file, but then retraced my steps because the `onAddToRoute` is coming from props and I would like to refactor that as well. But not for this PR. 
But I guess I can do a "temp" extraction and iterate it later.
___
*[`src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap` line 478 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N340UBw2TjXv_sIyIQf:-N3AhzPB18-wy6ZXVrc6:b-vm3i25) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap#L478)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

umm, how did this stop suddenly become part of this route? It smells like this test is failing for a reason. Did the logic somehow change?
</blockquote></details>

I think this was broken before. `RouteStopsTable.spec.tsx` `const mockResponse` did not return this one, which I added:
```
journey_ [...]

2022-06-09 09:30 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: 13 of 43 files reviewed, 21 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap` line 478 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N340UBw2TjXv_sIyIQf:-N41vzpO2PY6HZDDnmLT:b-kl8g4c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/__snapshots__/RouteStopsTable.spec.tsx.snap#L478)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think this was broken before. `RouteStopsTable.spec.tsx` `const mockResponse` did not return this one, which I added:
```
journey_pattern: {
   on_route_id: '03d55414-e5cf-4cce-9faf-d86ccb7e5f98',
},
```
And now they belong to the route as I think they should. So before this edit: none of the stops belonged to the route in the snapshot
</blockquote></details>

good catch!



_Code quote (from src/components/routes-and-lines/line-details/StopActionsDropdown.tsx):_
```XML
  const scheduledStopPointInJourneyPattern =
    stop.scheduled_stop_point_in_journey_patterns.find(
      (point) =>
        point.scheduled_stop_point_id === stop.scheduled_stop_point_id &&
        point.journey_pattern.on_route_id === routeId,
    );
```
___
*[`src/generated/fontello/css/hsl-icons.css` line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N340jyq1NjAXh1fW1U5:-N46LX9f63t7HXgiJItt:b5oz0s2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/generated/fontello/css/hsl-icons.css#L3)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yes, actually I only did half of the job by finding out possible reasons why it was missing from some of the exports. But because I have only readonly-rights to figma, I couldn't test them, so we did this with Juha. Juha should know how to do it properly. (It involves some required actions in figma to include the circles)
Here is one reference https://medium.com/mabiloft/we-designed-an-icon-font-with-figma-and-fontello-and-it-has-not-been-a-piece-of-cake-b2948973738e to the problem.
</blockquote></details>

I added the instructions to the README
___
*[`src/redux/slices/modals.ts` line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33ha-U4Q-hYJdNWgdR:-N46n5DN9faOJ2FzRDgF:b-lmws7p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/redux/slices/modals.ts#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm. Im not completely sure if undefined is the way to go here. Because these values are used in the hook which fetches the information:
```
const scheduledStopResult = useGetScheduledStopPointWithViaInfoQuery({
    variables: {
      journey_pattern_id: journeyPatternId,
      scheduled_stop_point_id: scheduledStopPointId,
    },
  });
```
And this hook will not accept undefined for the variables. As it is a hook, we cannot make the hook call conditional by checking before if the values exist. So I don't think that we can make these undefined. (At first I also defined these 
initialState variables as undefined.


</blockquote></details>

I fixed it to be undefined


<!-- Sent from Reviewable.io -->

2022-06-15 09:56 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: 12 of 46 files reviewed, 36 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/components/common/index.ts` line 1 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aRdqW1h-62Nq-yzyH:-N4aRdqW1h-62Nq-yzyI:b-ih31n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/common/index.ts#L1)):*
> ```XML
> export * from './ModalHeader';
> ```

What is difference of `/components/common` and `uiComponents`? I could understand if this would be e.g. in /components/modal or something like that and if there could be more modal-related components, but now this feels like this is in a wrong place.
___
*[`src/components/common/ModalHeader.tsx` line 4 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aS5VXEjyKJXNCZdcg:-N4aS5VXEjyKJXNCZdch:b-ku2dt2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/common/ModalHeader.tsx#L4)):*
> ```XML
> import { CloseIconButton } from '../../uiComponents';
> 
> interface HeaderProps {
> ```

Convention has been to call these just Props
___
*[`src/components/common/ModalHeader.tsx` line 11 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aSCa42ZBFNjPhWzNj:-N4aSCa42ZBFNjPhWzNk:bg12twn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/common/ModalHeader.tsx#L11)):*
> ```XML
> export const ModalHeader = ({ onClose, heading }: HeaderProps): JSX.Element => {
>   return (
>     <div className="border border-light-grey bg-background px-14 py-7">
> ```

Unnecessary div layer, classNames could be given directly to Row
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 30 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aSYZW-JO9fTkXhq1W:-N4aSYZW-JO9fTkXhq1X:bu72tvh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L30)):*
> ```XML
> 
>   // find the journey pattern instance that belongs to this route
>   const scheduledStopPointInJourneyPattern =
> ```

Feels a bit weird to have this kind of logic in UI component.  Why we can't query the right data straight away and allow hasura to do the filtering?
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 36 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aSrMc1YMLeY-_4Xv9:-N4aSrMdDKpcFjGJDMev:b-i37fvp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L36)):*
> ```XML
> 
>   // does the stop belong to this route's journey pattern?
>   const doesStopBelongToJourneyPattern = !!scheduledStopPointInJourneyPattern;
> ```

stopBelongsTo...

"does" is unnecessarily verbose prefix for boolean flag
___
*[`src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 8 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aTE_90NMkAncxNIhp:-N4aTE_90NMkAncxNIhq:b-82iydx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L8)):*
> ```XML
> import { showDangerToast, showSuccessToast } from '../../../utils';
> 
> interface StopActionsDropdownProps {
> ```

Props
___
*[`src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 23 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aTI171_5gWcYkgqzL:-N4aTI171_5gWcYkgqzM:b6m7vl2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L23)):*
> ```XML
> 
>   // find the journey pattern instance that belongs to this route
>   const scheduledStopPointInJourneyPattern =
> ```

Do we have to do filtering in ui component? If hasura can't do this, it would be nice to have some kind of selector/util/something for this.
___
*[`src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 29 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aTwmC57ZdKtuCULKR:-N4aTwmC57ZdKtuCULKS:b-r5vybe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L29)):*
> ```XML
> 
>   // does the stop belong to this route's journey pattern?
>   const doesStopBelongToJourneyPattern = !!scheduledStopPointInJourneyPattern;
> ```

stopBelongsTo...
___
*[`src/redux/slices/modals.ts` line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33ha-U4Q-hYJdNWgdR:-N4aldSa22UwyCN4tNfb:b-b1td8v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/redux/slices/modals.ts#L16)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I fixed it to be undefined
</blockquote></details>

Seems to still be false and not undefined
___
*[`src/redux/slices/modals.ts` line 7 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aln5C1bI_pirfPodB:-N4aln5DAOojiUVWCshx:b-s6cty7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/redux/slices/modals.ts#L7)):*
> ```XML
> }
> 
> interface ViaModalState {
> ```

Could be inlined to IState as it seems like this is not used individually anywhere.
___
*[`src/components/routes-and-lines/via/ViaForm.tsx` line 99 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4ajB53DFz-yoaKXlhY:-N4ajB53DFz-yoaKXlhZ:b3x6tbi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/via/ViaForm.tsx#L99)):*
> ```XML
>           />
>         </Row>
>         <Row className="mb-5 space-x-10">
> ```

Same class name is now defined 4 times, could consider extracting it to a variable or extracting Row to own local component.
___
*[`src/components/routes-and-lines/via/ViaModal.tsx` line 65 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4amBbz17SzyQBTeQbr:-N4amBbz17SzyQBTeQbs:bfsy3pc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/via/ViaModal.tsx#L65)):*
> ```XML
>       const variables = mapEditChangesToVariables(changes);
> 
>       editMutation(variables);
> ```

This is async thing that we should await.

Now this is async function without single await statement.
___
*[`src/components/routes-and-lines/via/ViaModal.tsx` line 99 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4ajl7l00BZpi1h-T3v:-N4ajl7l00BZpi1h-T3w:bxvrg5d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/via/ViaModal.tsx#L99)):*
> ```XML
>   return (
>     <div
>       className={`fixed top-1/2 left-1/2 z-10 -translate-y-1/2 -translate-x-1/2 overflow-auto overflow-y-auto bg-white drop-shadow-md ${className}`}
> ```

This pretty complex class name string is copypasta from `src/components/routes-and-lines/common/ConflictResolverModal.tsx`. Not sure if we want to do anything with it though.
___
*[`src/hooks/via/useEditViaInfo.ts` line 10 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4akRMb9TwUPkRx3p29:-N4akRMb9TwUPkRx3p2A:bfoqe8w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/hooks/via/useEditViaInfo.ts#L10)):*
> ```XML
>   journeyPatternId: UUID;
>   stopLabel: string;
>   isViaPoint: boolean;
> ```

These are inconsistent with other edit hooks, see e.g. `src/hooks/lines/useEditLine.ts`.



_Code quote:_
```XML
interface EditChanges {
  journeyPatternId: UUID;
  stopLabel: string;
  isViaPoint: boolea [...]

2022-06-15 10:11 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: 12 of 46 files reviewed, 33 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/redux/slices/modals.ts` line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33ha-U4Q-hYJdNWgdR:-N4apgiIDrrvNVZDkpSS:bqspdxe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/redux/slices/modals.ts#L16)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Seems to still be false and not undefined
</blockquote></details>

they are undefined. Are you looking at the correct revision?
```
journeyPatternId: undefined,
stopLabel: undefined,
```


<!-- Sent from Reviewable.io -->

2022-06-15 10:47 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: 12 of 46 files reviewed, 34 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 81 at r12](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4au5YNCCxJcwLT0Mnm:-N4au5YNCCxJcwLT0Mnn:bjiulx3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/408c742dd4818440cce89496e5374ff0b21cb51a/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L81)):*
> ```XML
>         <button
>           type="button"
>           onClick={() => onAddToRoute(stop.scheduled_stop_point_id)}
> ```

This needs to be `stop.label` since the reference has changed. 

There is also something else still wrong with removing stop from journey pattern. But this problem is also in main branch.
___
*[`src/hooks/via/useRemoveViaInfo.ts` line 34 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4al5Cv0mHejf5jKBBn:-N4ax-8P5r58RNpJ58RS:b-351gs0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/hooks/via/useRemoveViaInfo.ts#L34)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Same inconsistency here as with edit mutation.

Not sure if we want to use word "remove" or "delete"?
</blockquote></details>

I was thinking about the naming, and chose "remove" because we do not delete any database dows, only the via-information from a jointable is removed. But I'm not sure if that is the right logic for the naming, maybe not.


<!-- Sent from Reviewable.io -->

2022-06-15 10:49 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: 12 of 46 files reviewed, 32 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/components/common/ModalHeader.tsx` line 4 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aS5VXEjyKJXNCZdcg:-N4ardHsEriRFZwIJLEy:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/common/ModalHeader.tsx#L4)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Convention has been to call these just Props
</blockquote></details>

Done.
___
*[`src/components/common/ModalHeader.tsx` line 11 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aSCa42ZBFNjPhWzNj:-N4arnay4mhcK48saQ4E:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/common/ModalHeader.tsx#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Unnecessary div layer, classNames could be given directly to Row
</blockquote></details>

Done.
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 8 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33_ni1ACIw01CNyo68:-N4arp9D4UReagdjQQTU:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L8)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Thanks! 
</blockquote></details>

Done.
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 90 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33cFrX2IAFvsaCfpOt:-N4ayZPgDxjixDU08M4B:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L90)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Because of this:
`const isViaPoint = scheduledStopPointInJourneyPattern?.is_via_point;` it might be undefined and that is not accepted by the `visible` attribute.
But now that you say, maybe I should tweak the `<Visible>` component to allow undefined and then default it to false.
</blockquote></details>

Done.
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 30 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aSYZW-JO9fTkXhq1W:-N4auisO1M6S4kstAfFG:b-6jz2s6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L30)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Feels a bit weird to have this kind of logic in UI component.  Why we can't query the right data straight away and allow hasura to do the filtering?
</blockquote></details>

Couldn't find a way to reference the parent object's (route) id from the nested object (journey_pattern), so couldn't achieve this with a graphql query. Probably there's a way, but I didn't find it worth the effort (yet) to hunt down a nicer solution for this
___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 36 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aSrMc1YMLeY-_4Xv9:-N4avDSE8OwS2APfKqLP:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L36)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

stopBelongsTo...

"does" is unnecessarily verbose prefix for boolean flag
</blockquote></details>

Done.
___
*[`src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 8 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aTE_90NMkAncxNIhp:-N4ayedxAd106l8W_x01:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Props
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-16 09:39 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: 12 of 47 files reviewed, 30 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 23 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aTI171_5gWcYkgqzL:-N4fqpal7TVxyQJiXdIl:bxpvacw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L23)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we have to do filtering in ui component? If hasura can't do this, it would be nice to have some kind of selector/util/something for this.
</blockquote></details>

in the current query it's not possible to reference a parent object from within a nested object that would achieve this filtering. However there might be a way if we split the graphql query to smaller bits and pieces. I'd rather not bloat this PR any longer, let's return to this later as Eetu also has changes to this same stuff
___
*[`src/components/routes-and-lines/line-details/StopActionsDropdown.tsx` line 29 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aTwmC57ZdKtuCULKR:-N4frJYc-XeaJbNceNDd:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/StopActionsDropdown.tsx#L29)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

stopBelongsTo...
</blockquote></details>

Done.
___
*[`src/redux/slices/modals.ts` line 7 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aln5C1bI_pirfPodB:-N4fsQlN2xPwbFi2A-Gz:b-xcvy44) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/redux/slices/modals.ts#L7)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Could be inlined to IState as it seems like this is not used individually anywhere.
</blockquote></details>

There will be other modal states coming here in the future; better if this stays on its own
___
*[`src/components/routes-and-lines/ViaModal.tsx` line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33Yz6n6jM5fC2nZIKm:-N4frk-f5-csKwtkMbyu:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaModal.tsx#L13)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah nice that you noticed. That was actually the original plan, but forgot in the end. But there could be some more refactor to the `<Modal />` component, but that wont be in this PR.
</blockquote></details>

Done.
___
*[`src/components/routes-and-lines/ViaModal.tsx` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33ZBYW0kvNvn81eOVz:-N4frqpuAyMR3gEeQVKw:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/components/routes-and-lines/ViaModal.tsx#L35)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[`src/components/routes-and-lines/via/ViaForm.tsx` line 99 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4ajB53DFz-yoaKXlhY:-N4frXZJ8bTVjEuu57iG:bytccob) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/via/ViaForm.tsx#L99)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Same class name is now defined 4 times, could consider extracting it to a variable or extracting Row to own local component.
</blockquote></details>

I'd rather not do this now
___
*[`src/components/routes-and-lines/via/ViaModal.tsx` line 65 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4amBbz17SzyQBTeQbr:-N4frpgo1DsiBvromZjk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/via/ViaModal.tsx#L65)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This is async thing that we should await.

Now this is async function without single await statement.
</blockquote></details>

Done.
___
*[`src/hooks/via/useEditViaInfo.ts` line 10 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4akRMb9TwUPkRx3p29:-N4fs9lu4VDrfx68RqrL:b-huou7i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/hooks/via/useEditViaInfo.ts#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

These are inconsistent with other edit hooks, see e.g. `src/hooks/lines/useEditLine.ts`.
</blockquote></details>

I've improved this a bit
___
*[`src/hooks/via/useEditViaInfo.ts` line 53 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4akrpc4sAKpdESvLbN:-N4fsIMhEjaUinh8ypZd:b-huou7i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/hooks/via/useEditViaInfo.ts#L53)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Also this is inconsistent with rest of the edit hooks. Those don't wrap mutation to async/await function.
</blockquote></details>

I've improved this a bit
___
*[`src/hooks/via/useRemoveViaInfo.ts` line 34 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4al5Cv0mHejf5jKBBn:-N4fsKNREVeZ3HtWFPEl:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/hooks/via/useRemoveViaInfo.ts#L34)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I was thinking about the naming, and chose "remove" because we do not delete any database dows, only the via-information from a jointable is removed. But I'm not sure if that is the right logic for the naming, maybe not.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-16 11:42 UTC, tk-vincit approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/201)* status: 12 of 47 files reviewed, 17 unresolved discussions (waiting on @eleksi, @HenrikHartiala, @pallost, and @tk-vincit)

___
*[`src/components/routes-and-lines/line-details/RouteStopsRow.tsx` line 30 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4aSYZW-JO9fTkXhq1W:-N4gGS2B3tKJCZf4gSXf:b-7v2i07) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/line-details/RouteStopsRow.tsx#L30)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Couldn't find a way to reference the parent object's (route) id from the nested object (journey_pattern), so couldn't achieve this with a graphql query. Probably there's a way, but I didn't find it worth the effort (yet) to hunt down a nicer solution for this
</blockquote></details>

Ok, let's go with this for now. You can consider if we want to add comment explaining the situation.
___
*[`src/redux/slices/modals.ts` line 16 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N33ha-U4Q-hYJdNWgdR:-N4gJEuRDZy2Y1qyLUqS:b-t7e79x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/2456d7792b31986615eee335f4f65a085314f22d/src/redux/slices/modals.ts#L16)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

they are undefined. Are you looking at the correct revision?
```
journeyPatternId: undefined,
stopLabel: undefined,
```
</blockquote></details>

Ah, made parsing error in my head and was thinking this discussion was about isOpen parameter. 
___
*[`src/components/routes-and-lines/via/ViaForm.tsx` line 99 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4ajB53DFz-yoaKXlhY:-N4gHA9m2JNEG7A47jAR:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/components/routes-and-lines/via/ViaForm.tsx#L99)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd rather not do this now
</blockquote></details>

OK
___
*[`src/hooks/via/useEditViaInfo.ts` line 10 at r11](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4akRMb9TwUPkRx3p29:-N4gIBYRAD94IE44J7jy:br0bzsz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/f747cef91beb0d11fbc7b42745ae58a2c13fb394/src/hooks/via/useEditViaInfo.ts#L10)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I've improved this a bit
</blockquote></details>

Better now.
___
*[`src/hooks/via/useEditViaInfo.ts` line 62 at r17](https://reviewable.io/reviews/hsldevcom/jore4-ui/201#-N4gIIeE82LhxTC6wWyI:-N4gIIeE82LhxTC6wWyJ:bx8e7j6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e7709c22914d8658c93fca97eb93deb0a33b25fb/src/hooks/via/useEditViaInfo.ts#L62)):*
> ```XML
>   });
> 
>   const executeMutation = (
> ```

Seems like this now just wraps `myFunction`  to `(params) => myFunction(params)` like pattern (or actually `(params) => myFunction({ variables: params ))`. Not sure if this is worth it cause this makes this inconsistent with rest of the mutation hooks.

Same thing in remove hook below.


<!-- Sent from Reviewable.io -->

2022-06-16 12:25 UTC, closed without merging