Add and modify map tests
HSLdevcom/jore4-ui pull request #275
Opened 2022-07-28 09:31 UTC by HenrikHartiala

* Adds test-utils file to handle database actions when initializing for tests
* Adds map creator file for reusability and easier way to create routes (and stops)
* Stop test which creates two stops on map to same infralink, but on different sides of the road. It then draws two routes which are going on opposite directions through that infralink and this checks that the correct added stops are included in both routes.

2022-08-02 10:45 UTC, eleksi reviewed
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: all files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/e2e/creators/map.ts` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8T7IWl4wzxnu00LCr7:-N8T7IWl4wzxnu00LCr8:b-4hvneo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L56)):*
> ```XML
> }
> 
> export class MapCreator {
> ```

To me `MapCreator` implies creation of a map. I understand what it means here is things being created IN map, just wondering if there could be a better name for this.

e.g. `MapContentCreator`, `MapItemCreator` or something else
___
*[`cypress/e2e/creators/map.ts` line 147 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8Snuk1EJB3h6dMotbY:-N8Snuk2-xkA6LVvwtyF:b-tb7qjo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L147)):*
> ```XML
>     routePoints.forEach((routePoint) => {
>       this.mapEditor.clickAtPositionOnRouteEditorFromMapMarkerByTestId(
>         routePoint.x,
> ```

Would look cleaner if routePoint could be used as a parameter.
___
*[`cypress/e2e/creators/map.ts` line 153 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8SneAMD1MfAHRL02d2:-N8SneAN7mTvtP9sDY8I:bt7ss5e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L153)):*
> ```XML
>     });
> 
>     this.mapEditor.clickNthCreatedRectangle(1);
> ```

What for? Can you add a comment, I don't understand what does this do and why it is done.
___
*[`cypress/pageObjects/MapEditor.ts` line 26 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8SmcyI9mTzfp5vTVy-:-N8SmcyI9mTzfp5vTVy0:b-xj0io) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L26)):*
> ```XML
>    */
>   clickAtPositionOnRouteEditorFromMapMarkerByTestId(
>     xpos: number,
> ```

Could the parameter just be `StopPoint`?
___
*[`cypress/pageObjects/MapEditor.ts` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8T8GqSBwrY5-NQ0-m1:-N8T8GqSBwrY5-NQ0-m2:b-7stf0i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L33)):*
> ```XML
>       .parent()
>       .then((mark) => {
>         const x = mark.position().left;
> ```

Could this be wrapped in a function to avoid code duplication?

e.g.



_Code snippet:_
```XML
const {x,y} = getMarkLPositionInEditorCoordinates(mark):
```
___
*[`cypress/pageObjects/MapEditor.ts` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8SmpVJ4gOYfM0TVGxu:-N8SmpVJ4gOYfM0TVGxv:bno0jw6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L35)):*
> ```XML
>         const x = mark.position().left;
> 
>         // Map header heigth needs to be subtracted from the y coordinate
> ```

Typo: height


<!-- Sent from Reviewable.io -->

2022-08-02 11:12 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: all files reviewed, 15 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

___
*[`cypress/e2e/creators/map.ts` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TCNYxBBmkeEHg5ROg:-N8TCNYxBBmkeEHg5ROh:b-kqo5fg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L22)):*
> ```XML
> }
> 
> export enum Priority {
> ```

Shame we can't currently import these directly from ui project side...

Maybe we still should store this kind of duplicate code from ui project to clearly separate file so that those can be easily removed if importing those becomes available at some point? Or at least then it would be easier to see that this kind of stuff is just duplicate definitions from ui side and should be kept 1:1 with the original implementations.
___
*[`cypress/e2e/creators/map.ts` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TDqyeERR0xqHevQJ5:-N8TDqyeERR0xqHevQJ6:bfi330y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L33)):*
> ```XML
> }
> 
> interface CreateStopParameters {
> ```

I don't understand this and next datatype. Are these something user is going to enter to ui form? If yes, maybe their name and/or location in codebase should reflect that somehow.
___
*[`cypress/e2e/creators/map.ts` line 50 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TCtzb39Gjz-u-OAip:-N8TCtzb39Gjz-u-OAiq:b-z3ntxd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L50)):*
> ```XML
> interface CreateRouteParameters {
>   routeFormInfo: RouteFormInfo;
>   priority?: Priority;
> ```

Priority, startDate and endDate are in multiple interfaces. Should you rather define those once and then extend these interfaces?

Also wondering if string is correct type for dates.



_Code quote:_
```XML
  priority?: Priority;
  startDate: string;
  endDate?: string;
```
___
*[`cypress/e2e/creators/map.ts` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8T7IWl4wzxnu00LCr7:-N8TD4ox4gfhKkspRNC-:bcmmusx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L56)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

To me `MapCreator` implies creation of a map. I understand what it means here is things being created IN map, just wondering if there could be a better name for this.

e.g. `MapContentCreator`, `MapItemCreator` or something else
</blockquote></details>

I'm not familiar whit this kind of "creator" pattern. Anyway: seems like this class does plenty of things that are more or less related and its not clear what each function does. E.g. "setPriority" - does it affect priority of stop or route or what?

I suggest we refactor this so that responsibilities of this became more clear, otherwise this easily becomes something that is difficult to maintain and makes it also difficult to refactor current e2e tests.
___
*[`cypress/pageObjects/MapEditor.ts` line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TEBTI2ogrTlXTaYa3:-N8TEBTI2ogrTlXTaYa4:b-71dfee) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L21)):*
> ```XML
> 
>   /** This will click the route editor on a point that has
>    *  given StopMarker as origin and then the xpos and ypos are added
> ```

I don't understand what xpos and ypos mean? And what is their relation to x and y on the code block below?
___
*[`cypress/pageObjects/MapEditor.ts` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TER4i9-KNE9zS7Z_8:-N8TER4i9-KNE9zS7Z_9:b-w7uroj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L31)):*
> ```XML
>   ) {
>     cy.getByTestId(testId)
>       .parent()
> ```

Same thing that I commented on the previous (?) PR: it smells a bit fishy to access parent of selected element. Do we really have to do this? If yes, please at least comment why.
___
*[`cypress/pageObjects/MapEditor.ts` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8T8GqSBwrY5-NQ0-m1:-N8TEdoC6td7cNwThddA:b-vbxlkr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L33)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Could this be wrapped in a function to avoid code duplication?

e.g.

</blockquote></details>

Is this duplicated somewhere? Anyway, this could make sense to separate this whole inline function into own function somewhere.
___
*[`cypress/pageObjects/MapEditor.ts` line 40 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TExFw2lp3xLXqodVB:-N8TExFw2lp3xLXqodVC:b111vov) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L40)):*
> ```XML
>         const y = mark.position().top - MAP_HEADER_HEIGHT;
> 
>         cy.get('#editor').click(x + xpos, y + ypos, {
> ```

Why not getByTestId?
___
*[`cypress/pageObjects/MapEditor.ts` line 41 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TEqq28cSftr9sJ-Ks:-N8TEqq28cSftr9sJ-Kt:b-9rjacf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L41)):*
> ```XML
> 
>         cy.get('#editor').click(x + xpos, y + ypos, {
>           force: true,
> ```

Please comment why force: true is needed, or is it already something that we do in all tests and should thus be self-evident?
___
*[`cypress/pageObjects/MapEditor.ts` line 61 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TF69h3rS7fuN_QPab:-N8TF69h3rS7fuN_QPac:b-gy3tu1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L61)):*
> ```XML
>         const x = mark.position().left;
> 
>         // Map header heigth needs to be subtracted from the y coordinate
> ```

OK, seems like above we have copypasta from this function. I commented about this in previous (?) PR already, but: if we cannot get rid of this pattenr, then please at least separate this hack to own function that we can use everywhere instead of copying hack to multiple places.
___
*[`cypress/pageObjects/MapEditor.ts` line 66 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TF-jx5266nYqO3y35:-N8TF-jx5266nYqO3y36:b111vov) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L66)):*
> ```XML
>         const y = mark.position().top - MAP_HEADER_HEIGHT;
> 
>         cy.get('canvas').click(x + xpos, y + ypos, {
> ```

Why not getByTestId?


<!-- Sent from Reviewable.io -->

2022-08-02 11:33 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: all files reviewed, 20 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

___
*[`cypress/e2e/stops.cy.ts` line 41 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TJMeV9QoZevOh6d2w:-N8TJMeV9QoZevOh6d2x:bowv1yx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L41)):*
> ```XML
>     });
> 
>     it(
> ```

Wondering if we really want to have all these things in one test case or rather in 2 test cases. Now we are kind of testing same stuff twice in one test case. And this test case is now quite long and can break from multiple reasons.

Debugging/fixing test cases is easier if each case is short and has limited reasons why it can fail.
___
*[`cypress/e2e/stops.cy.ts` line 43 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TI0b2E6IaJrLrm9p3:-N8TI0b2E6IaJrLrm9p4:b-3td9jk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L43)):*
> ```XML
>     it(
>       'Creates two stops on different sides of the road and includes them correcetly to different directioned routes',
>       { scrollBehavior: 'bottom', defaultCommandTimeout: 10000 },
> ```

Please comment why defaultCommandTimeout is increased to 10 seconds(?)
___
*[`cypress/e2e/stops.cy.ts` line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TICiNEpX80-DEcmdj:-N8TICiNEpX80-DEcmdk:b12coev) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L49)):*
> ```XML
>           stopFormInfo: { label: testStopLabel1 },
>           stopPoint: { x: 25, y: 25, stopTestId: 'H1234_10' },
>           startDate: '2022-01-01',
> ```

now that I see how tis interface is used I wonder if `startDate` should rather be called `startISODate` to make it self-evident for the user that what kind of string it is supposed to be.
___
*[`cypress/e2e/stops.cy.ts` line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TIlelAo6Z_qSfAAic:-N8TIlelAo6Z_qSfAAid:b3fpoue) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L64)):*
> ```XML
> 
>         toast.checkStopSubmitSuccess();
>         cy.getByTestId(`${testStopLabel1}_10`).should('exist');
> ```

Why not check this already after checking submitSuccess for the first time?

Also now when I see this testId I realise that it would probably make more sense to set priorities as enum string value instead of number. Now it is not clear where does "_10" comes.
___
*[`cypress/e2e/stops.cy.ts` line 127 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TJnmV02bY2U4utSBW:-N8TJnmW6FvHro_IUlBR:b-s71y4a) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L127)):*
> ```XML
>         mapCreator.createRoute({
>           routeFormInfo: {
>             finnishName: 'Testireitti pysäkit manual',
> ```

"pysäkit manual"? I don't understand why we are mixing languages here.
___
*[`cypress/e2e/test-utils.ts` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TK2EP8LdmXkegcvYE:-N8TK2EP8LdmXkegcvYF:bohh1v0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/test-utils.ts#L1)):*
> ```XML
> export const deleteLineByLabel = (label: string) => {
> ```

Nice that these have been separated to own file. :+1: 


<!-- Sent from Reviewable.io -->

2022-09-01 07:36 UTC, HenrikHartiala reviewed
A lot have changed due to many refactorings. I can also make a new PR if this became too chaotic to follow.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-:-NAryL2U2s5pmpIrBimH:b-q60c9c)* status: 1 of 20 files reviewed, 17 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`cypress/e2e/stops.cy.ts` line 41 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TJMeV9QoZevOh6d2w:-NAnysP29DDsUH50sY5J:b5s85zr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L41)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Wondering if we really want to have all these things in one test case or rather in 2 test cases. Now we are kind of testing same stuff twice in one test case. And this test case is now quite long and can break from multiple reasons.

Debugging/fixing test cases is easier if each case is short and has limited reasons why it can fail.
</blockquote></details>

I removed this test for now.
___
*[`cypress/e2e/stops.cy.ts` line 43 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TI0b2E6IaJrLrm9p3:-NAnyyNB-Znj1YdofF9u:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L43)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please comment why defaultCommandTimeout is increased to 10 seconds(?)
</blockquote></details>

Done.
___
*[`cypress/e2e/stops.cy.ts` line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TICiNEpX80-DEcmdj:-NAo-BMWDtfhPihs525F:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L49)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

now that I see how tis interface is used I wonder if `startDate` should rather be called `startISODate` to make it self-evident for the user that what kind of string it is supposed to be.
</blockquote></details>

Done.
___
*[`cypress/e2e/stops.cy.ts` line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TIlelAo6Z_qSfAAic:-N9B9baY9PCVhEfRGexz:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L64)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why not check this already after checking submitSuccess for the first time?

Also now when I see this testId I realise that it would probably make more sense to set priorities as enum string value instead of number. Now it is not clear where does "_10" comes.
</blockquote></details>

Done.
___
*[`cypress/e2e/stops.cy.ts` line 127 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TJnmV02bY2U4utSBW:-N9B9cf07Osc_SflSBjT:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L127)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"pysäkit manual"? I don't understand why we are mixing languages here.
</blockquote></details>

Done.
___
*[`cypress/e2e/creators/map.ts` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TDqyeERR0xqHevQJ5:-NAo0G9d7m3Ma4TYszuv:bep8jp1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L33)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand this and next datatype. Are these something user is going to enter to ui form? If yes, maybe their name and/or location in codebase should reflect that somehow.
</blockquote></details>

This was just the function parameters, but removed it now and just use typings on function definition.
___
*[`cypress/e2e/creators/map.ts` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8T7IWl4wzxnu00LCr7:-N9BuQrdBgzkSkE_rxNM:b-hqtp44) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L56)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I'm not familiar whit this kind of "creator" pattern. Anyway: seems like this class does plenty of things that are more or less related and its not clear what each function does. E.g. "setPriority" - does it affect priority of stop or route or what?

I suggest we refactor this so that responsibilities of this became more clear, otherwise this easily becomes something that is difficult to maintain and makes it also difficult to refactor current e2e tests.
</blockquote></details>

Good points. This was a first iteration and I can also see how this is confusing.

The main idea behind this is that you can call this function when you want to for example: create a route via the UI. You only need to fill in the necessary details for the creation and you do not need to use cypress calls to find correct buttons and correct fields to fill in and so on. 
Maybe there is a better naming or pattern for this than `creator`, but this is the first iteration. I did change the class to `MapItemCreator` anyways.
___
*[`cypress/e2e/creators/map.ts` line 147 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8Snuk1EJB3h6dMotbY:-NAo4xdp-yN0eCdtIC2h:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L147)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Would look cleaner if routePoint could be used as a parameter.
</blockquote></details>

Done.
___
*[`cypress/e2e/creators/map.ts` line 153 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8SneAMD1MfAHRL02d2:-NAo51NL2uxlG399sTLk:bhmsv7r) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L153)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

What for? Can you add a comment, I don't understand what does this do and why it is done.
</blockquote></details>

This is now renamed to `clickNthSnappingPointHandle` and it is used for example to click the last snapping point handle to end route draw.
___
*[`cypress/pageObjects/MapEditor.ts` line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TEBTI2ogrTlXTaYa3:-N9BJUPVBcOzjzbRqCMl:b-89razf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand what xpos and ypos mean? And what is their relation to x and y on the code block below?
</blockquote></details>

This was resolved in earlier PR.
___
*[`cypress/pageObjects/MapEditor.ts` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TER4i9-KNE9zS7Z_8:-N9BBBSD0uuzDdm-roUl:b-43q2yg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L31)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Same thing that I commented on the previous (?) PR: it smells a bit fishy to access parent of selected element. Do we really have to do this? If yes, please at least comment why.
</blockquote></details>

(Reworked after the noticed the typings for getByTestId were wrong and this parent was unnecessary)
___
*[`cypress/pageObjects/MapEditor.ts` line 40 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TExFw2lp3xLXqodVB:-N9BBbx97JeRADLZp0KG:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/pageObjects/MapEditor.ts#L40)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why not getByTestId?
</blockquote></details>

Done.
___
*[`cypress/pageO [...]

2022-09-01 12:25 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: 1 of 20 files reviewed, 16 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`cypress/e2e/createRoute.cy.ts` line 7 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsu4QT77iu8fG6Ok-l:-NAsu4QU1n2beMBa6X4O:b-dq76b2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/createRoute.cy.ts#L7)):*
> ```XML
> 
> // Currently these tests can't be run in CI so we skip them.
> // TODO: Remove the if-statement after we can run map tests in CI
> ```

NOTE: I think we have PR about this by pallost open right now, so please sync its status before merging this PR.
___
*[`cypress/e2e/createRoute.cy.ts` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsuLos3jW6CBEHc0a6:-NAsuLos3jW6CBEHc0a7:bph4rdb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/createRoute.cy.ts#L50)):*
> ```XML
>               rightOffset: -10,
>               downOffset: 25,
>               testId: 'Map::Stops::stopMarker::H1234_Standard',
> ```

Where does this id (H1234_Standard) come from? Please import it somewhere or at least add comment about it, now this test is really annoying to debug in the future if H1234 happens to be missing and there is no context to hint where one should look for it. Same for H1236 below
___
*[`cypress/e2e/interfaces.ts` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsupSG-8n9HL0Vrh0I:-NAsupSG-8n9HL0Vrh0J:be088rg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/interfaces.ts#L1)):*
> ```XML
> export interface Coordinates {
> ```

We already have `cypress/types/` directory for these. Please move these there, maybe in a new file called `types.ts`. Ideally do not put these to `types.d.ts` as then these will be globally available and doesn't have to be imported. At least the interface below shoudn't be globally available.

It is implementation detail that these are interfaces and not types, so the file name doesn't have to specify that.
___
*[`cypress/e2e/stops.cy.ts` line 49 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TICiNEpX80-DEcmdj:-NAsvh1XEJRSfMNt6AME:b-zcjvte) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L49)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks
___
*[`cypress/e2e/stops.cy.ts` line 64 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TIlelAo6Z_qSfAAic:-NAsvnHy0IRkQ1GBF2xw:b8b30lr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/stops.cy.ts#L64)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't anymore see the context of this comment, so closing this thread for now and will open new thread at correct place if needed.
___
*[`cypress/e2e/stops.cy.ts` line 13 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsvHdXDJD6kSsWjvdx:-NAsvHdXDJD6kSsWjvdy:b-fjdgx9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/stops.cy.ts#L13)):*
> ```XML
> };
> 
> // Currently these tests can't be run in CI so we skip them.
> ```

Same note about these as mentioned before.
___
*[`cypress/e2e/stops.cy.ts` line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsvRdH9oEpYWivD678:-NAsvRdH9oEpYWivD679:be0a9lv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/stops.cy.ts#L27)):*
> ```XML
>       );
> 
>       clearDatabase();
> ```

I assume you want clear db BEFORE visiting map?
___
*[`cypress/e2e/stops.cy.ts` line 63 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAswAkJ1DDUal1ijdpz:-NAswAkJ1DDUal1ijdq-:b-v36330) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/stops.cy.ts#L63)):*
> ```XML
>           stopFormInfo: {
>             label: testStopLabel2,
>             // Actual coordinates will be on Topeliuksen katu
> ```

Topeliuksenkatu taitaa olla yhdyssana :wink: 
___
*[`cypress/e2e/utils/mapItemCreator.ts` line 14 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsyZ_d6-uX6fVEbhrY:-NAsyZ_d6-uX6fVEbhrZ:b8v8n8m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/utils/mapItemCreator.ts#L14)):*
> ```XML
> import { ClickPointNearMapMarker, Coordinates } from '../interfaces';
> 
> export class MapItemCreator {
> ```

This file seems to export just _class_ MapItemCreator so filename should start with capital letter as the class itself.
___
*[`cypress/e2e/utils/mapItemCreator.ts` line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAswqkh7H3XV9YXsMsZ:-NAswqkh7H3XV9YXsMs_:bl1cg5y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/utils/mapItemCreator.ts#L27)):*
> ```XML
>   stopForm = new StopForm();
> 
>   setPriority = (priority?: Priority) => {
> ```

Why `priority` param is optional? IMO calling `setPriority()` is confusing especially if it arbitrariry just defaults to some priority (standard).
___
*[`cypress/e2e/utils/mapItemCreator.ts` line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsxHJ3AGCGy-ndNjKQ:-NAsxHJ3AGCGy-ndNjKR:b7ak352) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/utils/mapItemCreator.ts#L40)):*
> ```XML
>   };
> 
>   setEndDate = (endDate?: string) => {
> ```

Parameter name could clarify that this is supposed to be ISO date, as defined in confirmSaveForm (`isoDate: string`). Other possibility would be to define new `type isoDate = string; // iso date, YYYY-MM-DD` and use it here.
___
*[`cypress/e2e/utils/mapItemCreator.ts` line 109 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsyCaZ5eSJVct8-w09:-NAsyCaZ5eSJVct8-w0A:bqprrre) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/utils/mapItemCreator.ts#L109)):*
> ```XML
>   };
> 
>   /**
> ```

Not yet sure about naming of this class, but at least this function seems to be useful. :+1: 

Please still remember that in most tests we want to insert routes etc. directly to the db and this should be used only when UI is needed for some specific reason, most likely because we want to test the UI itself.
___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsypBJ2zJ6TDhaGiNz:-NAsypBK5bTc7bChD3to:bn39kqb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/pageObjects/ConfirmSaveForm.ts#L3)):*
> ```XML
> import { Priority } from '@hsl/jore4-test-db-manager';
> 
> export interface ConfirmSaveFormInfo {
> ```

This doesn't seem to be used anywhere.
___
*[`cypress/pageObjects/StopForm.ts` line 31 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAszb9B6wdt5Fi6qcFp:-NAszb9B6wdt5Fi6qcFq:bdqs8cq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/pageObjects/StopForm.ts#L31)):*
> ```XML
> 
>   save(forceAction = false) {
>     return cy.getByTestId('Modal::saveButton').click({ force: forceAction });
> ```

This will break if we have multiple modals open at the same time. So I'd avoid this pattern. You should first add `StopFormComponent` or `StopFormComponent::form` or something like that test id to StopForm itself, then we should write this selector to be something like: `cy.getByTestId('StopFormComponent').findByTestId('Modal::saveButton')`.

Implementation of `findByTestId` is coming soon,  [...]

2022-09-06 07:40 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: 1 of 22 files reviewed, 16 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`cypress/e2e/createRoute.cy.ts` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsuLos3jW6CBEHc0a6:-NAwe6ua1ZBqU6fz33H2:bahbv6k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/createRoute.cy.ts#L50)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Where does this id (H1234_Standard) come from? Please import it somewhere or at least add comment about it, now this test is really annoying to debug in the future if H1234 happens to be missing and there is no context to hint where one should look for it. Same for H1236 below
</blockquote></details>

Good point! I'll add a comment that they are temp stops from seed data and will be populated in the future.
___
*[`cypress/e2e/stops.cy.ts` line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsvRdH9oEpYWivD678:-NAwflnG5GlaFT5cBrXU:bb74x83) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/stops.cy.ts#L27)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I assume you want clear db BEFORE visiting map?
</blockquote></details>

True
___
*[`cypress/e2e/stops.cy.ts` line 63 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAswAkJ1DDUal1ijdpz:-NAwfv_6Bu-ggQwBXAPw:bmsfqph) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/stops.cy.ts#L63)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Topeliuksenkatu taitaa olla yhdyssana :wink: 
</blockquote></details>

:D fuu
___
*[`cypress/pageObjects/ConfirmSaveForm.ts` line 3 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsypBJ2zJ6TDhaGiNz:-NAwkj0U4pLmSE-rkc0T:b-y61oak) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/pageObjects/ConfirmSaveForm.ts#L3)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This doesn't seem to be used anywhere.
</blockquote></details>

Nice, removed.
___
*[`cypress/pageObjects/StopForm.ts` line 31 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAszb9B6wdt5Fi6qcFp:-NAwoZmn0dothi8rBu8Q:b-uoprew) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/pageObjects/StopForm.ts#L31)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This will break if we have multiple modals open at the same time. So I'd avoid this pattern. You should first add `StopFormComponent` or `StopFormComponent::form` or something like that test id to StopForm itself, then we should write this selector to be something like: `cy.getByTestId('StopFormComponent').findByTestId('Modal::saveButton')`.

Implementation of `findByTestId` is coming soon, but before it you can do `cy.getByTestid(...).find(`[data-testid="Modal::saveButton"]`)` which will do the same.
</blockquote></details>

That is true. Although should we ever have multiple modals open at the same time with `Save` functionality? Nevertheless this  should be fixed like you said.

Update: I added testId for Modal, so now you can name your modals.
___
*[`cypress/e2e/interfaces.ts` line 1 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsupSG-8n9HL0Vrh0I:-NAwdFi044C1kknId_bT:brmux6m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/interfaces.ts#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

We already have `cypress/types/` directory for these. Please move these there, maybe in a new file called `types.ts`. Ideally do not put these to `types.d.ts` as then these will be globally available and doesn't have to be imported. At least the interface below shoudn't be globally available.

It is implementation detail that these are interfaces and not types, so the file name doesn't have to specify that.
</blockquote></details>

Check!
___
*[`cypress/e2e/utils/mapItemCreator.ts` line 27 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAswqkh7H3XV9YXsMsZ:-NAwgXaV-cZgYk6lxRet:b7s5fhz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/utils/mapItemCreator.ts#L27)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why `priority` param is optional? IMO calling `setPriority()` is confusing especially if it arbitrariry just defaults to some priority (standard).
</blockquote></details>

I think the reason behind this was that the developer who uses these creators (, can skip giving this information and it will be defaulted to standard. But good point that it should not be done in this function, but rather call it with a default value if it is missing.

So I changed this now so that the calling functions will have a default value for priority, so the developer can still skip giving the priority value when using createRoute or createStop.
___
*[`cypress/e2e/utils/mapItemCreator.ts` line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsxHJ3AGCGy-ndNjKQ:-NAwi3L_EUjS7h9bodYs:btwksoe) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/utils/mapItemCreator.ts#L40)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Parameter name could clarify that this is supposed to be ISO date, as defined in confirmSaveForm (`isoDate: string`). Other possibility would be to define new `type isoDate = string; // iso date, YYYY-MM-DD` and use it here.
</blockquote></details>

Good one. I think I'll go with the first suggestion. ISODate type could be nice as well, but that could need some formatting guards/constraints etc? (So that it is not just a hidden type for string with the same constraints)
___
*[`cypress/e2e/utils/mapItemCreator.ts` line 109 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsyCaZ5eSJVct8-w09:-NAwjkfDAAXA-8LjvEIe:b-uw0ea6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/utils/mapItemCreator.ts#L109)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not yet sure about naming of this class, but at least this function seems to be useful. :+1: 

Please still remember that in most tests we want to insert routes etc. directly to the db and this should be used only when UI is needed for some specific reason, most likely because we want to test the UI itself.
</blockquote></details>

Yep, totally agreed. And also these tests will still need work because we need to replace the usage of seed data with populated data.


<!-- Sent from Reviewable.io -->

2022-09-06 11:23 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: 1 of 22 files reviewed, 17 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBHRRAUAORno2IyghYj):*
Commit message talks about mapcreator but we don't have that concept anymore. :) 
___
*[`-- commits` line 5 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBHRWIi92c2wG95ZxCp):*
Maybe this could be _a little bit_ more descriptive? :) At least something like "Add e2e tests for stops" or even better: "Add e2e tests for doing xxx to stops"
___
*[`cypress/e2e/createRoute.cy.ts` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NAsuLos3jW6CBEHc0a6:-NBHRtNH70ob-o6nGRtz:b-tcrctb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/247e85ae6931791f5843bbc57f113a271cfa8fbc/cypress/e2e/createRoute.cy.ts#L50)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Good point! I'll add a comment that they are temp stops from seed data and will be populated in the future.
</blockquote></details>

Thanks. Still small point about variable naming: is it relevant to include ID (H1234) itself in variable's name, or should they rather be like `const testStopId1 = ...`?
___
*[`cypress/pageObjects/StopForm.ts` line 33 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBHXHoKBVBN-KmUraq9:-NBHXHoKBVBN-KmUraqA:b581jc2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afaa4500c11940c0b35c8a8a3490bbd229d9baf6/cypress/pageObjects/StopForm.ts#L33)):*
> ```XML
>     return cy
>       .getByTestId('EditStopModal::saveButton')
>       .click({ force: forceAction });
> ```

Please comment why force is needed.
___
*[`ui/src/components/map/Modal.tsx` line 8 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBHUMQQBusgA-UkzKxu:-NBHUMQQBusgA-UkzKxv:b53r6em) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afaa4500c11940c0b35c8a8a3490bbd229d9baf6/ui/src/components/map/Modal.tsx#L8)):*
> ```XML
> 
> const testIds = {
>   saveButton: (testId?: string) =>
> ```

Is reviewable doing its tricks or was this changed from string to function without refactoring how this is used?
___
*[`ui/src/components/map/Modal.tsx` line 66 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBHUB2w9He9inU43Vbm:-NBHUB2w9He9inU43Vbn:b1omt4f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afaa4500c11940c0b35c8a8a3490bbd229d9baf6/ui/src/components/map/Modal.tsx#L66)):*
> ```XML
>       <ModalHeader onClose={onClose} heading={heading} />
>       {children}
>       <ModalFooter testId={testId} onCancel={onCancel} onSave={onSave} />
> ```

Now **same** testid is given to two different elements? We don't want to do this, this makes testid ambiguous.
___
*[`cypress/types/types.ts` line 6 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBHWQye2o0LSa20YEJa:-NBHWQyf41aYiZjXhA_c:b39m8yc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afaa4500c11940c0b35c8a8a3490bbd229d9baf6/cypress/types/types.ts#L6)):*
> ```XML
> }
> 
> export interface ClickPointNearMapMarker {
> ```

Is this really type that we want to export from "global" file? At least now name of this interface looks a bit confusing and I'm wondering if this could be improved somehow. If I understood puprose of this correctly then we could at least rename `testId` -> `mapMarkerTestId`, but it is also possible that this whole concept could be thinked somehow differently.


<!-- Sent from Reviewable.io -->

2022-09-08 05:56 UTC, tk-vincit requested changes
Little bit of nitpicking and some thoughts about architecture.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-:-NBQenTm9-E27kM2dpxh:bcejxj2)* status: 1 of 22 files reviewed, 9 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`cypress/e2e/createRoute.cy.ts` line 55 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQX_669AJrbdd-_zLw:-NBQX_669AJrbdd-_zLx:bgzaqas) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/createRoute.cy.ts#L55)):*
> ```XML
>             rightOffset: -10,
>             downOffset: 25,
>             testId: testStopId1,
> ```

Now that I realise how this is used I started to wonder if this property should actually be called "stopTestId" (assuming it is always stop) or "targetStopTestId" or something like that? Maybe you can think of better alternatives. Plain testId sounds a bit ambiguous (unless this can be any element with testId on map, then this might be good enough).



_Code quote:_
```XML
            testId: testStopId1,
```
___
*[`cypress/e2e/createRoute.cy.ts` line 66 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQYEdY6yBD0vNs8dtn:-NBQYEdY6yBD0vNs8dto:b-asg5y4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/createRoute.cy.ts#L66)):*
> ```XML
> 
>       // waiting for the success toast is not reliable, thus waiting for the graphql request success instead
>       // TODO: find out why cypress chrome can't find toast messages.
> ```

Not sure what is the actual TODO/action point here. What should developer do after finding that out?
___
*[`cypress/e2e/stops.cy.ts` line 39 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQYs-L2pao9e7pnsTz:-NBQYs-L2pao9e7pnsU-:b5wnscz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/stops.cy.ts#L39)):*
> ```XML
>           y: 334,
>         },
>         startISODate: '2022-01-01',
> ```

Assuming this refers to validityStart field of stop entity, it could be better to call this validityStartISODate to avoid ambiguity. Same for validityEndISODate.
Sorry, seems like I suggested startDate/endDate naming month ago, but didn't realised this back then.
___
*[`cypress/e2e/stops.cy.ts` line 42 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQZPpMEfq_ZVfzA3nM:-NBQZPpMEfq_ZVfzA3nN:bhwh79k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/stops.cy.ts#L42)):*
> ```XML
>       });
> 
>       // Cypress chrome can't find our success toast messages for some reason,
> ```

"Cypress chrome" doesn't exists, so I'd rather talk about "cypress on chrome" to avoid misunderstandings in the future.
___
*[`cypress/e2e/stops.cy.ts` line 44 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQZd-Y1TSm8-eEJhku:-NBQZd-ZAJBD8cYWqRRD:b-22bv36) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/stops.cy.ts#L44)):*
> ```XML
>       // Cypress chrome can't find our success toast messages for some reason,
>       // so we check the request status code
>       // TODO: find out why cypress chrome can't find toast messages.
> ```

Same things as mentioned in previous comments:
- what is action point here?
- cypress ON chrome
___
*[`cypress/e2e/creators/map.ts` line 22 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TCNYxBBmkeEHg5ROg:-NBQaHw14xY-o8TJiHbB:b-vnbepx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L22)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Shame we can't currently import these directly from ui project side...

Maybe we still should store this kind of duplicate code from ui project to clearly separate file so that those can be easily removed if importing those becomes available at some point? Or at least then it would be easier to see that this kind of stuff is just duplicate definitions from ui side and should be kept 1:1 with the original implementations.
</blockquote></details>

Closing these threads for now as there doesn't seem to be changes in this file in this PR anymore, let's open new threads to relevant places if needed.
___
*[`cypress/e2e/creators/map.ts` line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TDqyeERR0xqHevQJ5:-NBQaSjqAhpaog3ZMPfl:b-vnbepx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L33)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This was just the function parameters, but removed it now and just use typings on function definition.
</blockquote></details>

Closing these threads for now as there doesn't seem to be changes in this file in this PR anymore, let's open new threads to relevant places if needed.
___
*[`cypress/e2e/creators/map.ts` line 50 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-N8TCtzb39Gjz-u-OAip:-NBQaQ593SAWMTdvFLyx:b-vnbepx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/271e7a6dc8409caff37a710ba681661f3972f270/cypress/e2e/creators/map.ts#L50)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Priority, startDate and endDate are in multiple interfaces. Should you rather define those once and then extend these interfaces?

Also wondering if string is correct type for dates.
</blockquote></details>

Closing these threads for now as there doesn't seem to be changes in this file in this PR anymore, let's open new threads to relevant places if needed.
___
*[`ui/src/components/map/Modal.tsx` line 8 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBHUMQQBusgA-UkzKxu:-NBMUf5IEAwmbBWhTvUL:b-w213w3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afaa4500c11940c0b35c8a8a3490bbd229d9baf6/ui/src/components/map/Modal.tsx#L8)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Answer is related to this and the next comment. So maybe the naming here is a bit wrong, and the parameter that comes to this `Modal.tsx` should maybe be "modalName" etc. instead of "testId". Because now the actual testId is generated dynamically. 

If you don't give the modal name for example, the save button will be "Modal::saveButton". But if you give the modal the name (testId in this case) the modal will have for example "EditStopModal" as testId, and the save button's testId will be "EditStopModal::saveButton".

Update: I kept the name testId with `<Modal>`but added it as `testIdPrefix` to modalFooter, if its more readable. If this is still confusing, I'll remove the dynamic testId generation and then just use the chained `getByTestId`.
</blockquote></details>

Ah, ok... My initial impression is that this `testIdPrefix` pattern makes using test id's more difficult, since you first have to define "test id prefix", then you have to go look the actual test id where the "prefix" is embedded, and then use that combination in tests.

And the other way around, if you have used "MyRandomTestPrefix::saveButton" in tests and try to find corresponding element from source code by searching "MyRandomTestPrefix::saveButton", you won't find it as it is build dynamically. 

The same problem is not if e.g. id/label is used dynamically in test id, as then test id is built dynamically also on test suites and it is self-evident that test id is dynamic.

I can re-review this PR and check how relevant these points are, but does this make sense to you?
___
*[`ui/src/components/map/Modal.tsx` line 66 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBHUB2w9He9inU43Vbm:-NBQeRLf4zC_rEfPgw8Q:b4thntl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afaa4500c11940c0b35c8a8a3490bbd229d9baf6/ui/src/components/map/Modal.tsx#L66)):*
<d [...]

2022-09-08 10:48 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: 1 of 22 files reviewed, 9 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`cypress/e2e/createRoute.cy.ts` line 55 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQX_669AJrbdd-_zLw:-NBRHHNGBymr08fW1Wpc:b-kwm8x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/createRoute.cy.ts#L55)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Now that I realise how this is used I started to wonder if this property should actually be called "stopTestId" (assuming it is always stop) or "targetStopTestId" or something like that? Maybe you can think of better alternatives. Plain testId sounds a bit ambiguous (unless this can be any element with testId on map, then this might be good enough).
</blockquote></details>

Yeah, I was thinking about `stopTestId` etc. But then I thought that in theory you could give it any testId you want. Im not sure if there could be some other markers to use for this as well and that is why I did not want to specify it for only stop. But maybe this can be "mapMarkerTestId", since "MapMarker" is used in the function names as well.
___
*[`cypress/e2e/createRoute.cy.ts` line 66 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQYEdY6yBD0vNs8dtn:-NBRHffP2nc-rOHH0wDE:bv4q0og) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/createRoute.cy.ts#L66)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure what is the actual TODO/action point here. What should developer do after finding that out?
</blockquote></details>

Meant that we could add the toast message assertion here or replace the statusCode assertion. The test gives us more value if we test that user gets the correct feedback rather than just checking if the statusCode is successful. I'll rephrase this a bit
___
*[`cypress/e2e/stops.cy.ts` line 39 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQYs-L2pao9e7pnsTz:-NBRK30w02L2Ei1DFt3y:b-pkeml6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/stops.cy.ts#L39)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Assuming this refers to validityStart field of stop entity, it could be better to call this validityStartISODate to avoid ambiguity. Same for validityEndISODate.
Sorry, seems like I suggested startDate/endDate naming month ago, but didn't realised this back then.
</blockquote></details>

Good one, I'll change this.
___
*[`cypress/e2e/stops.cy.ts` line 42 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQZPpMEfq_ZVfzA3nM:-NBRKOSV5PWMSzkPkrPE:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/stops.cy.ts#L42)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"Cypress chrome" doesn't exists, so I'd rather talk about "cypress on chrome" to avoid misunderstandings in the future.
</blockquote></details>

Done.
___
*[`ui/src/components/map/Modal.tsx` line 8 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBHUMQQBusgA-UkzKxu:-NBRMDzc0BK_Y54i6bLB:b-gklr4n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afaa4500c11940c0b35c8a8a3490bbd229d9baf6/ui/src/components/map/Modal.tsx#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Ah, ok... My initial impression is that this `testIdPrefix` pattern makes using test id's more difficult, since you first have to define "test id prefix", then you have to go look the actual test id where the "prefix" is embedded, and then use that combination in tests.

And the other way around, if you have used "MyRandomTestPrefix::saveButton" in tests and try to find corresponding element from source code by searching "MyRandomTestPrefix::saveButton", you won't find it as it is build dynamically. 

The same problem is not if e.g. id/label is used dynamically in test id, as then test id is built dynamically also on test suites and it is self-evident that test id is dynamic.

I can re-review this PR and check how relevant these points are, but does this make sense to you?
</blockquote></details>

Yeah it makes sense. Did not think for example about searching the dynamically built testId, if its not evident that it is build dynamically. Ok so need to change this back.
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 55 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQeZuDEiyYBJpwSR8w:-NBRMzvl5SMxUTn3epPg:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/ui/src/components/map/RouteStopsOverlay.tsx#L55)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Let's not call this testId unless it is actually passed directly as data-testid!
</blockquote></details>

Done.
___
*[`cypress/e2e/utils/db-utils.ts` line 1 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQaXyq7Tn_z_iy5j8c:-NBRKdOI6Il_hJ0lC-b1:bskdc7d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/utils/db-utils.ts#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

BTW/fyi, these can now be done via hasura api (see e.g. `test-db-manager/src/builders/mutations.ts`). That is possibly more maintainable/type safe in the future and is thus the recommended way. Anyway, no need to refactor these now as these serve as a good example about how to do things manually. It is good to have "escape hatch" available if needed at some point.
</blockquote></details>

Yep, this is something that can be refactored at the same time we remove seed data usage from the tests :+1: 
___
*[`cypress/e2e/utils/MapItemCreator.ts` line 15 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQcCXO5bHuIg_xOJFS:-NBRL_Tf5FtxItlp23GM:bm87u0z) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/utils/MapItemCreator.ts#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Still not completely sure about this "MapItemCreator" convept. Seems like this is actually one big pageObject with many responsibilities. So is there a reason this is trying to disguise itself as "util" by being in utils directory? Now one might figure out that this is preferred way to e.g. add stops to the db, which this is definitely not test spesificly requires that to be done (slowly) via UI instead of (quickly) via hasura api. So i think this should be moved to pageObjects directory.

Another point of view (to be considered by you): does it make sense to try to handle all "map items" here and thus have multiple responsibilities, or should we rather have multiple pageobjects with one responsibility each? (One for stops, one for routes etc.)
</blockquote></details>

Could this maybe be done with iteration in another later PR? This PR is already reworked so many times and keeps hanging here. I do know that this is a bit dimwitted, but I think this can easily be improved with iteration rounds.
___
*[`cypress/types/types.ts` line 6 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQe45aDzhneKCyRGCs:-NBRKy_B8qM6-aVPnYSH:b-8nha7j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/types/types.ts#L6)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

These two are already defined in `cypress/types/types.d.ts` (and thus globally available without importing). 
</blockquote></details>

We couldn't have `types.d.ts` and `types.ts` in the same folder. It ignored the other file so I moved the `types.d.ts` content to this file. Or maybe there is some importing trick whic [...]

2022-09-08 11:14 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: 1 of 22 files reviewed, 6 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`ui/src/components/map/Modal.tsx` line 8 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBHUMQQBusgA-UkzKxu:-NBRnIR_7o2O_xLrrqr5:b7o3xf1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/afaa4500c11940c0b35c8a8a3490bbd229d9baf6/ui/src/components/map/Modal.tsx#L8)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yeah it makes sense. Did not think for example about searching the dynamically built testId, if its not evident that it is build dynamically. Ok so need to change this back.
</blockquote></details>

At least this file seems to be OK now. We can add/change testid's later if needed.
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 55 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQeZuDEiyYBJpwSR8w:-NBRnA932W5EUqsjD088:b-s6doou) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/ui/src/components/map/RouteStopsOverlay.tsx#L55)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't seem to be done?
___
*[`cypress/e2e/utils/MapItemCreator.ts` line 15 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQcCXO5bHuIg_xOJFS:-NBRnVPlE1RURvKNRvcA:bu7hcsr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/utils/MapItemCreator.ts#L15)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Could this maybe be done with iteration in another later PR? This PR is already reworked so many times and keeps hanging here. I do know that this is a bit dimwitted, but I think this can easily be improved with iteration rounds.
</blockquote></details>

I would for the very least move this to PageObjects directory unless there was a reason why this tries to be util.
___
*[`cypress/types/types.ts` line 6 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQe45aDzhneKCyRGCs:-NBRmAtd8Kmg9U6tpU9M:bwjselo) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/types/types.ts#L6)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

We couldn't have `types.d.ts` and `types.ts` in the same folder. It ignored the other file so I moved the `types.d.ts` content to this file. Or maybe there is some importing trick which I'm not aware of, but atleast that time I couldn't find one.
</blockquote></details>

I don't understand the problem, but at least there is `cypress/types/types.d.ts` file in the `main` branch of the jore4-ui repository, and as it wasn't touched in this pr, this effectively **duplicated** `UUID` and `RequiredKeys` definition to another file! This is not ok and has to be fixed.

Also, as I pointed out, we have `cypress/types/types.d.ts` file, so now we do have `types.d.ts` and `types.ts` files in the same directory, right..?


<!-- Sent from Reviewable.io -->

2022-09-08 13:25 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: 1 of 25 files reviewed, 6 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`cypress/e2e/utils/MapItemCreator.ts` line 15 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQcCXO5bHuIg_xOJFS:-NBRzg5h-BYwMpYxUqzI:b-rcqfvl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/e2e/utils/MapItemCreator.ts#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I would for the very least move this to PageObjects directory unless there was a reason why this tries to be util.
</blockquote></details>

Okay :+1: 
___
*[`cypress/types/types.ts` line 6 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQe45aDzhneKCyRGCs:-NBS8iyPBwi7LTevGJJr:b4xfbi7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/cypress/types/types.ts#L6)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand the problem, but at least there is `cypress/types/types.d.ts` file in the `main` branch of the jore4-ui repository, and as it wasn't touched in this pr, this effectively **duplicated** `UUID` and `RequiredKeys` definition to another file! This is not ok and has to be fixed.

Also, as I pointed out, we have `cypress/types/types.d.ts` file, so now we do have `types.d.ts` and `types.ts` files in the same directory, right..?
</blockquote></details>

Okay, so as discussed in slack, some conflict or rebasing made the `types.d.ts` remain here, even though I initially removed it because of the described reasons. Also discussed in slack that I will keep this `types.d.ts` file and put `interface Coordinates` to `coordinates.ts` file for now.
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 55 at r4](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBQeZuDEiyYBJpwSR8w:-NBS71OhChbx262efXJi:b2e8j6a) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/fd645208b503381ba63bca5fc5788dfc4f2db315/ui/src/components/map/RouteStopsOverlay.tsx#L55)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Doesn't seem to be done?
</blockquote></details>

Now it should be. Also just realised that `<StopRow>` component is in this same file and I think it could maybe have own file. But that can be extracted in other PR if decided to do.


<!-- Sent from Reviewable.io -->

2022-09-08 13:37 UTC, tk-vincit approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: 1 of 24 files reviewed, 6 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 29 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBSJJsa-E73GY65EM2z:-NBSJJsa-E73GY65EM3-:b-3sc2m2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25775e8789240832205e111a8688c55dbd34cc4c/ui/src/components/map/RouteStopsOverlay.tsx#L29)):*
> ```XML
> const testIds = {
>   mapOverlayHeader: 'RouteStopsOverlay::mapOverlayHeader',
>   stopRow: (label: string) => `stopRow::${label}`,
> ```

This should be `StopRow::` and not `stopRow::` according to our standards :smile: 


<!-- Sent from Reviewable.io -->

2022-09-09 06:11 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/275)* status: 1 of 24 files reviewed, 6 unresolved discussions (waiting on @eleksi, @HenrikHartiala, and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 29 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/275#-NBSJJsa-E73GY65EM2z:-NBVrn-EEfvezNDBsE6X:b4b018d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/25775e8789240832205e111a8688c55dbd34cc4c/ui/src/components/map/RouteStopsOverlay.tsx#L29)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This should be `StopRow::` and not `stopRow::` according to our standards :smile: 
</blockquote></details>

Thanks! fixed :D 


<!-- Sent from Reviewable.io -->

2022-09-09 06:42 UTC, merged