Remove observation date from redux
HSLdevcom/jore4-ui pull request #322
Opened 2022-08-31 06:43 UTC by eleksi

- Observation date is already stored in query parameters, remove it from redux store

2022-08-31 07:31 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/322)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/hooks/useShowRoutesOnModal.ts` line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/322#-NAmneGF-PoMwfLldFaf:-NAmneGF-PoMwfLldFag:b-gdd3mc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cb1df1b4ec1e507d272f812953277cb5b9b9d847/ui/src/hooks/useShowRoutesOnModal.ts#L20)):*
> ```XML
>   const dispatch = useAppDispatch();
>   const { openMapInPosition } = useMapQueryParams();
>   const { observationDate } = useObservationDateQueryParam();
> ```

let's default the observationDate in the query to DateTime.now().startOf('day') in the useObservationDateQueryParam hook. Just like how it's done in linedraftdetails hook:

```
  /** Determines and sets date to query parameters if it's not there */
  const initializeObservationDate = useCallback(async () => {
    if (!queryParams.observationDate) {
      setObservationDateToUrl(DateTime.now().startOf('day'), true);
    }
  }, [queryParams.observationDate, setObservationDateToUrl]);

  useEffect(() => {
    initializeObservationDate();
  }, [initializeObservationDate]);
```

then basically we could remove 90% of the business logic related to observationDate setting and getting because they all could go through that hook
___
*[`ui/src/hooks/urlQuery/useMapQueryParams.ts` line 114 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/322#-NAmiUwQDnG_vxnVO-a_:-NAmiUwQDnG_vxnVO-aa:bp09pc6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/cb1df1b4ec1e507d272f812953277cb5b9b9d847/ui/src/hooks/urlQuery/useMapQueryParams.ts#L114)):*
> ```XML
>     mapPosition,
>     setMapPosition,
>     observationDate,
> ```

This is a bit of a semanticity problem. If someone imports observationDate from directly useObservationDateQueryParam, they might get different value (undefined) than here (DateTime.now()).

Let's keep the responsibility of handling the observationDate to the useObservationDateQueryParam hook and not export the observationDate value from here.

Better solution would be to check in this hook if observationDate is undefined and it it is, set it to the default DateTime.now() and write it back to the query.

On the other hand, this logic does not really belong to this hook, but I don't have a better idea for now where to do it from.


<!-- Sent from Reviewable.io -->

2022-09-01 08:54 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/322)* status: 0 of 16 files reviewed, 2 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx` line 79 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/322#-NAryXM47rFOWZhrjzWQ:-NAryXM47rFOWZhrjzWR:b-mfgomf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5442abbba19777c3fa4b5fe9f20ac625ae71b5af/ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx#L79)):*
> ```XML
>                   <RouteStopsTable
>                     routes={line.line_routes}
>                     observationDate={observationDate}
> ```

The RouteStopsTable component doesn't need the observationDate property anymore: it could just fetch it for itself from the hook
___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/322#-NAsE-CI0GAgkWK1Wi27:-NAsE-CI0GAgkWK1Wi28:bh50luv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5442abbba19777c3fa4b5fe9f20ac625ae71b5af/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L40)):*
> ```XML
>   /** Determines and sets date to query parameters if it's not there */
>   const initializeObservationDate = useCallback(async () => {
>     if (!queryParams.observationDate || !observationDate) {
> ```

We start to get into the useCallback hell again. I agree with this Stack Overflow discussion here:
https://stackoverflow.com/questions/68729164/children-usecallback-dependency-hell

Sometimes it's okay to not to want to use exhaustive deps and just ignore the linter rule. Could you try removing the dependencies from observationDate and setObservationDateToUrl (set them to []) and see if we get a render loop...? (And ofc remove the useCallback wrappers where possible)


<!-- Sent from Reviewable.io -->

2022-09-01 10:22 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/322)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[`ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx` line 79 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/322#-NAryXM47rFOWZhrjzWQ:-NAsRwIC8BkgYYDRQ6LB:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5442abbba19777c3fa4b5fe9f20ac625ae71b5af/ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx#L79)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

The RouteStopsTable component doesn't need the observationDate property anymore: it could just fetch it for itself from the hook
</blockquote></details>

Done.
___
*[`ui/src/hooks/urlQuery/useObservationDateQueryParam.ts` line 40 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/322#-NAsE-CI0GAgkWK1Wi27:-NAsZh0P0t8P-o11CEuY:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5442abbba19777c3fa4b5fe9f20ac625ae71b5af/ui/src/hooks/urlQuery/useObservationDateQueryParam.ts#L40)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

We start to get into the useCallback hell again. I agree with this Stack Overflow discussion here:
https://stackoverflow.com/questions/68729164/children-usecallback-dependency-hell

Sometimes it's okay to not to want to use exhaustive deps and just ignore the linter rule. Could you try removing the dependencies from observationDate and setObservationDateToUrl (set them to []) and see if we get a render loop...? (And ofc remove the useCallback wrappers where possible)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-01 11:06 UTC, pallost approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/322)* status: 0 of 18 files reviewed, 1 unresolved discussion (waiting on @pallost)



<!-- Sent from Reviewable.io -->

2022-09-01 11:26 UTC, merged