Improve move stop usability
HSLdevcom/jore4-ui pull request #325
Opened 2022-09-06 12:51 UTC by HenrikHartiala

Resolves HSLdevcom/jore4#733

Move stop functionality and visualisation improved to be more intuitive.
* Stop draggability is now removed. Pressing "move stop" will go to "moveStopMode" and clicking a location will attempt to move the stop there. This now works the same way as when creating a new stop. (Stop marker following the cursor and only one click will decide where to move the stop).
* The stop that is being moved will have the old location visualised with dotted gray circle
* Pressing ESC button will cancel the move
  * This also works when creating stop

2022-09-07 06:17 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/325)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBLXWbR289E_9xcwiXw):*
You had nice description of this change in PR description. Why not to include it in commit message?
___
*[`ui/src/components/map/Map.tsx` line 101 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBLXgWt05n1_6Kis0-d:-NBLXgWt05n1_6Kis0-e:b-vppclv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8ffa0ba5af69b90f68c5e5b32e3e4559b7265f13/ui/src/components/map/Map.tsx#L101)):*
> ```XML
> 
>   const onMoveStop = (e: MapEvent) => {
>     if (stopsRef.current && drawingMode === undefined) {
> ```

Do we want to explicitly check if drawingMode is `undefined` or what if it is e.g. `null`? How about just `if (!drawingMode) { stopsRef.current?.onMoveStop(e); }`
___
*[`ui/src/components/map/stops/CreateStopMarker.tsx` line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBLYXkx2mucSdiKBDMY:-NBLYXkx2mucSdiKBDMZ:brrqu58) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8ffa0ba5af69b90f68c5e5b32e3e4559b7265f13/ui/src/components/map/stops/CreateStopMarker.tsx#L34)):*
> ```XML
> 
>   const detectKeyDown = (e: KeyboardEvent) => {
>     if (e.key === 'Escape') {
> ```

What happens if user is using touchscreen, are they still able to cancel this operation somehow?

Is it documented that `KeyboardEvent.key` always returns esc key string as 'Escape', or can they also be e.g. 'ESCAPE' or 'escape'? A bit safer way would be to `if (String(e.key).toLowerCase() === 'escape')). But OK, this is a bit easier to read so if this works on chrome I'm ok with this.
___
*[`ui/src/components/map/stops/Stop.tsx` line 54 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBL_Yy-BW1pAOhiN4J2:-NBL_Yy-BW1pAOhiN4J3:b872fuh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8ffa0ba5af69b90f68c5e5b32e3e4559b7265f13/ui/src/components/map/stops/Stop.tsx#L54)):*
> ```XML
>   // If the stop is being moved, we use different styles for the stop
>   // to indicate the placeholder of the old location
>   const isPlaceHolder = selected && isMoveStopModeEnabled;
> ```

isPlaceholder, placeholder is one word.
___
*[`ui/src/components/map/stops/Stops.tsx` line 111 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBL_oIvENF8IXIheLw9:-NBL_oIvENF8IXIheLwA:b-cnmk4e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8ffa0ba5af69b90f68c5e5b32e3e4559b7265f13/ui/src/components/map/stops/Stops.tsx#L111)):*
> ```XML
>       setIsLoading(false);
>     },
>     onMoveStop: async (e: MapEvent) => {
> ```

I don't see `await` anywhere so does this have to be `async`?


<!-- Sent from Reviewable.io -->

2022-09-07 10:36 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/325)* status: 0 of 10 files reviewed, 4 unresolved discussions (waiting on @tk-vincit)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBLXWbR289E_9xcwiXw):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

You had nice description of this change in PR description. Why not to include it in commit message?
</blockquote></details>

Ah, it is not a flow I've used. But good point! I'll try to start adding the descriptions to the commit body :+1: 
___
*[`ui/src/components/map/Map.tsx` line 101 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBLXgWt05n1_6Kis0-d:-NBMOJiS2cXb9RJqDnof:b148ta8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8ffa0ba5af69b90f68c5e5b32e3e4559b7265f13/ui/src/components/map/Map.tsx#L101)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we want to explicitly check if drawingMode is `undefined` or what if it is e.g. `null`? How about just `if (!drawingMode) { stopsRef.current?.onMoveStop(e); }`
</blockquote></details>

Great one, I'll change this.
___
*[`ui/src/components/map/stops/CreateStopMarker.tsx` line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBLYXkx2mucSdiKBDMY:-NBMOjQxDXsSRmLPnEyv:bjdh11c) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8ffa0ba5af69b90f68c5e5b32e3e4559b7265f13/ui/src/components/map/stops/CreateStopMarker.tsx#L34)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What happens if user is using touchscreen, are they still able to cancel this operation somehow?

Is it documented that `KeyboardEvent.key` always returns esc key string as 'Escape', or can they also be e.g. 'ESCAPE' or 'escape'? A bit safer way would be to `if (String(e.key).toLowerCase() === 'escape')). But OK, this is a bit easier to read so if this works on chrome I'm ok with this.
</blockquote></details>

Yes, the user can also click anywhere on map and then press `Cancel`. The map footer needs some redesign / refactor, because already there are buttons that are not used anywhere else than some special case (for example there is a trash bin that only applies to routes). And within that refactor we could also add a `Cancel` button to the footer while moving a stop.

What comes to the key-event, it should be the same for every browser. https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key and https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values
Out of curiosity checked if the virtual keyboard works, and it does :+1: 
___
*[`ui/src/components/map/stops/Stop.tsx` line 54 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBL_Yy-BW1pAOhiN4J2:-NBMQheG8beo3zjKetVe:bxbwcfh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8ffa0ba5af69b90f68c5e5b32e3e4559b7265f13/ui/src/components/map/stops/Stop.tsx#L54)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

isPlaceholder, placeholder is one word.
</blockquote></details>

Whoops! Thanks.
___
*[`ui/src/components/map/stops/Stops.tsx` line 111 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBL_oIvENF8IXIheLw9:-NBMRcI0ACsWiOb5lYy0:bemivzw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8ffa0ba5af69b90f68c5e5b32e3e4559b7265f13/ui/src/components/map/stops/Stops.tsx#L111)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't see `await` anywhere so does this have to be `async`?
</blockquote></details>

Hmm, yeah maybe not. I'll remove it


<!-- Sent from Reviewable.io -->

2022-09-07 10:45 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/325)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @tk-vincit)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBLXWbR289E_9xcwiXw):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah, it is not a flow I've used. But good point! I'll try to start adding the descriptions to the commit body :+1: 
</blockquote></details>

I guess in ideal (=ancient?) world there would be some newlines in git commit messages to avoid very long lines, but maybe today's tools can handle also long lines without stupid issues :smile: 

But yeah, in the future I suggest to include these descriptions in commit messages too, since they're easier to find from commit messages than pull requests.
___
*[`ui/src/components/map/stops/CreateStopMarker.tsx` line 34 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBLYXkx2mucSdiKBDMY:-NBMXCH50XpZIs5BpC6k:bz8i9n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/8ffa0ba5af69b90f68c5e5b32e3e4559b7265f13/ui/src/components/map/stops/CreateStopMarker.tsx#L34)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yes, the user can also click anywhere on map and then press `Cancel`. The map footer needs some redesign / refactor, because already there are buttons that are not used anywhere else than some special case (for example there is a trash bin that only applies to routes). And within that refactor we could also add a `Cancel` button to the footer while moving a stop.

What comes to the key-event, it should be the same for every browser. https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key and https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values
Out of curiosity checked if the virtual keyboard works, and it does :+1: 
</blockquote></details>

:+1: :ok: 


<!-- Sent from Reviewable.io -->

2022-09-08 10:52 UTC, tk-vincit approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/325)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`ui/src/components/map/stops/Stop.tsx` line 17 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBROyqhDumSNRC5SKnw:-NBRiK8YEiL6XDbKieAx:b-mgh1n8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5261df74c4e46e26db8a924e8ab50df20bbef10a/ui/src/components/map/stops/Stop.tsx#L17)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

prop starting with `on` is react convention for naming callbacks (see e.g. onClick or onDragEnd above). Please rename this.
</blockquote></details>

Didn't noticed this was outside of scope of this PR so no need to fix this right now.
___
*[`ui/src/components/map/stops/Stop.tsx` line 33 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/325#-NBRMJhYAILGsVx3I594:-NBRiRPP0uWHVuzaRJWB:b92rdv8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5261df74c4e46e26db8a924e8ab50df20bbef10a/ui/src/components/map/stops/Stop.tsx#L33)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This looks suspicious, we have no guarantees that `colors.stops` has key  that corresponds onVehicleRoute.

Also this can got broken _very easily_ by a mistake if someone happens to edit theme and edits `colors.stops`, as theme file has not references to this kind of usage at all!  By very least I would do someting like
```
const vehicleStopColor = colors.stops[onVehicleRoute] || 'black';
return vehicleStopColor;

```
Then you could get rid of ternary and have sensible fallback. There could also be logging:
```
if (onVehicleRoute && !colors.stops[onVehicleRoute]) {
  console.log('Error: expected to find color corresponding ${onVehicleRoute} but none was defined')
}
```
But maybe that's a bit overkill if we have sensible fallback.


</blockquote></details>

OK, this problem was also on original implementation so I'll approve this for now.


<!-- Sent from Reviewable.io -->

2022-09-09 09:29 UTC, merged