Show route's stops' priorities in map view
HSLdevcom/jore4-ui pull request #330
Opened 2022-09-07 11:32 UTC by eleksi

Resolves HSLdevcom/jore4#931

2022-09-08 10:09 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 9 files reviewed, 10 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRWzQ25GQ17xXvXnut:-NBRWzQ25GQ17xXvXnuu:b1yzy19) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/components/map/RouteStopsOverlay.tsx#L23)):*
> ```XML
>   setStopOnRouteAction,
> } from '../../redux';
> import { RouteStop } from '../../redux/types/mapEditor';
> ```

`from '.../redux` or `.../redux/types`
___
*[`ui/src/hooks/routes/useCreateRoute.ts` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXLkh51xa5yYPbBCw:-NBRXLkh51xa5yYPbBCx:bsdzted) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/hooks/routes/useCreateRoute.ts#L12)):*
> ```XML
>   mapRouteStopsToStopSequence,
>   RouteGeometry,
> } from '../../redux/types/mapEditor';
> ```

See previous comment about import path
___
*[`ui/src/hooks/routes/useEditRouteGeometry.ts` line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXRun8KhVt5a7ChZL:-NBRXRun8KhVt5a7ChZM:bv81mrf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/hooks/routes/useEditRouteGeometry.ts#L13)):*
> ```XML
>   mapRouteStopsToStopSequence,
>   RouteGeometry,
> } from '../../redux/types/mapEditor';
> ```

Import path
___
*[`ui/src/hooks/routes/useEditRouteJourneyPattern.ts` line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXUak7D-o7vU9520W:-NBRXUak7D-o7vU9520X:bv81mrf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/hooks/routes/useEditRouteJourneyPattern.ts#L14)):*
> ```XML
>   mapStopToRouteStop,
>   RouteStop,
> } from '../../redux/types/mapEditor';
> ```

Import path
___
*[`ui/src/hooks/routes/useExtractRouteFromFeature.ts` line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRX_GX4To31dZo1kAx:-NBRX_GX4To31dZo1kAy:bv81mrf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/hooks/routes/useExtractRouteFromFeature.ts#L20)):*
> ```XML
>   RouteInfraLink,
> } from '../../graphql';
> import { mapStopToRouteStop, RouteStop } from '../../redux/types/mapEditor';
> ```

Import path
___
*[`ui/src/hooks/routes/useValidateRoute.ts` line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXaXf4FRgCwJlhWwL:-NBRXaXf4FRgCwJlhWwM:bv81mrf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/hooks/routes/useValidateRoute.ts#L9)):*
> ```XML
> } from '../../generated/graphql';
> import { mapLineDetailsResult } from '../../graphql';
> import { RouteGeometry, RouteStop } from '../../redux/types/mapEditor';
> ```

Import path
___
*[`ui/src/redux/slices/mapEditor.ts` line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXdl7AZo6pDMVRhkX:-NBRXdl7AZo6pDMVRhkY:b6s3ct5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/slices/mapEditor.ts#L5)):*
> ```XML
> import { LineAllFieldsFragment } from '../../generated/graphql';
> import { RouteInfraLink } from '../../graphql';
> import { RouteStop } from '../types/mapEditor';
> ```

50/60 if this should be imported from `../types`, especially if there are no dependency cycles
___
*[`ui/src/redux/types/mapEditor.ts` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXzdICoK3CmzIool3:-NBRXzdICoK3CmzIool4:bjw4juw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/types/mapEditor.ts#L1)):*
> ```XML
> import {
> ```

Starting to wonder: how these are redux-speficit? Because if these have nothing to do with redux, I don't see why we would want to move these to redux directory.
___
*[`ui/src/redux/types/mapEditor.ts` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRZHqQ22tHgNZ0am_w:-NBRZHqQ22tHgNZ0am_x:b63udwt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/types/mapEditor.ts#L2)):*
> ```XML
> import {
>   ScheduledStopPointAllFieldsFragment,
> ```

Another thing: this all was just moved from place a to place b? If yes, please do that kind of refactoring in a separate commit.
___
*[`ui/src/redux/types/mapEditor.ts` line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRZ_oj8L0bmC7ueuUO:-NBRZ_ok1YwdGCunHzj0:b-p8pi0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/types/mapEditor.ts#L21)):*
> ```XML
>  * @returns Stop in journey pattern
>  */
> const mapRouteStopToStopInSequence = (routeStop: RouteStop, index: number) => {
> ```

Usually things in `.../types/something.ts` or in `.../types.ts` should be TYPES, so either `type` or `interface` definitions. These are not type definitions, so these do not belong to `types` directory.


<!-- Sent from Reviewable.io -->

2022-09-08 10:10 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 9 files reviewed, 14 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRYoAe4-A3F1ggBdS0:-NBRYoAe4-A3F1ggBdS1:b-zehyaq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/components/map/RouteStopsOverlay.tsx#L23)):*
> ```XML
>   setStopOnRouteAction,
> } from '../../redux';
> import { RouteStop } from '../../redux/types/mapEditor';
> ```

let's group the redux/types into an index.ts file
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 44 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRZ-wH7zzCI8hOvF9s:-NBRZ-wH7zzCI8hOvF9t:b-v1zqip) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/components/map/RouteStopsOverlay.tsx#L44)):*
> ```XML
> 
> const StopRow = ({
>   routeStop: { label, belongsToJourneyPattern: onRoute, stopInstance },
> ```

I think the 'belongsToJourneyPattern' name describes the parameter better, no need to rename it to 'onRoute'
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 125 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXjliDuoELwdZz_fK:-NBRXjliDuoELwdZz_fL:b-ci0o5a) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/components/map/RouteStopsOverlay.tsx#L125)):*
> ```XML
>     : getRouteStops(
>         selectedRouteStops.flatMap((stop) =>
>           filterHighestPriorityCurrentStops(
> ```

this business logic is getting very messy. (also for the +-10 lines of code above and below this line) There are huge amounts of ternary operators, defaulting with || operator and random type conversations. This whole thing should be moved to a separate hook and split into tidy little functions

This filterHighestPriorityCurrentStops function call is already:
1. within a ternary operator
2. within the getRouteStops function
3. within a flatMap call

If this wasn't a red flag that something is wrong, then I don't know what is :) please write cleaner code...
___
*[`ui/src/redux/types/mapEditor.ts` line 57 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRVkTX6tfRksg-5k4U:-NBRVkTX6tfRksg-5k4V:b-re134s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/types/mapEditor.ts#L57)):*
> ```XML
>    * Label of the route
>    */
>   label: string;
> ```

There are several things here...
- if this was really the route's label, it doesn't belong here -> should remove it
- if this was the stops's label (as apparently how it's actually used, opposed to the comment) -> should remove it as the information is already found within the ScheduledStopPointAllFieldsFragment
- the belongsToJourneyPattern information is still valid -> should stay
- the "stop" attribute is actually only used for persisting the original via information, nothing else -> should rename it to viaInfo
- the scheduledStopPointId is a redundant field -> should remove it as the information is already found within the ScheduledStopPointAllFieldsFragment
- the stopInstance contains the actual information about the stop -> should stay. Maybe could rename it to "stop"?


<!-- Sent from Reviewable.io -->

2022-09-12 12:34 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 24 files reviewed, 14 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRWzQ25GQ17xXvXnut:-NBkxRglDLIC1XOB4i6I:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/components/map/RouteStopsOverlay.tsx#L23)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`from '.../redux` or `.../redux/types`
</blockquote></details>

Done.
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRYoAe4-A3F1ggBdS0:-NBkxS-b4pRYugM2Jnje:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/components/map/RouteStopsOverlay.tsx#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's group the redux/types into an index.ts file
</blockquote></details>

Done.
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 44 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRZ-wH7zzCI8hOvF9s:-NBkxssi6oESxtlxRAdu:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/components/map/RouteStopsOverlay.tsx#L44)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think the 'belongsToJourneyPattern' name describes the parameter better, no need to rename it to 'onRoute'
</blockquote></details>

Done.
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 125 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXjliDuoELwdZz_fK:-NBlERob-ukoOxFMBvUm:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/components/map/RouteStopsOverlay.tsx#L125)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this business logic is getting very messy. (also for the +-10 lines of code above and below this line) There are huge amounts of ternary operators, defaulting with || operator and random type conversations. This whole thing should be moved to a separate hook and split into tidy little functions

This filterHighestPriorityCurrentStops function call is already:
1. within a ternary operator
2. within the getRouteStops function
3. within a flatMap call

If this wasn't a red flag that something is wrong, then I don't know what is :) please write cleaner code...
</blockquote></details>

Done.
___
*[`ui/src/hooks/routes/useCreateRoute.ts` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXLkh51xa5yYPbBCw:-NBkxuGA7MMOY12D1UUZ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/hooks/routes/useCreateRoute.ts#L12)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

See previous comment about import path
</blockquote></details>

Done.
___
*[`ui/src/hooks/routes/useEditRouteGeometry.ts` line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXRun8KhVt5a7ChZL:-NBkxuhi73LWAAqrFgjM:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/hooks/routes/useEditRouteGeometry.ts#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Import path
</blockquote></details>

Done.
___
*[`ui/src/hooks/routes/useEditRouteJourneyPattern.ts` line 14 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXUak7D-o7vU9520W:-NBkxv8O9EcEfqx8Vaak:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/hooks/routes/useEditRouteJourneyPattern.ts#L14)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Import path
</blockquote></details>

Done.
___
*[`ui/src/hooks/routes/useExtractRouteFromFeature.ts` line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRX_GX4To31dZo1kAx:-NBkxvYr1hkDYI8l7Y2e:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/hooks/routes/useExtractRouteFromFeature.ts#L20)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Import path
</blockquote></details>

Done.
___
*[`ui/src/hooks/routes/useValidateRoute.ts` line 9 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXaXf4FRgCwJlhWwL:-NBkxw017fqd8UurNuBp:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/hooks/routes/useValidateRoute.ts#L9)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Import path
</blockquote></details>

Done.
___
*[`ui/src/redux/slices/mapEditor.ts` line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXdl7AZo6pDMVRhkX:-NBkxwlE1_PMGSmWg0QW:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/slices/mapEditor.ts#L5)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

50/60 if this should be imported from `../types`, especially if there are no dependency cycles
</blockquote></details>

Done.
___
*[`ui/src/redux/types/mapEditor.ts` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRXzdICoK3CmzIool3:-NBkxz2p9SAmfpTNQwIR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/types/mapEditor.ts#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Starting to wonder: how these are redux-speficit? Because if these have nothing to do with redux, I don't see why we would want to move these to redux directory.
</blockquote></details>

Done.
___
*[`ui/src/redux/types/mapEditor.ts` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRZHqQ22tHgNZ0am_w:-NBkxzkR-x-RIB4EUC7X:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/types/mapEditor.ts#L2)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Another thing: this all was just moved from place a to place b? If yes, please do that kind of refactoring in a separate commit.
</blockquote></details>

Done.
___
*[`ui/src/redux/types/mapEditor.ts` line 21 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRZ_oj8L0bmC7ueuUO:-NBky-jqCSICxPoE7sEN:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/types/mapEditor.ts#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Usually things in `.../types/something.ts` or in `.../types.ts` should be TYPES, so either `type` or `interface` definitions. These are not type definitions, so these do not belong to `types` directory.
</blockquote></details>

Done.
___
*[`ui/src/redux/types/mapEditor.ts` line 57 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRVkTX6tfRksg-5k4U:-NBlTb0P61LUeuYbjLeI:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/types/mapEditor.ts#L57)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

There are several things here...
- if this was really the route's label, it doesn't belong here -> should remove it
- if this was the stops's label (as apparently how it's actually used, opposed to the comment) -> should remove it as the information is already found within the ScheduledStopPointAllFieldsFragment
- the belongsToJourneyPattern information is still valid -> should stay
- the "stop" attribute is actually only used for persisting the original via information, nothing else -> should rena [...]

2022-09-13 12:53 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 24 files reviewed, 16 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 36 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBqkRpjCiPxfjzR0bot:-NBqkRpjCiPxfjzR0bou:bf07m6x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68dcacb0c9b524aa1c4e7080359970f84ee474e5/ui/src/components/map/RouteStopsOverlay.tsx#L36)):*
> ```XML
>   isReadOnly,
>   testId,
> }: {
> ```

you could extract these props to an own type. In fact, maybe should consider moving the whole component to an own file, called RouteStopsRow.tsx. But not necessarily in scope of this PR
___
*[`ui/src/hooks/routes/useActiveRouteInfo.ts` line 14 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBqq5XoE7xbcmHbwhA8:-NBqq5XoE7xbcmHbwhA9:bkuh9mv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68dcacb0c9b524aa1c4e7080359970f84ee474e5/ui/src/hooks/routes/useActiveRouteInfo.ts#L14)):*
> ```XML
> import { getRouteStops } from './useExtractRouteFromFeature';
> 
> export const useActiveRouteInfo = () => {
> ```

I've been wondering what would be a good interface for this hook to be able to possibly reuse it in DrawRouteLayer in the future...
___
*[`ui/src/hooks/routes/useActiveRouteInfo.ts` line 21 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBqlIS98nErirvIaLDl:-NBqlH6n4pfLjhxX5Fdw:b-j0ljty) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68dcacb0c9b524aa1c4e7080359970f84ee474e5/ui/src/hooks/routes/useActiveRouteInfo.ts#L21)):*
> ```XML
> 
>   // Get selected route data
>   const routesResult = useGetRoutesWithInfrastructureLinksQuery({
> ```

this graphql query definition should be moved to this hook. I'd also suggest that you actually fetch data that could be used as parameters for the `extractJourneyPatternCandidateStops` function. So most likely pretty much should just combine the GetRoutesWithInfrastructureLinks and GetLinksWithStopsByExternalLinkIds queries for this use-case

that should also already do most of the pre-processing for you to get the stops for the route. But remember that you'll still need to filter those stops afterwards with `filterDistinctConsecutiveRouteStops` and `filterHighestPriorityCurrentStops`

then convert them to RouteStop type

If the route is being edited, then you should already have the `stopsEligibleForJourneyPattern` variable in the redux store ready to be used for this
___
*[`ui/src/redux/mappers/mapEditor.ts` line 30 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBqssBq2lL4nGc8r8Kf:-NBqssBr4FhqGH1sSZOv:b-54ua9g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68dcacb0c9b524aa1c4e7080359970f84ee474e5/ui/src/redux/mappers/mapEditor.ts#L30)):*
> ```XML
>  * @returns Sequence of stops that belong to route's journey pattern
>  */
> export const mapRouteStopsToStopSequence = (stops: RouteStop[]) => {
> ```

mapping only should mean mapping, it shouldn't do filtering in the meantime. Maybe `buildStopSequenceFromRouteStops` name would work better?
___
*[`ui/src/redux/mappers/mapEditor.ts` line 46 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBqtO-rA_WhQq_ND9Yg:-NBqtO-rA_WhQq_ND9Yh:bwb80io) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68dcacb0c9b524aa1c4e7080359970f84ee474e5/ui/src/redux/mappers/mapEditor.ts#L46)):*
> ```XML
>  * @returns RouteStop
>  */
> export const mapStopToRouteStop = <
> ```

I'd also rather call this `buildRouteStop` as this does more than just mapping. But this is on the edge...
___
*[`ui/src/redux/types/mapEditor.ts` line 57 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBRVkTX6tfRksg-5k4U:-NBqu9WfD5tjZwSOt0B1:bhiqt0n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/410472af5bf55bff1c47c7331f38b1e9853a50d3/ui/src/redux/types/mapEditor.ts#L57)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

beautiful :heart_eyes: 


<!-- Sent from Reviewable.io -->

2022-09-15 06:41 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 25 files reviewed, 16 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 36 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBqkRpjCiPxfjzR0bot:-NBv3Y11AtvKm5O5wfeh:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68dcacb0c9b524aa1c4e7080359970f84ee474e5/ui/src/components/map/RouteStopsOverlay.tsx#L36)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you could extract these props to an own type. In fact, maybe should consider moving the whole component to an own file, called RouteStopsRow.tsx. But not necessarily in scope of this PR
</blockquote></details>

Done.
___
*[`ui/src/hooks/routes/useActiveRouteInfo.ts` line 14 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBqq5XoE7xbcmHbwhA8:-NBv3ZKfE_Wrhm-ujwMB:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68dcacb0c9b524aa1c4e7080359970f84ee474e5/ui/src/hooks/routes/useActiveRouteInfo.ts#L14)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I've been wondering what would be a good interface for this hook to be able to possibly reuse it in DrawRouteLayer in the future...
</blockquote></details>

Done.
___
*[`ui/src/hooks/routes/useActiveRouteInfo.ts` line 21 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBqlIS98nErirvIaLDl:-NBzs76sBb-K3zTgFSE1:b-70ozw8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68dcacb0c9b524aa1c4e7080359970f84ee474e5/ui/src/hooks/routes/useActiveRouteInfo.ts#L21)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this graphql query definition should be moved to this hook. I'd also suggest that you actually fetch data that could be used as parameters for the `extractJourneyPatternCandidateStops` function. So most likely pretty much should just combine the GetRoutesWithInfrastructureLinks and GetLinksWithStopsByExternalLinkIds queries for this use-case

that should also already do most of the pre-processing for you to get the stops for the route. But remember that you'll still need to filter those stops afterwards with `filterDistinctConsecutiveRouteStops` and `filterHighestPriorityCurrentStops`

then convert them to RouteStop type

If the route is being edited, then you should already have the `stopsEligibleForJourneyPattern` variable in the redux store ready to be used for this

</blockquote></details>

As discussed f2f, this will get prettier later on.
___
*[`ui/src/redux/mappers/mapEditor.ts` line 30 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBqssBq2lL4nGc8r8Kf:-NBv1oR67yRP2C-KV72b:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68dcacb0c9b524aa1c4e7080359970f84ee474e5/ui/src/redux/mappers/mapEditor.ts#L30)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

mapping only should mean mapping, it shouldn't do filtering in the meantime. Maybe `buildStopSequenceFromRouteStops` name would work better?
</blockquote></details>

Done.
___
*[`ui/src/redux/mappers/mapEditor.ts` line 46 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBqtO-rA_WhQq_ND9Yg:-NBv0Aq95AahZFpTL5fr:b-v7rn8s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/68dcacb0c9b524aa1c4e7080359970f84ee474e5/ui/src/redux/mappers/mapEditor.ts#L46)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'd also rather call this `buildRouteStop` as this does more than just mapping. But this is on the edge...
</blockquote></details>

This will be removed in the upcoming refactoring.


<!-- Sent from Reviewable.io -->

2022-09-15 07:03 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 25 files reviewed, 11 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlayRow.tsx` line 35 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzuW8uCdb89GiTLxzT:-NBzuW8uCdb89GiTLxzU:b8yxh5y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/components/map/RouteStopsOverlayRow.tsx#L35)):*
> ```XML
>   return (
>     <div
>       className="flex h-10 items-center justify-between border-b p-2"
> ```

Explicit height? Why?
___
*[`ui/src/components/map/RouteStopsOverlayRow.tsx` line 39 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzu-W_-OK9qfg9Mv8Z:-NBzu-W_-OK9qfg9Mv8_:bdssou5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/components/map/RouteStopsOverlayRow.tsx#L39)):*
> ```XML
>     >
>       <div className="flex items-center">
>         <div className="w-10">
> ```

Is it really need to define explicit width to element? This is not optimal for the responsivity, even though its not that bad with rem units that tailwind currently uses.
___
*[`ui/src/graphql/client.ts` line 15 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzusAg2jXtJ_nGSiR9:-NBzusAg2jXtJ_nGSiRA:bf883mk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/graphql/client.ts#L15)):*
> ```XML
> import introspectionResult from '../../graphql.schema.json';
> import { isDateLike, parseDate } from '../time';
> import { mapHttpToWs } from '../utils/url';
> ```

Note: no need to touch import unless this was to avoid dependency cycle. Same on `servicePattern.ts`
___
*[`ui/src/hooks/routes/useActiveRouteInfo.ts` line 23 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzvVv2C4NVe6fot9p_:-NBzvVv2C4NVe6fot9pa:b-f4j43m) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/hooks/routes/useActiveRouteInfo.ts#L23)):*
> ```XML
>   // Get selected route data
>   const routesResult = useGetRoutesWithInfrastructureLinksQuery({
>     // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
> ```

In perfect world we would avoid non-null assertions or at least comment why those are safe to do. Same for assertion few lines below this.
___
*[`ui/src/redux/mappers/mapEditor.ts` line 10 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzwcdPBiMaHbeIGXJL:-NBzwcdQ35EIjRdlMj1A:bw4eeft) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/redux/mappers/mapEditor.ts#L10)):*
> ```XML
>  * @param routeStop A stop along route's geometry
>  * @param index Stop's index on journey pattern
>  * @returns Stop in journey pattern
> ```

Btw: if we have generated graphql type for this, then this mapper function should return explicitly that. That would improve type safety.
___
*[`ui/src/redux/mappers/storeType.ts` line 9 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzwuG1DuU6_3UxqK1v:-NBzwuG1DuU6_3UxqK1w:borto0w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/redux/mappers/storeType.ts#L9)):*
> ```XML
>   isPlainObject,
>   PlainObject,
> } from '../../utils/object';
> ```

Also this might not be needed.


<!-- Sent from Reviewable.io -->

2022-09-15 07:14 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 25 files reviewed, 11 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlayRow.tsx` line 35 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzuW8uCdb89GiTLxzT:-NBzyNi27YAa3eOVQa6b:b-t66wx2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/components/map/RouteStopsOverlayRow.tsx#L35)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Explicit height? Why?
</blockquote></details>

So that the element is same height regardless whether or not it contains an icon displaying the priority.
___
*[`ui/src/components/map/RouteStopsOverlayRow.tsx` line 39 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzu-W_-OK9qfg9Mv8Z:-NBzybB44DggEGKeiwQd:bnpjg9p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/components/map/RouteStopsOverlayRow.tsx#L39)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is it really need to define explicit width to element? This is not optimal for the responsivity, even though its not that bad with rem units that tailwind currently uses.
</blockquote></details>

It is there really as a "placeholder" for the priority badge. No badge is rendered in most cases, so hard coded width takes up the space in that case. Maybe some other way to do it also.
___
*[`ui/src/graphql/client.ts` line 15 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzusAg2jXtJ_nGSiR9:-NBzyq_q8UKtQlobe31N:b-5y60p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/graphql/client.ts#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Note: no need to touch import unless this was to avoid dependency cycle. Same on `servicePattern.ts`
</blockquote></details>

It was done for exactly that reason, avoiding dependency cycles. Those index files have so much stuff in them that cycles easily happen.
___
*[`ui/src/hooks/routes/useActiveRouteInfo.ts` line 23 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzvVv2C4NVe6fot9p_:-NBzz0_60HECEDeZg52M:b-f8kuw1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/hooks/routes/useActiveRouteInfo.ts#L23)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

In perfect world we would avoid non-null assertions or at least comment why those are safe to do. Same for assertion few lines below this.
</blockquote></details>

Maybe a commend would be in place. But this is a pattern used in multiple places and the justification for non-null assertion is in the next line 
    skip: !selectedRouteId
___
*[`ui/src/redux/mappers/mapEditor.ts` line 10 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzwcdPBiMaHbeIGXJL:-NBzzOOAECtT2MegPVtB:bn4plrd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/redux/mappers/mapEditor.ts#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Btw: if we have generated graphql type for this, then this mapper function should return explicitly that. That would improve type safety.
</blockquote></details>

I will work on these mappers in the redux refactoring, I don't think fine tuning these is really necessary at this point. But good point.
___
*[`ui/src/redux/mappers/storeType.ts` line 9 at r10](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NBzwuG1DuU6_3UxqK1v:-NBzznDs4gUxrzX--QvL:bqtja4j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/5d45b3edf3e15bce0a1a3b24d8ddb741f3bde18f/ui/src/redux/mappers/storeType.ts#L9)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Also this might not be needed.
</blockquote></details>

Dependecy cycles


<!-- Sent from Reviewable.io -->

2022-09-15 08:16 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 25 files reviewed, 10 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 3 at r13](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NC-AB0sAo2F4kIk63w6:-NC-AB0sAo2F4kIk63w7:b-3xnj0b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67cbc39642c849f0f0e8f77d4216a1c13b0a2f01/ui/src/components/map/RouteStopsOverlay.tsx#L3)):*
> ```XML
> import { gql } from '@apollo/client';
> import { useAppDispatch, useAppSelector } from '../../hooks';
> import { useActiveRouteInfo } from '../../hooks/routes/useActiveRouteInfo';
> ```

import it directly from ../../hooks
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 25 at r13](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NC-AZt4ANpi3_4_ERHV:-NC-AZt4ANpi3_4_ERHW:b-a6jm6d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67cbc39642c849f0f0e8f77d4216a1c13b0a2f01/ui/src/components/map/RouteStopsOverlay.tsx#L25)):*
> ```XML
> }
> 
> const GQL_ROUTE_METADATA = gql`
> ```

this type is actually used within the useActiveRouteInfo hook, let's move it there instead.
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 92 at r13](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NC-Aui84DimKwtRFeAW:-NC-Aui84DimKwtRFeAX:b-udlkqi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67cbc39642c849f0f0e8f77d4216a1c13b0a2f01/ui/src/components/map/RouteStopsOverlay.tsx#L92)):*
> ```XML
>             // eslint-disable-next-line react/no-array-index-key
>             key={`${routeStop.stop.label}_${index}`}
>             testId={testIds.stopRow(routeStop.stop.label)}
> ```

the RouteStopsOverlayRow should define its own testId, internally, instead of receiving it from outside. Also, the testId shouldn't be StopRow::, but follow the name of the component and be `RouteStopsOverlayRow::${routeStop.stop.label}`
___
*[`ui/src/components/map/RouteStopsOverlayRow.tsx` line 42 at r13](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NC-C6r14vT8wXg0Oyon:-NC-C6r14vT8wXg0Oyoo:bba9qhy) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67cbc39642c849f0f0e8f77d4216a1c13b0a2f01/ui/src/components/map/RouteStopsOverlayRow.tsx#L42)):*
> ```XML
>           <PriorityBadge
>             priority={stop.priority}
>             validityStart={stop.validity_start}
> ```

isn't `stop.validity_start` a string? At least it's a store type, so I assume it has to be a string... This should've thrown a type error, didn't it? PriorityBadge expects a DateTime type input
___
*[`ui/src/hooks/routes/useActiveRouteInfo.ts` line 28 at r13](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NC-Ct431wCPb6UpgAHD:-NC-Ct431wCPb6UpgAHE:bndumu7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67cbc39642c849f0f0e8f77d4216a1c13b0a2f01/ui/src/hooks/routes/useActiveRouteInfo.ts#L28)):*
> ```XML
>     skip: !selectedRouteId,
>   });
>   const routes = mapRouteResultToRoutes(routesResult);
> ```

not in the scope of this PR, but would be nice if you could avoid using`mapRouteResultToRoutes` but use the precise generated type instead.


<!-- Sent from Reviewable.io -->

2022-09-15 10:03 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 25 files reviewed, 10 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 3 at r13](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NC-AB0sAo2F4kIk63w6:-NC-RJQ_E0Whfv7POiOe:bum2ioh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67cbc39642c849f0f0e8f77d4216a1c13b0a2f01/ui/src/components/map/RouteStopsOverlay.tsx#L3)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

import it directly from ../../hooks
</blockquote></details>

Dependency cycles...
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 25 at r13](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NC-AZt4ANpi3_4_ERHV:-NC-RxZjEUy7xICejDu0:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67cbc39642c849f0f0e8f77d4216a1c13b0a2f01/ui/src/components/map/RouteStopsOverlay.tsx#L25)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this type is actually used within the useActiveRouteInfo hook, let's move it there instead.
</blockquote></details>

Done.
___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 92 at r13](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NC-Aui84DimKwtRFeAW:-NC-SMXn-iv8X5CHGGUH:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67cbc39642c849f0f0e8f77d4216a1c13b0a2f01/ui/src/components/map/RouteStopsOverlay.tsx#L92)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

the RouteStopsOverlayRow should define its own testId, internally, instead of receiving it from outside. Also, the testId shouldn't be StopRow::, but follow the name of the component and be `RouteStopsOverlayRow::${routeStop.stop.label}`
</blockquote></details>

Done.
___
*[`ui/src/components/map/RouteStopsOverlayRow.tsx` line 42 at r13](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NC-C6r14vT8wXg0Oyon:-NC-SnMG7m9S5kcVcsjB:bwsg3ni) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67cbc39642c849f0f0e8f77d4216a1c13b0a2f01/ui/src/components/map/RouteStopsOverlayRow.tsx#L42)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

isn't `stop.validity_start` a string? At least it's a store type, so I assume it has to be a string... This should've thrown a type error, didn't it? PriorityBadge expects a DateTime type input
</blockquote></details>

Didn't get an error before and it seemed to work, but I changed it to not use StoreType.

Maybe there is something wrong with StoreType..?


<!-- Sent from Reviewable.io -->

2022-09-20 09:04 UTC, pallost approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 25 files reviewed, 8 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)

___
*[`ui/src/components/map/RouteStopsOverlayRow.tsx` line 42 at r13](https://reviewable.io/reviews/hsldevcom/jore4-ui/330#-NC-C6r14vT8wXg0Oyon:-NCP7WPT6oaM7PKsOAzY:bqnf7tp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/67cbc39642c849f0f0e8f77d4216a1c13b0a2f01/ui/src/components/map/RouteStopsOverlayRow.tsx#L42)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Didn't get an error before and it seemed to work, but I changed it to not use StoreType.

Maybe there is something wrong with StoreType..?
</blockquote></details>

might be...


<!-- Sent from Reviewable.io -->

2022-09-22 07:22 UTC, tk-vincit approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/330)* status: 0 of 25 files reviewed, 7 unresolved discussions (waiting on @eleksi, @pallost, and @tk-vincit)



<!-- Sent from Reviewable.io -->

2022-09-22 07:43 UTC, merged