WIP: RouteStop refactor
HSLdevcom/jore4-ui pull request #343
Opened 2022-09-21 07:22 UTC by eleksi

2022-09-23 10:48 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/343)* status: 0 of 30 files reviewed, 14 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/package.json` line 55 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdS8eP0ZRUPCLJRflI:-NCdS8eP0ZRUPCLJRflJ:b7thrpw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/package.json#L55)):*
> ```JSON
>     "react-spinners": "^0.13.4",
>     "redux-logger": "^3.0.6",
>     "remeda": "^1.1.0",
> ```

oh, I've been just using `pipe-ts` before, didn't know that there are also other implementations...
___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 198 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCddOEK99-9YfsgPqMM:-NCdcTWFD4N4bLBbL35F:b-tbk43s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/components/map/routes/DrawRouteLayer.tsx#L198)):*
> ```XML
>       const journeyPatternStops = creatingNewRoute
>         ? []
>         : mapRouteStopsToJourneyPatternStops(
> ```

in DrawRouteLayer, the journeyPatternStops should not change when updating the geometry, it always stays the same. It might have via information for stops that are not part of the route anymore, but that's okay, those will be dropped anyway when building the data for the mutation
___
*[`ui/src/hooks/routes/useRouteInfo.ts` line 117 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdTqd76-WO6Sp8SeW-:-NCdTqd76-WO6Sp8SeW0:b-2pyvd1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/hooks/routes/useRouteInfo.ts#L117)):*
> ```XML
>     // selectedRouteId must be defined, because query is skipped if selectedRouteId is undefined
>     // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
>     variables: { route_ids: [routeId!] },
> ```

let's fix the query to only take a single parameter instead of an array
___
*[`ui/src/hooks/ui/useAlertsAndHighLights.ts` line 22 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdUL-85B2BQrkQ8s0D:-NCdUL-85B2BQrkQ8s0E:b-7fy7w5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/hooks/ui/useAlertsAndHighLights.ts#L22)):*
> ```XML
>       | RouteAllFieldsFragment
>       | LineAllFieldsFragment
>       | RouteStopFieldsFragment,
> ```

this could be even more tight, like StopDefaultFieldsFragment
___
*[`ui/src/redux/selectors/index.ts` line 82 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdUrEC86-1iZLLehtE:-NCdUrEC86-1iZLLehtF:b-klejib) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/selectors/index.ts#L82)):*
> ```XML
> );
> 
> export const selectEditedRouteIncludedStops = createSelector(
> ```

smart!
___
*[`ui/src/redux/slices/mapEditor.ts` line 41 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdYy-11ANl6thKSj1A:-NCdYy-11ANl6thKSj1B:bbqs9wr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/slices/mapEditor.ts#L41)):*
> ```XML
>      * Array of stop labels that are included in the edited route
>      */
>     includedStopLabels: string[];
> ```

let's make this a Set<string>! That would allow you to efficiently and easily add and remove items here without having any duplicates
___
*[`ui/src/redux/slices/mapEditor.ts` line 45 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdV778Ccv-CJ1eBzUJ:-NCdV778Ccv-CJ1eBzUK:b-wutl91) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/slices/mapEditor.ts#L45)):*
> ```XML
>      * Array of metadata about a stop in journey pattern (including but not limited to via info)
>      */
>     journeyPatternStops: JourneyPatternStopFragment[];
> ```

this is a good name!
___
*[`ui/src/redux/slices/mapEditor.ts` line 154 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdZERb91fMcr5Sx49j:-NCdZERb91fMcr5Sx49k:bvbjo4r) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/slices/mapEditor.ts#L154)):*
> ```XML
>         belongsToJourneyPattern: boolean;
>       }>,
>     ) => {
> ```

let's rather split this to two actions. It will be also much simpler if you used a Set:
```
includeStopToJourneyPattern: (...) => {
  state.editedRouteData.includedStopLabels.add(stopLabel);
}

excludeStopFromJourneyPattern: () => {
  state.editedRouteData.includedStopLabels.delete(stopLabel);
}
```
___
*[`ui/src/redux/types/mapEditor.ts` line 9 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCd_Fjm5uV9TjgIFIS3:-NCd_Fjm5uV9TjgIFIS4:b-xudcx8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/types/mapEditor.ts#L9)):*
> ```XML
> import { StoreType } from '../mappers/storeType';
> 
> export interface RouteGeometry {
> ```

let's delete this interface as it's only used for packaging lots of route data into a single object. However in all hooks where this is used, only a single member is used. Let's just use those member objects directly instead of this "package"
___
*[`ui/src/redux/types/mapEditor.ts` line 22 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdb5fG9WYyvv8HQ7Vs:-NCdb5fG9WYyvv8HQ7Vt:b-ksiogi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/types/mapEditor.ts#L22)):*
> ```XML
>     is_via_point
>     via_point_name_i18n
>     via_point_short_name_i18n
> ```

you also use this type when sending data to the mutation, so this should contain the scheduled_stop_point_sequence attribute as well.
___
*[`ui/src/utils/journeyPattern.ts` line 25 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdaGcyAjZM-oQyV7sm:-NCda1zqCltxHwUxaQ9a:b-8qnr1u) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/utils/journeyPattern.ts#L25)):*
> ```XML
>  * @returns Stop in journey pattern
>  */
> const mapStopToStopInSequence = (
> ```

Actually, you could just delete this function, there's a simpler and clearer way to do this, I show you below
___
*[`ui/src/utils/journeyPattern.ts` line 48 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdbjhd743R_MF069hJ:-NCdbjhd743R_MF069hK:b-ypmu6d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/utils/journeyPattern.ts#L48)):*
> ```XML
>  * @returns Sequence of stops that belong to route's journey pattern
>  */
> export const buildStopSequence = ({
> ```

how about `buildJourneyPatternStopSequence` for the name? 
___
*[`ui/src/utils/journeyPattern.ts` line 53 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdbVLnCR2_mk-Tk1jM:-NCdbVLnCR2_mk-Tk1jN:btrmbt6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/utils/journeyPattern.ts#L53)):*
> ```XML
>   journeyPatternStops,
> }: {
>   stopsEligibleForJourneyPattern: StoreType<RouteStopFieldsFragment>[];
> ```

this is pretty big for an inline type, I'd rather extract it as its own
___
*[`ui/src/utils/journeyPattern.ts` line 67 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdajti4J4QZMytoVcu:-NCdajti4J4QZMytoVcv:byb9uz3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/utils/journeyPattern.ts#L67)):*
> ```XML
>         );
> 
>         return mapStopToStopInSequence(label, stopInJourneyPattern, index);
> ```

There's no real need for the mapToStopInSequence function here.
return {
  ...stopInJourneyPattern,
  scheduled_stop_point_label: label,
  scheduled_stop_point_sequence: index,
}
  


<!-- Sent from Reviewable.io -->

2022-09-26 12:07 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/343)* status: 0 of 30 files reviewed, 14 unresolved discussions (waiting on @pallost)

___
*[`ui/package.json` line 55 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdS8eP0ZRUPCLJRflI:-NCsWiLh61nli7w_E340:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/package.json#L55)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

oh, I've been just using `pipe-ts` before, didn't know that there are also other implementations...
</blockquote></details>

Done.
___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 198 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCddOEK99-9YfsgPqMM:-NCsawj606MUYjActD5i:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/components/map/routes/DrawRouteLayer.tsx#L198)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

in DrawRouteLayer, the journeyPatternStops should not change when updating the geometry, it always stays the same. It might have via information for stops that are not part of the route anymore, but that's okay, those will be dropped anyway when building the data for the mutation
</blockquote></details>

Done.
___
*[`ui/src/hooks/routes/useRouteInfo.ts` line 117 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdTqd76-WO6Sp8SeW-:-NCscBDf7ehEL_xFFxhJ:b-stwqni) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/hooks/routes/useRouteInfo.ts#L117)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's fix the query to only take a single parameter instead of an array
</blockquote></details>

There is a use case for array variant as well, so I just added new query that takes routeId.
___
*[`ui/src/hooks/ui/useAlertsAndHighLights.ts` line 22 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdUL-85B2BQrkQ8s0D:-NCscWLNA3XWmm8f0ZCu:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/hooks/ui/useAlertsAndHighLights.ts#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this could be even more tight, like StopDefaultFieldsFragment
</blockquote></details>

Done.
___
*[`ui/src/redux/selectors/index.ts` line 82 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdUrEC86-1iZLLehtE:-NCscd2BANcF8Jqg8-Ij:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/selectors/index.ts#L82)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

smart!
</blockquote></details>

Done.
___
*[`ui/src/redux/slices/mapEditor.ts` line 41 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdYy-11ANl6thKSj1A:-NCseEt38h8BMXlJIqRW:b-gdljdt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/slices/mapEditor.ts#L41)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's make this a Set<string>! That would allow you to efficiently and easily add and remove items here without having any duplicates
</blockquote></details>

Great idea, but redux does not like sets as it is not serializable...
___
*[`ui/src/redux/slices/mapEditor.ts` line 45 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdV778Ccv-CJ1eBzUJ:-NCsePG58N76-0WThQhf:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/slices/mapEditor.ts#L45)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is a good name!
</blockquote></details>

Done.
___
*[`ui/src/redux/slices/mapEditor.ts` line 154 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdZERb91fMcr5Sx49j:-NCseQ6h8iL9k2gO2HB_:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/slices/mapEditor.ts#L154)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's rather split this to two actions. It will be also much simpler if you used a Set:
```
includeStopToJourneyPattern: (...) => {
  state.editedRouteData.includedStopLabels.add(stopLabel);
}

excludeStopFromJourneyPattern: () => {
  state.editedRouteData.includedStopLabels.delete(stopLabel);
}
```
</blockquote></details>

Done.
___
*[`ui/src/redux/types/mapEditor.ts` line 9 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCd_Fjm5uV9TjgIFIS3:-NCsqzgGAbA5PGDyNFRV:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/types/mapEditor.ts#L9)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's delete this interface as it's only used for packaging lots of route data into a single object. However in all hooks where this is used, only a single member is used. Let's just use those member objects directly instead of this "package"
</blockquote></details>

Done.
___
*[`ui/src/redux/types/mapEditor.ts` line 22 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdb5fG9WYyvv8HQ7Vs:-NCsr-8ID48rHYXeWo9B:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/redux/types/mapEditor.ts#L22)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

you also use this type when sending data to the mutation, so this should contain the scheduled_stop_point_sequence attribute as well.
</blockquote></details>

Done.
___
*[`ui/src/utils/journeyPattern.ts` line 25 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdaGcyAjZM-oQyV7sm:-NCsoFns44v_IAFeo_ct:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/utils/journeyPattern.ts#L25)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Actually, you could just delete this function, there's a simpler and clearer way to do this, I show you below
</blockquote></details>

Done.
___
*[`ui/src/utils/journeyPattern.ts` line 48 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdbjhd743R_MF069hJ:-NCsoIwk5hWBVuUzjjk9:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/utils/journeyPattern.ts#L48)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

how about `buildJourneyPatternStopSequence` for the name? 
</blockquote></details>

Done.
___
*[`ui/src/utils/journeyPattern.ts` line 53 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdbVLnCR2_mk-Tk1jM:-NCsr16iDga6w2iCl0Vx:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/utils/journeyPattern.ts#L53)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is pretty big for an inline type, I'd rather extract it as its own
</blockquote></details>

Done.
___
*[`ui/src/utils/journeyPattern.ts` line 67 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NCdajti4J4QZMytoVcu:-NCsr24WAwort_I3CFkL:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/71854db696d8a2562a64ba11220457120a796e76/ui/src/utils/journeyPattern.ts#L67)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

There's no real need for the mapToStopInSequence function here.
return {
  ...stopInJourneyPattern,
  scheduled_stop_point_label: label,
  scheduled_stop_point_sequence: index,
}
  
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-05 11:40 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/343)* status: 0 of 32 files reviewed, 26 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 11 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbOnrA18YUi67b_ME4:-NDbOnrA18YUi67b_ME5:bpc7rzx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/RouteStopsOverlay.tsx#L11)):*
> ```XML
>   belongsToJourneyPattern,
>   useRouteInfo,
> } from '../../hooks/routes/useRouteInfo';
> ```

could import this directly from `hooks/index.ts`
___
*[`ui/src/components/map/RouteStopsOverlayRow.tsx` line 35 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbPKT49XUt1xn8dBDn:-NDbPKT49XUt1xn8dBDo:bnm08qb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/RouteStopsOverlayRow.tsx#L35)):*
> ```XML
>   const setOnRoute = (onRoute: boolean) => {
>     const setOnRouteAction = onRoute
>       ? includeStopToJourneyPatternAction
> ```

would `setBelongsToJourneyPattern` be a better name?
___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 204 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbS-aX8dYJLORH3nRg:-NDbS-aX8dYJLORH3nRh:bu7plbn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/routes/DrawRouteLayer.tsx#L204)):*
> ```XML
>         extractJourneyPatternCandidateStops(infraLinksWithStops, routeMetadata);
> 
>       const includedStopLabels = getStopLabelsIncludedInRoute(
> ```

Calculating the included stop labels here does not work too well. Currently it's:
1. getting the old labels from the old geometry (which feels a bit weird as at this point the labels should already exist in the mapEditor store)
2. calling getRemovedStopLabels which visits the backend (which feels a bit weird as all the data should already be available in the infraLinksWithStops variables)
3. does the inversion from removedLabels to includedLabels in an additional calculation

I _think_ this is rather how it should work
1a. if we are drawing a new route, includedStopLabels should be empty as there's no previous information
1b. if we are editing an existing route, then the RouteEditor.tsx could put the included stop labels to the store within the scope of the onEditRoute function
2. in the DrawRouteLayer, when the route geometry is being updated (so this function here), the only thing we'd need to do is to exclude stop labels from the includedStopLabels if the stops don't belong to the geometry anymore (so basically just cross-check that only stops that are eligible to be part of the journey pattern could belong to this array)

I think this could work pretty well and reliably. The only issue I see right now is that when creating a new route, be default all the stops should be included. The semantically most correct way to solve this would be to allow includedStopLabels to be undefined instead of always be existing and empty when being reset. That way we would semantically separate the two cases when:
- we haven't yet defined included stop labels (so when first drawing a new route)
- we have excluded all stops from the route
___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 205 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbQ08H1Xvfn7eYCRxd:-NDbQ08H1Xvfn7eYCRxe:b-rlrhx9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/33b6d798847518801436e0e502fba9aa3f4c496f/ui/src/components/map/routes/DrawRouteLayer.tsx#L205)):*
> ```XML
> 
>       // FIXME. We shouldn't filter stops by being visible on the map as it might rule
>       // out some of the possibly eligible stops from the journey pattern.
> ```

awesome that you managed to remove this filtering from here!
___
*[`ui/src/components/map/routes/RouteEditor.tsx` line 200 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbc98L4Uig7a9I9OhT:-NDbc98L4Uig7a9I9OhU:b5m8vpu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/routes/RouteEditor.tsx#L200)):*
> ```XML
>       );
> 
>       /**
> ```

a few things came to mind here:
- why is the variable called newJourneyPatternStops? There are just simply journeyPatternStops, what is new in them...?
- the getStopsFromRoute is basically just extracting data deep from an embedded object, but doesn't add any functionality there. To me at least it feels that it's just obfuscating the logic of what's happening in under
- I was trying to understand why the mapStopInJourneyPatternToJourneyPatternStop function was created, why is there a reason to try to strip anything from the JourneyPatternScheduledStopPointInJourneyPattern entity? In the mapEditor we are anyway only using the restricted JourneyPatternStopFragment type, but it is in fact compatible with the original JourneyPatternScheduledStopPointInJourneyPattern type.

Without further ado, is there a special reason this wasn't just written like this?
```
dispatch(setDraftRouteJourneyPatternStopsAction(routeDetailsResult.data.route_route_by_pk.route_journey_patterns[0].scheduled_stop_point_in_journey_patterns));
```
___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx` line 49 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbeA-6B4DE2LYZ9QFI:-NDbeA-6B4DE2LYZ9QFJ:brehnai) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx#L49)):*
> ```XML
>    * but are along route geometry.
>    */
>   const displayedStops = pipe(
> ```

we were talking about this component just getting `routeId` as a parameter and then using the `useRouteInfo` hook to fetch all the necessary data. Have you tried that, were there some unforeseen obstacles?
___
*[`ui/src/graphql/route.ts` line 359 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbf7pYBUbULFNg8DoK:-NDbf7pYBUbULFNg8DoL:b-qs1rmk) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/graphql/route.ts#L359)):*
> ```XML
> `;
> 
> const GET_ROUTE_WITH_INFRASTRUCTURE_LINKS = gql`
> ```

this should be defined within the component/hook it is used. (remember the `GQL_` prefix so that linter won't complain) Is it useEditRouteGeometry?
___
*[`ui/src/graphql/route.ts` line 489 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbfjDOB0N5B8u2IMrr:-NDbfjDOB0N5B8u2IMrs:b-p46545) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/graphql/route.ts#L489)):*
> ```XML
> 
> export const getRouteStopLabels = (
>   route: RouteWithJourneyPatternStopsFragment,
> ```

using more specific types, nice!
___
*[`ui/src/hooks/routes/useCreateRoute.ts` line 24 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbhdAOBTGaQ1HELHuH:-NDbhdAOBTGaQ1HELHuI:b-at85t8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/hooks/routes/useCreateRoute.ts#L24)):*
> ```XML
> import { useValidateRoute } from './useValidateRoute';
> 
> interface CreateParams extends BuildJourneyPatternStopSequenceProps {
> ```

This feels wrong. Extending an interface means that you want to be _compatible_ and extend a given type with some more fields. Here though the relation is different, not like a parent-child, more like a sibling relationship. I think this would describe the type better:

```
type CreateParams = {
  form: RouteFormState;
  infraLinksAlongRoute: RouteInfraLink[];
} & JourneyPatternData;
```

But personally I would not reuse a type name here, just copy the attributes as is:

```
interface CreateParams {
  form
  infraLinksAlongRoute
  journeyPatternStops
  stopsEligibleForJourneyPattern
  includedStopLabels
}
```
As they are all equal parameters and mig [...]

2022-10-06 12:22 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/343)* status: 0 of 36 files reviewed, 26 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/components/map/RouteStopsOverlay.tsx` line 11 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbOnrA18YUi67b_ME4:-NDc3igV45w-kL3BSrUI:b82hvp9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/RouteStopsOverlay.tsx#L11)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could import this directly from `hooks/index.ts`
</blockquote></details>

This was initially done because of some dependency cycles.

I moved some stop util functions to /utils/stops, so now importing like this is possible. Fixed.
___
*[`ui/src/components/map/RouteStopsOverlayRow.tsx` line 35 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbPKT49XUt1xn8dBDn:-NDc4bWy-DBrUWbFliiK:bsmd4l2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/RouteStopsOverlayRow.tsx#L35)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

would `setBelongsToJourneyPattern` be a better name?
</blockquote></details>

Yes. Done
___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 204 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbS-aX8dYJLORH3nRg:-NDc4edQ5sOLwPnzhwvS:buw96yn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/routes/DrawRouteLayer.tsx#L204)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Calculating the included stop labels here does not work too well. Currently it's:
1. getting the old labels from the old geometry (which feels a bit weird as at this point the labels should already exist in the mapEditor store)
2. calling getRemovedStopLabels which visits the backend (which feels a bit weird as all the data should already be available in the infraLinksWithStops variables)
3. does the inversion from removedLabels to includedLabels in an additional calculation

I _think_ this is rather how it should work
1a. if we are drawing a new route, includedStopLabels should be empty as there's no previous information
1b. if we are editing an existing route, then the RouteEditor.tsx could put the included stop labels to the store within the scope of the onEditRoute function
2. in the DrawRouteLayer, when the route geometry is being updated (so this function here), the only thing we'd need to do is to exclude stop labels from the includedStopLabels if the stops don't belong to the geometry anymore (so basically just cross-check that only stops that are eligible to be part of the journey pattern could belong to this array)

I think this could work pretty well and reliably. The only issue I see right now is that when creating a new route, be default all the stops should be included. The semantically most correct way to solve this would be to allow includedStopLabels to be undefined instead of always be existing and empty when being reset. That way we would semantically separate the two cases when:
- we haven't yet defined included stop labels (so when first drawing a new route)
- we have excluded all stops from the route

</blockquote></details>

I agree. 

I would like to limit the size of these PRs, though. I don't think this is in scope of this PR, even though it is related. Maybe separate PR?
___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 205 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbQ08H1Xvfn7eYCRxd:-NDc5-H70GNbpa0t-BlS:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/33b6d798847518801436e0e502fba9aa3f4c496f/ui/src/components/map/routes/DrawRouteLayer.tsx#L205)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

awesome that you managed to remove this filtering from here!
</blockquote></details>

Done.
___
*[`ui/src/components/map/routes/RouteEditor.tsx` line 200 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbc98L4Uig7a9I9OhT:-NDc5A_d88tXYv1FGDk-:b-bbqfv9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/routes/RouteEditor.tsx#L200)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

a few things came to mind here:
- why is the variable called newJourneyPatternStops? There are just simply journeyPatternStops, what is new in them...?
- the getStopsFromRoute is basically just extracting data deep from an embedded object, but doesn't add any functionality there. To me at least it feels that it's just obfuscating the logic of what's happening in under
- I was trying to understand why the mapStopInJourneyPatternToJourneyPatternStop function was created, why is there a reason to try to strip anything from the JourneyPatternScheduledStopPointInJourneyPattern entity? In the mapEditor we are anyway only using the restricted JourneyPatternStopFragment type, but it is in fact compatible with the original JourneyPatternScheduledStopPointInJourneyPattern type.

Without further ado, is there a special reason this wasn't just written like this?
```
dispatch(setDraftRouteJourneyPatternStopsAction(routeDetailsResult.data.route_route_by_pk.route_journey_patterns[0].scheduled_stop_point_in_journey_patterns));
```
</blockquote></details>

First of all I really think using pipe in a situation like this improves readability. But answers to your specific points are below:

1. journeyPatternStops is already defined in outer scope
2. Yeah maybe that could be inline
3. The type sure does match, but there will be extra fields. If we strip nothing, we will try to push some extra data to hasura when updating journey pattern. That will result e.g. the following error when adding/removing a stop from the journey pattern:



_Code snippet:_
```XML
Tallennus epäonnistui, 'Error: field "__typename" not found in type: 'journey_pattern_scheduled_stop_point_in_journey_pattern_insert_input''
```
___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx` line 49 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbeA-6B4DE2LYZ9QFI:-NDc8EK12Uses4CE9Y9u:b-tggpyw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx#L49)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

we were talking about this component just getting `routeId` as a parameter and then using the `useRouteInfo` hook to fetch all the necessary data. Have you tried that, were there some unforeseen obstacles?
</blockquote></details>

This change was done earlier than we talked about it and I didn't want to extend this PR diff any further after talking about it. 

Doing this change requires changes to this component, the one above it, and also hooks (`useEditRouteJourneyPattern` parameter typings etc.) etc. Maybe other PR?
___
*[`ui/src/graphql/route.ts` line 359 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbf7pYBUbULFNg8DoK:-NDfxVc37S2fgoSwLn9m:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/graphql/route.ts#L359)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this should be defined within the component/hook it is used. (remember the `GQL_` prefix so that linter won't complain) Is it useEditRouteGeometry?
</blockquote></details>

Done.
___
*[`ui/src/graphql/route.ts` line 489 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbfjDOB0N5B8u2IMrr:-NDc91fj7pRNGeWAceOF:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/graphql/r [...]

2022-10-07 07:30 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/343)* status: 0 of 36 files reviewed, 10 unresolved discussions (waiting on @eleksi and @pallost)

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 204 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbS-aX8dYJLORH3nRg:-NDlLPvLBpB1KDqP0QtR:brg6w48) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/routes/DrawRouteLayer.tsx#L204)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I agree. 

I would like to limit the size of these PRs, though. I don't think this is in scope of this PR, even though it is related. Maybe separate PR?
</blockquote></details>

okay, let's do this in a separate PR
___
*[`ui/src/components/map/routes/RouteEditor.tsx` line 200 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbc98L4Uig7a9I9OhT:-NDlBXEk6_t6M6VXg4Fv:b-zalq5v) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/routes/RouteEditor.tsx#L200)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

First of all I really think using pipe in a situation like this improves readability. But answers to your specific points are below:

1. journeyPatternStops is already defined in outer scope
2. Yeah maybe that could be inline
3. The type sure does match, but there will be extra fields. If we strip nothing, we will try to push some extra data to hasura when updating journey pattern. That will result e.g. the following error when adding/removing a stop from the journey pattern:

</blockquote></details>

1. good point, haven't noticed it
2. thanks for removing it
3. the only extra field that is there and causing issues is the __typename field. Also, currently the `buildJourneyPatternStopSequence` function is producing `JourneyPatternStopFragment[]` type which are not compatible with the expected `JourneyPatternScheduledStopPointInJourneyPatternInsertInput[]` type. The proper solution would be to set the `buildJourneyPatternStopSequence` function's return type to be this `InsertInput`. This will also warn you that the __typename is incompatible if you use the `...stopInJourneyPattern` spread, but that could be just fixed by manually setting `__typename: journey_pattern_scheduled_stop_point_in_journey_pattern_insert_input` afterwards. Or just set it to undefined...
So let's remove this 1->1 mapping function still and fix the issue where it's introduced.
___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx` line 49 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbeA-6B4DE2LYZ9QFI:-NDlFGwEC812NSESY6S5:bl1auf1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx#L49)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This change was done earlier than we talked about it and I didn't want to extend this PR diff any further after talking about it. 

Doing this change requires changes to this component, the one above it, and also hooks (`useEditRouteJourneyPattern` parameter typings etc.) etc. Maybe other PR?
</blockquote></details>

Fair enough, let's do this in another PR then!
___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx` line 59 at r41](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDlDvVOChUMNaI5mbyH:-NDlDvVOChUMNaI5mbyI:bb3bj6s) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/60988af01e2cced2d519704bff68b947d8d0e1ae/ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx#L59)):*
> ```XML
>       ),
>     (stops) =>
>       showUnusedStops
> ```

oh, that's an interesting way for bypassing a filtering within a pipe if a flag is present. Not a bad idea! 

This is all fine! This is how you can do conditional threading (=piping) with Clojure: https://stackoverflow.com/questions/11767931/conditional-elements-in-pipelines

Personally I will probably rather go with this approach for readability:

```
  const displayedStops = pipe(
    route,
    getEligibleStopsAlongRoute,
    (eligibleStops) =>
      getHighestPriorityStopsEligibleForJourneyPattern(
        eligibleStops,
        observationDate,
        route.priority === Priority.Draft,
      ),
    showUnusedStops ? _.identity : (stops) => stops.filter(...)
);
```
___
*[`ui/src/hooks/routes/useEditRouteJourneyPattern.ts` line 53 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDblEwf6Y6SQ4TNASz0:-NDlIt_C1AbhOrs9c7B4:bp2k91i) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/hooks/routes/useEditRouteJourneyPattern.ts#L53)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Probably
</blockquote></details>

alright, let's do it in a later PR then
___
*[`ui/src/hooks/routes/useEditRouteJourneyPattern.ts` line 71 at r41](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDlGkCi3aD4YT8dMo6p:-NDlGkCi3aD4YT8dMo6q:b5looaq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/60988af01e2cced2d519704bff68b947d8d0e1ae/ui/src/hooks/routes/useEditRouteJourneyPattern.ts#L71)):*
> ```XML
>       (stops) =>
>         stops
>           .filter((stop) => stopBelongsToJourneyPattern(stop, route.route_id))
> ```

umm, the extractEligibleStopsForJourneyPattern should already make sure that the stop belongs to the given journey pattern (as it was built from a route's data). Is there a bug there somewhere that you need to do this filtering here...?
___
*[`ui/src/hooks/routes/useEditRouteJourneyPattern.ts` line 75 at r41](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDlIERl12Mb3rHsC_kv:-NDlIERl12Mb3rHsC_kw:bcioq7g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/60988af01e2cced2d519704bff68b947d8d0e1ae/ui/src/hooks/routes/useEditRouteJourneyPattern.ts#L75)):*
> ```XML
>       // Add or remove stop from label list
>       (stopLabels) => {
>         const stops = new Set(stopLabels);
> ```

pipes help to group transformations on a variable in a visual way. E.g. could think of it like that within a pipe, only lodash functions should be used.

However it's not very good to use it for business logic like this, it makes it harder to read. Let's rather split the adding/removing logic out from the pipe.
___
*[`ui/src/hooks/routes/useRouteInfo.ts` line 79 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbmM9S6q2RjJS2YGLw:-NDlJBXxC71seV8Xlzxn:b-uq15dz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/hooks/routes/useRouteInfo.ts#L79)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Well, I don't think this function is even trying to do what `filterHighestPriorityCurrentStops` is doing and I don't think `filterHighestPriorityCurrentStops` really messes up the order.

`filterHighestPriorityCurrentStops` takes an array of stops, observation date and draft flag and returns an (still ordered) array of stops that only contains the highest priority instances of those stops that are valid during the given observation date. There is only one instance of each stop in the returned array, because that is what the function is supposed to do.

Now this function is here, because we have cases that we have one stop multiple times on the same journey pattern. If we used `filterHighestPriorityCurrentStops`, we would get only one (highest priority) instance of each stops that is in the list of stops given. The point here is not to "fix the order", but rather remove any lower priority eligible stops, so pattern of only the highest priority remains.

For example:

input -> output
A(20) A(10) B(10) (A20) A(10) -> A(20) B(10) A(20)  //StopLabel(priority)
</blockquote></details>

I think I see what you are aiming for here... Unfortunately this function does not [...]

2022-10-10 11:31 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/343)* status: 0 of 36 files reviewed, 10 unresolved discussions (waiting on @pallost)

___
*[`ui/src/components/map/routes/DrawRouteLayer.tsx` line 204 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbS-aX8dYJLORH3nRg:-NE-hctg1sgfu2XDxCr7:b2nhswv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/routes/DrawRouteLayer.tsx#L204)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

okay, let's do this in a separate PR
</blockquote></details>

Yep
___
*[`ui/src/components/map/routes/RouteEditor.tsx` line 200 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbc98L4Uig7a9I9OhT:-NE-n0mR0Cchq5_3dDwT:b-m8g3kh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/map/routes/RouteEditor.tsx#L200)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

1. good point, haven't noticed it
2. thanks for removing it
3. the only extra field that is there and causing issues is the __typename field. Also, currently the `buildJourneyPatternStopSequence` function is producing `JourneyPatternStopFragment[]` type which are not compatible with the expected `JourneyPatternScheduledStopPointInJourneyPatternInsertInput[]` type. The proper solution would be to set the `buildJourneyPatternStopSequence` function's return type to be this `InsertInput`. This will also warn you that the __typename is incompatible if you use the `...stopInJourneyPattern` spread, but that could be just fixed by manually setting `__typename: journey_pattern_scheduled_stop_point_in_journey_pattern_insert_input` afterwards. Or just set it to undefined...
So let's remove this 1->1 mapping function still and fix the issue where it's introduced.
</blockquote></details>

There are also some other extra fields e.g. journeyPatternId etc. It is not obvious from the type, but Hasura will return an error if those fields are present. 

But as you wish, I removed the mapping function and remove the extra fields inline.
___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx` line 49 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbeA-6B4DE2LYZ9QFI:-NE-nK4EDp7mXHHkUIJx:b2nhswv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx#L49)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Fair enough, let's do this in another PR then!
</blockquote></details>

Yep
___
*[`ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx` line 59 at r41](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDlDvVOChUMNaI5mbyH:-NE-uijG7j_ErftBw-tz:b95r6l8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/60988af01e2cced2d519704bff68b947d8d0e1ae/ui/src/components/routes-and-lines/line-details/RouteStopsSection.tsx#L59)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

oh, that's an interesting way for bypassing a filtering within a pipe if a flag is present. Not a bad idea! 

This is all fine! This is how you can do conditional threading (=piping) with Clojure: https://stackoverflow.com/questions/11767931/conditional-elements-in-pipelines

Personally I will probably rather go with this approach for readability:

```
  const displayedStops = pipe(
    route,
    getEligibleStopsAlongRoute,
    (eligibleStops) =>
      getHighestPriorityStopsEligibleForJourneyPattern(
        eligibleStops,
        observationDate,
        route.priority === Priority.Draft,
      ),
    showUnusedStops ? _.identity : (stops) => stops.filter(...)
);
```
</blockquote></details>

I changed this. Readability probably depends on who is reading it, as `identity` is probably confusing for developers without Clojure background.

After testing this, I noticed that lodash identity messes up the types. TS doesn't realize that identity always has a parameter, so it types identity return value as Stop[] | undefined. Then `displayedStops` becomes Stop[] | undefined as well... Fortunately remeda has identity function as well and it works :) 
___
*[`ui/src/hooks/routes/useEditRouteJourneyPattern.ts` line 53 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDblEwf6Y6SQ4TNASz0:-NE-dedj4-OYlMLaFrr7:b2nhswv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/hooks/routes/useEditRouteJourneyPattern.ts#L53)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

alright, let's do it in a later PR then
</blockquote></details>

Yep
___
*[`ui/src/hooks/routes/useEditRouteJourneyPattern.ts` line 71 at r41](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDlGkCi3aD4YT8dMo6p:-NE-e-B68dalDETkrq4q:b-hvicjl) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/60988af01e2cced2d519704bff68b947d8d0e1ae/ui/src/hooks/routes/useEditRouteJourneyPattern.ts#L71)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

umm, the extractEligibleStopsForJourneyPattern should already make sure that the stop belongs to the given journey pattern (as it was built from a route's data). Is there a bug there somewhere that you need to do this filtering here...?
</blockquote></details>

`extractEligibleStopsForJourneyPattern` gets all stops that are eligible to be added, not only the ones that belong to the journey pattern.

We could just remove`stopsEligibleForJourneyPattern` from this hook completely as it is no longer required as we don't use RouteStops. This however requires the passed route object to contain journey pattern data for all stops so we can map `journeyPatternStops` straight from the passed route instead of through `stopsEligibleForJourneyPattern`. Unfortunately this hook takes `RouteRoute` as parameter, and fixing it to use the correct type takes us to a rabbit hole again, having to change types in tons of components, `useGetLineDetails` hook etc., maybe even the line fetch query itself. Maybe fix this later as well..?
___
*[`ui/src/hooks/routes/useEditRouteJourneyPattern.ts` line 75 at r41](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDlIERl12Mb3rHsC_kv:-NE-fFPR83tC8ZUamEC0:b-xug83l) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/60988af01e2cced2d519704bff68b947d8d0e1ae/ui/src/hooks/routes/useEditRouteJourneyPattern.ts#L75)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

pipes help to group transformations on a variable in a visual way. E.g. could think of it like that within a pipe, only lodash functions should be used.

However it's not very good to use it for business logic like this, it makes it harder to read. Let's rather split the adding/removing logic out from the pipe.
</blockquote></details>

True. Struggled with function naming but now it is out of pipe.
___
*[`ui/src/hooks/routes/useRouteInfo.ts` line 79 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbmM9S6q2RjJS2YGLw:-NE-glVa9l9RETGf3gVF:b-i8gegp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/hooks/routes/useRouteInfo.ts#L79)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I think I see what you are aiming for here... Unfortunately this function does not do that :) you are filtering the eligible stops by the highest priority stops' *ids*, so in the end it will just return the same highest priority stops for you as the filterHighestPriorityCurrentStops function would.

Also remember that from stop A there can only be two versions active at a given observation date, with two different priorities. So your example, `A(20) A(10) B(10) (A20) A(10)` is not po [...]

2022-10-12 10:03 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/343)* status: 0 of 36 files reviewed, 1 unresolved discussion (waiting on @eleksi)

___
*[`ui/src/hooks/routes/useRouteInfo.ts` line 79 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbmM9S6q2RjJS2YGLw:-NEAantmDiAHNw3VbMXN:bvk9fno) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/hooks/routes/useRouteInfo.ts#L79)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I probably was not clear enough in my previous comment, when I explained the case this function is mostly for. Yes, it is true that in most of the cases my example is not possible, but if we go through the same infrastructure link multiple times (e.g. loop, or "pisto"), then we could have the same stop with same priority multiple times on the journey pattern. Therefore, I think this function does have a job.
</blockquote></details>

that is true, this function does that additional. If the same stop may appear multiple times in the array, then the current `filterHighestPriorityCurrentStops` will only return a single instance of it because of lodash's `maxBy` function. On the other hand, this issue could still be fixed within the `filterHighestPriorityCurrentStops` function directly (to be able to handle multiple instances of the same stop) instead of mitigating the delegating forward.


<!-- Sent from Reviewable.io -->

2022-10-13 08:31 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/343)* status: 0 of 36 files reviewed, 1 unresolved discussion (waiting on @pallost)

___
*[`ui/src/hooks/routes/useRouteInfo.ts` line 79 at r31](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-NDbmM9S6q2RjJS2YGLw:-NEFT3V97CNeH7NJlWkP:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/578afc999ac88c6ed964461a2f9b81331864907c/ui/src/hooks/routes/useRouteInfo.ts#L79)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

that is true, this function does that additional. If the same stop may appear multiple times in the array, then the current `filterHighestPriorityCurrentStops` will only return a single instance of it because of lodash's `maxBy` function. On the other hand, this issue could still be fixed within the `filterHighestPriorityCurrentStops` function directly (to be able to handle multiple instances of the same stop) instead of mitigating the delegating forward.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-13 08:40 UTC, pallost approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/343#-:-NEFV9h-6KgpR--S_swy:bnfp4nl)* status: 0 of 36 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2022-10-13 09:48 UTC, merged