Validity check hook tests + small fixes to hook itself
HSLdevcom/jore4-ui pull request #346
Opened 2022-09-29 13:19 UTC by tk-vincit

Tests included in this PR:
```
 PASS  src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts (5.801 s)
  useCheckValidityAndPriorityConflicts()
    ✓ Should return conflict on resources with same validity_start (14 ms)
    ✓ Should return conflict on resources with same validity_end (13 ms)
    ✓ Should return conflict on resource within existing instance of resource (16 ms)
    ✓ Should return conflict on resource starting before and ending after existing version (15 ms)
    ✓ Should not allow new version after current version when bounds overlap (12 ms)
    ✓ Should allow new version after current version, bounds not overlapping, validity_end null (11 ms)
    ✓ Should allow new version after current version, bounds not overlapping, validity_end defined (14 ms)
    ✓ Should not allow new version before current version when bounds overlap (12 ms)
    ✓ Should allow new version before current version, bounds not overlapping, validity_start defined (14 ms)
    ✓ Should allow new version before current version, bounds not overlapping, validity_start null (15 ms)
    Indefinite resources (validity_start and validity_end both null)
      ✓ Should return conflict on two resources with indefinite validity (43 ms)
      ✓ Should return conflict on bounded resource within existsting indefinite resource (16 ms)
    Special cases
      ✓ Should allow creating conflicting version with new priority (12 ms)
      ✓ Should allow creating conflicting version with draft priority (1 ms)
      ✓ Should allow creating conflicting version of the resource itself (=with same id). (Otherwise resources could not be edited. Conflicts do not matter in this case as we are *overwriting* conflicting version) (13 ms)
      ```
Resolves HSLdevcom/jore4[#740](https://github.com/HSLdevcom/jore4-ui/issues/740)

2022-10-07 10:42 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/346)* status: 0 of 3 files reviewed, 15 unresolved discussions (waiting on @pallost and @tk-vincit)

___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.ts` line 52 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlpE8f-Wi7l14X14N1:-NDlpE8f-Wi7l14X14N2:b-81rs7b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.ts#L52)):*
> ```XML
> const buildCommonGqlFilter = (
>   params: CommonParams,
>   allowUndefinedValidityStart = true,
> ```

I know it's not directly part of this PR, but this flag is never used, so this value is always true. I also don't think we should support it, it's not really in the scope of this hook. Let's just shove all the check conditions from buildValidityStartMissingGqlFilterOrConditions to this buildCommonGqlFilter function to see the full picture.

I also don't see a reason to fork the logic based on if the resource is indefinite. Let's just rather put all these conditions on the same level, connected with an OR operator. Having a comment or a visual representation of the intervals should help a lot!
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 36 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlv0Ym6HERgNHd8rGJ:-NDlv0Ym6HERgNHd8rGK:b-35rce7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L36)):*
> ```XML
> type TestLine = RouteLineInsertInput & {
>   label: string;
>   validity_start?: DateTime;
> ```

I do see the `null` value useful for the validity periods. Undefined means, well, that it's not defined. Null however means that it IS defined and is defined to be infinite.
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 116 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDm-yBb7yT4ebzKhVdu:-NDm-yBb7yT4ebzKhVdv:b5ikfdu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L116)):*
> ```XML
>   });
> 
>   const { result } = renderHook(
> ```

I'm wondering that is this hook now technically stateful? I understand that for this hook it's not an issue as there's no state within, but I wonder if we should add a comment here that people won't start copy-pasting this pattern to other hook tests but be warned that these hooks are actually stateful and if they need otherwise, they'd need to call the renderHook function within the tests themselves.
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 121 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlx2_E9bm8aNxUmJUF:-NDlx2_E9bm8aNxUmJUG:b-c0mni0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L121)):*
> ```XML
>   );
> 
>   describe('Indefinite resources (validity_start and validity_end both null)', () => {
> ```

this text is not true, you have tests within that check for bounded validity periods as well. How about this?
`Checking validity period conflicts (label and priority are the same)`



_Code quote:_
```XML
ndefinite resources (validity_start and validity_end both null)
```
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 125 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlwaaV8NEfud6BmpAm:-NDlwaaV8NEfud6BmpAn:b8qq0ox) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L125)):*
> ```XML
>       await act(async () => {
>         const conflicts = await result.current.getConflictingLines(
>           buildQuery({ label: indefiniteLine.label }),
> ```

let's add the full parameter set for clarity: `{label: indefiniteLine.label, validityStart: null, validityEnd: null}`
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 127 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlxVcBCJC56jdvmQz9:-NDlxVcBCJC56jdvmQzA:bhsq5f2) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L127)):*
> ```XML
>           buildQuery({ label: indefiniteLine.label }),
>         );
>         expect(conflicts.length).toBe(1);
> ```

should add an additional expect to every test below to be certain that the correct conflicting resource was found:
`expect(conflicts[0].line_id).toEqual(indefiniteLine.line_id)`
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 130 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlxtIMBWHAVOHhRabm:-NDlxtINAT5NwogcvriH:byd3jki) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L130)):*
> ```XML
>       });
>     });
>     test('Should return conflict on bounded resource within existsting indefinite resource', async () => {
> ```

typo, "existing"
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 144 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlyxQi8EMSja21XtLK:-NDlyxQi8EMSja21XtLL:b-peyqxq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L144)):*
> ```XML
>   });
> 
>   test('Should return conflict on resources with same validity_start', async () => {
> ```

this is an edge case. Would need a more generic test as well where we check that even if we query against (validity_start minus 1 millisecond), the conflict will happen
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 149 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlyqfO2xxeoeRa41GX:-NDlyqfO2xxeoeRa41GY:b-veeoil) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L149)):*
> ```XML
>         buildQuery({
>           label: indefiniteEndLine.label,
>           validityStart: indefiniteEndLine.validity_start,
> ```

let's write explicitly that validity_end = null
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 161 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlzTWo3txQi6vsF1X1:-NDlzTWo3txQi6vsF1X2:bqbeoin) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L161)):*
> ```XML
>         buildQuery({
>           label: indefiniteStartLine.label,
>           validityEnd: indefiniteStartLine.validity_end,
> ```

same as with the previous test: should write explicitly validity_start = null and should also add a test that's not an edge case (validity_end plus 1 millisecond)
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 173 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlzkb04xmn_A8fNv0c:-NDlzkb04xmn_A8fNv0d:bbsotyc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L173)):*
> ```XML
>         buildQuery({
>           label: boundedLine.label,
>           validityStart: boundedLine.validity_start?.plus({ milliseconds: 1 }),
> ```

the "!" operator would be better here instead of the "?" operator. We do know that this is defined.
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 186 at r9](https://rev [...]

2022-10-10 12:21 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/346)* status: 0 of 3 files reviewed, 14 unresolved discussions (waiting on @pallost)

___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.ts` line 52 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlpE8f-Wi7l14X14N1:-NE0mt4u7QBzFE8dyZvY:b7turso) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.ts#L52)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I know it's not directly part of this PR, but this flag is never used, so this value is always true. I also don't think we should support it, it's not really in the scope of this hook. Let's just shove all the check conditions from buildValidityStartMissingGqlFilterOrConditions to this buildCommonGqlFilter function to see the full picture.

I also don't see a reason to fork the logic based on if the resource is indefinite. Let's just rather put all these conditions on the same level, connected with an OR operator. Having a comment or a visual representation of the intervals should help a lot!
</blockquote></details>

I removed this flag now. 

Refactoring ternary to `_or` operator made some of the tests fail. I can investigate that a bit more tomorrow, but not sure if that improves the readability nor is worth the effort.
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 36 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlv0Ym6HERgNHd8rGJ:-NE0m8eC9mK8GiT3krbW:bt0jn8q) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L36)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I do see the `null` value useful for the validity periods. Undefined means, well, that it's not defined. Null however means that it IS defined and is defined to be infinite.
</blockquote></details>

Well. I kind of agree with you, but actually `CommonParams` from `ui/src/hooks/useCheckValidityAndPriorityConflicts.ts` have typed these so that validity_start/end are either defined or `undefined`, and this is now symmetrical to that implementation. So if we want to change that, then it would probably make sense to also refactor how `CommonParams` are defined, and that probably causes waterfall effect that requires typings around the whole app adjusted. And that starts to be out of scope of this PR.
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 116 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDm-yBb7yT4ebzKhVdu:-NE0npmo6DOWIMimEyZm:b-ie6gn9) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L116)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'm wondering that is this hook now technically stateful? I understand that for this hook it's not an issue as there's no state within, but I wonder if we should add a comment here that people won't start copy-pasting this pattern to other hook tests but be warned that these hooks are actually stateful and if they need otherwise, they'd need to call the renderHook function within the tests themselves.
</blockquote></details>

Not sure if I fully understand. `useCheckValidityAndPriorityConflicts` isn't stateful, it returns three functions
```
return {
    getConflictingLines,
    getConflictingStops,
    getConflictingRoutes,
  };
```
that are not pure but not "stateful" either. I can add some kind of warning comment if you clarify a bit what you have in mind or suggest the comment, but otherwise I don't see the problem here. I mean yeah, sometimes you should call `renderHook` in each test case, but that's not the case in this test suite.
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 121 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlx2_E9bm8aNxUmJUF:-NE0C9qEABggybfwfXn-:bsni1i1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L121)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this text is not true, you have tests within that check for bounded validity periods as well. How about this?
`Checking validity period conflicts (label and priority are the same)`
</blockquote></details>

Please note I have only two tests nested under this `describe` block. I don't think your suggestion works here.

Test output is someting like this when writing this comment:

```
  useCheckValidityAndPriorityConflicts()
    ✓ Should return conflict on resources with same validity_start (10 ms)
    ✓ Should return conflict on resources with same validity_end (11 ms)
    ✓ Should return conflict on resource within existing instance of resource (13 ms)
    ✓ Should return conflict on resource starting before and ending after existing version (13 ms)
    ✓ Should not allow new version after current version when bounds overlap (14 ms)
    ✓ Should allow new version after current version, bounds not overlapping, validity_end null (11 ms)
    ✓ Should allow new version after current version, bounds not overlapping, validity_end defined (13 ms)
    ✓ Should not allow new version before current version when bounds overlap (14 ms)
    ✓ Should allow new version before current version, bounds not overlapping, validity_start defined (12 ms)
    ✓ Should allow new version before current version, bounds not overlapping, validity_start null (11 ms)
    Indefinite resources (validity_start and validity_end both null)
      ✓ Should return conflict on two resources with indefinite validity (29 ms)
      ✓ Should return conflict on bounded resource within existsting indefinite resource (11 ms)
    Special cases
      ✓ Should allow creating conflicting version with new priority (10 ms)
      ✓ Should allow creating conflicting version with draft priority (1 ms)
      ✓ Should allow creating conflicting version of the resource itself (=with same id). (Otherwise resources could not be edited. Conflicts do not matter in this case as we are *overwriting* conflicting version) (11 ms)
      Routes
        ✓ Does not allow creating conflicting route with same direction (13 ms)
        ✓ Allow creating conflicting route with opposite direction (9 ms)

```
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 125 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlwaaV8NEfud6BmpAm:-NE0p3xD-K43O5-EKDXN:b-phy6ma) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L125)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

let's add the full parameter set for clarity: `{label: indefiniteLine.label, validityStart: null, validityEnd: null}`
</blockquote></details>

Yeah, that sound relevant in this case. Done.
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 127 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlxVcBCJC56jdvmQz9:-NE0_7F62Yq7_vnLv99H:b-ssybmz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L127)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

should add an additional expect to every test below to be certain that the correct conflicting resource was found:
`expect(conflicts[0].line_id).toEqual(indefiniteLine.line_id)`
</blockquote></details>

Expects like that added to the tests that had `expect [...]

2022-10-11 07:24 UTC, pallost requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/346)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.ts` line 52 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlpE8f-Wi7l14X14N1:-NE4vEAJ2zZwy98cCm4G:b-jvxw0e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.ts#L52)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I removed this flag now. 

Refactoring ternary to `_or` operator made some of the tests fail. I can investigate that a bit more tomorrow, but not sure if that improves the readability nor is worth the effort.
</blockquote></details>

that is weird... it should work. I don't think that validity_end being undefined should break break anything as you had the same case with validity_start being undefined within buildValidityStartMissingGqlFilterOrConditions

Could you investigate it?
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 36 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlv0Ym6HERgNHd8rGJ:-NE4rvRREobem-RjnRoJ:b32w0x) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L36)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Well. I kind of agree with you, but actually `CommonParams` from `ui/src/hooks/useCheckValidityAndPriorityConflicts.ts` have typed these so that validity_start/end are either defined or `undefined`, and this is now symmetrical to that implementation. So if we want to change that, then it would probably make sense to also refactor how `CommonParams` are defined, and that probably causes waterfall effect that requires typings around the whole app adjusted. And that starts to be out of scope of this PR.
</blockquote></details>

OK
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 116 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDm-yBb7yT4ebzKhVdu:-NE4rzj051gsYMmY_gpN:b-ncqq5k) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L116)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not sure if I fully understand. `useCheckValidityAndPriorityConflicts` isn't stateful, it returns three functions
```
return {
    getConflictingLines,
    getConflictingStops,
    getConflictingRoutes,
  };
```
that are not pure but not "stateful" either. I can add some kind of warning comment if you clarify a bit what you have in mind or suggest the comment, but otherwise I don't see the problem here. I mean yeah, sometimes you should call `renderHook` in each test case, but that's not the case in this test suite.
</blockquote></details>

I just mean that IF useCheckValidityAndPriorityConflicts used any variables within (regardless if useState of not), then that state variable would be carried around between the tests, which is to be avoided. How to write this? Well, how about "To make sure that the rendered hook does not carry state between tests, the renderHook function should be called once per test instead of once per suite"?
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 121 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlx2_E9bm8aNxUmJUF:-NE4t9i85Q-LT9xM05Al:bay0w0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L121)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please note I have only two tests nested under this `describe` block. I don't think your suggestion works here.

Test output is someting like this when writing this comment:

```
  useCheckValidityAndPriorityConflicts()
    ✓ Should return conflict on resources with same validity_start (10 ms)
    ✓ Should return conflict on resources with same validity_end (11 ms)
    ✓ Should return conflict on resource within existing instance of resource (13 ms)
    ✓ Should return conflict on resource starting before and ending after existing version (13 ms)
    ✓ Should not allow new version after current version when bounds overlap (14 ms)
    ✓ Should allow new version after current version, bounds not overlapping, validity_end null (11 ms)
    ✓ Should allow new version after current version, bounds not overlapping, validity_end defined (13 ms)
    ✓ Should not allow new version before current version when bounds overlap (14 ms)
    ✓ Should allow new version before current version, bounds not overlapping, validity_start defined (12 ms)
    ✓ Should allow new version before current version, bounds not overlapping, validity_start null (11 ms)
    Indefinite resources (validity_start and validity_end both null)
      ✓ Should return conflict on two resources with indefinite validity (29 ms)
      ✓ Should return conflict on bounded resource within existsting indefinite resource (11 ms)
    Special cases
      ✓ Should allow creating conflicting version with new priority (10 ms)
      ✓ Should allow creating conflicting version with draft priority (1 ms)
      ✓ Should allow creating conflicting version of the resource itself (=with same id). (Otherwise resources could not be edited. Conflicts do not matter in this case as we are *overwriting* conflicting version) (11 ms)
      Routes
        ✓ Does not allow creating conflicting route with same direction (13 ms)
        ✓ Allow creating conflicting route with opposite direction (9 ms)

```
</blockquote></details>

well, this grouping is a bit weird... how about grouping those first 10 tests into a describe block as well ("bounded resources (either validity_start or validity_end are defined)")?
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 303 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDm11so9Uc0RUsDizbo:-NE4uJIO9fUPerYjPwC4:btp54nw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L303)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Good idea, updated test description.

Not sure if I understand what kind of test you suggest to be added here? Resources can't conflict unless they have same label, and we already have tests covering different cases of operations related to bounded line.

And in this case we are creating version of bounded line that conflicts with existing version of it, but that conflicts is ignored as expalained in the new comment.
</blockquote></details>

Line1: [yesterday, today]
Line2: [today, tomorrow]
_edit_ Line1 validity_end to be "tomorrow" and expect a conflict

With this, we verify that conflict checking also works also when editing an existing resource, not only when creating one
___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 136 at r14](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NE4tdfh6waOJm7AqQPC:-NE4tdfh6waOJm7AqQPD:bag2ocf) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/a1bdb64d3bb3c18f0942b2b88afbe426be4e858c/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L136)):*
> ```XML
>     });
> 
>     test('Should return conflict on bounded resource within existsting indefinite resource', async () => {
> ```

existing :)



_Code quote:_
```XML
existsting
```


<!-- Sent from Reviewable.io -->

2022-10-11 07:26 UTC, pallost reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/346)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts` line 173 at r9](https://reviewable.io/reviews/hsldevcom/jore4-ui/346#-NDlzkb04xmn_A8fNv0c:-NE4vwTa82N9yuqiEOnU:btdfvnj) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/0453715482085e6f800bb814ca3ea09bbcbff591/ui/src/hooks/useCheckValidityAndPriorityConflicts.integration.spec.ts#L173)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Well, in that case we have to disable eslint, either for each row (which adds unnecessary noise to the tests) or for the whole file or for all test files.

Does it somehow improve test safety if we use `!` instead of `?`? At least this test would fail in either case if validity_start would be undefined.
</blockquote></details>

that is true, it won't improve type safety... leave it like this.


<!-- Sent from Reviewable.io -->

2022-10-12 13:03 UTC, tk-vincit commented
Due to Reasons this was split into two PR's, this one and https://github.com/HSLdevcom/jore4-ui/pull/360. 
Anyway, 360 is now approved and it has same changes as this one, but CI on it doesn't want to run tests.
Will merge this after CI shows green light and that closes both of the PR's.

2022-10-12 13:16 UTC, merged