Check stop draft priority when changing route
HSLdevcom/jore4-ui pull request #353
Opened 2022-10-05 11:48 UTC by culka

- Check priority for all stops when changing route priority from draft
- Add a confirmation window with options to keep stops or remove them

Resolves HSLdevcom/jore4#839

2022-10-19 10:31 UTC, culka reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/353)* status: 0 of 9 files reviewed, 16 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx` line 3 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAUfEl8RN6BRRnqt3A:-NEjmv-UDqM-u8QUgs6g:bxhdsw7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx#L3)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`import { CloseIconButton, SimpleButton } from '../../../uiComponents` (unless there are dependency cycle reasons to use direct imports)
</blockquote></details>

Removed need for these.
___
*[`ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAUyS29puT6N7WDRwE:-NEj7mkj1c-luOcawn5d:bkj63rm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx#L11)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This component seems to be highly specific, starting from the name of the component and also looking at the props.
Thus I wonder if it makes any sense to define text contents from outside and pass those as props? I would just put these directly in the component itself, making component interface cleaner.

Or if you want to define actually reusable component, then you probably want to also pass buttons and their onClick callbacks from outside.
</blockquote></details>

Created a DialogWithButtons with variable number of buttons.
___
*[`ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx` line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAWJlUCHD2qwK7be7V:-NEj7i6-6femaHyZxg0X:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx#L42)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

You can avoid defining "text-xl font-bold" classNames by defining this title as `<h3>` tag.
I assume you can write this like this:
`   <Dialog.Title className="flex " as="h3>`
but if that doesn't work, you can just wrap title in h3 tag:

```
<Dialog.Title ...>
<h3>{title}</h3}
</Dialog.Title>

```
</blockquote></details>

Done.
___
*[`ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx` line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAVlEa5VRhA9RzYSJ4:-NEjKx1b98rwnDbzOugi:b-jvmq2o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx#L47)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Wtf?
Seems like this should be written like this:

```
      <Dialog.Description className="my-5>
        {description}
      </Dialog.Description>
```
</blockquote></details>

I created a new generic DialogWithButtons which inherited this from ConfirmationDialog. Will not change until someone with a better idea how the text creation it should work.
___
*[`ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx` line 43 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAXBEZ0WcGily5ToXp:-NEjLPHf5czGQqaymFoK:bbvr834) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx#L43)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why do these have `has` prefix if these are not boolean flags?

Also wondering why these are defined as arrays? Assuming I parsed this file correctly in my head, seems like these have always either 0 or 1 elements, so array structure doesn't make sense to me.
</blockquote></details>

Renamed to plain `draftStops`. There can be multiple draft stops on the route, so kept as an array.
___
*[`ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx` line 79 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAXigr1TE2Qda9uIA8:-NEjLv4N5kqCHWvCJ0_K:bw770f4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx#L79)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`(form: RouteFormState | undefined)` -> `(form?: RouteFormState)`

(Its also a bit confusing why this parameter is optional in first place and what we should do if it is not given.
</blockquote></details>

It should not have been optional at all.
___
*[`ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx` line 114 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAZ4bz-zO4JDUAl420:-NEjVlAkCcZaBA4tEbuG:b94lijb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx#L114)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This "onSubmitFinish", "onSubmit" structure doesn't make sense. Seems like "onSubmit" function doesn't actually submit anything, and it then calls "onSubmitFinish" function that **does** submit something!

Seems like this function should be called something like "prepareSubmit". Also wondering if this (and onRemoveStopsFromRoute) logic should be extracted somewhere, e.g.  to`useEditRouteMetadata` or `useEditRouteJourneyPattern` hook, not sure which one these belong to. 
</blockquote></details>

Renamed to the proposed names. This logic was also moved to useEditRouteMetadata. onRemoveStopsFromRoute kept in this file since there is not really logic there, just passing the parameters around, and is done the same way on the geometry edit page.
___
*[`ui/src/graphql/route.ts` line 502 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAahDL97l0Y8dAhzAT:-NEjg1254-DOTZu-nF0B:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/graphql/route.ts#L502)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I would rather call this mapper function and not getter.
See this code from this same file as an example.
Please also comment why it is safe to take only first element from arrray and ignore the rest.

```
// The used query has limit: 1 for the result so it can't have more than 1 route_line in result array.
export const mapHighestPriorityLineDetailsWithRoutesResult = (
  result: GqlQueryResult<GetHighestPriorityLineDetailsWithRoutesQuery>,
) =>
  result.data?.route_line.length
    ? (result.data?.route_line[0] as RouteLine)
    : undefined;

```
</blockquote></details>

Done.
___
*[`ui/src/hooks/routes/useEditRouteMetadata.ts` line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAcmeZ4wSrmozxISm7:-NEjgEILBcGlcsKj477r:br0b243) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/hooks/routes/useEditRouteMetadata.ts#L42)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Kind of same here. Not sure if this interface is even needed at all, or does TS infern return type correctly also without this.
</blockquote></details>

Removed as unnecessary, routeId is not even needed here.
___
*[`ui/src/hooks/routes/useEditRouteMetadata.ts` line 141 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAcvqa-ufrythdqlkF:-NEjhI4c4S5okEF4401B:bt1b19p) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/hooks/routes/useEditRouteMetadata.ts#L141)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If you can figure out a bit more [...]

2022-10-20 09:49 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/353)* status: 0 of 13 files reviewed, 12 unresolved discussions (waiting on @culka)

___
*[`ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx` line 11 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAUyS29puT6N7WDRwE:-NEolWzL4ST1t29j95--:b-ws1b2t) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx#L11)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Created a DialogWithButtons with variable number of buttons.
</blockquote></details>

Thanks. Much better.
___
*[`ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx` line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAVlEa5VRhA9RzYSJ4:-NEoki4U4QoQqmqSf4ej:bxhnwb8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx#L47)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

I created a new generic DialogWithButtons which inherited this from ConfirmationDialog. Will not change until someone with a better idea how the text creation it should work.
</blockquote></details>

Moved discussion to the place where this is now, and also mentioned a better idea about how to do this.
___
*[`ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEokzVZ0MW1JkO-Y2Am:-NEokzV_6lqPeFiTaVl8:bou8rdq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx#L15)):*
> ```XML
> }
> 
> export const RouteDraftStopsConfirmationDialog: React.FC<Props> = ({
> ```

This doesn't take `children` prop which `React.FC` implicitly have, so should be typed as `JSX.Element` instead of `React.FC`. Didn't verified the syntax, but something like this:
`export const RouteDraftStopsConfirmationDialog: = ( { ... }:Props ): JSX.Element => (`
(Examples available all around the codebase.)
___
*[`ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEokESP8fj3qoHoRVr5:-NEokESP8fj3qoHoRVr6:b-37jf21) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx#L50)):*
> ```XML
>     ServicePatternScheduledStopPoint[]
>   >([]);
>   const [hasFormData, setHasFormData] = useState<RouteFormState[]>([]);
> ```

Same question as on previous round: why do these have "has" prefix? That makes it sound like "hasFormData" is boolean flag (or form data of form called "has"), but neither one seems to be the case so these need a better name. Perhaps [routeFormData, setRouteFormData]?

Also do we sometimes have more than one form data stored here, so does this have to be array? From current implementation it seems like this is always populated like this: `   setHasFormData([form]);` and used like `hasFormData[0]`, and if that is the case then this shouldn't be an array at all.
___
*[`ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx` line 97 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEofOp86jKYkOcq2bGd:-NEofOp86jKYkOcq2bGe:b-8hg8ju) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx#L97)):*
> ```XML
>       defaultErrorHandler(err);
>     } finally {
>       setHasFormData([]);
> ```

So, if submitting form fails, we just clear the contents of it? Isn't this a bit annoying for the user? Or did I misunderstood something?
___
*[`ui/src/graphql/route.ts` line 487 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEAa8YcD_lciyPGjNW5:-NEojbOb8CT9fFmCdNBn:bbxl5ll) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e8a632c028757e59ff39b5a42a6044011312d19c/ui/src/graphql/route.ts#L487)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I'm surprised if we don't have graphql query for this already, but didn't 
</blockquote></details>

Seems like end of this comment was missing. :smile: Tried to say that I didn't find similar query, so if we really need this then nothing to do here.
___
*[`ui/src/graphql/route.ts` line 514 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEog0yL2lNd2ox1XxCE:-NEog0yL2lNd2ox1XxCF:bfiipvm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/graphql/route.ts#L514)):*
> ```XML
> ) =>
>   result.data?.journey_pattern_journey_pattern[0]?.scheduled_stop_point_in_journey_patterns.flatMap(
>     (sspijp) => sspijp.scheduled_stop_points,
> ```

`sspijp` -> `item`
___
*[`ui/src/hooks/routes/useEditRouteJourneyPattern.ts` line 85 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEogAlYDQ8HDH2li4tt:-NEogAlYDQ8HDH2li4tu:b-av83uu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/hooks/routes/useEditRouteJourneyPattern.ts#L85)):*
> ```XML
> 
>     // Map ServicePatternScheduledStopPoints to RouteStops
>     // const routeStops: RouteStop[] = stopsEligibleForJourneyPattern.map((stop) => {
> ```

Please remove these or explain why we want to have these to version control.



_Code quote:_
```XML
    // Map ServicePatternScheduledStopPoints to RouteStops
    // const routeStops: RouteStop[] = stopsEligibleForJourneyPattern.map((stop) => {
    //  const isStopToEdit = includedStopLabels.includes(stop.label);
```
___
*[`ui/src/uiComponents/ConfirmationDialog.tsx` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEomiaj5cN35ymrHRIo:-NEomiakDGW5LOM9Jaoy:bllpal6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/ConfirmationDialog.tsx#L15)):*
> ```XML
> }
> 
> export const ConfirmationDialog: React.FC<Props> = ({
> ```

Sorry, not part of this PR but also this should be typed as `JSX.Element`.
___
*[`ui/src/uiComponents/ConfirmationDialog.tsx` line 31 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEohJ9_0AMCQU3hhoDz:-NEohJ9_0AMCQU3hhoE-:bpu9kqv) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/ConfirmationDialog.tsx#L31)):*
> ```XML
>       description={description}
>       buttons={[
>         { onAction: onCancel, text: cancelText, inverted: true },
> ```

IMO it would improve readability if "text" would be defined before "onAction".
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 7 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEogzCM293_DJg-DVIU:-NEogzCM293_DJg-DVIV:b-g3nxwx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/DialogWithButtons.tsx#L7)):*
> ```XML
> 
> export interface DialogButton {
>   onAction: () => void;
> ```

onAction -> onClick, buttons have onClick prop and this is passed directly there so it doesn't make sense to invent new name for that here.
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 41 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEojEjy6ngSybaExPLW:-NEojEjy6ngSybaExPLX:b-btu6bx) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/DialogWithButtons.tsx#L41)):*
> ```XML
>     >
>       <div className="flex h-full items-center justify-center">
>         <div
> ```

Do we need both of these divs, or could you just combine these? Now the biggest problem is that we have ambiguous "innerClassName", that is passed to arbitrary div inside this dialog.



_Code quote:_
```XML
      <div className [...]

2022-10-24 07:26 UTC, culka reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/353)* status: 0 of 13 files reviewed, 11 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEokzVZ0MW1JkO-Y2Am:-NF7nEef8rDewI9D1J6i:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/components/forms/route/RouteDraftStopsConfirmationDialog.tsx#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This doesn't take `children` prop which `React.FC` implicitly have, so should be typed as `JSX.Element` instead of `React.FC`. Didn't verified the syntax, but something like this:
`export const RouteDraftStopsConfirmationDialog: = ( { ... }:Props ): JSX.Element => (`
(Examples available all around the codebase.)
</blockquote></details>

Done.
___
*[`ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEokESP8fj3qoHoRVr5:-NEpOAbJ-Ky3BJvzGsxI:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx#L50)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Same question as on previous round: why do these have "has" prefix? That makes it sound like "hasFormData" is boolean flag (or form data of form called "has"), but neither one seems to be the case so these need a better name. Perhaps [routeFormData, setRouteFormData]?

Also do we sometimes have more than one form data stored here, so does this have to be array? From current implementation it seems like this is always populated like this: `   setHasFormData([form]);` and used like `hasFormData[0]`, and if that is the case then this shouldn't be an array at all.
</blockquote></details>

Done.
___
*[`ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx` line 97 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEofOp86jKYkOcq2bGd:-NEpOCgm07oCMman372D:ba2v7jh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/components/routes-and-lines/edit-route/EditRoutePage.tsx#L97)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

So, if submitting form fails, we just clear the contents of it? Isn't this a bit annoying for the user? Or did I misunderstood something?
</blockquote></details>

Yes, kinda. The formData state holds the form data that is going to be submitted once the user clicks an option in the confirmation dialog. If something goes wrong the interface returns back to the main form where they need to click save again, and then confirm in the dialog.
___
*[`ui/src/graphql/route.ts` line 514 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEog0yL2lNd2ox1XxCE:-NEpPQY_1D5n3AuEGH1O:bl34lxg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/graphql/route.ts#L514)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`sspijp` -> `item`
</blockquote></details>

Is that really any better? :slightly_smiling_face: 
___
*[`ui/src/hooks/routes/useEditRouteJourneyPattern.ts` line 85 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEogAlYDQ8HDH2li4tt:-NEpQ3-3EXqilHcDgGgF:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/hooks/routes/useEditRouteJourneyPattern.ts#L85)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please remove these or explain why we want to have these to version control.
</blockquote></details>

Done.
___
*[`ui/src/uiComponents/ConfirmationDialog.tsx` line 15 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEomiaj5cN35ymrHRIo:-NEpQhYq9nv4_Tc0lWl7:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/ConfirmationDialog.tsx#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Sorry, not part of this PR but also this should be typed as `JSX.Element`.
</blockquote></details>

Done.
___
*[`ui/src/uiComponents/ConfirmationDialog.tsx` line 31 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEohJ9_0AMCQU3hhoDz:-NF7miq04Xvne_QJDmM-:b4ug1nu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/ConfirmationDialog.tsx#L31)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

IMO it would improve readability if "text" would be defined before "onAction".
</blockquote></details>

Switched them.
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 7 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEogzCM293_DJg-DVIU:-NEpRU1G0X00SiFsEQY7:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/DialogWithButtons.tsx#L7)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

onAction -> onClick, buttons have onClick prop and this is passed directly there so it doesn't make sense to invent new name for that here.
</blockquote></details>

Done.
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 41 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEojEjy6ngSybaExPLW:-NEtUSRK1FR6LUPS5iuk:b6gkyms) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/DialogWithButtons.tsx#L41)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we need both of these divs, or could you just combine these? Now the biggest problem is that we have ambiguous "innerClassName", that is passed to arbitrary div inside this dialog.
</blockquote></details>

Added a wideDialog boolean property for the element to signify when it should be wide and when not.
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEoiDo-9qKB6TfRQzVI:-NEt6AHAAFXgmx4zdyFX:b-3wl3ev) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/DialogWithButtons.tsx#L50)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Still wtf for this... OK, seems like `ui/src/components/map/stops/EditStopConfirmationDialog.tsx` and `ui/src/components/map/stops/DeleteStopConfirmationDialog.tsx` files have used pattern like `return confirmationTextParts.join('<br/><br/>');`, and I assume that is why we have this hack, but probably those could be changed to `return confirmationTextParts.join('\n\n');` and then we could get rid of this... OK, this originates from things not related to this PR so this comment is non-blocking, but still wanted to point this out.
</blockquote></details>

Fixed this by changing those string joins and adding `whitespace-pre-line` class to enable line breaks in text. Much better. :slightly_smiling_face: 
___
*[`ui/src/utils/stops.ts` line 51 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEohfvcCoR23xD1Y8YI:-NF-e5KA3nGjgF17HOlm:b-u2zkjr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/utils/stops.ts#L51)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I don't understand this function, at least not anymore. If `belongsToJourneyPattern` is true, we are returning `stopsToRemove` with `stops`?
</blockquote></details>

Yeah remove is the wrong name here for the second parameter. The function either adds the provided stops or removes them from the stops -list. Added a proper comment for this function.


<!-- Sent from Reviewable.io -->

2022-10-24 09:33 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/353)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @culka)

___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 41 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEojEjy6ngSybaExPLW:-NF8FRC-6I7vlXyFBL8Z:bdur830) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/DialogWithButtons.tsx#L41)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Added a wideDialog boolean property for the element to signify when it should be wide and when not.
</blockquote></details>

Thanks. Much less confusing now.
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 50 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEoiDo-9qKB6TfRQzVI:-NF8FLgp6PDTu7OL55jo:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/uiComponents/DialogWithButtons.tsx#L50)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Fixed this by changing those string joins and adding `whitespace-pre-line` class to enable line breaks in text. Much better. :slightly_smiling_face: 
</blockquote></details>

Thanks!
___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NF8IRxK2sgnVfZq3u1v:-NF8IRxK2sgnVfZq3u1w:b-b21uqb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/96470736e26ef2cb7b3ad3abe1d7738d469d1e47/ui/src/uiComponents/DialogWithButtons.tsx#L20)):*
> ```XML
>   onCancel: () => void;
>   className?: string;
>   wideDialog?: boolean;
> ```

I suggest calling this `isWide` to indicate that it is supposed to be boolean flag, or just `wide`. `Dialog` postfix doesn't tell anything IMO but instead makes me wonder what does it mean
___
*[`ui/src/utils/stops.ts` line 51 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NEohfvcCoR23xD1Y8YI:-NF8H_A04BsnATEbsz2D:bu5q3pd) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/b95dace0be2de9f049b3fc74bf4dd2add7c0ab61/ui/src/utils/stops.ts#L51)):*
<details><summary><i>Previously, culka (Teemu Mäkinen) wrote…</i></summary><blockquote>

Yeah remove is the wrong name here for the second parameter. The function either adds the provided stops or removes them from the stops -list. Added a proper comment for this function.
</blockquote></details>

Thanks. Comment makes this good enough.


<!-- Sent from Reviewable.io -->

2022-10-24 09:46 UTC, culka reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/353)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @tk-vincit)

___
*[`ui/src/uiComponents/DialogWithButtons.tsx` line 20 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/353#-NF8IRxK2sgnVfZq3u1v:-NF8NiSuEKiYCboMqbME:bb6un1j) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/96470736e26ef2cb7b3ad3abe1d7738d469d1e47/ui/src/uiComponents/DialogWithButtons.tsx#L20)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I suggest calling this `isWide` to indicate that it is supposed to be boolean flag, or just `wide`. `Dialog` postfix doesn't tell anything IMO but instead makes me wonder what does it mean
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-10-24 09:58 UTC, tk-vincit approved these changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/353)* status: 0 of 15 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2022-10-24 10:47 UTC, merged