Add test that moves a stop on the map
HSLdevcom/jore4-ui pull request #375
Opened 2022-10-25 05:37 UTC by sr-vala

Resolves HSLdevcom/jore4#994

2022-10-25 07:43 UTC, eleksi reviewed
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/375)* status: all files reviewed, 5 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/editStop.cy.ts` line 47 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD0j5I4rDWQ2DgRvx4:-NFD0j5I4rDWQ2DgRvx5:bgw1d6h) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L47)):*
> ```XML
>     ...buildStop({
>       label: 'Move stop test stop',
>       located_on_infrastructure_link_id: infraLinks[0].infrastructure_link_id,
> ```

Could you add `measured_location` to make it not appear on top of the other stop?
___
*[`cypress/e2e/editStop.cy.ts` line 89 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD2ABJDUFnovpi2tRd:-NFD2ABJDUFnovpi2tRe:bin4f0y) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L89)):*
> ```XML
>     cy.mockLogin();
>     cy.visit(
>       `/routes?mapOpen=true&lng=${infrastructureLinks[0].shape.coordinates[0][0]}&lat=${infrastructureLinks[0].shape.coordinates[0][1]}&z=${infrastructureLinks[0].shape.coordinates[0][2]}`,
> ```

It could be easier to read this if it was not all in one row. Maybe get coordinates from infrastructure link separately? Or at least destructure coordinates from infralink above e.g.



_Code snippet:_
```XML
const {coordinates} = infrastructureLinks[0].shape
```
___
*[`cypress/pageObjects/ConfirmationDialog.ts` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD3C7l1k9CPhDapVDQ:-NFD3C7l1k9CPhDapVDR:bez7ck5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/pageObjects/ConfirmationDialog.ts#L2)):*
> ```XML
> export class ConfirmationDialog {
>   getConfirmButton() {
> ```

I don't think there is any problem here but I probably would just have made this function `clickConfirm`, `confirm` etc., because at least I cannot se a reason where we would need to get this button but not click it.
___
*[`cypress/pageObjects/Map.ts` line 57 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD3foJ4us0piWShr_5:-NFD3foJ4us0piWShr_6:bj9eg4l) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/pageObjects/Map.ts#L57)):*
> ```XML
> 
>   stopMarkerShouldExist(testStopLabel: string) {
>     cy.getByTestId(`Map::Stops::stopMarker::${testStopLabel}_Standard`).should(
> ```

Could you utilize the function below here



_Code snippet:_
```XML
getStopByStopLabel(testStopLabel).should('exist');
```
___
*[`cypress/pageObjects/StopPopUp.ts` line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD42ZA9Kl279wv-GW4:-NFD42ZA9Kl279wv-GW5:b1dl94o) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/pageObjects/StopPopUp.ts#L2)):*
> ```XML
> export class StopPopUp {
>   getMoveButton() {
> ```

Same here as earlier, I don't know if this is the way to do it, that first you get the button and then click it. I probably would have just made this function `clickMove` or something like that and the one below `clickEdit`. Name suggestions not thought though but the idea is moving the clicking inside here. And again, not sure if it is the clever way to do it, just sharing my thoughts.


<!-- Sent from Reviewable.io -->

2022-10-25 09:53 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/375)* status: all files reviewed, 16 unresolved discussions (waiting on @eleksi and @sr-vala)

___
*[`cypress/e2e/editStop.cy.ts` line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD0CG84FLfI5zzu8Zm:-NFD0CG84FLfI5zzu8Zn:bvixcd1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L13)):*
> ```XML
> } from '@hsl/jore4-test-db-manager';
> import { ConfirmationDialog } from '../pageObjects/ConfirmationDialog';
> import { FilterPanel } from '../pageObjects/FilterPanel';
> ```

If there are no dependency cycles that would trigger linting errors, these should be imported like this:

```
import { 
  ConfirmationDialog 
  FilterPanel,
  Map,
 StopForm
} from '../pageObjects;
```




_Code quote:_
```XML
import { ConfirmationDialog } from '../pageObjects/ConfirmationDialog';
import { FilterPanel } from '../pageObjects/FilterPanel';
import { Map } from '../pageObjects/Map';
import { StopForm } from '../pageObjects/StopForm';
```
___
*[`cypress/e2e/editStop.cy.ts` line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFDWzNQECtg5_fghFO-:-NFDWzNQECtg5_fghFO0:b-9nf5ey) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L18)):*
> ```XML
> import { insertToDbHelper, removeFromDbHelper } from '../utils';
> 
> // TODO: Better location for the test stop. Currently placed on top of another stop in the beginning.
> ```

This comment should be as close to the place that it refers to as possible.
If this can't be fixed as suggested below, I would move this to relevant place in the test case itself.
___
*[`cypress/e2e/editStop.cy.ts` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD0pTF2ZutJSrmPssI:-NFD0pTF2ZutJSrmPssJ:bplj7c8) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L19)):*
> ```XML
> 
> // TODO: Better location for the test stop. Currently placed on top of another stop in the beginning.
> const infrastructureLinks: InfrastructureNetworkInfrastructureLinkInsertInput[] =
> ```

Is it relevant for the test to define all these fields?
If not, look `cypress/e2e/routeStops.cy.ts` for reference and do something like this:

```
import {
  InfraLinkInsertInput,
  infrastructureLinks,
} from '@hsl/jore4-test-db-manager';

const infraLinks: InfraLinkInsertInput[] = [
  {
    ...(infrastructureLinks[0] as InfraLinkInsertInput),
      infrastructure_link_id: '3986bcc4-f3d7-44b8-b46a-0ade9d014af6',
      shape: {
        type: 'LineString',
        coordinates: [
          [24.925251259734353, 60.16287920585574, 15],
          [24.92832655782573, 60.16391811339392, 15],
        ],
      },
  },
];
```

Please avoid defining non-relevant fields in test files as possible, those just clutter up test files and make it more difficult to see what things really matter from the test's perspective.



_Code quote:_
```XML
const infrastructureLinks: InfrastructureNetworkInfrastructureLinkInsertInput[] =
  [
    {
      infrastructure_link_id: '3986bcc4-f3d7-44b8-b46a-0ade9d014af6',
      direction: InfrastructureNetworkDirectionEnum.Bidirectional,
      shape: {
        type: 'LineString',
        coordinates: [
          [24.925251259734353, 60.16287920585574, 15],
          [24.92832655782573, 60.16391811339392, 15],
        ],
      },
      estimated_length_in_metres: 10,
      external_link_source: InfrastructureNetworkExternalSourceEnum.DigiroadR,
      external_link_id: '1',
    },
  ];
```
___
*[`cypress/e2e/editStop.cy.ts` line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFDVXTh6OTQ4eprwWOY:-NFDVXTh6OTQ4eprwWOZ:b-reqgf7) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L27)):*
> ```XML
>         type: 'LineString',
>         coordinates: [
>           [24.925251259734353, 60.16287920585574, 15],
> ```

Commented about this below, but third item in an array is not supposed to be zoom level, but seems like it is used as zoom level here. Please remove it or define it as 0 unless it have some real meaning.
https://www.rfc-editor.org/rfc/rfc7946#section-3.1.1



_Code quote:_
```XML
          [24.925251259734353, 60.16287920585574, 15],
          [24.92832655782573, 60.16391811339392, 15],
```
___
*[`cypress/e2e/editStop.cy.ts` line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFDXp7i5l-Vj78sXp02:-NFDXp7i5l-Vj78sXp03:b-ssraab) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L37)):*
> ```XML
>   ];
> 
> const infraLinks: InfraLinkInsertInput[] = [
> ```

Why do we have both `infraLinks` and `infrastructureLinks`? What is supposed to be the difference? Also seems like `infrastructureLinks` is not even inserted to the db! Is it needed at all? 

In fact, now I realise that `infrastructureLinks` seems to be used only to enter coordinates in the test case. Seems like you could delete the whole `infrastructureLinks` and just define `testCoordinates` (or something like that) in a variable before test case.



_Code quote:_
```XML
InfrastructureNetworkInfrastructureLinkInsertInput
```
___
*[`cypress/e2e/editStop.cy.ts` line 45 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD1uHw5jhifK4UzueF:-NFD1uHw5jhifK4UzueG:bwnwmbg) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L45)):*
> ```XML
> const stops: StopInsertInput[] = [
>   {
>     ...buildStop({
> ```

If you add something like this here:
```
  measured_location: {
    type: 'Point',
    coordinates: [24.92832655782573, 60.16391811339392, 0],
  },
```
you can probably move the stop so that it won't be on top of pre-existing stop anymore? You probably have to adjust the coordinates and might also have to adjust the coordinates of infrastructure link. These coordinates in my example are just random example and do not make sense in this specific case.
___
*[`cypress/e2e/editStop.cy.ts` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD2MZJCdw0za_lRJOi:-NFD2MZJCdw0za_lRJOj:bslzzh3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L56)):*
> ```XML
>   [
>     {
>       infrastructure_link_id: infrastructureLinks[0].infrastructure_link_id,
> ```

This is not relevant for this test. Import `vehicleSubmodeOnInfrastructureLink` from `test-db-manager` and insert `[vehicleSubmodeOnInfrastructureLink[0]]` to db. Then you have to have infra link with corresponding ID in the db, so either do not override id definition of infra link here, or then use spread operator to override it here:
```
{ 
   ...vehicleSubmodeOnInfrastructureLink[0],
    infrastructure_link_id: infrastructureLinks[0].infrastructure_link_id,
}
```



_Code quote:_
```XML
    {
      infrastructure_link_id: infrastructureLinks[0].infrastructure_link_id,
      vehicle_submode: ReusableComponentsVehicleSubmodeEnum.GenericBus,
```
___
*[`cypress/e2e/editStop.cy.ts` line 89 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD39AK7jzSFNNu6uk3:-NFD39AK7jzSFNNu6uk4:b6yxgv0) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L89)):*
> ```XML
>     cy.mockLogin();
>     cy.visit(
>       `/routes?mapOpen=true&lng=${infrastructureLinks[0].shape.coordinates[0][0]}&lat=${infrastructureLinks[0].shape.coordinates[0][1]}&z=${infrastructureLinks[0].shape.coordinates[0][2]}`,
> ```

This looks really bad & difficult to maintain. :see_no_evil:  Also seems like there is logical error: `shape.coordinates[0][2]` is NOT zoom level, but altitude or elevation! https://www.rfc-editor.org/rfc/rfc7946#section-3.1.1 

Please ra [...]

2022-10-27 10:35 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/375)* status: 4 of 10 files reviewed, 12 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`cypress/e2e/editStop.cy.ts` line 13 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD0CG84FLfI5zzu8Zm:-NFNz_9X1r1aggvv3LPg:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If there are no dependency cycles that would trigger linting errors, these should be imported like this:

```
import { 
  ConfirmationDialog 
  FilterPanel,
  Map,
 StopForm
} from '../pageObjects;
```

</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFDWzNQECtg5_fghFO-:-NFNzbJa609HSz_rVhBf:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L18)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This comment should be as close to the place that it refers to as possible.
If this can't be fixed as suggested below, I would move this to relevant place in the test case itself.
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 27 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFDVXTh6OTQ4eprwWOY:-NFO-3-69N5E0U9qAwQO:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L27)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Commented about this below, but third item in an array is not supposed to be zoom level, but seems like it is used as zoom level here. Please remove it or define it as 0 unless it have some real meaning.
https://www.rfc-editor.org/rfc/rfc7946#section-3.1.1
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 37 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFDXp7i5l-Vj78sXp02:-NFO-4tp9RP8oD-mx1HJ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L37)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why do we have both `infraLinks` and `infrastructureLinks`? What is supposed to be the difference? Also seems like `infrastructureLinks` is not even inserted to the db! Is it needed at all? 

In fact, now I realise that `infrastructureLinks` seems to be used only to enter coordinates in the test case. Seems like you could delete the whole `infrastructureLinks` and just define `testCoordinates` (or something like that) in a variable before test case.
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 45 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD1uHw5jhifK4UzueF:-NFO-6jtBwNTAGw0nHnD:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L45)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If you add something like this here:
```
  measured_location: {
    type: 'Point',
    coordinates: [24.92832655782573, 60.16391811339392, 0],
  },
```
you can probably move the stop so that it won't be on top of pre-existing stop anymore? You probably have to adjust the coordinates and might also have to adjust the coordinates of infrastructure link. These coordinates in my example are just random example and do not make sense in this specific case.
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 89 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD39AK7jzSFNNu6uk3:-NFO-DMW44UUabYhTGSc:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L89)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This looks really bad & difficult to maintain. :see_no_evil:  Also seems like there is logical error: `shape.coordinates[0][2]` is NOT zoom level, but altitude or elevation! https://www.rfc-editor.org/rfc/rfc7946#section-3.1.1 

Please rather define function something like this to  `cypress/pageObjects/Map.ts`:

```
import qs from 'qs';
import { Position } from 'geojson';

visit(params?:  {
  zoom?: number;
  lat: number;
  lng: number;
 })
  if (parameters) {
    return cy.visit(`/routes?${qs.strinfigy({
      mapOpen: true,
      zoom: params.zoom || 13; // 13 is default zoom level
      lat: params.lat,
      lng: params.lng,
    
    })}`);

  }
return cy.visit('/routes?mapOpen=true');
```

and then call it here somehow like this:
```

map.visit({
  lat: infrastructureLinks[0].shape.coordinates[0][1];
  lng: infrastructureLinks[0].shape.coordinates[0][0];
});

```

You don't have to define zoom (`z`) parameter, seems like its not relevant for the test as coordinates[0][2]
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 114 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFDWpCb46irx7EvHymc:-NFO-E3K2U6NhW1aribR:b562sqq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L114)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should/could we also check that toast message is shown to the user?
</blockquote></details>

Tried it but does not seem to work in this case.
___
*[`cypress/e2e/editStop.cy.ts` line 122 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFDW9Wq6ETqN_MCHn7E:-NFO-JbF3_mg4eL8wtE1:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L122)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Where do these magical numbers come from? Seems like these happen to be same coordinates as the infra link defined in this file have. So should you check that these equal to those? Something like `should('have.value', String(infrastructureLinks[0].shape.coordinates[0][1]));`
</blockquote></details>

Done.
___
*[`cypress/pageObjects/ConfirmationDialog.ts` line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD3KDo3yyBSuLmTbQ5:-NFO-LJP7X-iLBe_TTC3:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/pageObjects/ConfirmationDialog.ts#L1)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please export this file from `cypress/pageObjects/index.ts`
</blockquote></details>

Done.
___
*[`cypress/pageObjects/Map.ts` line 57 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD3foJ4us0piWShr_5:-NFO-OU8EPgdppJjD4ve:b3nhmn4) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/pageObjects/Map.ts#L57)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Good point and something that I had actually missed. :) 
</blockquote></details>

Removed this since the next click implicitly checks that the element exists.


<!-- Sent from Reviewable.io -->

2022-10-27 14:53 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/375)* status: 4 of 10 files reviewed, 9 unresolved discussions (waiting on @eleksi and @sr-vala)

___
*[`cypress/package.json` line 16 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFOs5Y_4egfy9yzWoNc:-NFOs5Y_4egfy9yzWoNd:bpellzm) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/366b0fcfc301da70bdb6a4dfec88384d66626983/cypress/package.json#L16)):*
> ```JSON
>     "cypress": "^10.3.1",
>     "luxon": "^2.3.0",
>     "qs": "^6.10.1"
> ```

Sorry, didn't realised that this wasn't available in cypress workspace, and forgot to mention that. But thanks for adding it. :)
___
*[`cypress/e2e/editStop.cy.ts` line 18 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFOsepX3WuiQxsFWT9T:-NFOsepX3WuiQxsFWT9U:b4681vi) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/366b0fcfc301da70bdb6a4dfec88384d66626983/cypress/e2e/editStop.cy.ts#L18)):*
> ```XML
>   {
>     ...(infrastructureLinks[3] as InfraLinkInsertInput),
>   },
> ```

Let's refactor this to this:

```
const testCoordinates = [24.925251259734353, 60.16287920585574, 0];

const infraLinks: InfraLinkInsertInput[] = [
  {
    ...(infrastructureLinks[0] as InfraLinkInsertInput),
    shape: {
      type: 'LineString',
      coordinates: [testCoordinates, testCoordinates],
    },
  },
];
```
Then it is clear that it is important to have exactly this infra link inserted into db for this test, and it is relevant that infra link is located exactly at test coordinates. 

(I also verified that this works at least on my machine.)



_Suggestion:_
```XML
const testCoordinates = [24.925251259734353, 60.16287920585574];

const infraLinks: InfraLinkInsertInput[] = [
  {
    ...(infrastructureLinks[3] as InfraLinkInsertInput),
  },
];
```
___
*[`cypress/e2e/editStop.cy.ts` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFOu-pQ6_f9psB6Jmnn:-NFOu-pQ6_f9psB6Jmno:bbij5rt) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/366b0fcfc301da70bdb6a4dfec88384d66626983/cypress/e2e/editStop.cy.ts#L25)):*
> ```XML
>     {
>       infrastructure_link_id: infraLinks[0].infrastructure_link_id,
>       vehicle_submode: ReusableComponentsVehicleSubmodeEnum.GenericBus,
> ```

Not needed for this test... You can do e.g. this:



```
import {
  vehicleSubmodeOnInfrastructureLink,
} from '@hsl/jore4-test-db-manager';

...

const vehicleSubmodesOnInfrastructureLink = [
  vehicleSubmodeOnInfrastructureLink[0],
];

...

const dbResources = {
  infraLinks,
  vehicleSubmodeOnInfrastructureLink: vehicleSubmodesOnInfrastructureLink,
  stops,
};

```

(also verified that this works on my machine. )



_Code quote:_
```XML
const vehicleSubmodeOnInfrastructureLink: VehicleSubmodeOnInfraLinkInsertInput[] =
  [
    {
      infrastructure_link_id: infraLinks[0].infrastructure_link_id,
      vehicle_submode: ReusableComponentsVehicleSubmodeEnum.GenericBus,
    },
  ];
```
___
*[`cypress/e2e/editStop.cy.ts` line 37 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFOulqUDXvvPxc7heup:-NFOulqUDXvvPxc7heuq:b-rbi008) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/366b0fcfc301da70bdb6a4dfec88384d66626983/cypress/e2e/editStop.cy.ts#L37)):*
> ```XML
>     scheduled_stop_point_id: '0f6254d9-dc60-4626-a777-ce4d4381d38a',
>     measured_location: {
>       type: 'Point',
> ```

Two problems here:
- this id was resuded from another test suite, please don't do that, it makes impossible to run tests in parallel
- coordinates are copypasted from test coordinates

Generated new id here, so here's full snippet:

```
const stops: StopInsertInput[] = [
  {
    ...buildStop({
      label: 'Move stop test stop',
      located_on_infrastructure_link_id: infraLinks[0].infrastructure_link_id,
    }),
    scheduled_stop_point_id: '68684b40-c4db-4c72-b3b8-c3307dde7a72',
    measured_location: {
      type: 'Point',
      coordinates: testCoordinates,
    },
  },
];
```



_Code quote:_
```XML
    scheduled_stop_point_id: '0f6254d9-dc60-4626-a777-ce4d4381d38a',
    measured_location: {
      type: 'Point',
      coordinates: [24.925251259734353, 60.16287920585574, 0],
    },
```
___
*[`test-db-manager/src/datasets/infrastructureLinks.ts` line 54 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFOrQDGDWeqyIrV4SYF:-NFOrQDHEj4lCKIKLlCy:b-9im2hu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/366b0fcfc301da70bdb6a4dfec88384d66626983/test-db-manager/src/datasets/infrastructureLinks.ts#L54)):*
> ```XML
>       external_link_id: '3',
>     },
>     {
> ```

Please remove this. Commented in the test file alternative approach to do this.



_Code quote:_
```XML
    {
      infrastructure_link_id: '3986bcc4-f3d7-44b8-b46a-0ade9d014af6',
      direction: InfrastructureNetworkDirectionEnum.Bidirectional,
      shape: {
        type: 'LineString',
        coordinates: [
          [24.925251259734353, 60.16287920585574, 15],
          [24.92832655782573, 60.16391811339392, 15],
        ],
      },
      estimated_length_in_metres: 10,
      external_link_source: InfrastructureNetworkExternalSourceEnum.DigiroadR,
      external_link_id: '1',
    },
```


<!-- Sent from Reviewable.io -->

2022-10-28 10:43 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/375)* status: 4 of 10 files reviewed, 9 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`cypress/e2e/editStop.cy.ts` line 19 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD0pTF2ZutJSrmPssI:-NFTApvXDmSPkfzmN3_3:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Is it relevant for the test to define all these fields?
If not, look `cypress/e2e/routeStops.cy.ts` for reference and do something like this:

```
import {
  InfraLinkInsertInput,
  infrastructureLinks,
} from '@hsl/jore4-test-db-manager';

const infraLinks: InfraLinkInsertInput[] = [
  {
    ...(infrastructureLinks[0] as InfraLinkInsertInput),
      infrastructure_link_id: '3986bcc4-f3d7-44b8-b46a-0ade9d014af6',
      shape: {
        type: 'LineString',
        coordinates: [
          [24.925251259734353, 60.16287920585574, 15],
          [24.92832655782573, 60.16391811339392, 15],
        ],
      },
  },
];
```

Please avoid defining non-relevant fields in test files as possible, those just clutter up test files and make it more difficult to see what things really matter from the test's perspective.
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFD2MZJCdw0za_lRJOi:-NFTAzB3803xxBdkuNr_:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/6ae47622d0edf66c52e03686547cae6499766f1b/cypress/e2e/editStop.cy.ts#L56)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This is not relevant for this test. Import `vehicleSubmodeOnInfrastructureLink` from `test-db-manager` and insert `[vehicleSubmodeOnInfrastructureLink[0]]` to db. Then you have to have infra link with corresponding ID in the db, so either do not override id definition of infra link here, or then use spread operator to override it here:
```
{ 
   ...vehicleSubmodeOnInfrastructureLink[0],
    infrastructure_link_id: infrastructureLinks[0].infrastructure_link_id,
}
```
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 18 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFOsepX3WuiQxsFWT9T:-NFTAr_7CXVckwNclGJk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/366b0fcfc301da70bdb6a4dfec88384d66626983/cypress/e2e/editStop.cy.ts#L18)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Let's refactor this to this:

```
const testCoordinates = [24.925251259734353, 60.16287920585574, 0];

const infraLinks: InfraLinkInsertInput[] = [
  {
    ...(infrastructureLinks[0] as InfraLinkInsertInput),
    shape: {
      type: 'LineString',
      coordinates: [testCoordinates, testCoordinates],
    },
  },
];
```
Then it is clear that it is important to have exactly this infra link inserted into db for this test, and it is relevant that infra link is located exactly at test coordinates. 

(I also verified that this works at least on my machine.)
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 25 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFOu-pQ6_f9psB6Jmnn:-NFTAu4e4uZL4iMhgFYR:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/366b0fcfc301da70bdb6a4dfec88384d66626983/cypress/e2e/editStop.cy.ts#L25)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not needed for this test... You can do e.g. this:



```
import {
  vehicleSubmodeOnInfrastructureLink,
} from '@hsl/jore4-test-db-manager';

...

const vehicleSubmodesOnInfrastructureLink = [
  vehicleSubmodeOnInfrastructureLink[0],
];

...

const dbResources = {
  infraLinks,
  vehicleSubmodeOnInfrastructureLink: vehicleSubmodesOnInfrastructureLink,
  stops,
};

```

(also verified that this works on my machine. )
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 37 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFOulqUDXvvPxc7heup:-NFTB-SHCoaDUEmKVVRh:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/366b0fcfc301da70bdb6a4dfec88384d66626983/cypress/e2e/editStop.cy.ts#L37)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Two problems here:
- this id was resuded from another test suite, please don't do that, it makes impossible to run tests in parallel
- coordinates are copypasted from test coordinates

Generated new id here, so here's full snippet:

```
const stops: StopInsertInput[] = [
  {
    ...buildStop({
      label: 'Move stop test stop',
      located_on_infrastructure_link_id: infraLinks[0].infrastructure_link_id,
    }),
    scheduled_stop_point_id: '68684b40-c4db-4c72-b3b8-c3307dde7a72',
    measured_location: {
      type: 'Point',
      coordinates: testCoordinates,
    },
  },
];
```
</blockquote></details>

Done.
___
*[`test-db-manager/src/datasets/infrastructureLinks.ts` line 54 at r2](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFOrQDGDWeqyIrV4SYF:-NFTB1A-29piSLSnOla8:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/366b0fcfc301da70bdb6a4dfec88384d66626983/test-db-manager/src/datasets/infrastructureLinks.ts#L54)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please remove this. Commented in the test file alternative approach to do this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-31 12:54 UTC, tk-vincit approved these changes
Requested changes done, lgtm. I'd still check if we have logical error here (do we actually verify that stop is moved?), but test can be improved also in future PR. Even now this tests most of the stop moving flow.

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-:-NFi5_jn2OeONHx84qaR:b-u37cjy)* status: 4 of 10 files reviewed, 7 unresolved discussions (waiting on @eleksi and @sr-vala)

___
*[`cypress/e2e/editStop.cy.ts` line 104 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFi5A640yQtR7KzPIkc:-NFi5A640yQtR7KzPIkd:b-ecqd93) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ea151a70345fd89991a839fc90f733afb6542e22/cypress/e2e/editStop.cy.ts#L104)):*
> ```XML
> 
>       stopForm.getLatitudeInput().should('have.value', testCoordinates[1]);
>       stopForm.getLongitudeInput().should('have.value', testCoordinates[0]);
> ```

Aren't these actually the original coordinates of the stop? So is the stop actually moved at all in this test? :thinking: 



_Code quote:_
```XML
      stopForm.getLatitudeInput().should('have.value', testCoordinates[1]);
      stopForm.getLongitudeInput().should('have.value', testCoordinates[0]);
```


<!-- Sent from Reviewable.io -->

2022-11-07 08:16 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/375)* status: 4 of 11 files reviewed, 11 unresolved discussions (waiting on @eleksi and @sr-vala)

___
*[`cypress/e2e/editStop.cy.ts` line 19 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NGG1cVS0dPftEGop0_L:-NGG1cVS0dPftEGop0_M:b9maa4f) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3f98804e80b58c32f04234430aa07ede1931a52a/cypress/e2e/editStop.cy.ts#L19)):*
> ```XML
> import { insertToDbHelper, removeFromDbHelper } from '../utils';
> 
> const test1StartCoordinates = [24.925251259734353, 60.16287920585574, 0];
> ```

There are few problems with this kind of naming:
- There is no such thing as "test 1" or "test 2" in this file. Yes, we happen to have two test cases right now, but what if someone adds new test case to the beginning of suite or to the middle of suite?
- This seems to be actually used in both test cases, not only in first of those

If this would be related only to first test case, I would define this in test case itself.
But as this is shared, please call this e.g. `initialCoordinates` or`startCoordinates`.
___
*[`cypress/e2e/editStop.cy.ts` line 21 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NGG2rQSBoQuDFQnRxF_:-NGG2rQTAMqBV7xjGkR1:b-kiekyr) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3f98804e80b58c32f04234430aa07ede1931a52a/cypress/e2e/editStop.cy.ts#L21)):*
> ```XML
> const test1StartCoordinates = [24.925251259734353, 60.16287920585574, 0];
> const test1EndCoordinates = [24.924435868192024, 60.162622981678744];
> const test2MoveCoordinates = [60.166533287996124, 24.935753563211073];
> ```

These end coordinates are test-specific, so they could be defined in test suites itself.
___
*[`cypress/e2e/editStop.cy.ts` line 116 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NGG8upa0X68r0_uC1ql:-NGG8upa0X68r0_uC1qm:b-g9bjgz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3f98804e80b58c32f04234430aa07ede1931a52a/cypress/e2e/editStop.cy.ts#L116)):*
> ```XML
>       // TODO: This can be refactored if a better solution is found.
>       // eslint-disable-next-line cypress/no-unnecessary-waiting
>       cy.wait(100);
> ```

As discussed in slack, this it not optimal, but as we don't have really good solutions ant this is explained in comment this is OK for now. Anyway, let's monitor this and if this starts to make tests flaky then we can get back to this.
___
*[`cypress/e2e/editStop.cy.ts` line 132 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NGG83cy-LoZxvZnJhmI:-NGG83cy-LoZxvZnJhmJ:b-45fp5) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3f98804e80b58c32f04234430aa07ede1931a52a/cypress/e2e/editStop.cy.ts#L132)):*
> ```XML
>     { scrollBehavior: 'bottom', defaultCommandTimeout: 10000 },
>     () => {
>       const updatedStopInfo = {
> ```

This should be typed:

```
import {
  StopFormInfo,
} from '../pageObjects';
```
Then this won't blow up if someone modifies stop form page object.
___
*[`cypress/e2e/editStop.cy.ts` line 159 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NGG357w7T9CQl_w2pzH:-NGG357w7T9CQl_w2pzI:bx9c60g) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3f98804e80b58c32f04234430aa07ede1931a52a/cypress/e2e/editStop.cy.ts#L159)):*
> ```XML
>       map.stopPopUp.getEditButton().click();
> 
>       stopForm.getLatitudeInput().should('have.value', test2MoveCoordinates[0]);
> ```

This would be easier to read if asserted like this:
`stopForm.getLatitudeInput().should('have.value', updatedStopInfo.latitude);`

Same for longitude assertion on next row.


<!-- Sent from Reviewable.io -->

2022-11-08 06:33 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/375)* status: 4 of 11 files reviewed, 11 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`cypress/e2e/editStop.cy.ts` line 104 at r3](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NFi5A640yQtR7KzPIkc:-NGKwN158-8qbt2hYYIB:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/ea151a70345fd89991a839fc90f733afb6542e22/cypress/e2e/editStop.cy.ts#L104)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Aren't these actually the original coordinates of the stop? So is the stop actually moved at all in this test? :thinking: 
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 19 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NGG1cVS0dPftEGop0_L:-NGKlhI5EXROeO7dlCMs:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3f98804e80b58c32f04234430aa07ede1931a52a/cypress/e2e/editStop.cy.ts#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

There are few problems with this kind of naming:
- There is no such thing as "test 1" or "test 2" in this file. Yes, we happen to have two test cases right now, but what if someone adds new test case to the beginning of suite or to the middle of suite?
- This seems to be actually used in both test cases, not only in first of those

If this would be related only to first test case, I would define this in test case itself.
But as this is shared, please call this e.g. `initialCoordinates` or`startCoordinates`.

</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 21 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NGG2rQSBoQuDFQnRxF_:-NGKljGiAKjUne6r-xp1:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3f98804e80b58c32f04234430aa07ede1931a52a/cypress/e2e/editStop.cy.ts#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

These end coordinates are test-specific, so they could be defined in test suites itself.
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 132 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NGG83cy-LoZxvZnJhmI:-NGKnMxRCslj2yIYNcTC:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3f98804e80b58c32f04234430aa07ede1931a52a/cypress/e2e/editStop.cy.ts#L132)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This should be typed:

```
import {
  StopFormInfo,
} from '../pageObjects';
```
Then this won't blow up if someone modifies stop form page object.
</blockquote></details>

Done.
___
*[`cypress/e2e/editStop.cy.ts` line 159 at r5](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NGG357w7T9CQl_w2pzH:-NGKuHNp-neWiPfqvxBk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/3f98804e80b58c32f04234430aa07ede1931a52a/cypress/e2e/editStop.cy.ts#L159)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

This would be easier to read if asserted like this:
`stopForm.getLatitudeInput().should('have.value', updatedStopInfo.latitude);`

Same for longitude assertion on next row.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-08 13:58 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/375)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @eleksi and @sr-vala)

___
*[`cypress/e2e/editStop.cy.ts` line 22 at r6](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-NGMWGpZ1XA8eQb2oAxG:-NGMWGpZ1XA8eQb2oAxH:bxecczn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/e6d113a5999a1b4944fde4541037b39b155d6df7/cypress/e2e/editStop.cy.ts#L22)):*
> ```XML
> const startCoordinates = [24.925251259734353, 60.16287920585574, 0];
> 
> const moveCoordinates = [60.166533287996124, 24.935753563211073];
> ```

These end coordinates are test-specific, so they could be defined in test suites itself.
Please also explain where do these come from.
If I have understood correctly, something like this would do:
```
      // NOTE: these coordinates are taken from cypress UI and might change
      // if map zoom level is changed (as we are clicking point relative to stop)
```


<!-- Sent from Reviewable.io -->

2022-11-09 12:17 UTC, tk-vincit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 4 of 6 files at r1, 3 of 6 files at r2, 1 of 2 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/375#-:-NGRJemBDIPxXC7Syw-o:bg7igkv)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @eleksi and @sr-vala)



<!-- Sent from Reviewable.io -->

2022-11-09 12:21 UTC, merged