Add test that changes a route's shape
HSLdevcom/jore4-ui pull request #431
Opened 2022-12-20 06:53 UTC by sr-vala

Resolves HSLdevcom/jore4#760

2022-12-21 06:50 UTC, HenrikHartiala requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/431)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 155 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk1rip2_WkrUGxVcOY:-NJk1rip2_WkrUGxVcOZ:bzbovs6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L155)):*
> ```XML
> const clearDatabase = () => {
>   removeFromDbHelper(dbResources);
>   deleteRoutesByLabel(Object.values(testRouteLabels));
> ```

Isn't this unnecessary since the route is in dbResources and removed there?
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 202 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk282m6mZfLIo0daeL:-NJk282m6mZfLIo0daeM:b-5w7wxc) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L202)):*
> ```XML
>       searchResultsPage.getShowRouteOnMapButton().click();
> 
>       map.waitForMapToLoad();
> ```

I think this could be changed to `map.getLoader().should('not.exist')` etc. The current `waitForMapToLoad` has a bit misleading name and also I was planning on removing it completely, since it's current implementation might not be needed.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 211 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk4huG8CgC3GLXUYfB:-NJk4huG8CgC3GLXUYfC:b-x2lnky) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L211)):*
> ```XML
>       routeEditor.checkRouteSubmitSuccessToast();
> 
>       routeStopsOverlay.routeShouldExist(routes[0].label);
> ```

This might not be in the scope of this PR, but Im a bit confused why `routeShouldExist` is part of `routeStopsOverlay`
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 212 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk3gnZ1AguoQ7LbZCX:-NJk3gnZ1AguoQ7LbZCY:b-2rthn3) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L212)):*
> ```XML
> 
>       routeStopsOverlay.routeShouldExist(routes[0].label);
>     },
> ```

Hmm, currently we just check that the edit GQL request was successful and the route is still existing, but we are not checking if anything actually changed.
My suggestion is that we edit the route so that the edited route goes via some new stop.
So let's say that the original route has two stops: A and C. Then we modify the route in this test to take one building block detour to include stop B as well, so the result route would go through on A, B and C.

What do you think?
___
*[`cypress/pageObjects/Map.ts` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk51770_C7pzabqjJu:-NJk51770_C7pzabqjJv:btk9emz) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/Map.ts#L52)):*
> ```XML
> 
>   clickNthSnappingPointHandle(nth: number) {
>     this.getNthSnappingPointHandle(nth).first().click({ force: true });
> ```

Also not necessarily part of this PR, but do you know if the `force: true` is needed here? If not then maybe we could remove it. But no actions required here.
___
*[`cypress/pageObjects/RouteEditor.ts` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk5cLyBANg75vLkVpU:-NJk5cLzBpkic6xbhJ_b:b-iiphyw) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L12)):*
> ```XML
>   mapFooter = new MapFooter();
> 
>   routeStopsOverlay = new RouteStopsOverlay();
> ```

I think this can be removed since it is not used.
___
*[`cypress/pageObjects/RouteEditor.ts` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk6KQL81N_wvBdEheg:-NJk6KQL81N_wvBdEheh:bgm8239) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L31)):*
> ```XML
>   }
> 
>   // Locator matches multiple elements, but we need only one of them to be able to click the route.
> ```

I would rather have this comment right above the `return cy.get(...)` line since it is related more to that line than the description of this function.
___
*[`cypress/pageObjects/RouteEditor.ts` line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnRQuF9-gmoByXI6-g:-NJnRQuF9-gmoByXI6-h:bqt207e) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L36)):*
> ```XML
>   }
> 
>   moveRouteEditHandle(handleNumber: number, xPixels: number, yPixels: number) {
> ```

Same comment to this as for `editOneRoutePoint()`
___
*[`cypress/pageObjects/RouteEditor.ts` line 39 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk5sCvEOijxApIxFQ0:-NJk5sCvEOijxApIxFQ1:b-30efvq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L39)):*
> ```XML
>     this.map
>       .getNthSnappingPointHandle(handleNumber)
>       .move({ deltaX: xPixels, deltaY: yPixels, force: true });
> ```

is this `force: true` needed?
___
*[`cypress/pageObjects/RouteEditor.ts` line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnOOaT4_uDoxSAqR5k:-NJnOOaT4_uDoxSAqR5l:b-2czl36) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L42)):*
> ```XML
>   }
> 
>   editOneRoutePoint(handleNumber: number, xPixels: number, yPixels: number) {
> ```

I would give the parameters for this as an object, so that it is more readable when calling this function.
Because now this is called like `editRoutePoint(2, 100, 100)` and there is no way of knowing what these means.
Also maybe more clear to use the same parameter names as the move uses, so `deltaX` and `deltaY`.
And thirdly, this function could benefit from JSDoc comment with a little description.


<!-- Sent from Reviewable.io -->

2022-12-21 09:40 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/431)* status: 0 of 7 files reviewed, 18 unresolved discussions (waiting on @HenrikHartiala and @sr-vala)

___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnxUBi8hLWRHyZyR7l:-NJnxUBi8hLWRHyZyR7m:bykmlqb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L30)):*
> ```XML
> };
> 
> // These infralink IDs exist in the 'testInfraLinks.sql' test data file.
> ```

We don't have file called `testInfraLinks.sql`. Did you mean `cypress/fixtures/infraLinks/infraLinks.sql`?
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnzDQDC169JlHA4cRC:-NJnzDQDC169JlHA4cRD:bzdj8y1) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L31)):*
> ```XML
> 
> // These infralink IDs exist in the 'testInfraLinks.sql' test data file.
> // These form a straight line on Eerikinkatu in Helsinki.
> ```

Great explanation, thanks! :+1: 
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnzda29Ng9IVhH7yL8:-NJnzda29Ng9IVhH7yL9:b-raw7s6) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L32)):*
> ```XML
> // These infralink IDs exist in the 'testInfraLinks.sql' test data file.
> // These form a straight line on Eerikinkatu in Helsinki.
> // Coordinates are partial since they are needed only for the stop creation.
> ```

Seems like these coordinatees are used for nothing, so please remove this comment.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnyHU986GSRJpSlicq:-NJnyHU986GSRJpSlicr:b-q8qf8b) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L35)):*
> ```XML
> 
> const testInfraLinks = {
>   1: {
> ```

Why is this object with numbers as keys? Seems like this should actually be an array:
```
const testInfraLinks = [
  { id: '73bc2df9-f5af-4c38-a1dd-5ed1f71c90a8' },
  { id: 'ea69415a-9c54-4327-8836-f38b36d8fa99' },
  { id: '13de61c2-3fc9-4255-955f-0a2350c389e1' },
];
```
(please note that you have then fix index-based references to this array to start from 0, now they start from 1)

Also it seems like the coordinates are used for nothing, so we should just remove those.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJntCZr55mLLSIN7pO4:-NJntCZr55mLLSIN7pO5:btdjppu) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L52)):*
> ```XML
>   {
>     ...buildLine({ label: 'Test line' }),
>     line_id: '5dfa82f1-b3f7-4e26-b31d-0d7bd78da0bf',
> ```

Please use unique ids, otherwise we can't run tests in parallel in same db container
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJo-eBaDeGHzfTo4khn:-NJo-eBaDeGHzfTo4kho:b-rx5whq) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L56)):*
> ```XML
> ];
> 
> const stops: StopInsertInput[] = [
> ```

You could give ids as parameters to buildStop, and thus get rid of object spreading and make this prettier:

```
const stops: StopInsertInput[] = [
  buildStop({
    label: 'E2E001',
    located_on_infrastructure_link_id: testInfraLinks[1].id,
    scheduled_stop_point_id: '019ce3bf-cdcd-42ff-9a1d-363108d4c640',
  }),
  buildStop({
    label: 'E2E002',
    located_on_infrastructure_link_id: testInfraLinks[2].id,
    scheduled_stop_point_id: 'b59285c8-a2ee-49dc-ad36-313232947d8a',
  }),
  buildStop({
    label: 'E2E003',
    located_on_infrastructure_link_id: testInfraLinks[3].id,
    scheduled_stop_point_id: 'f2299595-7f95-4b1e-b7aa-4f6f26fc4bc5',
  }),
];
```
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 80 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJo0FmwE28WEftmguvj:-NJo0FmwE28WEftmguvk:b-elpe5d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L80)):*
> ```XML
> ];
> 
> const routes: RouteInsertInput[] = [
> ```

Also this can be simplified:
```
const routes: RouteInsertInput[] = [
  buildRoute({
    label: testRouteLabels.label1,
    route_id: 'c42ad186-b35a-4345-b2c5-31f6b21a9f1e',
    on_line_id: lines[0].line_id,
    validity_start: DateTime.fromISO('2022-08-11T13:08:43.315+03:00'),
    validity_end: DateTime.fromISO('2032-08-11T13:08:43.315+03:00'),
  }),
];

```

Please also use unique id's. (Generated one for the example above)
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 92 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJo0vjx4KuY_O3T7--b:-NJo0vjx4KuY_O3T7--c:bnbir9w) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L92)):*
> ```XML
> const infraLinksAlongRoute: InfraLinkAlongRouteInsertInput[] = [
>   {
>     ...infrastructureLinkAlongRoute[0],
> ```

Seems like you are overwriting _all_ fields from `infrastructureLinkAlongRoute[0]`, so no need to take it as a base here.

So this can too simplified a bit:
```
const infraLinksAlongRoute: InfraLinkAlongRouteInsertInput[] = [
  {
    route_id: routes[0].route_id,
    infrastructure_link_id: testInfraLinks[1].id,
    infrastructure_link_sequence: 0,
    is_traversal_forwards: true,
  },
  {

    route_id: routes[0].route_id,
    infrastructure_link_id: testInfraLinks[2].id,
    infrastructure_link_sequence: 1,
    is_traversal_forwards: true,
  },
  {
    route_id: routes[0].route_id,
    infrastructure_link_id: testInfraLinks[3].id,
    infrastructure_link_sequence: 2,
    is_traversal_forwards: true,
  },
];
```

Or then like this:
```
const infraLinksAlongRoute: InfraLinkAlongRouteInsertInput[] = [
  {
    ...infrastructureLinkAlongRoute[0],
    is_traversal_forwards: true,
  },
  {
    ...infrastructureLinkAlongRoute[1],
    is_traversal_forwards: true,
  },
  {
    ...infrastructureLinkAlongRoute[2],
    is_traversal_forwards: true,
  },
];
```

(The first one might be "safer" in the long run as the second expects that there are certain routes & infra links in the db already, but it is also more verbose.)
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 138 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJo2-uC7-Msh-FRxWc_:-NJo2-uC7-Msh-FRxWca:b-2tcwov) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L138)):*
> ```XML
> 
> const stopsInJourneyPattern = buildStopsInJourneyPattern(
>   [stops[0].label, stops[1].label, stops[2].label],
> ```

Optional protip, this might be better solution especially if we add more stops in the future: 
```
stops.map(item => item.label),
```
___
*[`cypress/pageObjects/Map.ts` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnvhzy7MBGviF58NER:-NJnvhzy7MBGviF58NES:bh3rvic) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/Map.ts#L52)):*
> ```XML
> 
>   clickNthSnappingPointHandle(nth: number) {
>     this.getNthSnappingPointHandle(nth).first().click({ force: true });
> ```

`first()` is already called in `getNthSnappingPointHandle`, so is is needed here?


<!-- Sent from Reviewable.io -->

2022-12-21 09:43 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/431)* status: 0 of 7 files reviewed, 18 unresolved discussions (waiting on @HenrikHartiala and @sr-vala)

___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnyHU986GSRJpSlicq:-NJo361L2KdzDkYo4hNo:b-5qju76) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L35)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why is this object with numbers as keys? Seems like this should actually be an array:
```
const testInfraLinks = [
  { id: '73bc2df9-f5af-4c38-a1dd-5ed1f71c90a8' },
  { id: 'ea69415a-9c54-4327-8836-f38b36d8fa99' },
  { id: '13de61c2-3fc9-4255-955f-0a2350c389e1' },
];
```
(please note that you have then fix index-based references to this array to start from 0, now they start from 1)

Also it seems like the coordinates are used for nothing, so we should just remove those.
</blockquote></details>

(And this could also be array of UUID's removing need for defining objects altogether, so `const testInfraLinkUuids = [uuid1, uuid2, uuid3]`, but both are fine for me)


<!-- Sent from Reviewable.io -->

2022-12-21 12:34 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/431)* status: 0 of 7 files reviewed, 18 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`cypress/pageObjects/Map.ts` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk51770_C7pzabqjJu:-NJnjUxf0LVcZAls2CZ_:bsav991) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/Map.ts#L52)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Also not necessarily part of this PR, but do you know if the `force: true` is needed here? If not then maybe we could remove it. But no actions required here.
</blockquote></details>

Seems to work without it.
___
*[`cypress/pageObjects/Map.ts` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnvhzy7MBGviF58NER:-NJoVlhiDNvY-RPyL9XB:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/Map.ts#L52)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

`first()` is already called in `getNthSnappingPointHandle`, so is is needed here?
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RouteEditor.ts` line 12 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk5cLyBANg75vLkVpU:-NJoWLFAAxzXODEYC2Hk:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L12)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think this can be removed since it is not used.
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RouteEditor.ts` line 31 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk6KQL81N_wvBdEheg:-NJoWMtE4QHPkMiwIYP8:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L31)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I would rather have this comment right above the `return cy.get(...)` line since it is related more to that line than the description of this function.
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RouteEditor.ts` line 36 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnRQuF9-gmoByXI6-g:-NJoZTM2CFmBQe2TaMVS:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L36)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Same comment to this as for `editOneRoutePoint()`
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RouteEditor.ts` line 39 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk5sCvEOijxApIxFQ0:-NJoZTqs772UGroqApWh:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L39)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

is this `force: true` needed?
</blockquote></details>

Done.
___
*[`cypress/pageObjects/RouteEditor.ts` line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnOOaT4_uDoxSAqR5k:-NJoZUo4-qVB8XDqveuN:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L42)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I would give the parameters for this as an object, so that it is more readable when calling this function.
Because now this is called like `editRoutePoint(2, 100, 100)` and there is no way of knowing what these means.
Also maybe more clear to use the same parameter names as the move uses, so `deltaX` and `deltaY`.
And thirdly, this function could benefit from JSDoc comment with a little description.
</blockquote></details>

Done.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 30 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnxUBi8hLWRHyZyR7l:-NJoTfIpEbk1MhMMp2n6:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L30)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

We don't have file called `testInfraLinks.sql`. Did you mean `cypress/fixtures/infraLinks/infraLinks.sql`?
</blockquote></details>

Done.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnzda29Ng9IVhH7yL8:-NJoThyo5ncc6kT10g-m:b-a9b0ba) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L32)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Seems like these coordinatees are used for nothing, so please remove this comment.
</blockquote></details>

The stop creation was actually broken without the coordinates in the stops' measured locations.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnyHU986GSRJpSlicq:-NJoTv6c0jTdJIdzEAnz:b-fuf8kb) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L35)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

(And this could also be array of UUID's removing need for defining objects altogether, so `const testInfraLinkUuids = [uuid1, uuid2, uuid3]`, but both are fine for me)
</blockquote></details>

Coordinates are used now.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJntCZr55mLLSIN7pO4:-NJoU2ho8zURnMSTn29G:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L52)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please use unique ids, otherwise we can't run tests in parallel in same db container
</blockquote></details>

Done.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJo-eBaDeGHzfTo4khn:-NJoUrdDAA8KA7sS098Z:b-dblt4n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L56)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

You could give ids as parameters to buildStop, and thus get rid of object spreading and make this prettier:

```
const stops: StopInsertInput[] = [
  buildStop({
    label: 'E2E001',
    located_on_infrastructure_link_id: testInfraLinks[1].id,
    scheduled_stop_point_id: '019ce3bf-cdcd-42ff-9a1d-363108d4c640',
  }),
  buildStop({
    label: 'E2E002',
    located_on_infrastructure_link_id: testInfraLinks[2].id,
    scheduled_stop_point_id: 'b59285c8-a2ee-49dc-ad36-313232947d8a',
  }),
  buildStop({
    label: 'E2E003',
    located_on_infrastructure_link_id: testInfraLinks[3].id,
    scheduled_stop_point_id: 'f2299595-7f95-4b1e-b7aa-4f6f26fc4bc5',
  }),
];
```
</blockquote></details>

This does not pass ts:check.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 80 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJo0FmwE28WEftmguvj:-NJoSRuWED5ce-kUNPW0:b-dblt4n) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L80)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Also this can be simplified:
```
const routes: RouteInsertInput[] = [
  buildRoute({
    label: testRouteLabels.label1,
    route_id: 'c42ad186-b35a-4345-b2c5-31f6b21a9f1e',
    on_line_id: lines[0].line_id,
    validity_start: DateTime.fromISO('2022-08-11T13:08:43.315+03:00'),
    validity_end: DateTime.fromISO('2032-08-11T13:08:43.315+03:00'),
  }),
];

```

Pl [...]

2022-12-22 10:28 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/431)* status: 0 of 7 files reviewed, 12 unresolved discussions (waiting on @HenrikHartiala and @sr-vala)

___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnyHU986GSRJpSlicq:-NJtHwfx87T0h3Y8U0kN:belfw8r) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L35)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Coordinates are used now.
</blockquote></details>

OK. This data structure should still be an array, or do we have any good reasons NOT to use array?
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJo-eBaDeGHzfTo4khn:-NJtJ8zR1iqOKClQaaaI:bx8g1yp) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L56)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

This does not pass ts:check.
</blockquote></details>

Oh, tried this yesterday locally with no errors, but I guess my TS server was then not working correctly... We really should update to TS 4.9 as `satisfies` operator would most likely save the day here: https://dev.to/ayc0/typescript-49-satisfies-operator-1e4i

But OK, as it seems to require bit of TS magic to update builder functions to work with this pattern, let's decide this is good enough for now. 
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 80 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJo0FmwE28WEftmguvj:-NJtHoIsDy1Sb7DPy5EQ:bboimrn) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L80)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

This does not pass ts:check.
</blockquote></details>

Please still use unique ids.


<!-- Sent from Reviewable.io -->

2022-12-22 12:01 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/431)* status: 0 of 7 files reviewed, 12 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 35 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnyHU986GSRJpSlicq:-NJtealOENHQ_K-46wvJ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L35)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

OK. This data structure should still be an array, or do we have any good reasons NOT to use array?
</blockquote></details>

Done.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 56 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJo-eBaDeGHzfTo4khn:-NJtefAM-gH5on1QFkID:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L56)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Oh, tried this yesterday locally with no errors, but I guess my TS server was then not working correctly... We really should update to TS 4.9 as `satisfies` operator would most likely save the day here: https://dev.to/ayc0/typescript-49-satisfies-operator-1e4i

But OK, as it seems to require bit of TS magic to update builder functions to work with this pattern, let's decide this is good enough for now. 
</blockquote></details>

Done.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 80 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJo0FmwE28WEftmguvj:-NJtexdZ8uWPFnX3FM0m:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L80)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please still use unique ids.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-28 08:35 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/431)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`cypress/pageObjects/Map.ts` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk51770_C7pzabqjJu:-NKMc0oz-vI4HinWCyCD:bl1tyga) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/Map.ts#L52)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

It is better to use it without it. Because if I've understood & remember correctly the usage of it, it is will force the click, even though it would not be visible to user. And that might be something we do not want to do. I think we should maybe check the other forced clicks as well and rethink if we want to use it anywhere.

Anyways, this is good thanks!
</blockquote></details>

Yes, I would like to avoid force as well as it can do things that a user cannot. This was left here after my several experiments with drag and drop without an external library, which I could not get working in the end.
___
*[`cypress/pageObjects/RouteEditor.ts` line 42 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJnOOaT4_uDoxSAqR5k:-NKMrrqs12CYAUFLikkE:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/RouteEditor.ts#L42)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Very nice explanation :+1: Thanks!
</blockquote></details>

Done.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 211 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk4huG8CgC3GLXUYfB:-NKMrdNo6Sa7rCZAhXGG:b-f8r80d) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L211)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yes, but to me it is odd that we are asserting that a _route_ is existing through _routeStopsOverlay_.
</blockquote></details>

I renamed this to routeShouldBeSelected now. Let me know if you have better ideas.
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 212 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk3gnZ1AguoQ7LbZCX:-NKMrpXECQ5jVVMkdbNX:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L212)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

It's better now thanks! But I think we should also do a check in the start that all the three stops are in place? Because even though we currently know that the input will be correct, but if they are modified somehow, we currently only check that the middle stop _is not there anymore_. But nothing checks that has it ever even been there.

1. Check that the route has 3 stops included in route
2. Do magic <This is already done>
3. Check the middle stop is not included anymore. <This is already done>


</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-09 13:03 UTC, HenrikHartiala approved these changes
> Reviewed 4 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-ui/431)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @tk-vincit)

___
*[`cypress/pageObjects/Map.ts` line 52 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk51770_C7pzabqjJu:-NLLc37f6MGFQOW0Qyee:b-w1pi47) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/pageObjects/Map.ts#L52)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Yes, I would like to avoid force as well as it can do things that a user cannot. This was left here after my several experiments with drag and drop without an external library, which I could not get working in the end.
</blockquote></details>

check :+1: 
___
*[`cypress/e2e/editRouteOnMap.cy.ts` line 211 at r1](https://reviewable.io/reviews/hsldevcom/jore4-ui/431#-NJk4huG8CgC3GLXUYfB:-NLLaftm6nemaMzA9woP:b-twig35) ([raw file](https://github.com/hsldevcom/jore4-ui/blob/caecb4566725da47525bf60f9a9b6f00ceaca356/cypress/e2e/editRouteOnMap.cy.ts#L211)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I renamed this to routeShouldBeSelected now. Let me know if you have better ideas.
</blockquote></details>

I think thats is a lot better name for this :+1: Thanks


<!-- Sent from Reviewable.io -->

2023-01-10 04:34 UTC, merged