Import timetables with preview
HSLdevcom/jore4-ui pull request #492
Opened 2023-02-01 08:40 UTC by eleksi

Resolves https://github.com/HSLdevcom/jore4/issues/1087

Test data for imported timetables can be generated with branch `seed-staging-timetables` seed commands.

2023-02-01 14:12 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492)* status: 0 of 17 files reviewed, 23 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/common/Loader.tsx` line 5 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCcIb5MlB4bIkVYPR:-NNCCcIb5MlB4bIkVYPS:b-14ld46) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L5)):*
> ```XML
> import { LoadingOverlay } from '../../uiComponents';
> 
> export const Loader = () => {
> ```

Should be typed as JSX.Element
___
*[`ui/src/components/common/Loader.tsx` line 6 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCgp69oi7fQdd2rw3:-NNCCgp69oi7fQdd2rw4:by626y2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L6)):*
> ```XML
> 
> export const Loader = () => {
>   const testIds = {
> ```

Should be defined outside of the component. Now it is impossible to e.g. import these to test file if needed.

By the way, is this even used anywhere?
___
*[`ui/src/components/common/Loader.tsx` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCsyw4YuLMkCpW2gm:-NNCCsyw4YuLMkCpW2gn:b-s45c8y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L10)):*
> ```XML
>   };
>   const { isMapOpen } = useMapQueryParams();
>   const isLoading = useAppSelector(selectIsOperationLoading);
> ```

"operationLoading" sounds a bit vague :thinking: 
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 9 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCDib39NvoMIKl69-1:-NNCDib39NvoMIKl69-2:b-sz8k6e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L9)):*
> ```XML
> import { DirectionBadge } from '../../routes-and-lines/line-details/DirectionBadge';
> 
> interface Props {
> ```

Please define this right before the component that actually used this.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 15 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCDPV20gqfQntQoW9J:-NNCDPV20gqfQntQoW9K:bkdlrkh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L15)):*
> ```XML
> 
> const testIds = {
>   table: 'RouteVehicleJourneysTable::table',
> ```

BlockVehicleJourneysTable. Same for next row.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCD_tgEsSnj0Y4fmYX:-NNCD_tgEsSnj0Y4fmYY:b28bem6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L19)):*
> ```XML
> };
> 
> const Td: React.FC = ({ children }) => (
> ```

No need to define this as own component, just extract `tdClassName` to own variable.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 28 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCDtdB05rLR6cLRA6N:-NNCDtdB05rLR6cLRA6O:b-q8cll8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L28)):*
> ```XML
> }
> 
> const Th: React.FC<ThProps> = ({ children, colSpan = 1, className = '' }) => (
> ```

No need to define this as own component. Now this just adds layer of complexity to the code, without making it any clearer.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 34 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCE7mc14vxdpDsN0gU:-NNCE7mc14vxdpDsN0gV:b-14ld46) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L34)):*
> ```XML
> );
> 
> const VehicleJourneyRow = ({
> ```

Should be typed as JSX.Element
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 44 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCEAzzAsZpUJUykgIN:-NNCEAzzAsZpUJUykgIO:b-4ttulp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L44)):*
> ```XML
> 
>   if (!route) {
>     throw new Error('No route found for vehicle journey!');
> ```

Don't throw from UI component unless defining error boundary. I don't know how this situation should be handled from user's perspective, but crashing the UI is not the way to go.

Rather e.g.:
- log error to console / show error toast
- render error message?
- render empty component?
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 60 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCFBDDAmG8piUneXST:-NNCFBDDAmG8piUneXSU:b-qkgrb6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L60)):*
> ```XML
>       <Td>{vehicleJourney.block.vehicle_service.day_type.name_i18n.fi_FI}</Td>
>       <Td>{mapDurationToShortTime(vehicleJourney.start_time)}</Td>
>       <Td>{mapDurationToShortTime(vehicleJourney.end_time)}</Td>
> ```

Did you checked what happens if either one of these is undefined? Just wondering if these should have `|| ''`



_Code quote:_
```XML
      <Td>{mapDurationToShortTime(vehicleJourney.start_time)}</Td>
      <Td>{mapDurationToShortTime(vehicleJourney.end_time)}</Td>
```
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 69 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCFKD034M2gvR5lmzd:-NNCFKD16A61S6HMu6-v:bc95pyc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L69)):*
> ```XML
>   title,
> }: Props): JSX.Element => {
>   const [isOpen, setIsOpen] = useReducer((value) => !value, true);
> ```

We have useToggle component hook for this: `ui/src/hooks/useToggle.ts`
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 78 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCFVqrECdikZO3CRYN:-NNCFVqrECdikZO3CRYO:b-v2fzfq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L78)):*
> ```XML
>       <thead>
>         <tr>
>           <Th className="w-64 bg-brand py-2 px-6 text-left text-white">
> ```

Do we have to use explicit widht? This won't work well on small screens.
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 34 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCFm5q77FA8E52Wc7M:-NNCFm5q77FA8E52Wc7N:bvxgjzp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L34)):*
> ```XML
>     try {
>       await confirmTimetablesImport(
>         state.priority as unknown as TimetablePriority,
> ```

Not part of this pr so this is optional commment, but why do we need as unknown casting here? Could we fix typings in `state`?
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 23 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCHI7EBtGJwvXk3999:-NNCHI7EBtGJwvXk399A:bb76va3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L23)):*
> ```XML
> const schema = priorityFormSchema;
> 
> export type FormState = Pr [...]

2023-02-02 09:23 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492)* status: 0 of 22 files reviewed, 23 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/common/Loader.tsx` line 5 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCcIb5MlB4bIkVYPR:-NNGBlus6j5UzumJMR91:b7ie0vg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L5)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should be typed as JSX.Element
</blockquote></details>

This could be added to linter rules if we want to enforce it. I fixed this to another component as well.
___
*[`ui/src/components/common/Loader.tsx` line 6 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCgp69oi7fQdd2rw3:-NNGBtHrDeDQZx80jySx:b-bqy3ux) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L6)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should be defined outside of the component. Now it is impossible to e.g. import these to test file if needed.

By the way, is this even used anywhere?
</blockquote></details>

Done. It is used
___
*[`ui/src/components/common/Loader.tsx` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCsyw4YuLMkCpW2gm:-NNGC-GfCYnFpQjG1wYz:bco4zjy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"operationLoading" sounds a bit vague :thinking: 
</blockquote></details>

It is vague but I just cannot figure out what to name some operation that is happening outside map. We have `mapOperationLoading`, but do we want `notMapOperationLoading` :D, or do we want something like `listViewOperationLoading`...? I just cannot figure it out..
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 9 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCDib39NvoMIKl69-1:-NNGCuMw8Xniid9F7Bdi:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L9)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Please define this right before the component that actually used this.
</blockquote></details>

Done.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 15 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCDPV20gqfQntQoW9J:-NNGChuD3_SXR2iB0Exq:b-oq6h9b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

BlockVehicleJourneysTable. Same for next row.
</blockquote></details>

Good spot!
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCD_tgEsSnj0Y4fmYX:-NNGCwV37VzZItSs1rpz:b-8fbzkm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

No need to define this as own component, just extract `tdClassName` to own variable.
</blockquote></details>

I followed a pattern used earlier, but as discussed this will be fixed when new version of tailwindcss is available.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 28 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCDtdB05rLR6cLRA6N:-NNGD65A968B-ccLBUk7:b-kuzsez) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L28)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

No need to define this as own component. Now this just adds layer of complexity to the code, without making it any clearer.
</blockquote></details>

Same as above. Will be fixed when tailwindcss new version is available
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 34 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCE7mc14vxdpDsN0gU:-NNGDL_p4UZtMHrbqt0G:b-zddnt3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L34)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should be typed as JSX.Element
</blockquote></details>

Done. Can you make sure we get linter rule from this? There is probably a few more places in the code base where this is not followed.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 44 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCEAzzAsZpUJUykgIN:-NNGDW274y6JPl1o7-w-:bef7lwr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L44)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Don't throw from UI component unless defining error boundary. I don't know how this situation should be handled from user's perspective, but crashing the UI is not the way to go.

Rather e.g.:
- log error to console / show error toast
- render error message?
- render empty component?
</blockquote></details>

This should never happen if we don't have a bug in the code, it is pretty much just a guard for ts to know route is defined. Fixed it a little bit though.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 60 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCFBDDAmG8piUneXST:-NNGG-DdCi2Uq8ZueokM:b-jvn20g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L60)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Did you checked what happens if either one of these is undefined? Just wondering if these should have `|| ''`
</blockquote></details>

Good point. Added empty strings for safety.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 69 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCFKD034M2gvR5lmzd:-NNGG5JAExw-9qtaiKPv:bhsxype) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L69)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

We have useToggle component hook for this: `ui/src/hooks/useToggle.ts`
</blockquote></details>

Yes :) I can use it then, even though I think this one liner is not that bad either :)
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 78 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCFVqrECdikZO3CRYN:-NNGGhwfAr_-BJGTwy-m:b-twmye2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L78)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we have to use explicit widht? This won't work well on small screens.
</blockquote></details>

Changed it to relative width and it seems to work ok as well.
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 34 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCFm5q77FA8E52Wc7M:-NNGH4Oe2x88OhMpz0sz:b-61qjkt) ([raw file](https://github.com/HSLdevcom/jor [...]

2023-02-03 10:04 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492)* status: 0 of 22 files reviewed, 11 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/common/Loader.tsx` line 5 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCcIb5MlB4bIkVYPR:-NNLQHlH8-Ap-a4I__WH:bxxdu0p) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L5)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This could be added to linter rules if we want to enforce it. I fixed this to another component as well.
</blockquote></details>

That would indeed be useful, but haven't seen suitable eslint rule for that and didn't found one either when tried briefly to find rule for that.
___
*[`ui/src/components/common/Loader.tsx` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCsyw4YuLMkCpW2gm:-NNLcugg4hn4KTbku-Qa:bym1d16) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L10)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

It is vague but I just cannot figure out what to name some operation that is happening outside map. We have `mapOperationLoading`, but do we want `notMapOperationLoading` :D, or do we want something like `listViewOperationLoading`...? I just cannot figure it out..
</blockquote></details>

Umm... When I dug a bit deeper onto this, I don't see any real benefits of separating MapLoader and Loader components just now. I mean, their state in redux is stored in literally same slice, and the loader components are ~identical but one is shown when map is open and another when map is not open.

So OK, this name could be fine but then we probably don't need separate MapLoader concept. Or what do you think about this?
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCD_tgEsSnj0Y4fmYX:-NNLccMn9lnj6AEGb7Vs:by36q0b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L19)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I followed a pattern used earlier, but as discussed this will be fixed when new version of tailwindcss is available.
</blockquote></details>

I just approved PR for tailwindcss update, so I assume it is in main branch when you are reading this.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 69 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCFKD034M2gvR5lmzd:-NNLRw5g-pyEPWuGfqP5:b12njm1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L69)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Yes :) I can use it then, even though I think this one liner is not that bad either :)
</blockquote></details>

useToggle(true)
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 98 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLeKvAB11EXRlEpgLR:-NNLeKvAB11EXRlEpgLS:b302mpo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L98)):*
> ```XML
>           >
>             <Row className="flex-1 items-center justify-between font-normal">
>               <div>!Kalustotyyppi 3 - Normaalibussi</div>
> ```

Why div instead of p?
If font-normal style is not intented to be shared across multiple elements, it could be defined directly for this tag. It is easier to understand styles if they are defined directly to the component that they are supposed to affect to. 
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 30 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLgZoX3n0Mph4Zwz07:-NNLgZoX3n0Mph4Zwz08:b-fpwzvz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L30)):*
> ```XML
> 
>   const onSave = async (state: FormState) => {
>     setIsLoading(true);
> ```

Seems like this is intented for handling redux state during api call. Why this is not done in `confirmtTimetablesImport` hook?
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 36 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLfz5t2c2f0Q-oHiQr:-NNLfz5t2c2f0Q-oHiQs:b-h2nxzp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L36)):*
> ```XML
>         state.priority as unknown as TimetablePriority,
>       );
>       showSuccessToast(t('timetables.importSuccess'));
> ```

Should `confirmTimetablesImport` rather handle showing the success toast? If it is something that we always want to do after saving the changes, it would make more sense to define it there. Also it shouldn't be responsibility of UI component.
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 50 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLh97TEC8aowuCVAZ6:-NNLh97TEC8aowuCVAZ7:bv4a7ih) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L50)):*
> ```XML
>         state.priority as unknown as TimetablePriority,
>       );
>       showSuccessToast(t('timetables.importSuccess'));
> ```

Ok, this is second time UI component is handling this after calling `confirmTimetablesImport`, so this definitely belongs to the `confirmTimetablesImport` itself. It could most likely handle setting isLoading flag too.
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 78 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLhSYJ5mqRuXZ2RuHK:-NNLhSYJ5mqRuXZ2RuHL:b8r9v88) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L78)):*
> ```XML
>               className="font-bold"
>             >
>               {showStagingTimetables
> ```

Semantic tag for text content
___
*[`ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx` line 21 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCIRjF7XDgfFgXod6a:-NNLRilu65lHGUutcvpx:b-lrs5n2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx#L21)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now you also changed initial state from true tof alse. `useToggle(true)`
___
*[`ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx` line 43 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCJ6zm1_IL2jspQzsc:-NNLhd8j5tf119zHyE67:b9b2np3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx#L43)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

What would the component contain? I just want the icon to be 50px high, there is nothing else that is special with that component. I don't see why this should be only considered as one-off fix.
</blockquote></details>

Well, this sounds kind of bad for maintainability because one would assume that if font size in one of these is changed, the others should be changed too. But OK, this is fine for me.
___
*[`ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx` line 55 at r4](https://review [...]

2023-02-07 10:11 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492)* status: 0 of 22 files reviewed, 10 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/common/Loader.tsx` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCsyw4YuLMkCpW2gm:-NNf0rYP7gMspQHYo31e:b7u77tc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Umm... When I dug a bit deeper onto this, I don't see any real benefits of separating MapLoader and Loader components just now. I mean, their state in redux is stored in literally same slice, and the loader components are ~identical but one is shown when map is open and another when map is not open.

So OK, this name could be fine but then we probably don't need separate MapLoader concept. Or what do you think about this?
</blockquote></details>

When the loader was separated for map and other views, the assumption was made that these components would differ from each other even visually, probably different position or something. Now that I implemented the first loader for non-map-operation, I was lazy and just copy pasted this. I think this is something that should be checked with design and then act according to that.

If we realize they are the same, there probably is no reason to keep them separate. I'm just wondering if e.g. something done in map view could trigger loading event in underlying other view and then the loading spinner would be shown with no reason. E.g. if we change observation date in map, the query is changed, would e.g. list view start loading new routes also in the background showing the spinner with no reason over map view.

I don't know if that made any sense explained in textual format, I can elaborate in some other forum.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCD_tgEsSnj0Y4fmYX:-NNf8dcsCQO1mvXfw5dl:b-2s1tgq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L19)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I just approved PR for tailwindcss update, so I assume it is in main branch when you are reading this.
</blockquote></details>

Ahh it is so nice to get rid of these.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 69 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCFKD034M2gvR5lmzd:-NNf92V0EEiGaIijV3gT:b-48szhd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L69)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

useToggle(true)
</blockquote></details>

Now that I think about this, I'm not sure if we want to open these by default. There could be quite a lot of these when the view is opened, and a lot of scrolling would be needed. Maybe default value false is ok after all.
___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 98 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLeKvAB11EXRlEpgLR:-NNf9Q2q1kQ-GRJwS8gw:bikx91h) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L98)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Why div instead of p?
If font-normal style is not intented to be shared across multiple elements, it could be defined directly for this tag. It is easier to understand styles if they are defined directly to the component that they are supposed to affect to. 
</blockquote></details>

I think there could be more content added in here, e.g. day type.
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 30 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLgZoX3n0Mph4Zwz07:-NNfATbk39WTsgM1YH5n:b-dtufp7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L30)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Seems like this is intented for handling redux state during api call. Why this is not done in `confirmtTimetablesImport` hook?
</blockquote></details>

I kind of disagree. I don't think we want to mix UI state (showing loader) with the business logic that the hook is for. At least for now, loading state and success toasts are something that UI components are responsible for in all other places in our codebase, not the business logic hooks.
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 36 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLfz5t2c2f0Q-oHiQr:-NNfAkffBHjwTVVEw2wG:bsse9xe) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L36)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Should `confirmTimetablesImport` rather handle showing the success toast? If it is something that we always want to do after saving the changes, it would make more sense to define it there. Also it shouldn't be responsibility of UI component.
</blockquote></details>

I kind of disagree. I don't think we want to mix UI things with the business logic that the hook is for. At least for now, loading state and success toasts are something that UI components are responsible for in all other places in our codebase, not the business logic hooks.
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 50 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLh97TEC8aowuCVAZ6:-NNfAwWc2x-ge0dqMe3q:b-k7nfm1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L50)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Ok, this is second time UI component is handling this after calling `confirmTimetablesImport`, so this definitely belongs to the `confirmTimetablesImport` itself. It could most likely handle setting isLoading flag too.
</blockquote></details>

I kind of disagree. I don't think we want to mix UI things with the business logic that the hook is for. At least for now, loading state and success toasts are something that UI components are responsible for in all other places in our codebase, not the business logic hooks.

I agree that we do this similar thing multiple times and it seems a little stupid, but what if at some point `confirmTimetablesImport` is called in some other context where we don't want to show the loader or success toast?
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 78 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLhSYJ5mqRuXZ2RuHK:-NNfCd_Y6NESBPEqyjr9:b86ohs4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L78)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Semantic tag for text content
</blockquote></details>

But this is a button :thinking: , do we want to put `<p>` inside a button?
___
*[`ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx` line 21 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCIRjF7XDgfFgXod6a:-NNfD-0pBMLpmKihb2B3:b3zz7ua) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx#L21)): [...]

2023-02-08 11:11 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492)* status: 0 of 22 files reviewed, 6 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 42 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNkYTdO00M_NkQZo3tS:-NNkYTdO00M_NkQZo3tT:bvk8k4p) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f5b5f5abbd588e5627bba183977ac9645d2d110d/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L42)):*
> ```XML
>         </Row>
>       </td>
>       <td>{vehicleJourney.block.vehicle_service.day_type.name_i18n.fi_FI}</td>
> ```

See `ui/src/i18n/utils.ts` and use `parseI18nField` from it to show correct language version instead of hardcoding to fi_Fi.
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 30 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLgZoX3n0Mph4Zwz07:-NNkdFdMDkedOvdvhVRw:bnag14r) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L30)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I kind of disagree. I don't think we want to mix UI state (showing loader) with the business logic that the hook is for. At least for now, loading state and success toasts are something that UI components are responsible for in all other places in our codebase, not the business logic hooks.
</blockquote></details>

Replied to discussion below, but keeping this open until the discussion is finished as it concerns also this place
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 36 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLfz5t2c2f0Q-oHiQr:-NNkdM-LDuUK6AyhU717:bnag14r) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L36)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I kind of disagree. I don't think we want to mix UI things with the business logic that the hook is for. At least for now, loading state and success toasts are something that UI components are responsible for in all other places in our codebase, not the business logic hooks.
</blockquote></details>

Replied to discussion below, but keeping this open until the discussion is finished as it concerns also this place
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 50 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLh97TEC8aowuCVAZ6:-NNk_CQt9f42ncLBWzT2:bvz3v93) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L50)):*
>but what if at some point confirmTimetablesImport is called in some other context where we don't want to show the loader or success toast?

~Why we would want to be inconsistent with giving feedback to the user, especially when doing undoable operation like this?~

OK, so far we have kept all showSuccessToast calls as responsibility of UI components itself, so keeping it here is OK for consistency, but IMO it just doesn't make sense.

But regarding loading state, it makes even less sense. We are setting loading state to redux, instead of local state of this component, and we don't even utilize the loading state in this component, so why it should be done here? It just bloats this component up, an which is even worse, in this case this duplicates almost same logic in two different components.

If we want to separate this kind of stuff from the hook which makes the api call, then we could intorude yet another layer of hooks which would combine
- hook for doing api call
- hook for setting loading state
- hook for showing toast message 

That option would
- keep api hook "pure" from this kind of side effects so that it could still be used in the unlikely case were we don't want toast messages or spinners
- keep unrelated logics out of ui components
- improve maintanability by reducing code duplciation
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 78 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLhSYJ5mqRuXZ2RuHK:-NNk_YtEBRQXX7t2l9bS:b-3aqhqk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L78)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

But this is a button :thinking: , do we want to put `<p>` inside a button?
</blockquote></details>

Sorry, missed the button tag for some reason. Yeah, no other tags inside button.


<!-- Sent from Reviewable.io -->

2023-02-08 14:43 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492)* status: 0 of 24 files reviewed, 6 unresolved discussions (waiting on @tk-vincit)

___
*[`ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx` line 42 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNkYTdO00M_NkQZo3tS:-NNlNGtz8P42XHVIB8B6:b7zy2ce) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f5b5f5abbd588e5627bba183977ac9645d2d110d/ui/src/components/timetables/import/BlockVehicleJourneysTable.tsx#L42)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

See `ui/src/i18n/utils.ts` and use `parseI18nField` from it to show correct language version instead of hardcoding to fi_Fi.
</blockquote></details>

Thanks! Didn't really know of this.
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 30 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLgZoX3n0Mph4Zwz07:-NNlTOvt-sJR9520-w9s:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L30)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Replied to discussion below, but keeping this open until the discussion is finished as it concerns also this place
</blockquote></details>

Done.
___
*[`ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx` line 36 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLfz5t2c2f0Q-oHiQr:-NNlTPHq5ahVqJYYxD8A:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/ConfirmTimetablesImportModal.tsx#L36)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Replied to discussion below, but keeping this open until the discussion is finished as it concerns also this place
</blockquote></details>

Done.
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 50 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLh97TEC8aowuCVAZ6:-NNlTROB2BHo09wmNEEo:b-jligct) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L50)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

>but what if at some point confirmTimetablesImport is called in some other context where we don't want to show the loader or success toast?

~Why we would want to be inconsistent with giving feedback to the user, especially when doing undoable operation like this?~

OK, so far we have kept all showSuccessToast calls as responsibility of UI components itself, so keeping it here is OK for consistency, but IMO it just doesn't make sense.

But regarding loading state, it makes even less sense. We are setting loading state to redux, instead of local state of this component, and we don't even utilize the loading state in this component, so why it should be done here? It just bloats this component up, an which is even worse, in this case this duplicates almost same logic in two different components.

If we want to separate this kind of stuff from the hook which makes the api call, then we could intorude yet another layer of hooks which would combine
- hook for doing api call
- hook for setting loading state
- hook for showing toast message 

That option would
- keep api hook "pure" from this kind of side effects so that it could still be used in the unlikely case were we don't want toast messages or spinners
- keep unrelated logics out of ui components
- improve maintanability by reducing code duplciation
</blockquote></details>

I tried to do something for this. How does it look?


<!-- Sent from Reviewable.io -->

2023-02-09 06:53 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492)* status: 0 of 24 files reviewed, 4 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/common/Loader.tsx` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCsyw4YuLMkCpW2gm:-NNowFSl6STskIpx6m2_:b-f3gdw6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L10)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

When the loader was separated for map and other views, the assumption was made that these components would differ from each other even visually, probably different position or something. Now that I implemented the first loader for non-map-operation, I was lazy and just copy pasted this. I think this is something that should be checked with design and then act according to that.

If we realize they are the same, there probably is no reason to keep them separate. I'm just wondering if e.g. something done in map view could trigger loading event in underlying other view and then the loading spinner would be shown with no reason. E.g. if we change observation date in map, the query is changed, would e.g. list view start loading new routes also in the background showing the spinner with no reason over map view.

I don't know if that made any sense explained in textual format, I can elaborate in some other forum.
</blockquote></details>

As discussed in slack, blocking full screen spinner is antipattern and shouldn't be used unless there is _real_ need for it. If I understood correctly, in this case there is no need for that, so this should be removed and we should rather show spinner in disabled "save" button during the operation.
___
*[`ui/src/components/timetables/import/PreviewTimetablesPage.tsx` line 50 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNLh97TEC8aowuCVAZ6:-NNovwoL99ntstmL2FRE:bcs1g51) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ee754f6cf7710154f3360d0d17cf4182c055b98a/ui/src/components/timetables/import/PreviewTimetablesPage.tsx#L50)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

I tried to do something for this. How does it look?
</blockquote></details>

IMO much better now. :+1: 
___
*[`ui/src/hooks/timetables-import/useTimetablesImportUIActions.ts` line 6 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNouxU44XKupxEu5dQE:-NNouxU44XKupxEu5dQF:b-w8lxno) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77130a85ae0810387ede22ecc391a0e94e85832b/ui/src/hooks/timetables-import/useTimetablesImportUIActions.ts#L6)):*
> ```XML
> import { showSuccessToast } from '../../utils';
> import { useLoader } from '../ui';
> import { useConfirmTimetablesImport } from './useConfirmTimetablesImport';
> ```

The "original" hook file is called "useConfirmTimetablesImport", so it could make sense to name this file according to it.
"UIActions" postfix is OK for me, so the final name could then be "useConfirmTimetablesImportUIAction".

Thumbs up for organizing these to the same folder already, that helps too. :+1: 
___
*[`ui/src/hooks/timetables-import/useTimetablesImportUIActions.ts` line 24 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNotyNh5NMJdgZ_PJrU:-NNotyNh5NMJdgZ_PJrV:b-r1nh30) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77130a85ae0810387ede22ecc391a0e94e85832b/ui/src/hooks/timetables-import/useTimetablesImportUIActions.ts#L24)):*
> ```XML
>   };
> 
>   return { onTimetablesImportConfirm };
> ```

:raised_eyebrow: , "onConfirmTimetablesImport" would sound better. OK, hmm, the name is already used original hook, but still this doesn't make any sense. :) 
Maybe you could either:
- Import it `as` another name `import { useConfirmTimetablesImport as confirmImport } from './useConfirmTimetablesImport';` so that you could re-export it as "onConfirmTimetablesImport"
- Invent new naming scheme for these actions, "onComfirmTimetablesImportWithFeedback" or something.
___
*[`ui/src/hooks/timetables-import/useTimetablesImportUIActions.ts` line 24 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNovsI24S2lw9u6XLO6:-NNovsI24S2lw9u6XLO7:bl515gt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77130a85ae0810387ede22ecc391a0e94e85832b/ui/src/hooks/timetables-import/useTimetablesImportUIActions.ts#L24)):*
> ```XML
>   };
> 
>   return { onTimetablesImportConfirm };
> ```

I could also re-consider the whole "confirm timetables import" naming, I found it very confusing on first time. Should we rather talk about "saving draft timetables" or something like that? "on confirm" sounds like we are showing some kind of confirmation dialog before actually saving something. But as this naming pattern is probably used even before this PR, you can decide that this it out of scope of this PR.


<!-- Sent from Reviewable.io -->

2023-02-09 10:24 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492)* status: 0 of 24 files reviewed, 3 unresolved discussions (waiting on @eleksi)

___
*[`ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx` line 25 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNpg86426SGHYr5N9Mk:-NNpg86426SGHYr5N9Ml:b4tg1np) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6f90ea9b380c90424b4c1b378c138ac2c1bc9263/ui/src/components/timetables/import/VehicleScheduleFrameBlocksView.tsx#L25)):*
> ```XML
>   const blocks = vehicleScheduleFrame.vehicle_services.flatMap((service) =>
>     // TODO: Get Block label from vehicle service after it has been implemented to data model
>     service.blocks.map((block) => ({ label: '!Block label', block })),
> ```

By the way, did you rather wanted to: `({ label: '...', ...block})`?
___
*[`ui/src/redux/selectors/index.ts` line 108 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNpgUfrAQyySlxkMbN4:-NNpgUfrAQyySlxkMbN5:b9p6es1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6f90ea9b380c90424b4c1b378c138ac2c1bc9263/ui/src/redux/selectors/index.ts#L108)):*
> ```XML
> );
> 
> export const selectIsOperationLoading = createSelector(
> ```

Not sure if we have use case for this anymore.
___
*[`ui/src/components/common/Loader.tsx` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-NNCCsyw4YuLMkCpW2gm:-NNpc4i3BaS4OBzrDZgT:b-bgmhia) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a26b4572c6ae49dbe63660c44e641bfbd7c63684/ui/src/components/common/Loader.tsx#L10)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Spinner removed, ticket created.
</blockquote></details>

If this loader is not used anymore, please remove this.


<!-- Sent from Reviewable.io -->

2023-02-09 10:54 UTC, tk-vincit approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/492#-:-NNpnzFF-EKSJmtOk2Bq:b-uwkowd)* status: 0 of 24 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-09 11:02 UTC, merged