Timetable versions page
HSLdevcom/jore4-ui pull request #501
Opened 2023-02-03 13:55 UTC by HenrikHartiala

Adds the timetable versions page first iteration. This has some logic that will be moved to SQL function and also we need to rework some logic after we get reference days implemented.

2023-02-08 08:44 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501)* status: 0 of 17 files reviewed, 10 unresolved discussions (waiting on @HenrikHartiala)

___
*[`package.json` line 26 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk1dja7XNHpai2Vd80:-NNk1dja7XNHpai2Vd81:b-v7kss8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/package.json#L26)):*
> ```JSON
>     "test:e2e:list": "yarn ws:e2e print-tests 'e2e/**.cy.ts'",
>     "qa": "yarn --frozen-lockfile && yarn ws:db build && yarn ts:check && yarn prettier:check && yarn lint && yarn test && yarn test:integration && yarn test:e2e",
>     "qa:fast": "yarn qa --config-file cypress.config.fast.ts"
> ```

By the way, this command works mostly "by luck" as `--` flag (which is intented for cypress) gets passedt to last ommand in `yarn qa` script, and if someone happens to add more commands there, things explode...
Thus I would just remove this command (assuming that no one used it as it was broken), but if you find this useful, we can keep it.
___
*[`ui/src/components/forms/common/ObservationDateInput.tsx` line 20 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk2W12Bbx8sTbUfYbn:-NNk2W12Bbx8sTbUfYbo:bav5ygl) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/forms/common/ObservationDateInput.tsx#L20)):*
> ```XML
>   return (
>     <Row className={className}>
>       <Column>
> ```

Now this can't be used anymore in contexts where form layout is not column, so this is now less flexibe.

By the way, is Row actually used for anything?



_Code quote:_
```XML
    <Row className={className}>
      <Column>
```
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 37 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk3DRa13703fwSX127:-NNk3DRa13703fwSX128:b7s01u5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L37)):*
> ```XML
>  *  line id.
>  */
> const getVersionsUrlWithReturnToQueryString = (line: RouteLine) => {
> ```

By the way, this removes possibly existing query from url - is this intented? 
___
*[`ui/src/components/timetables/versions/TimetableVersionTable.tsx` line 8 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk6UPL14070-a-55cq:-NNk6UPM9T31WTT2oxM6:b-nvcl2x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionTable.tsx#L8)):*
> ```XML
> export const TimetableVersionTable = ({
>   data,
>   className,
> ```

Please default to `= ''` to avoid having 'undefined' strings as classNames in DOM if this is not given.

By the way, usually we have defined `interface Props` for these before the actual component, but as we don't have linter rules or anything for this I guess both approaches are OK.
___
*[`ui/src/components/timetables/versions/TimetableVersionTable.tsx` line 15 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk6r185gWhrYSjhtRI:-NNk6r185gWhrYSjhtRJ:bezkeib) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionTable.tsx#L15)):*
> ```XML
>   const { t } = useTranslation();
>   return (
>     <table className={`${className} w-full`}>
> ```

className prop should be last in this list as it is intented for overriding default styles.
Also one could argue w-full should be passed from outside, but do as you wish regarding that.
___
*[`ui/src/components/timetables/versions/TimetableVersionTable.tsx` line 26 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk7GSr8yC7XRbH99Ba:-NNk7GSr8yC7XRbH99Bb:b-l2hea2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionTable.tsx#L26)):*
Is span valid child for tbody element? Probably not:
>The only allowed child nodes of the HTML <tbody> tag are <tr> (table row) elements.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 29 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk8Is45Ex_VIjrmcUZ:-NNk8Is45Ex_VIjrmcU_:b-1dfecy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L29)):*
> ```XML
> };
> 
> const StatusTableDataCell = ({
> ```

Should be typed to JSX.Element.
But as this is used only once, I don't see reason why this is implemented as own component instead of inlining this.
___
*[`ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts` line 81 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkARX-0ufLEuVOxmfX:-NNkARX-0ufLEuVOxmfY:bpr345y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts#L81)):*
> ```XML
>       isDateInRange(
>         DateTime.now(),
>         // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
> ```

Please comment why this is safe to do, or do we have bug here?
___
*[`ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts` line 144 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkArnd0zMWdnQ3M9oC:-NNkArnd0zMWdnQ3M9oD:b-w1z5nu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts#L144)):*
> ```XML
>       timetableVersionsTableData.push({
>         routeLabelAndVariant: route.routeLabelAndVariant,
>         ...foo,
> ```

:notbad:, but please use e.g. `item` instead
___
*[`ui/src/locales/en-US/common.json` line 301 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk9guJ1RolxnRBc0YN:-NNk9guJ1RolxnRBc0YO:b-dl76cm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/locales/en-US/common.json#L301)):*
> ```JSON
>     "operatingCalendar": "Operating calendar",
>     "drafts": "Drafts",
>     "noDrafts": "No drafts",
> ```

Just note that "lines" has following translations too:
"draftsTitle": "Drafts",
    "noDrafts": "No drafts",

It is a matter of opinion if those should be combined, so do as you wish
___
*[`ui/src/locales/fi-FI/common.json` line 180 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkA0kPE7pD2nw2dY2Q:-NNkA0kPE7pD2nw2dY2R:b-ju5jn7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/locales/fi-FI/common.json#L180)):*
> ```JSON
>     "temporary": "Väliaikainen",
>     "draft": "Luonnos",
>     "special": "Special",
> ```

"Special" is not finnish. "Erityinen"? Or is this intented?


<!-- Sent from Reviewable.io -->

2023-02-08 09:42 UTC, eleksi requested changes
> Reviewed 1 of 1 files at r1, 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501)* status: 16 of 17 files reviewed, 23 unresolved discussions (waiting on @HenrikHartiala and @tk-vincit)

___
*[`ui/src/components/forms/common/ObservationDateInput.tsx` line 19 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkEgebArmBwGObG3cf:-NNkEgebArmBwGObG3cg:bfvyymj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/forms/common/ObservationDateInput.tsx#L19)):*
> ```XML
>   const dateInputId = 'observation-date-input';
>   return (
>     <Row className={className}>
> ```

What is the role if this `Row`
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 37 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkExw0-02p37E7EVXn:-NNkExw0-02p37E7EVXo:b70je7t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L37)):*
> ```XML
>  *  line id.
>  */
> const getVersionsUrlWithReturnToQueryString = (line: RouteLine) => {
> ```

Could we just save the url from history when coming to this page or just do history.goBack() etc?
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 81 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkHCIY0XLnrUt1qDsE:-NNkHCIY0XLnrUt1qDsF:b-u0slg7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L81)):*
> ```XML
>             {line && (
>               <SimpleButton
>                 className="mt-auto"
> ```

What is this classname for
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 17 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkHJoR8SH1YNQ236HA:-NNkHJoR8SH1YNQ236HB:bk9v7vw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L17)):*
> ```XML
>   const history = useHistory();
> 
>   const { timetableVersionsTableData } = useGetLineTimetableVersions({ label });
> ```

Is the observation date supposed to always be today, or can the "observation date line" in the visual view (in designs) be moved?
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 25 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkHkM-2XYBedzrIs2K:-NNkHkM-2XYBedzrIs2L:bm7f89r) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L25)):*
> ```XML
>           queryParams.returnTo as string,
>         )
>       : routeDetails[Path.timetables].getLink();
> ```

Again, I would rather try going back in history rather than hard coded url. If history has no back, then maybe go to that page.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 25 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkFxKE961rsbgslFKA:-NNkFxKE961rsbgslFKB:baw1h1p) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L25)):*
> ```XML
>       return 'bg-gray-100';
>     default:
>       throw new Error(`Unkown priority: ${priority}`);
> ```

What if we have staging priority timetables (as I had when tried to test this)? The page crashes. If we do not support them and the app crashes instead, maybe we should filter them out completely so the view can be opened even if there were staging priority timetables.
___
*[`ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts` line 10 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkJT0O31uC8w8LeDE7:-NNkJT0O31uC8w8LeDE8:bc0n9vr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts#L10)):*
> ```XML
> import { TimetablePriority } from '../../types/Priority';
> import { buildRouteLineLabelGqlFilter, mapToVariables } from '../../utils';
> import { getRouteLabelVariantText } from '../../utils/route';
> ```

Not part of this PR but if you want you could make this file contents to be exported from /utils/index :smile: 
___
*[`ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts` line 12 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkMPWY3jk9RKI2bUST:-NNkMPWY3jk9RKI2bUSU:byqrekx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts#L12)):*
> ```XML
> import { getRouteLabelVariantText } from '../../utils/route';
> 
> export interface TimetablesVersionsRowData {
> ```

This looks funny with combination of camel case and snake case fields, but I guess that is ok :smile: 
___
*[`ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts` line 13 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkJoe1-aD0cE7P3kxy:-NNkJoe1-aD0cE7P3kxz:br2alhf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts#L13)):*
> ```XML
> 
> export interface TimetablesVersionsRowData {
>   routeLabelAndVariant: string;
> ```

We have `unique_label` in route information, which includes route and variant. There is _ as a separator between the label and variant though, so it cant be used straight away. But just FYI there is pretty much similar field in the data model which is named unique label, if you want to utilize this info, it might affect this field naming and/or source.
___
*[`ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts` line 140 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkNhxyDGOEnI3pPiMz:-NNkNhxyDGOEnI3pPiN-:bevsylh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts#L140)):*
> ```XML
>   const timetableVersionsTableData: TimetablesVersionsRowData[] = [];
> 
>   distinctMappedVersionsData.forEach((route) => {
> ```

This kind of looks like two `flatMap`s to me, instead of `forEach`.
___
*[`ui/src/locales/en-US/common.json` line 181 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkOQIL61_8lXpdwQXJ:-NNkOQIL61_8lXpdwQXK:b-twqj2c) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/locales/en-US/common.json#L181)):*
> ```JSON
>     "draft": "Draft",
>     "special": "Special",
>     "staging": "Staging"
> ```

This could be mapped to some different value as well. "Staging" might not tell the user much, this is more like "timetable being imported". I don't know if we want to be exact just tell the timetable is "staging" priority or actually tell them what the priority means.
___
*[`ui/src/locales/fi-FI/common.json` line 180 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkA0kPE7pD2nw2dY2Q:-NNkOI7e2e5W1pfoi0_5:bn4pxoi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/locales/fi-FI/common.json#L180)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

"Special" is not finnish. "Erityinen"? Or is this intented?
</blockquote></details>

Erityispäivä?
___
*[`ui/src/locales/fi-FI/common.json` line 181 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkOcyI6qydGfA6InHX:-NNkOcyI6qydGfA6InHY:b7rliyx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/locales/fi-FI/common.json#L1 [...]

2023-02-08 11:30 UTC, tk-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501)* status: 16 of 17 files reviewed, 23 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 25 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkHkM-2XYBedzrIs2K:-NNkjdt2AJGxVaGJSB73:b-1tnai) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L25)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

Again, I would rather try going back in history rather than hard coded url. If history has no back, then maybe go to that page.
</blockquote></details>

Also it could be considered if this kind of logics should be extracted to a hook for a very least.
That would couple "both sides" of this hack into a single file.
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 36 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkjulkCwkRYNVllM37:-NNkjulkCwkRYNVllM38:bo23fu0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L36)):*
> ```XML
>   );
>   const onlyDraftTimetables = timetableVersionsTableData.filter(
>     (item) => item.vehicle_schedule_frame.priority === TimetablePriority.Draft,
> ```

Kind of matter of opinion, but as `useGetTimetableVerions` returns timetables already mapped to a data structure designed specially for UI's needs, this kind of splitting could be done in the hook itself.



_Code quote:_
```XML
  const timetablesExcludingDrafts = timetableVersionsTableData.filter(
    (item) => item.vehicle_schedule_frame.priority !== TimetablePriority.Draft,
  );
  const onlyDraftTimetables = timetableVersionsTableData.filter(
    (item) => item.vehicle_schedule_frame.priority === TimetablePriority.Draft,
  );
```
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 25 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkFxKE961rsbgslFKA:-NNkkQ0uC0HeyZwMkgp-:bm7cadp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L25)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

What if we have staging priority timetables (as I had when tried to test this)? The page crashes. If we do not support them and the app crashes instead, maybe we should filter them out completely so the view can be opened even if there were staging priority timetables.
</blockquote></details>

Very good catch. Another alternative could be defining some kind of bg colour for those here.
Annoying that TS compiler doesn't complain here that we have unhandled cases. That is one reason why this kind of Record-based pattern is sometimes preferred:

```
export const mapPriorityToUiName = (key: Priority) => {
  const uiStrings: Record<Priority, string> = {
    [Priority.Standard]: i18n.t('priority.standard'),
    [Priority.Temporary]: i18n.t('priority.temporary'),
    [Priority.Draft]: i18n.t('priority.draft'),
  };
  return uiStrings[key];
};

```
___
*[`ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts` line 12 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkMPWY3jk9RKI2bUST:-NNkkyzt3csMCU9vvX-f:b-k91odt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts#L12)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

This looks funny with combination of camel case and snake case fields, but I guess that is ok :smile: 
</blockquote></details>

That is a good point. As this is custom datatype for UI's needs, there is no need to use snake_case :thinking: 


<!-- Sent from Reviewable.io -->

2023-02-15 10:06 UTC, tk-vincit requested changes
> Reviewed 3 of 25 files at r4.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501)* status: 7 of 29 files reviewed, 23 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

___
*[`package.json` line 26 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk1dja7XNHpai2Vd80:-NOJ1Ab5EAe3E3MBQCCI:b-8a4tgd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/package.json#L26)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yeah good point, that is the downside of this. But if I put it back like it was (having all the necessary commands in this script), then we need to update both always. And this should apply to `test:e2e:fast` as well. (Or is there another way of fixing this?)
So at least we have less text int he scripts :D

And about the other point, I did use the `yarn:qa` command every day but then the tests started to fail locally and everywhere so bad that I've just used CI. I do think that I'm going to continue using this command again later :+1: It is nice that it runs all the tests and eslints and prettier checks for me. Although I could just create a commithook for myself to run prettier.
</blockquote></details>

This could be solved by having more yarn scripts and composing this kind of commands from previously introduced scripts. But that also causes us to have more and more script definitions, which clutters things up and has thus also drawbacks.
But as discussed f2f, this is OK for now.  :+1: 
___
*[`ui/src/components/forms/common/ObservationDateInput.tsx` line 20 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk2W12Bbx8sTbUfYbn:-NOJ1jbA7vIeKBpjHjZ2:bp9i1nt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/forms/common/ObservationDateInput.tsx#L20)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

The Row + Column combination is for the layout of this component. Now it will always be the same size look the same where ever you put it.
Im not sure what you mean by "can't be used in context where form layout is not column" I think you can now put this anywhere and it will look the same.

The Row is used for the layout of this component. If I remove the `Row`, then the outer component will be "Column" and this component will start to look different depending on what is the parent component. 
I can demonstrate this if needed, but you can also check what happens for example on line details page if you remove the Row component.

So with this Row + Colum combination, where ever you put it, it will always be so that the <label> (Tarkasteluhetki) will be on top of the input field and the size of the input will always be the same (minimum size so it won't take as much space as it is given). 
</blockquote></details>

As discussed f2f, defining size of component is arguably rather responsibility of the parent component.
But do as you wish here.
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 37 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk3DRa13703fwSX127:-NOJ23_40yAzs2csWhoO:bx8sstd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L37)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Good point, I am not sure. We might want them to persist there? Maybe this needs to be confirmed from Juha.
</blockquote></details>

Let's continue this discussion within the new place where this code is now moved, if there is still something to discuss.
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 37 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkExw0-02p37E7EVXn:-NOJ2Jgl9D3k4MdrmTJX:be31d2m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L37)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This is implemented like this to match the same behaviour and implementation as in LineDrafts. The reason is that if the URL is copypasted, the `Close` button in versions page would throw you out. (Copy paste it to blank page and this button would return you to blank page). 

We want this button to return you to the line page you came here from.
And our VehicleScheduleDetailsPage (and LineDetailsPage) is LineID based, but TimetableVersionsPage (and LineDraftsPage) is label based, we can't just remove the label and return to the corresponding linePage.
</blockquote></details>

Henrik has valid points about drawbacks of history.goBack, e.g. that the history might be empty (or it could even have some 3rd party page is user pastes url of this page e.g. after reading the news!)
___
*[`ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx` line 34 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJ3AHm1jf5JB_vw1qs:-NOJ3AHm1jf5JB_vw1qt:b2zce5o) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9e8120f4878ff6b499342eaa9680e3eed97369da/ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx#L34)):*
> ```XML
>   const { t } = useTranslation();
> 
>   const getHeadingBgColor = (key: TimetablePriority) => {
> ```

If this is actually used only here for now, then it might make more sense to keep it here.
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 25 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkHkM-2XYBedzrIs2K:-NOJ3e1F1VXKDtUFqD2m:b-87u105) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L25)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yeah so this is the same behaviour in which we ended up with when implementing LineDrafts. Currently this will make the "Close" buttons behaviour more sensible when this URL is copypasted (we dont want to "go back" we want to "close" this and return to the VehicleScheduleDetailsPage. I know that there could be arguments about other nonsensible behaviours in some use cases and I'm open for suggestions, but I do think that we should rather discuss this live, since it is very hard topic to discuss here.

All that said, the suggestion about hook extraction I can already do. Let's see if I can combine these two implementations :+1: 
</blockquote></details>

Let's continue this discussion (if needed) within the new hook implementation.
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 36 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkjulkCwkRYNVllM37:-NOJ4H-yDSAy2aIG7Lkm:b1lt0tw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L36)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Thanks, I thought of that but then I argumented myself that "what if someone does not want these separated"?  But you do have a point that it is not the RAW data anyway, and the user can just .concat these (or simply return all three variations from the hook) if doesn't want these separated.
So I'll change this :+1: 
</blockquote></details>

The hook itself could also return `allTimetables` if someone needs them :shrug: 
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 12 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJ3rXuAP18RripbkSm:-NOJ3rXuAP18RripbkSn:bsyfrx5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e [...]

2023-02-15 10:11 UTC, tk-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501)* status: 7 of 29 files reviewed, 24 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

___
*[`ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts` line 4 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJYfHeALq799HjleUI:-NOJYfHeALq799HjleUJ:btmrd2m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e95a/ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts#L4)):*
> ```XML
> import { useHistory } from 'react-router';
> 
> export const useVersionsOnCloseWithReturnToQueryParam = () => {
> ```

What does "version" mean in this context?


<!-- Sent from Reviewable.io -->

2023-02-15 14:45 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501)* status: 3 of 30 files reviewed, 21 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`ui/src/components/forms/common/ObservationDateInput.tsx` line 20 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk2W12Bbx8sTbUfYbn:-NOJuQScCHv35wnfrWDE:b3oqey) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/forms/common/ObservationDateInput.tsx#L20)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

As discussed f2f, defining size of component is arguably rather responsibility of the parent component.
But do as you wish here.
</blockquote></details>

:+1: Moved the row-component to parent to make the sizing more flexible.
___
*[`ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx` line 34 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJ3AHm1jf5JB_vw1qs:-NOK2GrB2DvS4NTGUJf5:buj2azj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9e8120f4878ff6b499342eaa9680e3eed97369da/ui/src/components/timetables/vehicle-schedule-details/vehicle-service-table/VehicleServiceTable.tsx#L34)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

If this is actually used only here for now, then it might make more sense to keep it here.
</blockquote></details>

Check, I'll revert this.
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 36 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkjulkCwkRYNVllM37:-NOK2yGD-z9ACfWmCUgi:b-k08qa0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L36)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

The hook itself could also return `allTimetables` if someone needs them :shrug: 
</blockquote></details>

yeah true.
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 12 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJ3rXuAP18RripbkSm:-NOK2cgv2Q4l4w2yaoii:b1aytns) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e95a/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L12)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Exported component name should be the same as file name, so please rename either one.
</blockquote></details>

Good one
___
*[`ui/src/components/timetables/versions/TimetableVersionsPage.tsx` line 24 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJ4WroD14u8Qh87fCo:-NOK3pyX1MEzEtFu32GP:b2nh52p) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e95a/ui/src/components/timetables/versions/TimetableVersionsPage.tsx#L24)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I see potential misuse here, what if someone writes something stupid to the label part of url and then we just show it here :fearful: 
OK, maybe that one would be on user :grin: 
</blockquote></details>

:D 
___
*[`ui/src/components/timetables/versions/TimetableVersionTable.tsx` line 8 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk6UPL14070-a-55cq:-NOK3yTZ5AczFED7knzE:b-3wzb56) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionTable.tsx#L8)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I once fixed all of these to default to `= ''`, but it is possible that someone has introduced classNames without default values since that :unamused: :smile: 
</blockquote></details>

Meant the interface Props. 
___
*[`ui/src/components/timetables/versions/TimetableVersionTable.tsx` line 15 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNk6r185gWhrYSjhtRI:-NOK4ome4q5YjW5cTqMX:bm6ngfc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/components/timetables/versions/TimetableVersionTable.tsx#L15)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Not a big thing, but string template is not needed anymore as we have only one className.
<table className={className}>`
</blockquote></details>

:travolta:
___
*[`ui/src/components/timetables/versions/TimetableVersionTable.tsx` line 21 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJ6FrWEe_fAGkicb-Y:-NOK6ygu7lnVrfpJFh4o:boov682) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e95a/ui/src/components/timetables/versions/TimetableVersionTable.tsx#L21)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Btw, another way to write this without ternary. Not sure which one is pretier though.
```{(data || [].)map(...)}

<Visible show={!data.lenght} > no timetables </Visible}
```
</blockquote></details>

as discussed f2f, minor change but no Visible component. 
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 54 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJ8trx5szYAa-LPqMa:-NOKLf3m6iXJ7qqcLcHe:brmux6m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e95a/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L54)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What is the point of having i18n field and then hardcoding the ui to use fi_FI? :wink: 
Please see `parseI18nField` from `ui/src/i18n/utils.ts`.

(By the way, not sure if these UI's should rather show all different translations to the user :thinking: . But that is out of scope of this PR, so just use `parseI18nField` here and we are good to go.)
</blockquote></details>

Check!
___
*[`ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts` line 4 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJYfHeALq799HjleUI:-NOKOiKXAmIR3VAg4Dg2:b-byc3h8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e95a/ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts#L4)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

What does "version" mean in this context?
</blockquote></details>

Yes, it is unnecessary strict naming here, should be generic so I'll remove it.
___
*[`ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts` line 10 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJVAfo79GMC0aKLfMv:-NOKOuv77sLbJv80fPJD:b4qkeyp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e95a/ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts#L10)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

dsaasdfafdsfadsadfsadfdsfaadfsadfadfdfadafswe :joy: 
</blockquote></details>

:proud: :man_facepalming: This absolutely broke me :laughing: 
___
*[`ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts` line 13 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJVSle8BR_cX_gKGjL:-NOKPKXnDRTDCMgLCub3:b-dnqxp8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e95a/ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

if returnToId is optional, it can be undefined. Does this then add `?returnTo=undefined` to url? Maybe that is not what we want...
</blockquote></details>

:+1: good one
___
*[`ui/src/components/timetables/versions/TimetableVersionTableHeader.tsx` line 3 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJ6jIy-5aQd8IR3EWM:-NOK7VXH5caPvOfJeawu:b-u2pg5i) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf0 [...]

2023-02-16 08:07 UTC, tk-vincit approved these changes
> Reviewed 6 of 19 files at r6.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501)* status: 9 of 30 files reviewed, 7 unresolved discussions (waiting on @eleksi and @HenrikHartiala)

___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 47 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOO5i-gD4wRJi9qRIb3:-NOO5i-gD4wRJi9qRIb4:bc3fl41) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84c6f0750d721aa1eb2f881e4eceaec46bf5eef2/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L47)):*
> ```XML
>       <div className="mx-12 my-8">
>         <FormRow mdColumns={2} className="mb-8">
>           <Row>
> ```

Do we need row inside FormRow? :raised_eyebrow: 
I assume passing some className to ObservationDateControl would actually do what you want to do without introducing new dom node.
Same applies to other similar places in this PR.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 23 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOOEr1XBYfJklbG58LS:-NOOEr1XBYfJklbG58LT:b-cywa45) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84c6f0750d721aa1eb2f881e4eceaec46bf5eef2/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L23)):*
> ```XML
>     [TimetablePriority.Special]: 'bg-hsl-light-purple',
>     [TimetablePriority.Draft]: 'bg-background',
>     [TimetablePriority.Staging]: '', // Staging priority should not be used anywhere in the UI
> ```

I guess those are actually shown within timetables import preview, so not sure if this is a bit misleading?
___
*[`ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts` line 4 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJYfHeALq799HjleUI:-NOOFg8Y4C8PVWS11CKT:bjxivhu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e95a/ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts#L4)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yes, it is unnecessary strict naming here, should be generic so I'll remove it.
</blockquote></details>

Now that I think of this, also "onClose" might be too specific information.
___
*[`ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts` line 13 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkJoe1-aD0cE7P3kxy:-NOOFNAg0f1o11OKW-gW:byqli2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts#L13)):*
<details><summary><i>Previously, eleksi wrote…</i></summary><blockquote>

We have `unique_label` in route information, which includes route and variant. There is _ as a separator between the label and variant though, so it cant be used straight away. But just FYI there is pretty much similar field in the data model which is named unique label, if you want to utilize this info, it might affect this field naming and/or source.
</blockquote></details>

Was anything done regarding this? Should anything be done regarding this?


<!-- Sent from Reviewable.io -->

2023-02-16 13:05 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501)* status: 7 of 30 files reviewed, 6 unresolved discussions (waiting on @eleksi and @tk-vincit)

___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx` line 47 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOO5i-gD4wRJi9qRIb3:-NOOIdu63MkDNRZty72b:bhmxrmp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84c6f0750d721aa1eb2f881e4eceaec46bf5eef2/ui/src/components/timetables/vehicle-schedule-details/VehicleScheduleDetailsPage.tsx#L47)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Do we need row inside FormRow? :raised_eyebrow: 
I assume passing some className to ObservationDateControl would actually do what you want to do without introducing new dom node.
Same applies to other similar places in this PR.
</blockquote></details>

Good point. Now that it is not anymore inside the component to make the layout of the component, this is confusing here. Should be changed in both places now. Here and in ActionsRow.tsx
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 23 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOOEr1XBYfJklbG58LS:-NOOjk4l0NTX4u1AtK7C:bhjtfwt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84c6f0750d721aa1eb2f881e4eceaec46bf5eef2/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L23)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

I guess those are actually shown within timetables import preview, so not sure if this is a bit misleading?
</blockquote></details>

Hmm. Yeah that might be. I'll just add the same colour that was in the other function. 
___
*[`ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts` line 13 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NNkJoe1-aD0cE7P3kxy:-NOOm3MT3jMGQ40fb5kR:b-cznwqf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77287eaff54c35f031136052f9f3597ed3af0791/ui/src/hooks/line-timetable-versions/useGetLineTimetableVersions.ts#L13)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Was anything done regarding this? Should anything be done regarding this?
</blockquote></details>

Forgot to write anything there, but we discussed f2f at the office at one point and yes this unique_label could be used, but it is in a fixed form of "<label>_<variant>".
Also if we need more unique attributes, then they will be added in uniqueLabel as well. So I think we decided to go with this approach where we define it separately and we can decide how it is presented in the UI.
___
*[`ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts` line 4 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501#-NOJYfHeALq799HjleUI:-NOOmwSL42G_6dd37CIU:bxq7v8b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc533e5f9366577de698a7bff3ecf458bf06e95a/ui/src/hooks/ui/useVersionsOnCloseWithReturnToQueryParam.ts#L4)):*
<details><summary><i>Previously, tk-vincit wrote…</i></summary><blockquote>

Now that I think of this, also "onClose" might be too specific information.
</blockquote></details>

Good point :D I'll remove the "onClose" from the other hook names as well. Unfortunately the more specific hooks names got a bit longer now. But it is more descriptive I think.


<!-- Sent from Reviewable.io -->

2023-02-16 14:09 UTC, tk-vincit approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/501)* status: 7 of 30 files reviewed, 3 unresolved discussions (waiting on @eleksi)



<!-- Sent from Reviewable.io -->

2023-02-16 14:40 UTC, merged