Make route related component fetch their own data
HSLdevcom/jore4-ui pull request #554
Opened 2023-03-15 15:52 UTC by eleksi

2023-03-16 10:37 UTC, pallost requested changes

2023-03-16 10:37 UTC, pallost commented on ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetables.tsx
> +export const VehicleRouteTimetables = ({ routeIds }: Props): JSX.Element => {
it's not necessarily in the scope of this PR, but this is a pretty bad name for these components. Would these be better?
VehicleRouteTimetables -> LineTimetables
VehicleRouteTimetable -> RouteTimetables

2023-03-16 10:37 UTC, pallost commented on ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx
> +  const routeResult = useGetRouteDetailsByIdQuery({
I'm pretty sure you don't need all the fields of the GetRouteDetailsById query here, please restrict it a bit!

2023-03-16 10:37 UTC, pallost commented on ui/src/hooks/vehicle-service/useGetTimetables.ts
> +export const useGetTimetables = (journeyPatternId?: UUID) => {
this is a bad name for a hook. Is this rather a useGetRouteTimetables? (at least the parameter is a journey pattern id, that's why I think so)

2023-03-16 10:37 UTC, pallost commented on ui/src/hooks/vehicle-service/useGetTimetables.ts
>      const res = await getTimetablesForOperationDay({
this is a bad name for this function... is this rather getRouteTimetablesForOperationDay?

2023-03-20 11:58 UTC, eleksi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/554)* status: 0 of 14 files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/554#-NQ_yINRSbyteM_jUdjQ-r1-34:-NQyjmzf7_o88yEnrkW6:bs6ocsw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7e3caa6fb732d6607cb8a360c4693000caabe82c/ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetableSection.tsx#L34)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I'm pretty sure you don't need all the fields of the GetRouteDetailsById query here, please restrict it a bit!
</blockquote></details>

Good spot, infrastructure related data was not needed!
___
*[`ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetables.tsx` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/554#-NQ_yINRSbyteM_jUdjR-r1-7:-NQyqkRKARCT14rW_aUm:bkzt7to) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7e3caa6fb732d6607cb8a360c4693000caabe82c/ui/src/components/timetables/vehicle-schedule-details/VehicleRouteTimetables.tsx#L7)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it's not necessarily in the scope of this PR, but this is a pretty bad name for these components. Would these be better?
VehicleRouteTimetables -> LineTimetables
VehicleRouteTimetable -> RouteTimetables
</blockquote></details>

We discussed this with Henkka and came up with these names. I hope they are little better than the original ones
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 202 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/554#-NQ_yINSqxsfWz9nR9Bd-r1-202:-NQys5Wj1oDaVk3kVQff:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7e3caa6fb732d6607cb8a360c4693000caabe82c/ui/src/hooks/vehicle-service/useGetTimetables.ts#L202)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is a bad name for a hook. Is this rather a useGetRouteTimetables? (at least the parameter is a journey pattern id, that's why I think so)
</blockquote></details>

Done.
___
*[`ui/src/hooks/vehicle-service/useGetTimetables.ts` line 215 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/554#-NQ_yINSqxsfWz9nR9Bd-r1-215:-NQys5oj1MZE8NSbDw7l:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7e3caa6fb732d6607cb8a360c4693000caabe82c/ui/src/hooks/vehicle-service/useGetTimetables.ts#L215)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

this is a bad name for this function... is this rather getRouteTimetablesForOperationDay?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 08:11 UTC, merged