Parallelize e2e tests
HSLdevcom/jore4-ui pull request #572
Opened 2023-03-30 09:47 UTC by sr-vala

Resolves HSLdevocom/jore4#965

2023-03-30 14:26 UTC, HenrikHartiala requested changes
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: all files reviewed, 10 unresolved discussions (waiting on @sr-vala)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmgzqACxuACgIrfMZb):*
typo  won't match link the ticket
___
*[`cypress/cypress.config.ts` line 15 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmhz6a41PX_mJ_RkXv:-NRmhz6a41PX_mJ_RkXw:b-wic78y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b45cccf9b641e25c2c40ee7c0776e93287b9f4f1/cypress/cypress.config.ts#L15)):*
> ```XML
>     screenshotsFolder: 'reports/screenshots',
>     videosFolder: 'reports/videos',
>     reporter: 'junit',
> ```

Is this remove intended? Didn't we just add this config for the foresight?
___
*[`docker/docker-compose.custom.yml` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmieKNEznqVxCBA2bz:-NRmieKNEznqVxCBA2c-:b-jx5yr9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/docker/docker-compose.custom.yml#L7)):*
> ```YAML
>     # https://hub.docker.com/r/hsldevcom/jore4-hasura/tags?page=1&ordering=last_updated
>     # The :seed-data tag contains the latest main-build image with seed data.
>     image: &hasura-image 'hsldevcom/jore4-hasura:seed-main--20230323-c2b9c0b5408336240492e0619cdc96e0971d930e'
> ```

What does this change do? Maybe add an explanation in the comment above
___
*[`docker/docker-compose.custom.yml` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmj8CE8cIQPq9Upltt:-NRmj8CE8cIQPq9Upltu:bxyrc4v) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b45cccf9b641e25c2c40ee7c0776e93287b9f4f1/docker/docker-compose.custom.yml#L14)):*
> ```YAML
>         condition: service_healthy
>     environment:
>       HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
> ```

Why do we disable this?
___
*[`docker/docker-compose.e2e.yml` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmjZa76whd9KlX9Pz9:-NRmjZa8Alzju3DZCuma:b-gsac8b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/docker/docker-compose.e2e.yml#L7)):*
> ```YAML
>     # https://hub.docker.com/r/hsldevcom/jore4-hasura/tags?page=1&ordering=last_updated
>     # The :hsl tag contains hsl specific image without seed data.
>     image: &hasura-image 'hsldevcom/jore4-hasura:hsl-main--20230323-c2b9c0b5408336240492e0619cdc96e0971d930e'
> ```

Same question here
___
*[`test-db-manager/src/config.ts` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmjxt_6DbDJzX-bE-3:-NRmjxt_6DbDJzX-bE-4:b-dy07n5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/config.ts#L1)):*
> ```XML
> const envPort = process.env.POSTGRES_PORT;
> ```

This seems redundant. Explanation below
___
*[`test-db-manager/src/config.ts` line 4 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmpi7Z6R4SyPP_FwgG:-NRmpi7Z6R4SyPP_FwgH:b-5l7sdr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/config.ts#L4)):*
> ```XML
> const e2eDatabaseConfig = {
>   host: process.env.POSTGRES_HOST || '127.0.0.1',
>   port: envPort || 6432,
> ```

You can extract the switch case logic to a separate  helper function and then just call it here in case the `process.env.POSTGRES_PORT` is not existing.


```
const getTestDbPort = () => {
    // default instance = thread4, e2e1 = thread1, etc
    const currentExecutorIndex = process.env.CYPRESS_THREAD || '4';

    switch (currentExecutorIndex) {
      // testdb-e2e1
      case '1':
        return 6532;
      // testdb-e2e2
      case '2':
        return 6533;
      // testdb-e2e3
      case '3':
        return 6534;
      // testdb
      default:
        return 6432;
    }
  }

  const e2eDatabaseConfig = {
    host: process.env.POSTGRES_HOST || '127.0.0.1',
    port: process.env.POSTGRES_PORT || getTestDbPort(),
    database: process.env.POSTGRES_DB || 'jore4e2e',
    user: process.env.POSTGRES_USER || 'dbadmin',
    password: process.env.POSTGRES_PASSWORD || 'adminpassword',
  };
```
And then the getDbConfig can just return the config. Also this simplifies the logic a lot because you dont need to use 'let' nor override anything with spread.
___
*[`test-db-manager/src/config.ts` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmqar-25djfuVjzR7l:-NRmqar0DJq51QnNe9bL:bhn2jq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/config.ts#L16)):*
> ```XML
>   switch (currentExecutorIndex) {
>     // testdb-e2e1
>     case '1':
> ```

You could also enumerate these cases, so the comment wouldn't be needed and it would also explain the default value '4'. Also now we assign the '4' but do not use it. So I would say that either use it or remove it.

Also one good solution would be to add the enum for these values, and then use Record for the values.

```
const testDbPorts: Record<TimetablePriority, number> = {
    [Foobar.e2e1]: 6532,
    [Foobar.e2e2]: 6533,
    [Foobar.e2e3]: 6534,
    [Foobar.default]: 6432,
  };

  return testDbPorts[currentExecutorIndex];
```
This solution would also make sure that all of the cases are handled, because Record enforces a value for all the enums.
___
*[`test-db-manager/src/hasuraApi.ts` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmtMxe0oVppee9nb53:-NRmtMxfCP6CyrtvNqaY:b-jf431m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/hasuraApi.ts#L16)):*
> ```XML
>   const currentExecutorIndex = process.env.CYPRESS_THREAD || '4';
>   let hasuraUrl = '';
>   switch (currentExecutorIndex) {
> ```

You could use the same principles here as described in config.ts.

Also now that I see that this same values are here, I think that you should definitely add an enum, maybe to a separate file and then export it and use it here and in config.ts.
___
*[`ui/server.js` line 24 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmu5r15v5wyMwm4t3B:-NRmu5r15v5wyMwm4t3C:b-qu3n9y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/ui/server.js#L24)):*
> ```JavaScript
>     router: (req) => {
>       switch (req.headers['x-environment']) {
>         case 'e2e1':
> ```

Hmm, same thing could be applied here, but pfft, the value's don't match. Well I guess this is fine like it is.


<!-- Sent from Reviewable.io -->

2023-03-31 05:31 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: all files reviewed, 10 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/cypress.config.ts` line 15 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmhz6a41PX_mJ_RkXv:-NRpuBX1CG5kesxnegwt:b8qehbb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b45cccf9b641e25c2c40ee7c0776e93287b9f4f1/cypress/cypress.config.ts#L15)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Is this remove intended? Didn't we just add this config for the foresight?
</blockquote></details>

Yes, this was necessary because of overlapping configurations. The cypress-parallel library uses the cypress-multi-reporters library, and the reporterModulePath needs to be configured in the cypress-parallel command. cypress-parallel should produce junit files anyway.
___
*[`docker/docker-compose.custom.yml` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmieKNEznqVxCBA2bz:-NRpvcCG6f7V3J7VSouc:bo63esj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/docker/docker-compose.custom.yml#L7)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

What does this change do? Maybe add an explanation in the comment above
</blockquote></details>

The yaml anchor? The value can be referenced later in the file with '*hasura-image'. This was done by Tamas originally.
___
*[`test-db-manager/src/config.ts` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmqar-25djfuVjzR7l:-NRq5sOs001n2H-3TOUt:b-paxl5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/config.ts#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

You could also enumerate these cases, so the comment wouldn't be needed and it would also explain the default value '4'. Also now we assign the '4' but do not use it. So I would say that either use it or remove it.

Also one good solution would be to add the enum for these values, and then use Record for the values.

```
const testDbPorts: Record<TimetablePriority, number> = {
    [Foobar.e2e1]: 6532,
    [Foobar.e2e2]: 6533,
    [Foobar.e2e3]: 6534,
    [Foobar.default]: 6432,
  };

  return testDbPorts[currentExecutorIndex];
```
This solution would also make sure that all of the cases are handled, because Record enforces a value for all the enums.
</blockquote></details>

This is confusing me. Does TimetablePriority have something to do with this? What can testDbPorts[currentExecutorIndex] return exactly with the possible index values 1-3? The default value is used when not running the tests in parallel, and that uses the original testdb container. Not sure if we should default to one of the e2e containers in all cases and not use the original container at all, if developers have seed data in it.


<!-- Sent from Reviewable.io -->

2023-03-31 07:24 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: 17 of 21 files reviewed, 8 unresolved discussions (waiting on @HenrikHartiala)

___
*[`test-db-manager/src/config.ts` line 4 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmpi7Z6R4SyPP_FwgG:-NRqYOer54T7EOeUeOd5:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/config.ts#L4)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

You can extract the switch case logic to a separate  helper function and then just call it here in case the `process.env.POSTGRES_PORT` is not existing.


```
const getTestDbPort = () => {
    // default instance = thread4, e2e1 = thread1, etc
    const currentExecutorIndex = process.env.CYPRESS_THREAD || '4';

    switch (currentExecutorIndex) {
      // testdb-e2e1
      case '1':
        return 6532;
      // testdb-e2e2
      case '2':
        return 6533;
      // testdb-e2e3
      case '3':
        return 6534;
      // testdb
      default:
        return 6432;
    }
  }

  const e2eDatabaseConfig = {
    host: process.env.POSTGRES_HOST || '127.0.0.1',
    port: process.env.POSTGRES_PORT || getTestDbPort(),
    database: process.env.POSTGRES_DB || 'jore4e2e',
    user: process.env.POSTGRES_USER || 'dbadmin',
    password: process.env.POSTGRES_PASSWORD || 'adminpassword',
  };
```
And then the getDbConfig can just return the config. Also this simplifies the logic a lot because you dont need to use 'let' nor override anything with spread.
</blockquote></details>

Done.
___
*[`test-db-manager/src/hasuraApi.ts` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmtMxe0oVppee9nb53:-NRqY-x72lfsPNM25WSA:by455go) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/hasuraApi.ts#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

You could use the same principles here as described in config.ts.

Also now that I see that this same values are here, I think that you should definitely add an enum, maybe to a separate file and then export it and use it here and in config.ts.
</blockquote></details>

Not sure what you mean with "same values". The testdb and hasura ports are separate things at least?


<!-- Sent from Reviewable.io -->

2023-03-31 08:41 UTC, HenrikHartiala requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: 17 of 21 files reviewed, 5 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/cypress.config.ts` line 15 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmhz6a41PX_mJ_RkXv:-NRqRu_Z6N2UyTbLmcSg:bb71kmx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b45cccf9b641e25c2c40ee7c0776e93287b9f4f1/cypress/cypress.config.ts#L15)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Yes, this was necessary because of overlapping configurations. The cypress-parallel library uses the cypress-multi-reporters library, and the reporterModulePath needs to be configured in the cypress-parallel command. cypress-parallel should produce junit files anyway.
</blockquote></details>

Okay
___
*[`docker/docker-compose.custom.yml` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmieKNEznqVxCBA2bz:-NRqSLf70rEBYP2koqxm:b6g5428) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/docker/docker-compose.custom.yml#L7)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

The yaml anchor? The value can be referenced later in the file with '*hasura-image'. This was done by Tamas originally.
</blockquote></details>

Ah now I see, and it is referenced with `*` I suppose. Okay maybe it doesn't need a comment :+1:. Was thinking if this should be defined on top like as a variable, but I don't know the best practices for this so maybe this is fine like it is :+1: 
___
*[`docker/docker-compose.e2e.yml` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmjZa76whd9KlX9Pz9:-NRqaQ7j9Ed9J_cIKBoa:b2xvxbz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/docker/docker-compose.e2e.yml#L7)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Same question here
</blockquote></details>

This was solved :+1: 
___
*[`test-db-manager/src/config.ts` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmqar-25djfuVjzR7l:-NRqaa2f1JsF-n2fZzWz:b-og5upx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/config.ts#L16)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

This is confusing me. Does TimetablePriority have something to do with this? What can testDbPorts[currentExecutorIndex] return exactly with the possible index values 1-3? The default value is used when not running the tests in parallel, and that uses the original testdb container. Not sure if we should default to one of the e2e containers in all cases and not use the original container at all, if developers have seed data in it.
</blockquote></details>

Oops,  that "TimetablePriority" was a copy-paste devil. Was supposed to change that to `Foobar` which is the enum here. Anyway, the logic doesn't change. You just use enum for the '1' '2' '3' and '4' values.

 I'll open another thread where this function lies now.
___
*[`test-db-manager/src/config.ts` line 1 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRqb7yC-zUu4hWn_2cV:-NRqb7yC-zUu4hWn_2cW:beiuj9j) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/35c067da68bffc118b6063e38bd0ee6e80d014e3/test-db-manager/src/config.ts#L1)):*
> ```XML
> import { getTestDbPort } from './db-helpers';
> ```

Not sure if this getTestDbPort function would be needed in anywhere else? If not then maybe it is more clear to have it in this file rather than in a separate file.
___
*[`test-db-manager/src/hasuraApi.ts` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmtMxe0oVppee9nb53:-NRqnv3rAJ6fQfH9bBUY:b-eefccu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/hasuraApi.ts#L16)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Not sure what you mean with "same values". The testdb and hasura ports are separate things at least?
</blockquote></details>

The cased currentExecutorIndex values are the same. '1' to '4'. You should use an enum for these.
___
*[`test-db-manager/src/db-helpers/getDbPort.ts` line 7 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRqo6O64XqGOLPQpZ2j:-NRqo6O64XqGOLPQpZ2k:bqscs08) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/35c067da68bffc118b6063e38bd0ee6e80d014e3/test-db-manager/src/db-helpers/getDbPort.ts#L7)):*
> ```XML
>   switch (currentExecutorIndex) {
>     // testdb-e2e1
>     case '1':
> ```

So these cases '1', '2', '3', and '4' should be in an enum. You can put that enum to a separate file and export it from there. Then you can use that enum for these cases here and also in hasuraApi.ts


<!-- Sent from Reviewable.io -->

2023-03-31 10:53 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: 16 of 22 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`test-db-manager/src/hasuraApi.ts` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmtMxe0oVppee9nb53:-NRrHgGj15STEoS-tnSJ:b-63hfkh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/hasuraApi.ts#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

The cased currentExecutorIndex values are the same. '1' to '4'. You should use an enum for these.
</blockquote></details>

Tried to do this now.
___
*[`test-db-manager/src/db-helpers/getDbPort.ts` line 7 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRqo6O64XqGOLPQpZ2j:-NRrHin1EKSyRMFZMJ-b:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/35c067da68bffc118b6063e38bd0ee6e80d014e3/test-db-manager/src/db-helpers/getDbPort.ts#L7)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

So these cases '1', '2', '3', and '4' should be in an enum. You can put that enum to a separate file and export it from there. Then you can use that enum for these cases here and also in hasuraApi.ts
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-31 11:19 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: 16 of 22 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`docker/docker-compose.custom.yml` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmj8CE8cIQPq9Upltt:-NRrNuxv2gMignRZUBbj:b-83cr7r) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b45cccf9b641e25c2c40ee7c0776e93287b9f4f1/docker/docker-compose.custom.yml#L14)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Why do we disable this?
</blockquote></details>

This was done by Tamas at some point so can't really comment.


<!-- Sent from Reviewable.io -->

2023-04-03 09:56 UTC, HenrikHartiala requested changes
> Reviewed 1 of 4 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: all files reviewed, 8 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/support/commands.ts` line 82 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5WzJTAhpQZwwSIgMv:-NS5WzJTAhpQZwwSIgMw:b-25somr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/cypress/support/commands.ts#L82)):*
> ```XML
>       req.alias = `gql${req.body.operationName}`;
>       // default instance = thread4, e2e1 = thread1, etc
>       const currentExecutorIndex = Cypress.env('THREAD') || '4';
> ```

'4' here, please use the enum value.
___
*[`docker/docker-compose.custom.yml` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmj8CE8cIQPq9Upltt:-NS5NJGM6BnBUVCGadJ0:b-tasowq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b45cccf9b641e25c2c40ee7c0776e93287b9f4f1/docker/docker-compose.custom.yml#L14)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

This was done by Tamas at some point so can't really comment.
</blockquote></details>

Hmm, I thought this would disable the :3201/console (And I would not want to disable that), but as I tested, for some reason this does not disable it. So maybe it is okay to disable it for now, since it seems to not have any effect.
___
*[`test-db-manager/src/config.ts` line 5 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5T2A66c9hg0B1SEPN:-NS5T2A66c9hg0B1SEPO:b-jnc60h) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/config.ts#L5)):*
> ```XML
> const getTestDbPort = () => {
>   // default instance = thread4, e2e1 = thread1, etc
>   const currentExecutorIndex = process.env.CYPRESS_THREAD || '4';
> ```

Still '4' here, you should use the enum value.
___
*[`test-db-manager/src/config.ts` line 7 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5VquB8wMRepZQ2u0T:-NS5VquC8S1UzPXMkn51:b-wf2baa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/config.ts#L7)):*
> ```XML
>   const currentExecutorIndex = process.env.CYPRESS_THREAD || '4';
> 
>   switch (currentExecutorIndex) {
> ```

So this switch case can now be replaced with the Record. 

```
const testDbPorts: Record<CurrentExecuterIndex, number> = {
    [CurrentExecuterIndex.e2e1]: 6532,
    [CurrentExecuterIndex.e2e2]: 6533,
    [CurrentExecuterIndex.e2e3]: 6534,
    [CurrentExecuterIndex.default]: 6432,
  };
  return testDbPorts[currentExecutorIndex];
```
This way we make sure that all the different cases are handled. (You can test to remove one row, and it will instantly give warning / error that ...Property is missing from type..

This replacement can be used in the other function as well.
___
*[`test-db-manager/src/hasuraApi.ts` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmtMxe0oVppee9nb53:-NS5Vk771yde0dEEOjZu:b-xiycl6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/hasuraApi.ts#L16)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Tried to do this now.
</blockquote></details>

Please extract this to it's own helper function as well just like the other one.
___
*[`test-db-manager/src/hasuraApi.ts` line 15 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5Up-e0azu2CnTWu4F:-NS5Up-e0azu2CnTWu4G:b-foo7hp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/hasuraApi.ts#L15)):*
> ```XML
> 
>   // default instance = thread4, e2e1 = thread1, etc
>   const currentExecutorIndex = process.env.CYPRESS_THREAD || '4';
> ```

'4' here.
___
*[`test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts` line 1 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5TDHR-j7lF0E2Xh7v:-NS5TDHR-j7lF0E2Xh7w:b-a46zsw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts#L1)):*
> ```XML
> export enum CurrentExecutorIndex {
> ```

Maybe add a bit JSDoc comments to explain the usage of this just a little bit. 
___
*[`test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts` line 5 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5V1043CLXbIT0Imkc:-NS5V1043CLXbIT0Imkd:bdi2tox) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts#L5)):*
> ```XML
>   e2e2 = '2',
>   e2e3 = '3',
>   e2e = '4',
> ```

"default" would be better name for this. If I understood this right, the thread is 1-3 for e2e instances and the fourth is for the default (testdb/hasura).


<!-- Sent from Reviewable.io -->

2023-04-04 06:02 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: 15 of 24 files reviewed, 8 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/support/commands.ts` line 82 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5WzJTAhpQZwwSIgMv:-NS9qa-pB6k5TlNRanQV:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/cypress/support/commands.ts#L82)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

'4' here, please use the enum value.
</blockquote></details>

Done.
___
*[`test-db-manager/src/config.ts` line 5 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5T2A66c9hg0B1SEPN:-NS9qdLlByLZCmJp4tIH:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/config.ts#L5)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Still '4' here, you should use the enum value.
</blockquote></details>

Done.
___
*[`test-db-manager/src/config.ts` line 7 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5VquB8wMRepZQ2u0T:-NS9qmoe04lL0oZp_fXf:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/config.ts#L7)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

So this switch case can now be replaced with the Record. 

```
const testDbPorts: Record<CurrentExecuterIndex, number> = {
    [CurrentExecuterIndex.e2e1]: 6532,
    [CurrentExecuterIndex.e2e2]: 6533,
    [CurrentExecuterIndex.e2e3]: 6534,
    [CurrentExecuterIndex.default]: 6432,
  };
  return testDbPorts[currentExecutorIndex];
```
This way we make sure that all the different cases are handled. (You can test to remove one row, and it will instantly give warning / error that ...Property is missing from type..

This replacement can be used in the other function as well.
</blockquote></details>

Done.
___
*[`test-db-manager/src/hasuraApi.ts` line 16 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NRmtMxe0oVppee9nb53:-NS9qsDxDqS8S_TafIHs:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f304bf43822abf57655c0cdedb1f24fb3b6e6269/test-db-manager/src/hasuraApi.ts#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Please extract this to it's own helper function as well just like the other one.
</blockquote></details>

Done.
___
*[`test-db-manager/src/hasuraApi.ts` line 15 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5Up-e0azu2CnTWu4F:-NS9qqdi1wBVfVdvRWQR:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/hasuraApi.ts#L15)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

'4' here.
</blockquote></details>

Done.
___
*[`test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts` line 1 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5TDHR-j7lF0E2Xh7v:-NS9qtKcAoYONNh74wrD:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts#L1)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Maybe add a bit JSDoc comments to explain the usage of this just a little bit. 
</blockquote></details>

Done.
___
*[`test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts` line 5 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5V1043CLXbIT0Imkc:-NS9qtwUCe1MmJeit0Ea:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts#L5)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

"default" would be better name for this. If I understood this right, the thread is 1-3 for e2e instances and the fourth is for the default (testdb/hasura).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-04 08:58 UTC, HenrikHartiala approved these changes
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: all files reviewed, 1 unresolved discussion (waiting on @sr-vala)

___
*[`.github/workflows/run-cypress-tests.yml` line 38 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NSARNjo8SCL-RlOphFk:-NSARNjo8SCL-RlOphFl:b-8xcax8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6be27108411a060b37df6e23484cb21a3ba9d45b/.github/workflows/run-cypress-tests.yml#L38)):*
> ```YAML
>         with:
>           test-tags: ''
>           threads: '3'
> ```

Is my reviewable working it's magic or was this change done in the latest revision? If yes, then why? What does this change do?
___
*[`test-db-manager/src/config.ts` line 1 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NSAT5qe6k3MazK02tR_:-NSAT5qe6k3MazK02tRa:bmx1kbs) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6be27108411a060b37df6e23484cb21a3ba9d45b/test-db-manager/src/config.ts#L1)):*
> ```XML
> import { CurrentExecutorIndex } from './db-helpers/enums/currentExecutorIndex';
> ```

A little bit nitpicking, but you have correctly added the exports to the index -files, so you should be able to remove the last part if there is no dependency cycles.
`import { CurrentExecutorIndex } from './db-helpers/enums';` 
___
*[`test-db-manager/src/hasuraApi.ts` line 2 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NSATK2y-FxJi12SQbF1:-NSATK2y-FxJi12SQbF2:bmx1kbs) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6be27108411a060b37df6e23484cb21a3ba9d45b/test-db-manager/src/hasuraApi.ts#L2)):*
> ```XML
> import fetch from 'cross-fetch';
> import { CurrentExecutorIndex } from './db-helpers/enums/currentExecutorIndex';
> ```

A little bit nitpicking, but you have correctly added the exports to the index -files, so you should be able to remove the last part if there is no dependency cycles.
`import { CurrentExecutorIndex } from './db-helpers/enums';` 
___
*[`test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts` line 1 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NS5TDHR-j7lF0E2Xh7v:-NSASFRH7EeIWXQ44kQW:b-ucfknh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/5093a6f524041203198a23bcfccb38ec59430a5e/test-db-manager/src/db-helpers/enums/currentExecutorIndex.ts#L1)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2023-04-04 09:10 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`.github/workflows/run-cypress-tests.yml` line 38 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NSARNjo8SCL-RlOphFk:-NSAV7t15SBlu5_-O2RY:b-9qv85o) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6be27108411a060b37df6e23484cb21a3ba9d45b/.github/workflows/run-cypress-tests.yml#L38)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Is my reviewable working it's magic or was this change done in the latest revision? If yes, then why? What does this change do?
</blockquote></details>

This workflow goes hand-in-hand with the action changes that were done in jore4-tools. The action was reviewed by Teemu, and I made the change that the action can be called with the amount of threads to be used when running the tests. You can check the related PR here: https://github.com/HSLdevcom/jore4-tools/pull/12


<!-- Sent from Reviewable.io -->

2023-04-04 09:13 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572)* status: 22 of 24 files reviewed, 1 unresolved discussion (waiting on @sr-vala)

___
*[`.github/workflows/run-cypress-tests.yml` line 38 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/572#-NSARNjo8SCL-RlOphFk:-NSAX9s9BRAU9CKulQq4:b-kz3qfi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6be27108411a060b37df6e23484cb21a3ba9d45b/.github/workflows/run-cypress-tests.yml#L38)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

This workflow goes hand-in-hand with the action changes that were done in jore4-tools. The action was reviewed by Teemu, and I made the change that the action can be called with the amount of threads to be used when running the tests. You can check the related PR here: https://github.com/HSLdevcom/jore4-tools/pull/12
</blockquote></details>

Ah, right. this was the one. I already forgot it when I started to review this :D. So all good :+1: 


<!-- Sent from Reviewable.io -->

2023-04-04 11:36 UTC, merged