Add timetable import and export tests
HSLdevcom/jore4-ui pull request #611
Opened 2023-05-30 04:22 UTC by sr-vala

Timetable import and export tests and resources.
Made database config more generic since there are more databases to connect to, and timetables database needs to be truncated in teardowns.

Resolves HSLdevcom/jore4#1011
Resolves HSLdevcom/jore4#1010

2023-06-01 09:15 UTC, HenrikHartiala reviewed
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611)* status: all files reviewed, 18 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/editRoute.cy.ts` line 140 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlF0Vt4kCRvvAhBAEC:-NWlF0Vt4kCRvvAhBAED:b-468ej6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/editRoute.cy.ts#L140)):*
> ```XML
>     editRoutePage.routePropertiesForm.getForm().should('not.exist');
>     cy.visit('/routes');
>     routesAndLinesPage.searchContainer
> ```

This kind of changes `getRoutesAndLinesSearchInput -> searchContainer.getSearchInput()` should be in their own commit, if you still can separate changes that affect existing code in to their own commits, would be nice. 

But if it seems too much hassle and work, then this is fine too. But for future reference, it would be easier to review if these were separated 👍  (All that said, I tend to do the same myself though: too much in to one commit :D)
___
*[`cypress/e2e/timetables.cy.ts` line 60 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlIZIw9XRINR-OSUC4:-NWlIZIw9XRINR-OSUC5:b2ydcrt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L60)):*
> ```XML
> 
> const timingPlaces: TimingPatternTimingPlaceInsertInput[] = [
>   {
> ```

There seems to also be this `buildTimingPlace()` builder in  `entities.ts` if it would assist here.
___
*[`cypress/e2e/timetables.cy.ts` line 216 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlKX3u6gnd_SNVQlYU:-NWlKX3u6gnd_SNVQlYV:b-re9ytj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L216)):*
> ```XML
>   context('Import', () => {
>     it(
>       'Imports a Hastus timetable file',
> ```

This is a bit opionated, but I would prefer that these titles start with "should",  I know that we haven't followed this everywhere always, but maybe we could try to change these towards it (If all agress). (This won't be a blocking comment anyway)

What's your take on this?

Also it could have the "using preview" 
___
*[`cypress/e2e/timetables.cy.ts` line 219 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlcQlT5ODwgnNLkn99:-NWlcQlT5ODwgnNLkn9A:b-u7kv50) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L219)):*
> ```XML
>       { tags: [Tag.Smoke, Tag.Timetables] },
>       () => {
>         const ImportFileName = 'hastusImport.exp';
> ```

This variable could maybe be in SCREAMING_SNAKE_CASE, since it is a const.



_Suggestion:_
```XML
        const IMPORT_FILENAME = 'hastusImport.exp';
```
___
*[`cypress/e2e/timetables.cy.ts` line 221 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlduBr69v4tWc0oUeN:-NWlduBr69v4tWc0oUeO:bboe4q3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L221)):*
> ```XML
>         const ImportFileName = 'hastusImport.exp';
>         timetablesMainPage.getImportButton().click();
>         cy.get('input[type=file]')
> ```

Should we create a function about this? Something like: `importTimetablesPage.selectFile(filename)`. It seems that we only have 2 occurances, but just wondering. But on the bright side, we can "hide" the invoking from this test to the function.
___
*[`cypress/e2e/timetables.cy.ts` line 222 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWldVEqDh5ezGKFKU20:-NWldVEqDh5ezGKFKU21:b-w8kyql) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L222)):*
> ```XML
>         timetablesMainPage.getImportButton().click();
>         cy.get('input[type=file]')
>           // Cypress cannot interact with the input component that is hidden
> ```

Good explanation!

If I remember correctly, it is hidden because we have our own implementation of it :+1: 
___
*[`cypress/e2e/timetables.cy.ts` line 249 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlfStz0LBpwS5RtL3C:-NWlfStz0LBpwS5RtL3D:b-tl0boo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L249)):*
> ```XML
>           'Aikataulujen tuonti onnistui!',
>         );
>         // Check the imported timetable on a Saturday, which is the day type of the imported timetable
> ```

Great comment! Really helps to follow the test flow :ok_hand: 
___
*[`cypress/e2e/timetables.cy.ts` line 275 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlgRx69d_B3wH-udpf:-NWlgRx69d_B3wH-udpg:b-3swoyd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L275)):*
> ```XML
>   });
> 
>   context('Export', () => {
> ```

Do we get some benefits for having these in the same file? Would like to have export tests and import tests in separate files. Currently the "timetables.cy.ts" does not point me towards importing / exporting particularly. In addition the exporting part is actually done in routes module, since we export routes (for hastus to create the timetables)
___
*[`cypress/e2e/timetables.cy.ts` line 282 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlj9WO-g3dUAuUEC66:-NWlj9WO-g3dUAuUEC67:b-vku9mj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L282)):*
> ```XML
> 
>     beforeEach(() => {
>       // Import timetable data that can be exported
> ```

Ok so now I understand a bit better why these are in the same file. But there is a misunderstanding here, we do not export timetables, we export routes.

So the flow is that we have a route which has stops on it's journey. The user first exports the route from jore4 for hastus (third party software). The user then imports the newly exported route file in to hastus and then the user plans the schedules for that route and exports a timetable file. After this the user comes back to jore4 and imports the newly exported timetable file in to jore4.

So the export is actually a pre-action to importing timetables, not the other way around
___
*[`cypress/e2e/timetables.cy.ts` line 308 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWll2y2EWiehjoa_3DL:-NWll2y2EWiehjoa_3DM:b-529zi5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L308)):*
> ```XML
>     });
> 
>     it('Exports a timetable of a line', { tags: [Tag.Timetables] }, () => {
> ```

So I think you can save this test, just change these names. Also if it makes more sense, you could use the routes and lines list when choosing the route or line to be exported, but either is fine since it is possible to do from both. 
___
*[`cypress/e2e/timetables.cy.ts` line 312 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWllush2TeSikulDdvR:-NWllush2TeSikulDdvS:b7nbjmj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L312)):*
> ```XML
>       cy.visit('/timetables');
>       timetablesMainPage.searchContainer.getChevron().click();
>       timetablesMainPage.searchContainer.priorityCondition
> ```

Since we are at first iteration of MVP stage and the exporting requires to change the priority option in search criteria (which is really not nice). We could maybe add a comment here that we actually uncheck the temporary priority here.

I hope that at some point we get an enhancement which makes this flow more clear and better UX, but until then the comment would help!
___
*[`cypress/e2e/timetables.cy.ts` line 317 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlmox_Ati [...]

2023-06-02 09:44 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611)* status: all files reviewed, 16 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/e2e/timetables.cy.ts` line 216 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlKX3u6gnd_SNVQlYU:-NWuEYIrCHLhIHFrdbbQ:bihxn1c) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L216)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This is a bit opionated, but I would prefer that these titles start with "should",  I know that we haven't followed this everywhere always, but maybe we could try to change these towards it (If all agress). (This won't be a blocking comment anyway)

What's your take on this?

Also it could have the "using preview" 
</blockquote></details>

I find the it('') convention weird altogether. No preference regarding 'Should', really.
___
*[`cypress/e2e/timetables.cy.ts` line 219 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlcQlT5ODwgnNLkn99:-NWuFZl2ApXQdjTLUzNb:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L219)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This variable could maybe be in SCREAMING_SNAKE_CASE, since it is a const.
</blockquote></details>

Done.
___
*[`cypress/e2e/timetables.cy.ts` line 249 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlfStz0LBpwS5RtL3C:-NWuFmje5PUngz16poFT:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L249)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Great comment! Really helps to follow the test flow :ok_hand: 
</blockquote></details>

Done.
___
*[`cypress/e2e/timetables.cy.ts` line 275 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlgRx69d_B3wH-udpf:-NWuFxJKANV5mEi956cJ:brsj13f) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L275)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Do we get some benefits for having these in the same file? Would like to have export tests and import tests in separate files. Currently the "timetables.cy.ts" does not point me towards importing / exporting particularly. In addition the exporting part is actually done in routes module, since we export routes (for hastus to create the timetables)
</blockquote></details>

Biggest benefit was not having to repeat 212 lines of setup code.
___
*[`cypress/e2e/timetables.cy.ts` line 282 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlj9WO-g3dUAuUEC66:-NWuM9vk8Q_8DLqgTEqS:b7ohrh1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L282)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ok so now I understand a bit better why these are in the same file. But there is a misunderstanding here, we do not export timetables, we export routes.

So the flow is that we have a route which has stops on it's journey. The user first exports the route from jore4 for hastus (third party software). The user then imports the newly exported route file in to hastus and then the user plans the schedules for that route and exports a timetable file. After this the user comes back to jore4 and imports the newly exported timetable file in to jore4.

So the export is actually a pre-action to importing timetables, not the other way around
</blockquote></details>

I somehow missed this flow entirely. Maybe my brain just wanted to believe that such awkward workflows don't exist.
___
*[`cypress/e2e/timetables.cy.ts` line 308 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWll2y2EWiehjoa_3DL:-NWutB6K3omil_96oaDM:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L308)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

So I think you can save this test, just change these names. Also if it makes more sense, you could use the routes and lines list when choosing the route or line to be exported, but either is fine since it is possible to do from both. 
</blockquote></details>

Done.
___
*[`cypress/e2e/timetables.cy.ts` line 312 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWllush2TeSikulDdvR:-NWuN3Ku-yp7A-y3joNv:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L312)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Since we are at first iteration of MVP stage and the exporting requires to change the priority option in search criteria (which is really not nice). We could maybe add a comment here that we actually uncheck the temporary priority here.

I hope that at some point we get an enhancement which makes this flow more clear and better UX, but until then the comment would help!
</blockquote></details>

Done.
___
*[`cypress/e2e/timetables.cy.ts` line 323 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlmug7D11c1H3h4gk9:-NWuNYEEECl6B8GKlyM7:b-jdxd8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L323)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think we need to figure some way of validating the exported file, for example, we maybe could pre-create an export file and then compare this exported file to the pre-created one etc.
</blockquote></details>

The issue written by Tamas mentions: "check the contents of the generated csv on a very high level that it makes sense. (The detailed csv content checking happens in the jore4-hastus repository's integration tests)." We're not checking the database, but is checking all of the file necessary?
___
*[`cypress/e2e/utils/tasks.ts` line 66 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWpxKfY99wQ_tXoOIxt:-NWuOU3VE3aUtmSOwh9P:b5i2coo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/utils/tasks.ts#L66)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Should this be here? Or should it be some cyrpess-logging etc.?
</blockquote></details>

It can be removed if you feel it is better to log nothing. Logging to Cypress does not work from tasks, at least directly.
___
*[`cypress/pageObjects/ImportTimetablesPage.ts` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWpz6dp0NjXWUksQT4x:-NWutnUXAJloW97_0I9n:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/pageObjects/ImportTimetablesPage.ts#L14)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Maybe this could be just `clickPreviewButton`?
</blockquote></details>

Done.
___
*[`cypress/pageObjects/index.ts` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWq42WL4rBr6dBh1NUx:-NWuSAXbDooeaAzMMztd:b-7qdq4l) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/pageObjects/index.ts#L1)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

FYI: noticed that the pageObjects folder has no deeper structure, so some kind of reasonable folder structure would be in place, so it wouldn't be so cluttered up :+1: . But I think that deserves a separate PR.
</blockquote></details>

I commented about this when I started in the project, since there was always going to be more page objects, but Tuomas did not find a deeper structure necessary back t [...]

2023-06-05 05:43 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611)* status: 30 of 43 files reviewed, 16 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/e2e/editRoute.cy.ts` line 140 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlF0Vt4kCRvvAhBAEC:-NX925Ar0p97pG88AQ1U:bwipk27) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/editRoute.cy.ts#L140)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This kind of changes `getRoutesAndLinesSearchInput -> searchContainer.getSearchInput()` should be in their own commit, if you still can separate changes that affect existing code in to their own commits, would be nice. 

But if it seems too much hassle and work, then this is fine too. But for future reference, it would be easier to review if these were separated 👍  (All that said, I tend to do the same myself though: too much in to one commit :D)
</blockquote></details>

Tried to find out how to separate already committed files into their own commit, but I would probably mess up something with Git in the process, so if it's ok I would leave this as is. I'll keep this in mind in the future.
___
*[`cypress/e2e/timetables.cy.ts` line 60 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlIZIw9XRINR-OSUC4:-NX93utU6fxOvbO4OPVk:bwcyh9e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L60)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

There seems to also be this `buildTimingPlace()` builder in  `entities.ts` if it would assist here.
</blockquote></details>

Couldn't figure out how buildTimingPlace is used or how it helps. It's not used anywhere, so is it dead code?


<!-- Sent from Reviewable.io -->

2023-06-06 14:00 UTC, HenrikHartiala requested changes
> Reviewed 12 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611)* status: 42 of 43 files reviewed, 7 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/editRoute.cy.ts` line 140 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlF0Vt4kCRvvAhBAEC:-NXF2Q9MCUfmK8shQ1YZ:brn31t8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/editRoute.cy.ts#L140)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Tried to find out how to separate already committed files into their own commit, but I would probably mess up something with Git in the process, so if it's ok I would leave this as is. I'll keep this in mind in the future.
</blockquote></details>

Yeah it is okay to not separate these if doubting. If you want to practice, just create another branch where you can do all the changes you want. I can give a couple of examples in slack about how to do it.
___
*[`cypress/e2e/hastusExport.cy.ts` line 159 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NXFmkgj1suNDFA4F0TI:-NXFmkgj1suNDFA4F0TJ:b-9batg8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7366c015728730b8c1c444faddc6ea5f84ede4e4/cypress/e2e/hastusExport.cy.ts#L159)):*
> ```XML
>   let routesAndLinesPage: RoutesAndLinesPage;
> 
>   const exportDate = DateTime.now().toFormat('yyyy-MM-dd');
> ```

This can be simplified



_Suggestion:_
```XML
  const exportDate = DateTime.now().toISODate();
```
___
*[`cypress/e2e/utils/tasks.ts` line 66 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWpxKfY99wQ_tXoOIxt:-NXFxv7yCRMoLIVtLwx7:b-pjtaih) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/utils/tasks.ts#L66)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

It can be removed if you feel it is better to log nothing. Logging to Cypress does not work from tasks, at least directly.
</blockquote></details>

I was just curious if it was supposed to be there, or left over from some testing :D If it brings valuable info then by all means.
___
*[`cypress/pageObjects/index.ts` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWq42WL4rBr6dBh1NUx:-NXFyHQy0eub6tEBtWg8:b-wtp43r) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/pageObjects/index.ts#L1)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I commented about this when I started in the project, since there was always going to be more page objects, but Tuomas did not find a deeper structure necessary back then.
</blockquote></details>

Yeah, maybe Tuomas had some other plans or vision how the page objects would look like back then. But as it is now pretty clear that it would benefit from a deeper folder structure, I think we should clean it up when have the time :+1: 
___
*[`cypress/pageObjects/Navbar.ts` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWq-lsw0DEL0ftxg-GV:-NXFzB381AAR4Aa8WTlR:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/pageObjects/Navbar.ts#L6)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

We can use the link to get to the timetables page. Users will probably use it rather than type the url.
</blockquote></details>

:+1: 
___
*[`cypress/e2e/timetableImport.cy.ts` line 224 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NXFw3IQ9idVRejW8FzN:-NXFw3IQ9idVRejW8FzO:b-gns9qz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7366c015728730b8c1c444faddc6ea5f84ede4e4/cypress/e2e/timetableImport.cy.ts#L224)):*
> ```XML
>       const IMPORT_FILENAME = 'hastusImport.exp';
>       timetablesMainPage.getImportButton().click();
>       importTimetablesPage.selectFileToImport(`${IMPORT_FILENAME}`);
> ```

You can remove the template literals now that it is only the filename



_Suggestion:_
```XML
      importTimetablesPage.selectFileToImport(IMPORT_FILENAME);
```
___
*[`cypress/e2e/timetables.cy.ts` line 60 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlIZIw9XRINR-OSUC4:-NXFucgc7SIWedBNfzuh:b2kjtm8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L60)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Couldn't figure out how buildTimingPlace is used or how it helps. It's not used anywhere, so is it dead code?
</blockquote></details>

Yep, it is not used anywhere so currently it is dead code. But I think it was build in front for cases where the timingPlaces need to be built. You could use it for example something like this:
```
const timingPlaces = [
  buildTimingPlace('78ee94c3-e856-4fdc-89ad-10b72cadb444', '1AACKT'),
  buildTimingPlace('f8a93c6f-5ef7-4b09-ae5e-0a04ea8597e9', '1ELIMK'),
  buildTimingPlace('5240633b-5c94-49c1-b1c2-26e9d61a01cd', '1AURLA')
]
```
Or modify it to have an optional description, if you want to give it e.g. a specific description. But if you see no value in using this builder then it is ok to leave it as it is. Up to you
___
*[`cypress/e2e/timetables.cy.ts` line 282 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlj9WO-g3dUAuUEC66:-NXFwp414GN6neF97_q-:b-u8j7j5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L282)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I somehow missed this flow entirely. Maybe my brain just wanted to believe that such awkward workflows don't exist.
</blockquote></details>

Yeah, thats the cost when "integrating" to a desktop software which only communicates with files :D 
___
*[`cypress/e2e/timetables.cy.ts` line 323 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlmug7D11c1H3h4gk9:-NXFxSRT8W65OQiAEsmm:btam3jj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L323)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

The issue written by Tamas mentions: "check the contents of the generated csv on a very high level that it makes sense. (The detailed csv content checking happens in the jore4-hastus repository's integration tests)." We're not checking the database, but is checking all of the file necessary?
</blockquote></details>

Ah, if the content of the exported file is validated in hastus tests, then it should be okay. Maybe add a comment about the more specific file test in hastus


<!-- Sent from Reviewable.io -->

2023-06-07 07:13 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611)* status: 42 of 43 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/e2e/editRoute.cy.ts` line 140 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlF0Vt4kCRvvAhBAEC:-NXJgtutCauJWP5dxomz:bpeyc9c) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/editRoute.cy.ts#L140)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yeah it is okay to not separate these if doubting. If you want to practice, just create another branch where you can do all the changes you want. I can give a couple of examples in slack about how to do it.
</blockquote></details>

I'll do some experimentation in another branch.
___
*[`cypress/e2e/hastusExport.cy.ts` line 159 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NXFmkgj1suNDFA4F0TI:-NXJQY7M6TGQIIs9UU7s:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7366c015728730b8c1c444faddc6ea5f84ede4e4/cypress/e2e/hastusExport.cy.ts#L159)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This can be simplified
</blockquote></details>

Done.
___
*[`cypress/e2e/utils/tasks.ts` line 66 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWpxKfY99wQ_tXoOIxt:-NXJb7Iw-0e1CkMURwOT:b-6r1oco) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/utils/tasks.ts#L66)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I was just curious if it was supposed to be there, or left over from some testing :D If it brings valuable info then by all means.
</blockquote></details>

I think it can be left out. Digging for console logs is not really convenient.
___
*[`cypress/e2e/timetableImport.cy.ts` line 224 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NXFw3IQ9idVRejW8FzN:-NXJQd7v2o6vs-xiwnc8:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/7366c015728730b8c1c444faddc6ea5f84ede4e4/cypress/e2e/timetableImport.cy.ts#L224)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

You can remove the template literals now that it is only the filename
</blockquote></details>

Done.
___
*[`cypress/e2e/timetables.cy.ts` line 282 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlj9WO-g3dUAuUEC66:-NXJQefZ4YjFPOlcE4jJ:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L282)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yeah, thats the cost when "integrating" to a desktop software which only communicates with files :D 
</blockquote></details>

Done.
___
*[`cypress/e2e/timetables.cy.ts` line 323 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlmug7D11c1H3h4gk9:-NXJaxWSAcdDVDQND4Uo:b-hueahc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L323)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah, if the content of the exported file is validated in hastus tests, then it should be okay. Maybe add a comment about the more specific file test in hastus
</blockquote></details>

This was pretty easy to do in Cypress, so I added it now.


<!-- Sent from Reviewable.io -->

2023-06-08 08:20 UTC, HenrikHartiala requested changes
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611)* status: 43 of 44 files reviewed, 4 unresolved discussions (waiting on @sr-vala)

___
*[`-- commits` line 3 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NXP2_keABIW4WfdzPDE):*
NIT: could be precisely "Refactor RoutesAndLinesPage page object.

But otherwise nice!
___
*[`cypress/e2e/hastusExport.cy.ts` line 216 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NXP3Q_O4B0oP_rRGHBp:-NXP3Q_O4B0oP_rRGHBq:btojbfd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65848b3ced5b4ec57dbdf9462f5628a6a1c791f0/cypress/e2e/hastusExport.cy.ts#L216)):*
> ```XML
>       cy.wait('@hastusExport').its('response.statusCode').should('equal', 200);
>       cy.readFile(exportFilePath).then((exportedFile) => {
>         cy.readFile(comparisonExportFilePath).should('eq', exportedFile);
> ```

Great!
___
*[`cypress/e2e/utils/tasks.ts` line 66 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWpxKfY99wQ_tXoOIxt:-NXP4X9S1vM6mMsD-RU3:b-w1pi47) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/utils/tasks.ts#L66)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I think it can be left out. Digging for console logs is not really convenient.
</blockquote></details>

check :+1: 
___
*[`cypress/e2e/timetableImport.cy.ts` line 198 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NXP3qUd-eJCK98Ubf55:-NXP3qUd-eJCK98Ubf56:b-g9vxde) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65848b3ced5b4ec57dbdf9462f5628a6a1c791f0/cypress/e2e/timetableImport.cy.ts#L198)):*
> ```XML
>     cy.mockLogin();
>     cy.visit('/');
>     navbar.getTimeTablesLink().click();
> ```

Ah, sorry did not notice this earlier, but timetable is one word, so I would change this to:



_Suggestion:_
```XML
    navbar.getTimetablesLink().click();
```
___
*[`cypress/e2e/timetables.cy.ts` line 323 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NWlmug7D11c1H3h4gk9:-NXP4TKtB5rZDDVXYlBV:btojbfd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/47bff2d7c18b95629d60488f16750eaa80c34d3d/cypress/e2e/timetables.cy.ts#L323)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

This was pretty easy to do in Cypress, so I added it now.
</blockquote></details>

Great!


<!-- Sent from Reviewable.io -->

2023-06-08 09:35 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611)* status: 43 of 44 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/e2e/hastusExport.cy.ts` line 216 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NXP3Q_O4B0oP_rRGHBp:-NXPFQaE91rteqCvbh2F:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65848b3ced5b4ec57dbdf9462f5628a6a1c791f0/cypress/e2e/hastusExport.cy.ts#L216)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Great!
</blockquote></details>

Done.
___
*[`cypress/e2e/timetableImport.cy.ts` line 198 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-NXP3qUd-eJCK98Ubf55:-NXPF_RI6ee9LEJQ3r9b:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/65848b3ced5b4ec57dbdf9462f5628a6a1c791f0/cypress/e2e/timetableImport.cy.ts#L198)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah, sorry did not notice this earlier, but timetable is one word, so I would change this to:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-12 10:04 UTC, HenrikHartiala approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/611#-:-NXj30055LVCRt-MwJyk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sr-vala)



<!-- Sent from Reviewable.io -->

2023-06-12 10:13 UTC, merged