Add substitute operating period
HSLdevcom/jore4-ui pull request #627
Opened 2023-06-27 05:59 UTC by Perholehto

2023-07-25 14:41 UTC, HenrikHartiala requested changes
> Reviewed 1 of 2 files at r1, 48 of 48 files at r2.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627)* status: 48 of 49 files reviewed, 37 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 13 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBa-Gs6ULSmT2nRdbi:-NaBa-Gt3wBwVCGWUrxq:b9u8fp5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L13)):*
> ```XML
> };
> // eslint-disable-next-line @typescript-eslint/ban-types
> export const EnumMultiSelectDropdown = <TEnum extends Object>({
> ```

Out of curiosity, could we use `<TEnum extends object>` (lower case)? We could get rid of the eslint disable, but not sure if this achieves the same thing.
___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 49 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBbhKz3IsXsuAzSfT_:-NaBbhKz3IsXsuAzSfTa:b417z28) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L49)):*
> ```XML
>   });
> 
>   const getButtonContent = (inputValue: string | undefined): string => {
> ```

Can the inputValue be optional, or does it need to be set, just undefined is one of the options?



_Suggestion:_
```XML
  const getButtonContent = (inputValue?: string): string => {
```
___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 51 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBc3deENwJF9ukQXOD:-NaBc3deENwJF9ukQXOE:b-34xjug) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L51)):*
> ```XML
>   const getButtonContent = (inputValue: string | undefined): string => {
>     const enumValues = inputValue?.split(',');
>     if (isUndefined(enumValues) || first(enumValues) === '') return placeholder;
> ```

I personally don't like one liner if's because they make the flow of the function a bit hard to read. I suggest using explicit scopes.



_Suggestion:_
```XML
    if (isUndefined(enumValues) || first(enumValues) === ''){
      return placeholder;
    }
```
___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 51 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBfTOM4PQD01tyLz3O:-NaBfTOM4PQD01tyLz3P:b-ohywgk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L51)):*
> ```XML
>   const getButtonContent = (inputValue: string | undefined): string => {
>     const enumValues = inputValue?.split(',');
>     if (isUndefined(enumValues) || first(enumValues) === '') return placeholder;
> ```

Also, not sure if it's error prone if we just check the first value. One could be that we just. But I mean, that is not that readable, but it would also check that the there is no values at all. 
Well, this was really just thinking aloud and I think this is fine like this. If you get ideas from this then by all means.



_Suggestion:_
```XML
    if(!enumValues?.filter(Boolean).length) {
      return placeholder;
    }
```
___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 65 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBhOvU6zno9i1KdnqG:-NaBhOvU6zno9i1KdnqH:b-dfzt7z) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L65)):*
> ```XML
>     <MultiSelectListbox
>       id={id}
>       testId={testId || testIds.enumDropdown}
> ```

Kind of not part of this PR. since this is used in other places as well, but I was thinking that should we actually enforce giving the testId? Because is same page has two similar components, and neither of them have testId set, then we have two same testId's, and that may not be so nice.

What do you think?
___
*[`ui/src/components/forms/common/InputLabel.tsx` line 26 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBiOBZ303PvI1DL0yI:-NaBiOBZ303PvI1DL0yJ:b9vac2f) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/InputLabel.tsx#L26)):*
> ```XML
>   return (
>     <label className={className} htmlFor={`${translationPrefix}.${fieldPath}`}>
>       {t(`${translationPrefix}.${fieldPath.replace(/\.\d+/, '')}`)}
> ```

Why is this change done? It refactors existing code, does it deserve its own commit to be sure?
___
*[`ui/src/components/forms/timetables/LineTypeMultiSelectDropdown.tsx` line 9 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBjESL2wJk7URGrioo:-NaBjESL2wJk7URGriop:btg064g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/timetables/LineTypeMultiSelectDropdown.tsx#L9)):*
> ```XML
> interface Props extends FormInputProps {
>   id?: string;
>   testId?: string;
> ```

Same thing here, we could enforce the testId
___
*[`ui/src/components/forms/timetables/ObservationPeriodForm.tsx` line 9 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBppEZ-JqTR86LyMKH:-NaBppEZ-JqTR86LyMKI:b6x68no) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/timetables/ObservationPeriodForm.tsx#L9)):*
> ```XML
> 
> const testIds = {
>   startDate: 'TimetableFilterForm::startDate',
> ```

Ah, we should name the testId's matching the components name: https://github.com/HSLdevcom/jore4-ui#test-ids



_Suggestion:_
```XML
  startDate: 'ObservatoinPeriodForm::startDate',
```
___
*[`ui/src/components/forms/timetables/ObservationPeriodForm.tsx` line 31 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBmPjq0bNaJ9YSRHgH:-NaBmPjq0bNaJ9YSRHgI:b-x2bn7j) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/timetables/ObservationPeriodForm.tsx#L31)):*
> ```XML
>   return (
>     <>
>       <FormRow mdColumns={9}>
> ```

Hmm, I am not sure if this is the best way for the layout, because now we have this "ObservationPeriodForm" but it will always take the whole row. It would be better that the layout of the components inside of ObservationPeriodForm are defined in this component, but the "larger" layout is defined in the parent element.

And if you change this to be just <Row>, then maybe you also need to return a div, not an empty fragment, or the layout breaks again.

If this was confusing description, then let's take a telco :D 
___
*[`ui/src/components/forms/timetables/ObservationPeriodForm.tsx` line 57 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBrYvw8H-jYKF8_KXK:-NaBrYvw8H-jYKF8_KXL:bkf61dh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/timetables/ObservationPeriodForm.tsx#L57)):*
> ```XML
>         title={t('confirmReferenceDayFilterDialog.title')}
>         description={t('confirmReferenceDayFilterDialog.description')}
>         buttons={[
> ```

We have tried to avoid inline codes, this is somewhat confusing. But the confusion is minorly part of the component used here as well. Maybe it's the naming or something :D.
I guess this is kind of a warningPopUp which prevents changing the date? But if it always prevents it, could we rather just disable them when the form is dirty?

I do not have the silver bullet here, but it for me It feels like they (observation date range inputs) should be rather disabled and somehow indicated that "finish changes before changing the observation date range". 

If decided to change this, I also accept doing this iteratively, I believe it has been a long journey with this one for you already :D so I don't want to  [...]

2023-07-25 14:51 UTC, HenrikHartiala requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627)* status: 48 of 49 files reviewed, 38 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayForm.tsx` line 132 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCWt-c-YrXsTgiOO9U:-NaCWt-c-YrXsTgiOO9V:bycksqc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/59ae4fa11f12b6435a2b8a2e6754f827212c9459/ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayForm.tsx#L132)):*
> ```XML
>             </SimpleButton>
>           </Row>
>           <Row className="my-8 justify-end space-x-4">
> ```

This Cancel and Save button are always enabled. I think they should be disabled as long as the sections form is not "dirty"


<!-- Sent from Reviewable.io -->

2023-07-31 10:50 UTC, HenrikHartiala requested changes
> Reviewed 1 of 1 files at r3, 35 of 35 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627)* status: all files reviewed, 12 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 13 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBa-Gs6ULSmT2nRdbi:-Naf0weCAaRI8ONmHKJC:brmux6m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L13)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

It would be a good change but our EnumTypes don't work with `object`
</blockquote></details>

Check!
___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 51 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBc3deENwJF9ukQXOD:-Naf14iI7uH6gvWd8iNR:b8n9lmz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L51)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Is this only a personal opinion or is this a team-wide convention? One line if's were a thing in my old job... I don't personally have a strong feeling about this. Will fix these tho.
</blockquote></details>

It is my personal opinion, but I haven't seen them very often and also at least think I have a good reason why not to use them :D. The readability suffers and also harder to debug or make extensions to the if, because you would like to add a console.log for example, you would need to create the block first. Or even worse scenario is that you don't notice that it does not have a scope, and you just add a console log right below the if-clause thinking it is inside the if.

But I can also add an eslint rule about this, so then it would be a strict convention :D 

Anyway, thanks for the fix!
___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 51 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBfTOM4PQD01tyLz3O:-Naf2znI2g6_HYqM9T-y:bjebfwy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L51)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I didn't get your point, maybe eli5 in call? 

todo tarkista vielä enumValues:n pituus
</blockquote></details>

This might still be missing. I think we discussed this to be something like this.



_Suggestion:_
```XML
    if (isUndefined(enumValues) || (first(enumValues) === '' && !!enumValues.length))
```
___
*[`ui/src/components/forms/common/InputLabel.tsx` line 26 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBiOBZ303PvI1DL0yI:-Naf3lBtD_E6Gv7mdANX:b-wdj8zi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/InputLabel.tsx#L26)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Added to own commit
</blockquote></details>

Nice, thanks!
___
*[`ui/src/components/forms/timetables/LineTypeMultiSelectDropdown.tsx` line 9 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBjESL2wJk7URGrioo:-Naf4BEiCOLXF6HxSBLV:bi9estx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/timetables/LineTypeMultiSelectDropdown.tsx#L9)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

done
</blockquote></details>

:pray: 
___
*[`ui/src/components/forms/timetables/ObservationPeriodForm.tsx` line 31 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBmPjq0bNaJ9YSRHgH:-NafA5Hn3Ni0WjoKxI98:b-n4ff02) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/timetables/ObservationPeriodForm.tsx#L31)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

No `div`s but refactored, what do you think?
</blockquote></details>

Better, but I think there seems to still be some issues with the the outer layout. I can demo this in a telco :+1: 
___
*[`ui/src/components/forms/timetables/ObservationPeriodForm.tsx` line 57 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBrYvw8H-jYKF8_KXK:-NafAUTkEq7XeDYEZ4GV:b-3ymtqy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/timetables/ObservationPeriodForm.tsx#L57)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

removed...
</blockquote></details>

Thanks, I think this warning text and disable results in better UX than to enforce the user to first click the date to notice that it can't be changed.
___
*[`ui/src/components/timetables/main/TimetablesMainPage.tsx` line 9 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCFwf_5wiZqkokMNQN:-NafBZPyCSUJ8cSy2Lm2:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/timetables/main/TimetablesMainPage.tsx#L9)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Let's see where this goes!
</blockquote></details>

:+1: 
___
*[`ui/src/components/timetables/main/TimetablesMainPage.tsx` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCGzqq1TNMVDj-deZv:-NafBfK87pTtuMDSFHpN:b-wdj8zi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/timetables/main/TimetablesMainPage.tsx#L16)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Went with the `period`
</blockquote></details>

Nice, thanks!
___
*[`ui/src/hooks/reference-days/useEditSubstituteOperatingPeriod.ts` line 49 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NafU4zSDiHdqzf6rH_L:-NafU4zSDiHdqzf6rH_M:b-7ne4oc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a4546c776f2326dcecf30c7173898eb540737134/ui/src/hooks/reference-days/useEditSubstituteOperatingPeriod.ts#L49)):*
> ```XML
> `;
> 
> // export const useEditSubstituteOperatingPeriod = () => {
> ```

commented code
___
*[`ui/src/hooks/reference-days/useGetSubstituteOperatingPeriod.ts` line 42 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCKjvw-E9t6uEdCD3N:-NafUphI90pX2xJGoz7H:b81yleo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/hooks/reference-days/useGetSubstituteOperatingPeriod.ts#L42)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

This hook is refactored and should have functionality what the name suggests.
</blockquote></details>

Seems clear!
___
*[`ui/src/uiComponents/Combobox.tsx` line 6 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCQBF94_yXS34sbzY_:-NafV97Z05ssEuHR2dsC:b-ucfknh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/uiComponents/Combobox.tsx#L6)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Added to own commit
</blockquote></details>

Thanks!
___
*[`ui/src/uiComponents/MultiSelectListbox.tsx` line 46 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCTE0u3qigN_QtGeta:-NafWOkf45GCwMQYmHDt:b-clwlb2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/uiComponents/MultiSelectListbox.tsx#L46)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Tried to refactor this. What you think?
</blockquote></details>

Yep, nice. I think it is more clear what happens here! :ok_hand: 
___
*[`ui/src/uiComponents/MultiSelectListbox.spec.tsx` line 17 at r2](https [...]

2023-08-07 10:27 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627)* status: 36 of 58 files reviewed, 11 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 51 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBfTOM4PQD01tyLz3O:-NbDrseAB603c_4mAx7N:bb7f2mf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L51)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This might still be missing. I think we discussed this to be something like this.
</blockquote></details>

done
___
*[`ui/src/components/forms/timetables/ObservationPeriodForm.tsx` line 31 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBmPjq0bNaJ9YSRHgH:-NbDugqM7kOBSj5FiAsC:begw0lt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/timetables/ObservationPeriodForm.tsx#L31)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Better, but I think there seems to still be some issues with the the outer layout. I can demo this in a telco :+1: 
</blockquote></details>

How about now?
___
*[`ui/src/components/forms/timetables/ObservationPeriodForm.tsx` line 57 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBrYvw8H-jYKF8_KXK:-NajitGw-QIUzNnEI3D7:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/forms/timetables/ObservationPeriodForm.tsx#L57)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Thanks, I think this warning text and disable results in better UX than to enforce the user to first click the date to notice that it can't be changed.
</blockquote></details>

Done.
___
*[`ui/src/uiComponents/index.ts` line 13 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCQSU75pv54J-BX04y:-Najjl9m01olmedqc3pY:b-htipa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/uiComponents/index.ts#L13)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

should the newly created ListBoxOptions and ListBoxButton be here as well?
</blockquote></details>

These are added
___
*[`ui/src/uiComponents/MultiSelectListbox.spec.tsx` line 17 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCTdfIDW8Vy8RXcLKJ:-NbDsZzTDrDwBtlX_1Ad:b-4ro67e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/uiComponents/MultiSelectListbox.spec.tsx#L17)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I think the todo is missing 
</blockquote></details>

Now it's really added :) 
___
*[`ui/src/components/timetables/day-settings/DaySettingsPage.tsx` line 12 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaBu5gI1ToEhLMp8mK-:-Najl5qT6gZli4apTPWj:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/timetables/day-settings/DaySettingsPage.tsx#L12)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

The new component name does not reflect to the testId anymore, pretty classic fix & refactor :D 
</blockquote></details>

Done.
___
*[`ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayForm.tsx` line 87 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaC0oZa2Qx7qEvogbmE:-NajjCf-8IEXCNkal7VK:bt3qw7c) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayForm.tsx#L87)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Thanks!
I dont think we have a strict guideline for this, because we also have some state information in the query parameters, which makes it kind of situational. But maybe the cases where you need the information in multiple components, and it is something we do not want to put in query parameters. So the case where you would need to pass the information through components.

</blockquote></details>

Maybe this is shady for me because we have those query parameters and I'm not yet used to those :D
___
*[`ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayForm.tsx` line 132 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCWt-c-YrXsTgiOO9U:-NbDus8I3A3j4T_-NSQc:by4ypgr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/59ae4fa11f12b6435a2b8a2e6754f827212c9459/ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayForm.tsx#L132)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This is now better UX in my opinion, but found one case where it did not work and here are the steps to reproduce:
* Add new period for today
* SAve period (here it works fine, the buttons go disabled after save)
* add another period for let's say tomorrow
* save
Result: SAving succesful, but the form seems to be dirty and the buttons won't go back to disabled.
</blockquote></details>

This should be now fixed. I made changed that we discussed in telco. I can demo this if needed.
___
*[`ui/src/hooks/reference-days/useEditSubstituteOperatingPeriod.ts` line 49 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NafU4zSDiHdqzf6rH_L:-NajkdGP23v62ancbg4K:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a4546c776f2326dcecf30c7173898eb540737134/ui/src/hooks/reference-days/useEditSubstituteOperatingPeriod.ts#L49)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

commented code
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-10 14:26 UTC, HenrikHartiala requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627)* status: 36 of 58 files reviewed, 12 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/forms/common/EnumDropdown.tsx` line 65 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbUc2yMDkGOPjTTRBAX:-NbUc2yMDkGOPjTTRBAY:b-7ijr36) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ace284907a8c22ee92c782ad8d93ee425ffed0fd/ui/src/components/forms/common/EnumDropdown.tsx#L65)):*
> ```XML
>         value ? uiNameMapper(value as unknown as TEnum) : placeholder
>       }
>       buttonClassNames={disabled ? 'input-disabled' : ''}
> ```

This should not be necessary to add the buttonClassName here as well. It should be enough to give the `disabled` attribute.

I dove to HUI.ListboxButton, which takes the disabled as paramtere, but for some reason it does not make the button look like disabled which is unfortunate. (Or I did something wrong). There might be another way of making this also visually disabled. 

In any case, I'd at least bake the className logic inside the actual component getting disabledw, instead of putting it here and then passing it through the components.
___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 73 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbUgMFw2O-hVQSHNYfH:-NbUgMFw2O-hVQSHNYfI:bjturct) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ace284907a8c22ee92c782ad8d93ee425ffed0fd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L73)):*
> ```XML
>       testId={testId || testIds.enumDropdown}
>       buttonContent={getButtonContent(value)}
>       buttonClassNames={disabled ? 'input-disabled' : ''}
> ```

Same thing here, so you should not need to give the component both: the class and the `disabled` value.


<!-- Sent from Reviewable.io -->

2023-08-11 11:50 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627)* status: 34 of 58 files reviewed, 12 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/forms/common/EnumMultiSelectDropdown.tsx` line 73 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbUgMFw2O-hVQSHNYfH:-NbZQXV_5fL4bT-Av9U_:bgzf9g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ace284907a8c22ee92c782ad8d93ee425ffed0fd/ui/src/components/forms/common/EnumMultiSelectDropdown.tsx#L73)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Same thing here, so you should not need to give the component both: the class and the `disabled` value.
</blockquote></details>

`disabled` comes from `formInputProps`
___
*[`ui/src/components/forms/common/EnumDropdown.tsx` line 65 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbUc2yMDkGOPjTTRBAX:-NbYPj_g93A5eTHx82Lh:bedhnrf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ace284907a8c22ee92c782ad8d93ee425ffed0fd/ui/src/components/forms/common/EnumDropdown.tsx#L65)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This should not be necessary to add the buttonClassName here as well. It should be enough to give the `disabled` attribute.

I dove to HUI.ListboxButton, which takes the disabled as paramtere, but for some reason it does not make the button look like disabled which is unfortunate. (Or I did something wrong). There might be another way of making this also visually disabled. 

In any case, I'd at least bake the className logic inside the actual component getting disabledw, instead of putting it here and then passing it through the components.
</blockquote></details>

I took a second look about `HUI.Listbox` that component takes `disabled` prop and should disable the input. I tested this with an example from their site  (https://headlessui.com/react/listbox#basic-example) by pasting that example to our code base. When I passed `disabled` as true, the input was disabled.

I think problem in our implementation is that we  use`buttonContent` and disabled prop will never get there.


<!-- Sent from Reviewable.io -->

2023-08-14 09:42 UTC, HenrikHartiala requested changes
> Reviewed 16 of 22 files at r5, 3 of 8 files at r6, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627)* status: 50 of 58 files reviewed, 5 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/hooks/urlQuery/useTimeRangeQueryParams.ts` line 30 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbnIg6DBbVs4WelpVBU:-NbnIg6DBbVs4WelpVBV:bxjnewn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d18ec2c591a4695fb532722e59aef020c149dc64/ui/src/hooks/urlQuery/useTimeRangeQueryParams.ts#L30)):*
> ```XML
>     start: DateTime,
>     end: DateTime,
>     showToast = true,
> ```

discussed f2f, probably not needed.
___
*[`ui/src/components/forms/common/EnumDropdown.tsx` line 65 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbUc2yMDkGOPjTTRBAX:-NbnPCYg2H8ebEZ5VFUd:b413qcg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ace284907a8c22ee92c782ad8d93ee425ffed0fd/ui/src/components/forms/common/EnumDropdown.tsx#L65)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I took a second look about `HUI.Listbox` that component takes `disabled` prop and should disable the input. I tested this with an example from their site  (https://headlessui.com/react/listbox#basic-example) by pasting that example to our code base. When I passed `disabled` as true, the input was disabled.

I think problem in our implementation is that we  use`buttonContent` and disabled prop will never get there.
</blockquote></details>

Yeah, okay. Maybe we need to refactor this at some point. Nice that you tested this :+1: 
___
*[`ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayForm.tsx` line 87 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaC0oZa2Qx7qEvogbmE:-NbnBvQt3yxR3H4ZdOlt:b-h980v8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayForm.tsx#L87)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Maybe this is shady for me because we have those query parameters and I'm not yet used to those :D
</blockquote></details>

Yeah, we have added those in some cases, where a user might want to a) refresh page or b) copypaste the url for a particular view to another user (this is probably just a guess), so it wouldn't be possible without the queryparams. Also it makes e2e testing a bit easier, e.g. map tests.
___
*[`ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayFormRow.tsx` line 37 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCCRPx0dC_uSGF8gjd:-NbnCka14Z9_McVgMkv4:b-ewu11g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayFormRow.tsx#L37)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Naming is changed in multiple places. Does it make a sense now?
</blockquote></details>

Yes, the naming is now much clearer! Thanks
___
*[`ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodRow.tsx` line 43 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbnCqW806fMB-n3ggOG:-NbnCqW806fMB-n3ggOH:b-4n2w3e) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d18ec2c591a4695fb532722e59aef020c149dc64/ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodRow.tsx#L43)):*
> ```XML
>   const { t } = useTranslation();
>   const { register, watch } = useFormContext<FormState>();
>   const deleted = watch(`periods.${index}.deleted`);
> ```

NIT, would `toBeDeleted`  be clearer? Since it is not yet actually deleted (or at least I assume so :D)?


<!-- Sent from Reviewable.io -->

2023-08-14 10:54 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627)* status: 45 of 58 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/hooks/urlQuery/useTimeRangeQueryParams.ts` line 30 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbnIg6DBbVs4WelpVBU:-NbnSfOH2rou0uUqROua:b-hfpv0l) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d18ec2c591a4695fb532722e59aef020c149dc64/ui/src/hooks/urlQuery/useTimeRangeQueryParams.ts#L30)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

discussed f2f, probably not needed.
</blockquote></details>

removed
___
*[`ui/src/components/forms/common/EnumDropdown.tsx` line 65 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbUc2yMDkGOPjTTRBAX:-NbnTy_X2ry1U0UX4quV:bulmy6s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/ace284907a8c22ee92c782ad8d93ee425ffed0fd/ui/src/components/forms/common/EnumDropdown.tsx#L65)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yeah, okay. Maybe we need to refactor this at some point. Nice that you tested this :+1: 
</blockquote></details>

Maybe :) 
___
*[`ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayFormRow.tsx` line 37 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NaCCRPx0dC_uSGF8gjd:-NbnStMHCih3dcA60v56:b-eapfem) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bbb94de8a8131ca36a11edfb2de71438170659cd/ui/src/components/timetables/day-settings/RandomReferenceDay/RandomReferenceDayFormRow.tsx#L37)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yes, the naming is now much clearer! Thanks
</blockquote></details>

Resolved?
___
*[`ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodRow.tsx` line 43 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbnCqW806fMB-n3ggOG:-NbnSciO32rN83I0V0NV:bb7f2mf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d18ec2c591a4695fb532722e59aef020c149dc64/ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodRow.tsx#L43)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, would `toBeDeleted`  be clearer? Since it is not yet actually deleted (or at least I assume so :D)?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2023-08-14 11:44 UTC, HenrikHartiala approved these changes
> Reviewed 5 of 8 files at r6, 2 of 3 files at r7, 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627)* status: all files reviewed, 1 unresolved discussion (waiting on @Perholehto)

___
*[`ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodRow.tsx` line 43 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627#-NbnCqW806fMB-n3ggOG:-NbnqsGI3_yfg3FIRziZ:b-ucfknh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d18ec2c591a4695fb532722e59aef020c149dc64/ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodRow.tsx#L43)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

done
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2023-08-14 11:44 UTC, HenrikHartiala approved these changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/627)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Perholehto)



<!-- Sent from Reviewable.io -->

2023-08-15 09:48 UTC, merged