Add common substitute period
HSLdevcom/jore4-ui pull request #650
Opened 2023-08-23 11:54 UTC by Perholehto

2023-08-24 13:10 UTC, HenrikHartiala requested changes
> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 1 of 2 files at r4, 7 of 11 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650)* status: all files reviewed, 17 unresolved discussions (waiting on @Perholehto)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcaklzX-byWlZMu8QX9):*
NIT,  layout? Not sure though if it is a change to layout either, if its just a minor padding change :D. But formatting also sounds too strong.
Maybe something like this?



_Suggestion:_
```
- f0e7bd1: Remove OccasionalSubstitutePeriodSection bottom padding
```
___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcanvSCE43yEU3tB_6o):*
NIT, I think the hyphen is extra



_Suggestion:_
```
- 6e493de: Add common substitute days data
```
___
*[`-- commits` line 16 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-Ncat5Ev8PMRpPgFwQXo):*
NIT, `better place` is a bit non-informative :D. How about `Move substitute day helper functions under utils`or something similar a bit more descriptive?
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 34 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbGrib2YFF_OUvpUVo:-NcbGrib2YFF_OUvpUVp:b-xycwjm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L34)):*
> ```XML
> 
> const generatePresetDates = (startDate: DateTime, endDate: DateTime) => {
>   const years = range(startDate.year, endDate.year + 1);
> ```

Hmm, so we generate dates always at least for 1 year, and then filter the result by the startDate and endDate. Is there some particular benefit with this method, or would it be possible to just generate the dates that are found between the startDate and endDate?

I mean I do understand that it is easier to just generate all commonSubstituteDays at once, then filter, but would it be more complex to just generate by the dates?
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 52 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbNM6K9tg2qgbeMg7V:-NcbNM6K9tg2qgbeMg7W:bi8btk0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L52)):*
> ```XML
> };
> 
> export const mapSubstituteOperatingPeriodsToFormState = (
> ```

It feels like this function does more stuff than just maps periods to form state, it seems like it also generates the dates and does some replacing logic there as well. So could this be refactored to something bit simpler? Maybe the "generate & replace" stuff could be somewhere else, and this function could just map the results. 
(FYI, wrote this comment after the two comments below, because the more I watched this the more I started to understand)
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 57 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbHqc991IESIGIwKGe:-NcbHqc991IESIGIwKGf:bq0s8jk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L57)):*
> ```XML
>   endDate: DateTime,
> ) => {
>   const commonDays: CommonDayType[] = input?.map((item) => {
> ```

extra `?`, since input is not optional parameter. Also wondering if there is a more descriptive name for `input`, because now we are mapping `input`, and the items inside are named `item`, so the content gets a bit lost there.



_Suggestion:_
```XML
  const commonDays: CommonDayType[] = input.map((item) => {
```
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 83 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbJK_K7gg-gc3kNwK4:-NcbJK_K7gg-gc3kNwK5:b-5q6pmh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L83)):*
> ```XML
> 
>   // Remove dates that overlap with days from database
>   const filteredDays = presetDates.filter((d) => {
> ```

Hmm, we already filter the generated preset dates in the generatePresetDates once. What is this filter? I'm cant catch what are these "days from database"? 

Ahhh, wait so this is the combination of dates that are set and dates that are not set?
I would probably rethink the naming of these a little bit to make it more clear.
Now we have presetDates, commonDays, filteredDays and so on, it's a bit confusing.

Don't have the perfect solution straight away, but maybe something to iterate.
How about we generate the presetDates, then we enrich/replace the values with already set substitute days and in the end we have displayedSubstituteDays etc.
This enrich/replace could be its own helper function also.

(After this comment I wrote the comment related above, so maybe we could discuss this further in telco if needed.)
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 114 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbPd37Diuo1iWs-0VU:-NcbPd37Diuo1iWs-0VV:b-xte6sq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L114)):*
> ```XML
>   onSubmit: (state: FormState) => void;
> }): JSX.Element => {
>   const [isResetting, setIsResetting] = useState<boolean>(false);
> ```

NIT, these consts could be maybe rearranged and have some line breaks here and there. Maybe the most valuable thing here would be to at least move this useState declaration to bottom of the list, since it is the least "boiler" here :D But this is really nitpicking.
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx` line 32 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbQjkN867jjhATvtYA:-NcbQjkN867jjhATvtYB:b-qe5r61) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx#L32)):*
> ```XML
> }
> 
> const EditAndRemoveButtons = ({
> ```

This naming implies that it returns multiple buttons, but in the end it actually returns only one button. 
So how about `EditRemoveButton` etc?
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx` line 45 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbRy0k7R_L2NMfWMgZ:-NcbRy0k7R_L2NMfWMg_:blx102h) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx#L45)):*
> ```XML
>   return (
>     <div className="flex justify-end">
>       <Visible visible={showAnyButtons}>
> ```

This outer visible logic with `showAnyButtons` would be better on the parent. So we either render the component, or we don't render the component. Now it is baked inside this component, which reduces the readability by a tiny bit.

Another thing which came to mind is that this is pretty specific button which has a specific logic. You could make this more generic UI element, which takes in just onEdit(), onClose() and some flag determining which button to show, if you want, but this is not nece [...]

2023-09-04 06:22 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650)* status: 10 of 21 files reviewed, 17 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcaklzX-byWlZMu8QX9):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT,  layout? Not sure though if it is a change to layout either, if its just a minor padding change :D. But formatting also sounds too strong.
Maybe something like this?
</blockquote></details>

ok
___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcanvSCE43yEU3tB_6o):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, I think the hyphen is extra
</blockquote></details>

I accidentally resolved this, but this commit is now squashed
___
*[`-- commits` line 16 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-Ncat5Ev8PMRpPgFwQXo):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, `better place` is a bit non-informative :D. How about `Move substitute day helper functions under utils`or something similar a bit more descriptive?
</blockquote></details>

under utils from now on
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 34 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbGrib2YFF_OUvpUVo:-Nd9O3-dDkhG72BH2Y7w:b521jil) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L34)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, so we generate dates always at least for 1 year, and then filter the result by the startDate and endDate. Is there some particular benefit with this method, or would it be possible to just generate the dates that are found between the startDate and endDate?

I mean I do understand that it is easier to just generate all commonSubstituteDays at once, then filter, but would it be more complex to just generate by the dates?
</blockquote></details>

This was the first solution and seems like it was also the latest one :laughing: 

After changes it still generates dates all dates but if generated date is not in time range it doesn't push it to return array.

Do you feel that it should not even create date object for comparison?
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 52 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbNM6K9tg2qgbeMg7V:-NdAVVSj5lE9fSsN9XIP:b-r53tpe) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L52)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

It feels like this function does more stuff than just maps periods to form state, it seems like it also generates the dates and does some replacing logic there as well. So could this be refactored to something bit simpler? Maybe the "generate & replace" stuff could be somewhere else, and this function could just map the results. 
(FYI, wrote this comment after the two comments below, because the more I watched this the more I started to understand)
</blockquote></details>

Check reply below
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 57 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbHqc991IESIGIwKGe:-NdAVcGGDYfJyxM6OskH:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L57)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

extra `?`, since input is not optional parameter. Also wondering if there is a more descriptive name for `input`, because now we are mapping `input`, and the items inside are named `item`, so the content gets a bit lost there.
</blockquote></details>

Done.
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 83 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbJK_K7gg-gc3kNwK4:-NdAVo-a8-8k2ETPB6JP:bqfndjo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L83)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, we already filter the generated preset dates in the generatePresetDates once. What is this filter? I'm cant catch what are these "days from database"? 

Ahhh, wait so this is the combination of dates that are set and dates that are not set?
I would probably rethink the naming of these a little bit to make it more clear.
Now we have presetDates, commonDays, filteredDays and so on, it's a bit confusing.

Don't have the perfect solution straight away, but maybe something to iterate.
How about we generate the presetDates, then we enrich/replace the values with already set substitute days and in the end we have displayedSubstituteDays etc.
This enrich/replace could be its own helper function also.

(After this comment I wrote the comment related above, so maybe we could discuss this further in telco if needed.)
</blockquote></details>

I agree it was a mess. There was so much stuff in the `mapSubstitute...` function... Now that function only maps substitute operating periods to common days. 

Here is a lot of changes, I hope that code will explain it but let's have telco if it's hard to understand or messy or something
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 114 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbPd37Diuo1iWs-0VU:-NcfNvID0oBlgY5xnrZH:bupybby) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L114)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

NIT, these consts could be maybe rearranged and have some line breaks here and there. Maybe the most valuable thing here would be to at least move this useState declaration to bottom of the list, since it is the least "boiler" here :D But this is really nitpicking.
</blockquote></details>

Added some spacing and moved useState to "bottom"
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx` line 32 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbQjkN867jjhATvtYA:-NdAoJnf0wHnhTJXBuYl:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx#L32)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This naming implies that it returns multiple buttons, but in the end it actually returns only one button. 
So how about `EditRemoveButton` etc?
</blockquote></details>

Done.
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx` line 45 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbRy0k7R_L2NMfWMgZ:-NdAqV1Z4MVVqfefIPqB:b-hwpfi2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriod [...]

2023-09-04 09:13 UTC, HenrikHartiala requested changes
> Reviewed 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650)* status: all files reviewed, 4 unresolved discussions (waiting on @Perholehto)

___
*[`-- commits` line 13 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcanvSCE43yEU3tB_6o):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I accidentally resolved this, but this commit is now squashed
</blockquote></details>

Check :+1: 
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 34 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbGrib2YFF_OUvpUVo:-NdUD8Ma7UQhZ3E-i3Og:b2nbbqc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L34)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

This was the first solution and seems like it was also the latest one :laughing: 

After changes it still generates dates all dates but if generated date is not in time range it doesn't push it to return array.

Do you feel that it should not even create date object for comparison?
</blockquote></details>

Well, I think it doesn't matter so much that it is worth the effort to refactor this further now, because this change you made is now more clear what happens and more straight forward, so I most definitely think this is good now! Nice :ok_hand: 

Although after writing the comment I gave the code another look, can you just move the const date = ... inside the if? then it would not even create it.



_Suggestion:_
```XML
    commonSubstituteDayData.forEach((day) => {
      if (date >= startDate && date <= endDate) {
        const date = DateTime.fromISO(
        `${year}-${padToTwoDigits(day.month)}-${padToTwoDigits(day.day)}`,
      );
        generatedDates.push({
          name: `${day.name} ${year}`,
          date,
        });
      }
```
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 83 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbJK_K7gg-gc3kNwK4:-NdUFaak5gn6-1CxTf2f:b-qd96cv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L83)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I agree it was a mess. There was so much stuff in the `mapSubstitute...` function... Now that function only maps substitute operating periods to common days. 

Here is a lot of changes, I hope that code will explain it but let's have telco if it's hard to understand or messy or something
</blockquote></details>

Ahh, reeally really great work with the refactor! :muscle: This is so so much more clear and neat!
Awesome :star_struck: 
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 114 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbPd37Diuo1iWs-0VU:-NdUG7sm1z6nT5lUJoFs:b-un3dxg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L114)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Added some spacing and moved useState to "bottom"
</blockquote></details>

Nice, thanks! :pray: 
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx` line 45 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbRy0k7R_L2NMfWMgZ:-NdUGd8B8D2xsRMG_W3u:bp763ow) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx#L45)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Moved the outer logic to parent.

I made this more generic not because I think it will be used at some place else. It is just cleaner now
</blockquote></details>

Great work with this one as well! And the `EditRemove` -> `EditClose` was a nice enhancement as well, since the "remove" part is more like a side effect to the "close"/"cancel". Now IF we would want to give the user a confirm dialog, it would be easy to implement. 
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx` line 95 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbZMc_DqzkubpPCK35:-NdUK3C49UGGR_X2KRvD:b-6uhnml) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx#L95)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Really good points! Made some changes here, removed margins and changed parent div. 

I also refactored child element to use flexbox instead of grid.

I understand what you mean by layout definitions given from outside, but seems like I have hard time to follow it when developing :/
</blockquote></details>

Yeah it is easy to make the mistake even when knowing the reason behind it. 

Like said in the telco, the `basis-` attributes are new to me and I can't say if there are any downsides to them, but they most definitely are better than precision margins with each element. So nice one! 
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx` line 33 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NdUHMqZDIamQP1O5HcJ:-NdUHMqZDIamQP1O5HcK:bypry8t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc99f29ff4ca43c43c3d5e8ee5f64cd5220d60c7/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx#L33)):*
> ```XML
> 
> const EditCloseButton = ({
>   flag,
> ```

This `flag` is kind of hard to understand what it does without actually reading the code. But for this generic EditCloseButton it is kind of hard to think of one, since something like `showEdit` or `isClosable` or whatever are also maybe a bit awkward. Maybe if you add a minor JSDoc comment on this component which explains that that when the flag is set to true, it shows the close option and on false it shows the edit option. Or something like that.

Minor edit/addition: maybe the "showEdit" could be better? If you check these two choices when using the component:

```
<EditCloseButton
            flag={created}
            onEdit={() => update(index, created)}
            onClose={() => update(index, created)}
          />
vs.
<EditCloseButton
            showEdit={created}
            onEdit={() => update(index, created)}
            onClose={() => update(index, created)}
          />

```
Even with the JSDoc comment, I think the showEdit or something that hinges the user towards what it is might be better, even though the parameter name is still a bit awkward. What do you think?

Btw, this component probably could now live in `uiComponents` in it's own file, since it is nicely already made generic :+1: 
___
*[`ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodForm.tsx` line 49 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcamHp29CcfyqpRmHil:-NdUOkP--t6nUFr5JX-n:bnutve6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6628085babe49a326a23db5157871c302bf02978/ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodForm.tsx#L49)):*
<details><summary><i>Previously, P [...]

2023-09-04 10:10 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650)* status: 19 of 21 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 34 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbGrib2YFF_OUvpUVo:-NdUXH9Y2Ue-E_oErhu8:bu6qthu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L34)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Well, I think it doesn't matter so much that it is worth the effort to refactor this further now, because this change you made is now more clear what happens and more straight forward, so I most definitely think this is good now! Nice :ok_hand: 

Although after writing the comment I gave the code another look, can you just move the const date = ... inside the if? then it would not even create it.
</blockquote></details>

Hmm that could be nice, but if we move declaration of `date` inside if statement we can't use it in comparison because it is not declared before usage
___
*[`ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodSection.tsx` line 17 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NdUQDg62UWiNi8pN7K0:-NdUZr_B6XT0mX4gCN_b:bi1m5ce) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc99f29ff4ca43c43c3d5e8ee5f64cd5220d60c7/ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodSection.tsx#L17)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Seems like a VSCode rename leftover (?)
</blockquote></details>

Yeah, not first time and not last one... 
___
*[`ui/src/hooks/substitute-operating-periods/useGetSubstituteOperatingPeriod.ts` line 67 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NdUQw7q4SuJZUt8VtdB:-NdUYIcHAeLnA379fQYf:bqm0lwr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc99f29ff4ca43c43c3d5e8ee5f64cd5220d60c7/ui/src/hooks/substitute-operating-periods/useGetSubstituteOperatingPeriod.ts#L67)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I really like that these are now separated :+1: :ok_hand:
</blockquote></details>

You liked them so much that this needs to be blocked? :DD
___
*[`ui/src/data/common_substitute_days.ts` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-Ncap1vHBxy0Uum9NXgU:-NdUWQSDAo2nb21Kr9m5:b61r6t5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6e493de13f89d18180b3b531fddf7c74c10880a2/ui/src/data/common_substitute_days.ts#L2)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ahh, right, these are saved to database. I just thought that these were used only for the hardcodes on page but yeah of course when the user sets a common substitute day, then it is saved to database.

Yeah no changes needed here. Maybe this comes somewhere in the future if we want to have translations for these. It kind of is the same for occasional subsitute days, but those can't have hardcoded translations so they would need user to input the translation and that doesn't sound fun.
</blockquote></details>

Yep, if there is need for translations, one possibility is to change `period_name` in database to `i18n` but that's different story


<!-- Sent from Reviewable.io -->

2023-09-04 10:58 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650)* status: 18 of 22 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx` line 33 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NdUHMqZDIamQP1O5HcJ:-NdUnEEX8Ac3rfyMKcoP:by4d9t6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc99f29ff4ca43c43c3d5e8ee5f64cd5220d60c7/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx#L33)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This `flag` is kind of hard to understand what it does without actually reading the code. But for this generic EditCloseButton it is kind of hard to think of one, since something like `showEdit` or `isClosable` or whatever are also maybe a bit awkward. Maybe if you add a minor JSDoc comment on this component which explains that that when the flag is set to true, it shows the close option and on false it shows the edit option. Or something like that.

Minor edit/addition: maybe the "showEdit" could be better? If you check these two choices when using the component:

```
<EditCloseButton
            flag={created}
            onEdit={() => update(index, created)}
            onClose={() => update(index, created)}
          />
vs.
<EditCloseButton
            showEdit={created}
            onEdit={() => update(index, created)}
            onClose={() => update(index, created)}
          />

```
Even with the JSDoc comment, I think the showEdit or something that hinges the user towards what it is might be better, even though the parameter name is still a bit awkward. What do you think?

Btw, this component probably could now live in `uiComponents` in it's own file, since it is nicely already made generic :+1:
</blockquote></details>

Moved this to `uiComponents` that's good place for it now.
Changed `flag` to `showEdit`
Flipped `!` inside component to make more sense. Now if `showEdit` is `true` it shows edit button
Also added comment to clarify it more. I think it's ready to :ship: 


<!-- Sent from Reviewable.io -->

2023-09-04 11:05 UTC, HenrikHartiala approved these changes
Great work! :muscle: 

> Reviewed 2 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-:-NdUrb_u7UBqQdA9_vEe:bibggeh)* status: all files reviewed, 3 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx` line 34 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NcbGrib2YFF_OUvpUVo:-NdUqWhpB5JBNLlqBgg6:b-mksmup) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d6f06634607c2c48398c3398d9c47ac403bffd7f/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodForm.tsx#L34)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Hmm that could be nice, but if we move declaration of `date` inside if statement we can't use it in comparison because it is not declared before usage
</blockquote></details>

haha, wth. I was only half a cup of my morning coffee when I checked that. Oh well.... :D 
___
*[`ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx` line 33 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NdUHMqZDIamQP1O5HcJ:-NdUrLaY96AG48ehLJYk:b-pagv6f) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc99f29ff4ca43c43c3d5e8ee5f64cd5220d60c7/ui/src/components/timetables/substitute-day-settings/CommonSubstitutePeriod/CommonSubstitutePeriodItem.tsx#L33)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Moved this to `uiComponents` that's good place for it now.
Changed `flag` to `showEdit`
Flipped `!` inside component to make more sense. Now if `showEdit` is `true` it shows edit button
Also added comment to clarify it more. I think it's ready to :ship:
</blockquote></details>

Nice, thanks! :shipit: 
___
*[`ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodSection.tsx` line 17 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-NdUQDg62UWiNi8pN7K0:-NdUrWS42B20Qbujb3MY:bun9gfx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/bc99f29ff4ca43c43c3d5e8ee5f64cd5220d60c7/ui/src/components/timetables/substitute-day-settings/OccasionalSubstitutePeriod/OccasionalSubstitutePeriodSection.tsx#L17)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Yeah, not first time and not last one...
</blockquote></details>

Exactly :D 
___
*[`ui/src/data/common_substitute_days.ts` line 2 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/650#-Ncap1vHBxy0Uum9NXgU:-NdUqQRU2c4Nga0goNjp:bc1fb3y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6e493de13f89d18180b3b531fddf7c74c10880a2/ui/src/data/common_substitute_days.ts#L2)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Yep, if there is need for translations, one possibility is to change `period_name` in database to `i18n` but that's different story
</blockquote></details>

Yeah :+1: 


<!-- Sent from Reviewable.io -->

2023-09-04 13:01 UTC, merged