Take timetables-data-inserter in to use
HSLdevcom/jore4-ui pull request #670
Opened 2023-09-19 12:40 UTC by HenrikHartiala

Timetables data inserter is used for easier data insert e.g. for tests. The inserter is located in hasura repository which is imported as git submodule.

2023-09-22 04:52 UTC, Leitsi requested changes
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 237 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670#-NevDdJWBA509KccM9pr:-NevDdJWBA509KccM9ps:b-104bzb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4a969dbfb4b785a01dc21facb165c898a80100cf/cypress/e2e/timetablePassingTimes.cy.ts#L237)):*
> ```XML
>           validity_end: DateTime.fromISO('2023-05-31'),
>           name: 'Talvi 2022',
>           created_at: DateTime.fromISO('2021-01-01T02:34:56.789+02:00'),
> ```

Most likely `created_at` makes no difference, maybe just omit it.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 250 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670#-NevDMErByD01Kp6vTIF:-NevDMErByD01Kp6vTIG:bbk24fa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4a969dbfb4b785a01dc21facb165c898a80100cf/cypress/e2e/timetablePassingTimes.cy.ts#L250)):*
> ```XML
>                         {
>                           _scheduled_stop_point_label: 'H1234',
>                           arrival_time: null,
> ```

To keep the data more "symmetric", I would rather always include both `arrival_time: null,` and `departure_time: null,`, or omit them both. Now the `departure_time` has been omitted (on the last stop) but `arrival_time` has not.


<!-- Sent from Reviewable.io -->

2023-09-22 05:39 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670)* status: 14 of 17 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala and @Leitsi)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 250 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670#-NevDMErByD01Kp6vTIF:-NevNWCvCXA-TPdiiYPv:b-tpoedg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4a969dbfb4b785a01dc21facb165c898a80100cf/cypress/e2e/timetablePassingTimes.cy.ts#L250)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

To keep the data more "symmetric", I would rather always include both `arrival_time: null,` and `departure_time: null,`, or omit them both. Now the `departure_time` has been omitted (on the last stop) but `arrival_time` has not.
</blockquote></details>

Is there a real world use case for having a departure time at the end of a timetable?


<!-- Sent from Reviewable.io -->

2023-09-22 05:53 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670)* status: 14 of 17 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala and @Leitsi)

___
*[`cypress/e2e/utils/tasks.ts` line 72 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670#-NevR8KP2sU6Gg1zEUMu:-NevR8KP2sU6Gg1zEUMv:b-w75qup) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/390bd42a03672649ffd664590e8ad3db7a772661/cypress/e2e/utils/tasks.ts#L72)):*
> ```XML
> };
> 
> export const insertHslDatasetToDb = (input: HslTimetablesDatasetInput) => {
> ```

Could be insertHslTimetableDatasetToDb.


<!-- Sent from Reviewable.io -->

2023-09-22 06:00 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670)* status: 14 of 17 files reviewed, 3 unresolved discussions (waiting on @Leitsi and @sr-vala)

___
*[`cypress/e2e/utils/tasks.ts` line 72 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670#-NevR8KP2sU6Gg1zEUMu:-NevSP-UDgcmTVP0oOpX:bamqw3s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/390bd42a03672649ffd664590e8ad3db7a772661/cypress/e2e/utils/tasks.ts#L72)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Could be insertHslTimetableDatasetToDb.
</blockquote></details>

Good one, I'll change this


<!-- Sent from Reviewable.io -->

2023-09-22 09:14 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670)* status: 13 of 17 files reviewed, 2 unresolved discussions (waiting on @Leitsi and @sr-vala)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 237 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670#-NevDdJWBA509KccM9pr:-New9ghr7e8gjGdq3m82:bwj6bvb) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4a969dbfb4b785a01dc21facb165c898a80100cf/cypress/e2e/timetablePassingTimes.cy.ts#L237)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Most likely `created_at` makes no difference, maybe just omit it.
</blockquote></details>

Yeah, just an example, but I'll remove it.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 250 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670#-NevDMErByD01Kp6vTIF:-New9jUf8hwTbZOHARWX:bemw59y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4a969dbfb4b785a01dc21facb165c898a80100cf/cypress/e2e/timetablePassingTimes.cy.ts#L250)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Is there a real world use case for having a departure time at the end of a timetable?
</blockquote></details>

Added the symmetry :+1: 


<!-- Sent from Reviewable.io -->

2023-10-04 11:44 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670)* status: 12 of 17 files reviewed, all discussions resolved (waiting on @sr-vala)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 250 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670#-NevDMErByD01Kp6vTIF:-NfuUf_V1s3T6sXWXc7M:bidqd1h) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/4a969dbfb4b785a01dc21facb165c898a80100cf/cypress/e2e/timetablePassingTimes.cy.ts#L250)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Added the symmetry :+1:
</blockquote></details>

@sr-vala no, it must be null for the last stop. Same as arrival must be null for first stop.


<!-- Sent from Reviewable.io -->

2023-10-04 11:45 UTC, Leitsi reviewed
Separated the example out of this PR as discussed.

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670#-:-NfuVRsN7WfYR0lf-yMW:b2aa2lv)* status: 12 of 17 files reviewed, all discussions resolved (waiting on @sr-vala)



<!-- Sent from Reviewable.io -->

2023-10-05 05:49 UTC, Leitsi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/670#-:-NfyNaCH5mxNKMGkunQL:bnfp4nl)* status: 12 of 17 files reviewed, all discussions resolved (waiting on @sr-vala)



<!-- Sent from Reviewable.io -->

2023-10-05 05:50 UTC, merged