Add notification about deviations
HSLdevcom/jore4-ui pull request #683
Opened 2023-10-17 07:47 UTC by Perholehto

Separated adding three hooks to own commits. There has been arguments that "dead" code should not be added before usage, but I think this can help in review etc.. 
These hooks are: `useGetStagingVehicleScheduleFrameIds`, `useVehicleScheduleFramesWithRouteLabelAndLineId` and `useToReplaceVehicleScheduleFrames`

Latest commit has a few new components and there is a few unit tests for those. There is also hook `useReplaceDeviations`. This hook uses hooks added in earlier commits. There is also few "helper" hooks and they have few unit tests to endorse wanted behavior.

2023-10-17 13:01 UTC, Leitsi requested changes
> Reviewed 3 of 5 files at r2, 1 of 2 files at r3, 3 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683)* status: 7 of 24 files reviewed, 6 unresolved discussions (waiting on @Perholehto)

___
*[`-- commits` line 14 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxgGb05F2eNz2q5BkZ):*
I would maybe squash all of this. The earlier hook commits are quite simple since the actual hook aren't that long, and mostly they just contain autogenerated code. As it is now, the earlier commits just contain dead code that doesn't really clarify things that much by being on separate commits.
___
*[`ui/src/generated/graphql.tsx` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Ngx2kKn64F_wxtYFnP4:-Ngx2kKn64F_wxtYFnP5:bmuzh8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77be8c9840898ad6b5945fc261a4e65d0441307f/ui/src/generated/graphql.tsx#L1)):*
> ```XML
> import * as Apollo from '@apollo/client';
> ```

These come from commit [Update hasura image and generated sources](https://github.com/HSLdevcom/jore4-ui/pull/683/commits/77be8c9840898ad6b5945fc261a4e65d0441307f) that doesn't actually update the Hasura image.
___
*[`ui/src/hooks/vehicle-schedule-frame/useReplaceDeviations.ts` line 29 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxiK_CELybWIjfTWkQ:-NgxiK_D6wFahRhsHALm:b-2oi88m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useReplaceDeviations.ts#L29)):*
> ```XML
> 
>   const fetchRouteDeviations = useCallback(
>     async (targetPriority: number) => {
> ```

Is it not possible to use `TimetablePriority` here?
___
*[`ui/src/hooks/vehicle-schedule-frame/useToReplaceVehicleScheduleFrames.ts` line 39 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxcpROEJ9QNE1hjijj:-NgxcpRPD5bqn8nBS4Ao:b-ffdal8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useToReplaceVehicleScheduleFrames.ts#L39)):*
> ```XML
>         return compact(replaced);
>       } catch (error) {
>         log.error(error);
> ```

Maybe add some prefix at least? `log.error('Could not fetch frames to replace: ', error);`

Though I'm wondering, is this the best way to handle this? Looks to be the only `log.error` instance in the codebase. If this doesn't work, then user won't know what the changes they are about to make actually do. Would it be better to just let this fail, and add some handling for expected (are there any?) error cases?
___
*[`ui/src/locales/en-US/common.json` line 276 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxfEsKEONjEYC8nnSf:-NgxfEsKEONjEYC8nnSg:b-l194ac) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/locales/en-US/common.json#L276)):*
> ```JSON
>     "leaveMultipleHandles": "Cannot delete snap point(s)! You should leave at least two of them.",
>     "tooFarFromInfrastructureLink": "Make sure each point in route geometry is close enough to the road network. Check coverage of the road network along the route, if necessary.",
>     "deviationFetchFailed": "Failed to fetch missing routes"
> ```

Not sure what the intention of this "errors" object has been originally. I'm assuming "generic error messages that can be used in multiple places", but doesn't seem to be the case anymore. But I would rather move this `"deviationFetchFailed"` closer to its actual context, that is, under `"timetablesPreview"`.
___
*[`ui/src/locales/en-US/common.json` line 400 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxfkhRCtJrbIgSxo3O:-NgxfkhRCtJrbIgSxo3P:b-9gglbz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/locales/en-US/common.json#L400)):*
> ```JSON
>     "preview": "Preview",
>     "save": "Save timetables",
>     "showContent": "Show content",
> ```

Something got messed up here, while rebasing or something? Many keys are present here multiple times. Same in the finnish translation file.


<!-- Sent from Reviewable.io -->

2023-10-17 17:27 UTC, Leitsi requested changes
> Reviewed 1 of 2 files at r4, 11 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683)* status: 19 of 24 files reviewed, 18 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 27 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyKH7p4-g2_1t_Ty4S:-NgyKH7q73Snp-Z6RQ7S:bito6s4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L27)):*
> ```XML
>       <div className="mt-8 rounded-lg border bg-hsl-highlight-yellow-light px-12 py-6">
>         <MdWarning className="mr-2 inline text-hsl-red" />
>         {t('timetablesPreview.deviationsText')}
> ```

"text" feels rather weak / too generic for what this is actually used for. Maybe `deviationsWarning` or `missingRoutesWarning` or something?
___
*[`ui/src/components/timetables/import/RouteDeviationLink.tsx` line 23 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyLVBpBXMBR1vX4IIf:-NgyLVBpBXMBR1vX4IIg:b-pci1ak) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.tsx#L23)):*
> ```XML
>     >
>       <div className="flex items-center">
>         {!!index && ', '}
> ```

Nit: this approach causes there to be a space on both sides of the comma. Would need some refactoring to fix, easiest maybe to pass "isLast" or something instead of index and moving the comma. But perhaps we don't care?
___
*[`ui/src/components/timetables/import/RouteDeviationLink.tsx` line 30 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyNP71E3UWdMEDqtRt:-NgyNP71E3UWdMEDqtRu:b-oh671i) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.tsx#L30)):*
> ```XML
>         />
>         <span className="mr-1 font-bold text-black underline">{label}</span>
>         {variant && <span>{variant}</span>}
> ```

Does this need a span? No class or anything associated, which always seems a bit weird.
___
*[`ui/src/components/timetables/import/RouteDeviationLink.spec.tsx` line 40 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyNhSMEZ7bwO3Ss4kd:-NgyNhSMEZ7bwO3Ss4ke:b-qhr3y7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.spec.tsx#L40)):*
> ```XML
> 
>     expect(getByText('2')).toBeInTheDocument();
>   });
> ```

Empty line between tests. Same issue after next test.

Maybe fixable automatically with eslint, we did similar thing on hasura side: https://github.com/HSLdevcom/jore4-hasura/commit/3b03d9391e7d02a61f2d346c353463ca2e616c31
___
*[`ui/src/components/timetables/import/RouteDeviationLink.spec.tsx` line 108 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyP37PEV1dd-oJwuLc:-NgyP37PEV1dd-oJwuLd:blmb6kt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.spec.tsx#L108)):*
> ```XML
>       />,
>     );
>     expect(getByText('3')).toBeInTheDocument();
> ```

Dunno what is the established practice in this repository, but I would typically test specific elements (in this case the variant), and add classes for accessing those accurately in tests if needed. Less likely that the expects pass because the element happens to contain the expected test somewhere else. What do you think?
___
*[`ui/src/hooks/timetables-import/useDeviationSort.ts` line 10 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyelJLDEKW3iZWsYIa:-NgyelJLDEKW3iZWsYIb:b6efhvk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/timetables-import/useDeviationSort.ts#L10)):*
> ```XML
>     return orderBy(
>       routeDeviations,
>       ['label', 'direction', (deviation) => deviation.variant || -1],
> ```

Note that route also has unique_label which is derived from label and variant.
___
*[`ui/src/hooks/timetables-import/useDeviationSort.spec.ts` line 11 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgybUdw421V6x81As59:-NgybSkEA75F1CBp-xPV:btybb68) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/timetables-import/useDeviationSort.spec.ts#L11)):*
> ```XML
> const hookForNames = renderHook(useDeviationSort);
> 
> describe(`${hookForNames.result.current.sortDeviations.name}`, () => {
> ```

Why not just `describe('sortDeviations hook'`?
This kind of smartness makes it harder to run only some tests from command line with eg. `yarn test -t 'sortDeviations'`.

I would remove this from other similar instances as well.
___
*[`ui/src/hooks/timetables-import/useDeviationSort.spec.ts` line 52 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Ngyb3qw9QlktRe41nb4:-Ngyb3qw9QlktRe41nb5:b-kkifos) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/timetables-import/useDeviationSort.spec.ts#L52)):*
> ```XML
>       routeId: '1',
>       routeName: buildLocalizedString('route'),
>     });
> ```

I would rather compare the whole array at once. Less error prone (no possibility that you eg. put wrong index at ` expect(sortedDeviations[0])`) and shows errors nicer.



_Suggestion:_
```XML
    expect(sortedDeviations).toEqual([
      {
        label: 'A',
        lineId: '2',
        direction: RouteDirectionEnum.Inbound,
        variant: null,
        routeId: '2',
        routeName: buildLocalizedString('route'),
      },
      {
        label: 'B',
        lineId: '1',
        direction: RouteDirectionEnum.Inbound,
        variant: null,
        routeId: '1',
        routeName: buildLocalizedString('route'),
      },
    ]);
```
___
*[`ui/src/hooks/vehicle-schedule-frame/useFindOrphanRoutes.spec.ts` line 103 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgycnYs2BVRMG5ZDhO5:-NgycnYs2BVRMG5ZDhO6:b-364h4i) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useFindOrphanRoutes.spec.ts#L103)):*
> ```XML
>   },
>   {
>     testName: 'when toReplace is empty',
> ```

should do what?
___
*[`ui/src/hooks/vehicle-schedule-frame/useFindOrphanRoutes.spec.ts` line 125 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgycIfz1n-BAtDYLtAi:-NgycIfz1n-BAtDYLtAj:bxy7ubq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useFindOrphanRoutes.spec.ts#L125)):*
> ```XML
>     const { testName, toReplaceRoutes, stagingRoutes, expected } = testArgs;
> 
>     test(`${testName}`, () => {
> ```

:thumbsup: for generated tests.

Debugging is a bit harder when doing it this way though, instead of typing out each test-block manually and calling shared test implementations (though I do both as well). Eg. think how you'd have to debug stuff if one of these cases fails. No need to refactor though, can just do that if one ever encounters issues.

No need for template string though, just ` test(testName, () => {` should work?
___
*[`ui/src/hooks/vehicle-schedule-frame/useFindOrphanroutes.ts` line 4 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgydnAE5A_hmyNcVkPF:-NgydnAE5A_hmyNcVkPG:bwe9w76) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useFindOrphanroutes.ts#L4)):*
> ```XML
> import { VehicleScheduleFrameInfo } from './useVehicleScheduleFramesToVehicleScheduleFrameInfo';
> 
> export const useFindOrpanRoutes = () => {
> ```

Typo

Also filename `useFindOrphanroutes.ts` -> `useFindOrphanRoutes.ts`



_Suggestion:_
```XML
export const useFindOrphanRoutes = () => {
```
___
*[`ui/src/hooks/v [...]

2023-10-18 05:55 UTC, Leitsi requested changes
> Reviewed 1 of 2 files at r4, 4 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683)* status: all files reviewed, 25 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/components/timetables/import/RouteDeviationLink.tsx` line 18 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0KnpF064ZGelzU1uv:-Nh0KnpF064ZGelzU1uw:byb76p7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.tsx#L18)):*
> ```XML
>   return (
>     <Link
>       to={routeDetails['/lines/:id'].getLink(lineId, label)}
> ```

Should this maybe link to the line _timetable_ page instead? `/timetables/lines/` that is. Since the issue has to do with timetables and you can't see those from route/line page.

Hmm, doesn't even look like there's any link from line view -> line timetables view, maybe there should be :thinking: Not in scope of this PR though.
___
*[`ui/src/hooks/vehicle-schedule-frame/useFindOrphanroutes.ts` line 15 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgydPnCC5bUHGPt_L3x:-Nh0KQDg8JICQVTK3hkb:b-bar1nu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useFindOrphanroutes.ts#L15)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I would rather use a parameter object if possible. Here we have two parameters with exactly same type, and it is not intuitive which one should be first, so might be possible to mix them up when calling. Or if order truly doesn't matter then maybe this is fine.
</blockquote></details>

Edit: order does matter. Managed to mix up these by accident when hacking around and wrong deviations get shown.
___
*[`ui/src/hooks/vehicle-schedule-frame/useGetStagingVechicleScheduleFrameIds.ts` line 5 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0DKh19bhPQyqfX3qy:-Nh0DKh19bhPQyqfX3qz:b356vpd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useGetStagingVechicleScheduleFrameIds.ts#L5)):*
> ```XML
> import { useGetStagingVehicleScheduleFrameIdsAsyncQuery } from '../../generated/graphql';
> 
> const GQL_GET_STAGING_VEHICLE_SCHEDULE_FRAME_IDS = gql`
> ```

There's a very similar query `GQL_GET_STAGING_VEHICLE_SCHEDULE_FRAMES` in `useTimetablesImport.ts`, could we maybe use that instead? Returns some extra info, but because of caching that shouldn't matter, especially since that query is already executed from the same view.
___
*[`ui/src/hooks/vehicle-schedule-frame/useReplaceDeviations.ts` line 13 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0F7GM9OzuBxRTrQLj:-Nh0F7GNCxGP6fBFWE2i:b7ny9xt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useReplaceDeviations.ts#L13)):*
> ```XML
> export const useReplaceDeviations = (
>   fetchToReplaceFrames: (
>     ids: string[],
> ```

Could maybe use `UUID` type for DB ids (even if it's just an alias for `string`).
___
*[`ui/src/hooks/vehicle-schedule-frame/useReplaceDeviations.ts` line 50 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0HeCb0Kh8iZY6ZhWk:-Nh0HeCb0Kh8iZY6ZhWl:bex039t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useReplaceDeviations.ts#L50)):*
> ```XML
>         );
>         const stagedVehicleScheduleFramesWithRouteInfo =
>           await fetchVehicleFrames(stagedVehicleScheduleFrameIds);
> ```

Minor optimization: these could be fetched in parallel.



_Suggestion:_
```XML

        const [
          toReplaceVehicleFramesWithRouteInfo,
          stagedVehicleScheduleFramesWithRouteInfo,
        ] = await Promise.all([
          fetchVehicleFrames(toReplace),
          fetchVehicleFrames(stagedVehicleScheduleFrameIds),
        ]);
```
___
*[`ui/src/hooks/vehicle-schedule-frame/useReplaceDeviations.ts` line 65 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0HyXxBQdFdXiFNzLe:-Nh0HyXxBQdFdXiFNzLf:bmd3cqo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useReplaceDeviations.ts#L65)):*
> ```XML
>           toReplaceVehicleScheduleFrameInfo,
>           stagedVehicleScheduleFrameInfo,
>         );
> ```

Maybe this would be neater if you just remove the variables, they don't really help readability.



_Suggestion:_
```XML
        const foundDeviations = findOrphanRoutes(
          vehicleScheduleFramesToVehicleScheduleFrameInfo(
            toReplaceVehicleFramesWithRouteInfo,
          ),
          vehicleScheduleFramesToVehicleScheduleFrameInfo(
            stagedVehicleScheduleFramesWithRouteInfo,
          ),
        );
```
___
*[`ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFramesToVehicleScheduleFrameInfo.ts` line 17 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0BUq79_mMzG76B0WU:-Nh0BUq79_mMzG76B0WV:bj44ahl) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFramesToVehicleScheduleFrameInfo.ts#L17)):*
> ```XML
> };
> 
> export const useVehicleScheduleFramesToVehicleScheduleFrameInfo = () => {
> ```

I keep thinking about the organization of these hooks / files. Especially this `VehicleScheduleFrameInfo` is very ambiguous.

Would it make sense to move all of these new hooks to eg. `hooks/timetables-import/deviations`? I feel like they're more related to the import process than just vehicle schedule frames in general.
___
*[`ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFramesToVehicleScheduleFrameInfo.ts` line 17 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0FYjw-j0X9EFMY5ni:-Nh0FYjw-j0X9EFMY5nj:b3vx49a) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFramesToVehicleScheduleFrameInfo.ts#L17)):*
> ```XML
> };
> 
> export const useVehicleScheduleFramesToVehicleScheduleFrameInfo = () => {
> ```

The hook and callback names are rather long. Would something like `useCreateVehicleScheduleFrameInfo` work? Parameters already tell that they're created based on frames.


<!-- Sent from Reviewable.io -->

2023-10-18 06:21 UTC, niknii-vincit commented
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 22 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxUXYwB__G3bJx5frk:-NgxUXYxD-sp1zf8bjp6:bnov1gc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L22)):*
> ```XML
>     <div className={className}>
>       <h3>
>         <MdWarning className="mr-2 inline text-hsl-red" />
> ```

I would add `role="img"`and `alt="Attention"` to these two warning icons, for clarity's (_and accessibility's_) sake. My reasoning for "attention": this isn't _that_ dangerous to do, but just something that needs to be informed.


<!-- Sent from Reviewable.io -->

2023-10-18 06:25 UTC, niknii-vincit commented
*[`ui/src/components/timetables/import/RouteDeviationLink.tsx` line 18 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0KnpF064ZGelzU1uv:-Nh0RkFY3Qw8fE9c0g0l:br9epcj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.tsx#L18)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Should this maybe link to the line _timetable_ page instead? `/timetables/lines/` that is. Since the issue has to do with timetables and you can't see those from route/line page.

Hmm, doesn't even look like there's any link from line view -> line timetables view, maybe there should be :thinking: Not in scope of this PR though.
</blockquote></details>

Just a note on the "line view -> line timetables view" link, I informed Juha about this ~two weeks ago, and he said that he'll spin up some designs for it... Haven't heard anything after that :thinking: 


<!-- Sent from Reviewable.io -->

2023-10-18 06:40 UTC, niknii-vincit reviewed
> Reviewed 1 of 1 files at r1, 5 of 5 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 4 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683)* status: all files reviewed, 26 unresolved discussions (waiting on @Leitsi and @Perholehto)



<!-- Sent from Reviewable.io -->

2023-10-18 15:05 UTC, niknii-vincit commented
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 27 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh2IPmVDBHMRM-qNSZE:-Nh2IPmVDBHMRM-qNSZF:b79940c) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L27)):*
> ```XML
>       <div className="mt-8 rounded-lg border bg-hsl-highlight-yellow-light px-12 py-6">
>         <MdWarning className="mr-2 inline text-hsl-red" />
>         {t('timetablesPreview.deviationsText')}
> ```

Not sure if this causes more trouble than what it's worth, but I think the text should be broken up a bit: 
![image.png](https://files.reviewableusercontent.io/images/reviewable/135983800/tcndHLFQvVInSn6EmWhcGdk0/image.png)

I added them into separate paragraphs with `mt-4` on the latter 2 paragraphs.


<!-- Sent from Reviewable.io -->

2023-10-20 06:59 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683)* status: 3 of 28 files reviewed, 27 unresolved discussions (waiting on @Leitsi and @niknii-vincit)

___
*[`-- commits` line 14 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxgGb05F2eNz2q5BkZ):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I would maybe squash all of this. The earlier hook commits are quite simple since the actual hook aren't that long, and mostly they just contain autogenerated code. As it is now, the earlier commits just contain dead code that doesn't really clarify things that much by being on separate commits.
</blockquote></details>

Now it's just one commit
___
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 22 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxUXYwB__G3bJx5frk:-Nh0pMeZ5UHHtGKVs5ER:b-sp8w29) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L22)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

I would add `role="img"`and `alt="Attention"` to these two warning icons, for clarity's (_and accessibility's_) sake. My reasoning for "attention": this isn't _that_ dangerous to do, but just something that needs to be informed.
</blockquote></details>

Added `role='img'` but `IconType` don't have `alt` prop :(
___
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 27 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyKH7p4-g2_1t_Ty4S:-Nh0q4unDcoSqbxe4iL-:b32s7he) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L27)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

"text" feels rather weak / too generic for what this is actually used for. Maybe `deviationsWarning` or `missingRoutesWarning` or something?
</blockquote></details>

changed to `deviationsWarning`
___
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 27 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh2IPmVDBHMRM-qNSZE:-NhAoXkL6VTxCSyK3Giy:bhubxwq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L27)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Not sure if this causes more trouble than what it's worth, but I think the text should be broken up a bit: 
![image.png](https://files.reviewableusercontent.io/images/reviewable/135983800/tcndHLFQvVInSn6EmWhcGdk0/image.png)

I added them into separate paragraphs with `mt-4` on the latter 2 paragraphs.
</blockquote></details>

Hmm, this looks clean, but should we still stick with design? Juha designed this a few weeks ago and this should be up to date.
___
*[`ui/src/components/timetables/import/RouteDeviationLink.tsx` line 18 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0KnpF064ZGelzU1uv:-Nh1Q3BXAxrZ2tPBYD0h:bu0zzdy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.tsx#L18)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Just a note on the "line view -> line timetables view" link, I informed Juha about this ~two weeks ago, and he said that he'll spin up some designs for it... Haven't heard anything after that :thinking:
</blockquote></details>

Hmm, we went through how this works with Juha. I don't recall that he had anything to say where the link goes, but that wasn't the main point in discussion. For me it also makes more sense to change the link to `/timetables/lines/` 
___
*[`ui/src/components/timetables/import/RouteDeviationLink.tsx` line 23 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyLVBpBXMBR1vX4IIf:-Nh6jb0XDQA2Fs-bj0qy:b-2j7fvo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.tsx#L23)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Nit: this approach causes there to be a space on both sides of the comma. Would need some refactoring to fix, easiest maybe to pass "isLast" or something instead of index and moving the comma. But perhaps we don't care?
</blockquote></details>

Removed index trickery and added your suggested `isLast` to indicate when render comma
___
*[`ui/src/components/timetables/import/RouteDeviationLink.tsx` line 30 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyNP71E3UWdMEDqtRt:-Nh1TkpG4XFhncMrcp-K:b-yoaz4p) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.tsx#L30)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Does this need a span? No class or anything associated, which always seems a bit weird.
</blockquote></details>

span was unnecessary, removed it and also added one space between label and variant
___
*[`ui/src/components/timetables/import/RouteDeviationLink.spec.tsx` line 40 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyNhSMEZ7bwO3Ss4kd:-NhAo8Dl9crtn2JjBLjr:bsb6hn9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.spec.tsx#L40)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Empty line between tests. Same issue after next test.

Maybe fixable automatically with eslint, we did similar thing on hasura side: https://github.com/HSLdevcom/jore4-hasura/commit/3b03d9391e7d02a61f2d346c353463ca2e616c31
</blockquote></details>

I will add this in separate PR
___
*[`ui/src/components/timetables/import/RouteDeviationLink.spec.tsx` line 108 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgyP37PEV1dd-oJwuLc:-Nh6jqc220VGj6YwK5Db:bd32f7t) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.spec.tsx#L108)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Dunno what is the established practice in this repository, but I would typically test specific elements (in this case the variant), and add classes for accessing those accurately in tests if needed. Less likely that the expects pass because the element happens to contain the expected test somewhere else. What do you think?
</blockquote></details>

I'm on same track. Changed tests to be more specific about what they assert
___
*[`ui/src/generated/graphql.tsx` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Ngx2kKn64F_wxtYFnP4:-NhAmZkG5drgO8PUTuBj:b5v4fam) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/77be8c9840898ad6b5945fc261a4e65d0441307f/ui/src/generated/graphql.tsx#L1)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

These come from commit [Update hasura image and generated sources](https://github.com/HSLdevcom/jore4-ui/pull/683/commits/77be8c9840898ad6b5945fc261a4e65d0441307f) that doesn't actually update the Hasura image.
</blockquote></details>

Dunno what is this? Something from rebasing?
___
*[`ui/src/locales/en-US/common.json` line 276 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxfEsKEONjEYC8nnSf:-NhAfoPPBQl9iMqeSPMj:b-84847m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/locales/en-US/common.json#L276)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Not sure what the int [...]

2023-10-20 07:30 UTC, Leitsi reviewed
> Reviewed 3 of 24 files at r6.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683)* status: 6 of 28 files reviewed, 2 unresolved discussions (waiting on @niknii-vincit)

___
*[`ui/src/hooks/vehicle-schedule-frame/useFindOrphanRoutes.spec.ts` line 125 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgycIfz1n-BAtDYLtAi:-NhAxVl8ATboDlGW1l77:b-htqtb8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/hooks/vehicle-schedule-frame/useFindOrphanRoutes.spec.ts#L125)):*
> `Title must be a string (eslint)`

Hmmh, okay, would've imagined that to work since `testName` is of string type. :shrug: 
This is good to go then, :ok_hand: 

> good or bad way to do things
> they are both at same time?

Basically yeah. Is a small trade-off in my opinion: more concise tests and less repetition (good), but debugging test failures is harder because errors inside loops tend to do that (bad).
Personally I'm still not sure which one is "better" in general. I do both.

Was just me ranting about general stuff, you can ignore the comment, this is all fine.


<!-- Sent from Reviewable.io -->

2023-10-20 07:31 UTC, Leitsi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-:-NhAzd-E1hpHnNASP__w:bnfp4nl)* status: 6 of 28 files reviewed, 2 unresolved discussions (waiting on @niknii-vincit)



<!-- Sent from Reviewable.io -->

2023-10-20 10:28 UTC, niknii-vincit commented
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 22 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxUXYwB__G3bJx5frk:-NhBc-ToA2HmEEt47mv0:bn2j2h2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L22)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Added `role='img'` but `IconType` don't have `alt` prop :(
</blockquote></details>

Hmm, it probably doesn't have a `title` either? Wonder if I should just rebase this and add it with all the other icon alt/title texts.. :thinking: 


<!-- Sent from Reviewable.io -->

2023-10-20 10:40 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683)* status: 6 of 28 files reviewed, 2 unresolved discussions (waiting on @Leitsi and @niknii-vincit)

___
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 22 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxUXYwB__G3bJx5frk:-NhBeuVi3Is0GvqtsjRg:b2b461p) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L22)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Hmm, it probably doesn't have a `title` either? Wonder if I should just rebase this and add it with all the other icon alt/title texts.. :thinking:
</blockquote></details>

Yeah, my bad. It has `title`, I will add it.


<!-- Sent from Reviewable.io -->

2023-10-20 10:46 UTC, niknii-vincit commented
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 27 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh2IPmVDBHMRM-qNSZE:-NhBf0oZ5MCcrS0GH3Fl:b-g2tsg2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L27)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Hmm, this looks clean, but should we still stick with design? Juha designed this a few weeks ago and this should be up to date.
</blockquote></details>

Ah, true. Well as a "compromise" solution: the design has the "Puuttuvat reitit" in a separate text field, and that's better than a single text block. Also, should the close button be implemented as well? :thinking: 


<!-- Sent from Reviewable.io -->

2023-10-20 12:54 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683)* status: 6 of 28 files reviewed, 2 unresolved discussions (waiting on @Leitsi and @niknii-vincit)

___
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 27 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh2IPmVDBHMRM-qNSZE:-NhBmGnt1PLPIsfk1lOZ:b-g6f744) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L27)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Ah, true. Well as a "compromise" solution: the design has the "Puuttuvat reitit" in a separate text field, and that's better than a single text block. Also, should the close button be implemented as well? :thinking:
</blockquote></details>

Yeah, I'm fine with that "compromise" solution. Added "Puuttuvat reitit" in separate line. Also added border color and changed layout a little bit. 

Good point that button is missing, not a game changer, tho. Added button to close the deviation section. Added `useEffect` to show the deviation section if deviations are changed. This way there is possibility to get deviations to show again without refresh.


<!-- Sent from Reviewable.io -->

2023-10-22 16:15 UTC, niknii-vincit commented
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 22 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-NgxUXYwB__G3bJx5frk:-NhN9fv58cktu8MOPaMx:bxvzklw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L22)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Yeah, my bad. It has `title`, I will add it.
</blockquote></details>

Awesome :fire: 


<!-- Sent from Reviewable.io -->

2023-10-22 16:19 UTC, niknii-vincit commented
*[`ui/src/components/timetables/import/RouteDeviationLink.tsx` line 18 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0KnpF064ZGelzU1uv:-NhNA0XN78CvLhwSnzdt:bbd8fkm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.tsx#L18)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Hmm, we went through how this works with Juha. I don't recall that he had anything to say where the link goes, but that wasn't the main point in discussion. For me it also makes more sense to change the link to `/timetables/lines/`
</blockquote></details>

Ah, I'm sorry if I said it in a misleading way. Clarifying just in case: I meant that there is no link from the Line's detailed view into the same Line's timetable view, which I discussed with Juha :smile: 

And on-topic: I also agree that `/timetables/lines/` makes more sense.


<!-- Sent from Reviewable.io -->

2023-10-22 16:35 UTC, niknii-vincit commented
*[`ui/src/components/timetables/import/DeviationSection.tsx` line 27 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh2IPmVDBHMRM-qNSZE:-NhN9ubTDapzo3Mj_coX:by80aam) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/DeviationSection.tsx#L27)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Yeah, I'm fine with that "compromise" solution. Added "Puuttuvat reitit" in separate line. Also added border color and changed layout a little bit. 

Good point that button is missing, not a game changer, tho. Added button to close the deviation section. Added `useEffect` to show the deviation section if deviations are changed. This way there is possibility to get deviations to show again without refresh.
</blockquote></details>

Sounds and looks good, great work! :ok_hand: 


<!-- Sent from Reviewable.io -->

2023-10-22 16:53 UTC, niknii-vincit reviewed
:shipit:

> Reviewed 15 of 24 files at r6, 5 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-:-NhNId8X6IQnnl6r2Edy:b-xr9eiq)* status: 23 of 28 files reviewed, all discussions resolved (waiting on @Leitsi)



<!-- Sent from Reviewable.io -->

2023-10-23 06:04 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683)* status: 23 of 28 files reviewed, all discussions resolved (waiting on @Leitsi and @niknii-vincit)

___
*[`ui/src/components/timetables/import/RouteDeviationLink.tsx` line 18 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/683#-Nh0KnpF064ZGelzU1uv:-NhQ7I8-522WDIlAmMqP:bhvp4ks) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d04c6d5ea6a2ce2147673d59deecc71564958385/ui/src/components/timetables/import/RouteDeviationLink.tsx#L18)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Ah, I'm sorry if I said it in a misleading way. Clarifying just in case: I meant that there is no link from the Line's detailed view into the same Line's timetable view, which I discussed with Juha :smile: 

And on-topic: I also agree that `/timetables/lines/` makes more sense.
</blockquote></details>

And we are talking about different things here :D My comments were about this PR. You and Tommi talked about adding link to other page... 


<!-- Sent from Reviewable.io -->

2023-10-23 06:27 UTC, merged