Add tests for creating common substitute operation days
HSLdevcom/jore4-ui pull request #725
Opened 2023-11-20 05:14 UTC by sr-vala

Resolves HSLdevcom/jore4#1388

2023-11-24 08:06 UTC, Perholehto requested changes
> Reviewed 5 of 7 files at r1, 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725)* status: all files reviewed, 10 unresolved discussions (waiting on @sr-vala)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-DQfy1taR05gHOUx2):*
If you gonna keep all these commits in here then I this `4d9d5b0` should be moved to after `c25148f`. This will keep all commits working.
___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 483 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-G_6m6JC_VA8Ao15G:-Nk-G_6m6JC_VA8Ao15H:b-rgiwnw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/e2e/commonSubstituteDays.cy.ts#L483)):*
> ```XML
>       vehicleScheduleDetailsPage.getShowAllValidSwitch().click();
> 
>       route1231InboundThursdayVehicleService
> ```

It's already long name, but for me it was not clear what is `...VehicleService`, if it was name `route1231InboundThursdayVehicleServiceTable` then it's easy to understand what were are checking.
___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 487 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-Gs9_8F8z3iGoGCRi:-Nk-Gs9_8F8z3iGoGCRj:b-q6yksf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/e2e/commonSubstituteDays.cy.ts#L487)):*
> ```XML
>         .should('contain', '1.1.2024 - 31.12.2024')
>         .and('contain', '3 lähtöä')
>         .and('contain', '11:05 ... 13:05');
> ```

For me this `.get().should(...).and()..` does not belong here, it's too low level for this file. As it seems this has been the way to use `VehicleServiceTable`. No actions needed here but would like to see `VehicleServiceTable` to be refactored in future
___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 596 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-LtzAEK-haHbrAegi:-Nk-LtzAEK-haHbrAegj:boi7sbg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/e2e/commonSubstituteDays.cy.ts#L596)):*
> ```XML
>       { tags: [Tag.Timetables] },
>       () => {
>         substituteDaySettingsPage.observationPeriodForm.setObservationPeriod(
> ```

Maybe here we could wait that page is loaded? I don't believe that users are that quick to change observation period. Tho not mandatory..
___
*[`cypress/pageObjects/CommonSubstitutePeriodForm.ts` line 7 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-E0bx8819W4mocwhr:-Nk-E0bx8819W4mocwhs:b-dzemz3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodForm.ts#L7)):*
> ```XML
> 
> export class CommonSubstitutePeriodForm {
>   commonSubstitutePeriodItem = new CommonSubstitutePeriodItem();
> ```

This good addition compared to `OccasionalSubstitutePeriodForm`
___
*[`cypress/pageObjects/CommonSubstitutePeriodForm.ts` line 29 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-EdfzBNd_UazR3Hyt:-Nk-EdfzBNd_UazR3Hyu:b-cwlwi9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodForm.ts#L29)):*
> ```XML
>   }
> 
>   removeCommonSubstituteDay(periodName: string) {
> ```

removeCommonSubstitutePeriod



_Code quote:_
```XML
removeCommonSubstituteDay
```
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NjgZ1sWC4QzoDf7SRkc:-NjgZ1sWC4QzoDf7SRkd:b-q9s2rk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cfe6552ae428d030f6e2bccf5e378068bb9a48b9/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L43)):*
> ```XML
>   selectLineType(lineType: string) {
>     this.getLineTypeDropdown().click();
>     // Sometimes checkboxes are all checked and sometimes none are checked.
> ```

Does these comments describe current behavior ?
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 8 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-F6xDB2eqX4--Ei8w:-Nk-F6xDB2eqX4--Ei8x:bxvmnpu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L8)):*
> ```XML
> 
> export class CommonSubstitutePeriodItem {
>   getPeriodContainer(periodName: string) {
> ```

I think here `getContainer` is enough for naming. Do you think its not informative enough?
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 41 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-8ey24qfM5pqYHy3D:-Nk-8ey24qfM5pqYHy3E:b-g5xm7v) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L41)):*
> ```XML
>   }
> 
>   selectLineType(lineType: string) {
> ```

This function has lot of duplication if you compare it to `OccasionalSubstitutePeriodForm` -> `selectLineType` There could be more general function and then these form specifics. Would that DRY this code?

And why this function takes `string` but same function in `OccasionalSubstitutePeriodForm` takes `string[]` ?
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 45 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-8Yre5zwz8YxMgWiu:-Nk-8Yre5zwz8YxMgWiv:b-ud22i1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L45)):*
> ```XML
>     // Sometimes checkboxes are all checked and sometimes none are checked.
>     // Uncheck them all if any are checked.
>     cy.get('ul').then((ul) => {
> ```

This `ul` should have `data-testid` to use
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 47 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-C2MV5PQEAJAELfks:-Nk-C2MV5PQEAJAELfkt:bs1xijc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L47)):*
> ```XML
>     cy.get('ul').then((ul) => {
>       if (ul.find('input[type="checkbox"]:checked').length > 0) {
>         cy.get('input[type="checkbox"]:checked').uncheck();
> ```

`lineTypeDropdown` has no checked boxes when initially loading page. This doesn't make sense when this function is called twice, because what was selected in first call is removed in second call. 


<!-- Sent from Reviewable.io -->

2023-11-27 10:00 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725)* status: 7 of 10 files reviewed, 10 unresolved discussions (waiting on @Perholehto)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-DQfy1taR05gHOUx2):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

If you gonna keep all these commits in here then I this `4d9d5b0` should be moved to after `c25148f`. This will keep all commits working.
</blockquote></details>

I did a fixup into the original commit.
___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 483 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-G_6m6JC_VA8Ao15G:-NkEP6A96GJS_EtFQmNc:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/e2e/commonSubstituteDays.cy.ts#L483)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

It's already long name, but for me it was not clear what is `...VehicleService`, if it was name `route1231InboundThursdayVehicleServiceTable` then it's easy to understand what were are checking.
</blockquote></details>

Done.
___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 487 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-Gs9_8F8z3iGoGCRi:-NkEP6vCE3EjgvQ68uyQ:brznxx2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/e2e/commonSubstituteDays.cy.ts#L487)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

For me this `.get().should(...).and()..` does not belong here, it's too low level for this file. As it seems this has been the way to use `VehicleServiceTable`. No actions needed here but would like to see `VehicleServiceTable` to be refactored in future
</blockquote></details>

This comment is a bit too vague for me to do anything about this.
___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 596 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-LtzAEK-haHbrAegi:-NkEPMmq62Lbz3_LYJxG:b-6a10pe) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/e2e/commonSubstituteDays.cy.ts#L596)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Maybe here we could wait that page is loaded? I don't believe that users are that quick to change observation period. Tho not mandatory..
</blockquote></details>

There is no specific way to "wait that page is loaded" in Cypress. Do you mean waiting for some request to finish? Cypress does have built-in checks for element actionability: https://docs.cypress.io/guides/core-concepts/interacting-with-elements
___
*[`cypress/pageObjects/CommonSubstitutePeriodForm.ts` line 29 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-EdfzBNd_UazR3Hyt:-NkESm0_4WoOBnwQcxRP:beee6hn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodForm.ts#L29)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

removeCommonSubstitutePeriod
</blockquote></details>

Made me wonder why the UI uses the word 'days' instead of 'periods'.
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NjgZ1sWC4QzoDf7SRkc:-NkEfITZ8Uo0-Im6dVZo:b-ehc26u) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cfe6552ae428d030f6e2bccf5e378068bb9a48b9/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L43)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Does these comments describe current behavior ?
</blockquote></details>

Yes, the functionality is not stable.
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 8 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-F6xDB2eqX4--Ei8w:-NkETLGG7Qau_y3v_1jg:b-l01vbv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L8)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I think here `getContainer` is enough for naming. Do you think its not informative enough?
</blockquote></details>

getContainer should be enough since the class name provides context.
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 41 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-8ey24qfM5pqYHy3D:-NkETdZr-HT15bQpOqaN:b-h08faa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L41)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

This function has lot of duplication if you compare it to `OccasionalSubstitutePeriodForm` -> `selectLineType` There could be more general function and then these form specifics. Would that DRY this code?

And why this function takes `string` but same function in `OccasionalSubstitutePeriodForm` takes `string[]` ?
</blockquote></details>

I think that would mean creating a separate page object for LineTypeMultiSelectDropdown. This requires changes to test-ids and three page objects, so I would like to think about this in a separate issue after this general functionality has been merged.
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 45 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-8Yre5zwz8YxMgWiu:-NkEj_Y7Ez6YARR_Zb8B:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L45)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

This `ul` should have `data-testid` to use
</blockquote></details>

Done.
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 47 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-C2MV5PQEAJAELfks:-NkEk9t05SLgQiKtIIew:b-4u8ous) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L47)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

`lineTypeDropdown` has no checked boxes when initially loading page. This doesn't make sense when this function is called twice, because what was selected in first call is removed in second call.
</blockquote></details>

When running these Cypress tests the boxes are checked sometimes and sometimes they are not. I'm not sure what could cause this behavior.

In my mind this functions simply since the line types that are provided as arguments are always explicitly the only ones that will be selected.


<!-- Sent from Reviewable.io -->

2023-11-28 07:48 UTC, Perholehto requested changes
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @sr-vala)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-DQfy1taR05gHOUx2):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I did a fixup into the original commit.
</blockquote></details>

Hmm, it seems that you just squashed these to a one commit? 
___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 487 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-Gs9_8F8z3iGoGCRi:-NkJoSb36SLM8TDXbQ1_:b-ii4r9m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/e2e/commonSubstituteDays.cy.ts#L487)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

This comment is a bit too vague for me to do anything about this.
</blockquote></details>

No actions needed as I mentioned in original comment, but I think this could use refactoring in near future. 

I will try to explain it again, because it was vague for you. Tho would be great to know what part was vague.

In this file there is 
```  
substituteDaySettingsPage.observationPeriodForm.setObservationPeriod('2024-01-01', '2024-12-31');
substituteDaySettingsPage.commonSubstitutePeriodForm.editCommonSubstitutePeriod({
  periodName: 'Tapaninpäivä 2024',
  substituteDay: 'Lauantai',
  lineType: 'Peruslinja',
});
```
and this

```
route1231InboundThursdayVehicleService
  .get()
  .should('contain', '26.12.2024 - 26.12.2024')
  .and('contain', '2 lähtöä')
  .and('contain', '07:05 ... 08:20');
route1231InboundSaturdayVehicleService
  .get()
  .should('contain', '1.1.2024 - 31.12.2024')
  .and('contain', '2 lähtöä')
  .and('contain', '07:05 ... 08:20');
```
For me there is clearly two levels of abstraction there, `substituteDaySettingsPage` abstracts nicely Cypress things to functions and if we use those functions there is no need to know Cypress stuff. Second example has some abstraction but it still brings all the implementation details to high level. 

Do you now understand why I wrote that comment? Any other thoughts ?
___
*[`cypress/pageObjects/CommonSubstitutePeriodForm.ts` line 29 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-EdfzBNd_UazR3Hyt:-NkJkUi26SDy62JGlyjN:bv9bq1b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodForm.ts#L29)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Made me wonder why the UI uses the word 'days' instead of 'periods'.
</blockquote></details>

I think you need to wonder this in more general discussion forum than this PR 
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NjgZ1sWC4QzoDf7SRkc:-NkJjaad5iT2cGykAXqI:b8rro8l) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cfe6552ae428d030f6e2bccf5e378068bb9a48b9/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L43)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Yes, the functionality is not stable.
</blockquote></details>

Hmm, so the functionality is stable in `OccasionalSubstitutePeriodForm>selectLineTypes` but not here? If this is the case I would argue that something needs to be done.

How I can reproduce flakiness? I would like to check why there is this behavior.
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 41 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-8ey24qfM5pqYHy3D:-NkJnXA42323M0-Uy6lt:b-3qf2ao) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L41)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I think that would mean creating a separate page object for LineTypeMultiSelectDropdown. This requires changes to test-ids and three page objects, so I would like to think about this in a separate issue after this general functionality has been merged.
</blockquote></details>

I'm fine with this. I hope this gets priority because now it's only three page objects, when time passes it can be more work..
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 47 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-C2MV5PQEAJAELfks:-NkJm9Gf2ipUkMli8K7v:b5dw96) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L47)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

When running these Cypress tests the boxes are checked sometimes and sometimes they are not. I'm not sure what could cause this behavior.

In my mind this functions simply since the line types that are provided as arguments are always explicitly the only ones that will be selected.
</blockquote></details>

How does the function caller know that this function has behavior that clears selections that have been made? If I call function `selectLinetypes` I cant know that first it will clear selection and then choose those.

If you want this to be a simple, create a function that clears the checkboxes eg `clearLinetypes()` and then `selectLinetypes` truly only selects linetypes 

But this doesn't solve the problem with unclear behavior...


<!-- Sent from Reviewable.io -->

2023-11-30 08:09 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725)* status: 8 of 14 files reviewed, 4 unresolved discussions (waiting on @Perholehto)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-DQfy1taR05gHOUx2):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Hmm, it seems that you just squashed these to a one commit?
</blockquote></details>

I did a fixup to the first commit, so yes, they are in the same commit now. Would it be better to keep all the commits separate?
___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 487 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-Gs9_8F8z3iGoGCRi:-NkTmv_QDBib20JWrG_b:b-duul49) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/e2e/commonSubstituteDays.cy.ts#L487)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

No actions needed as I mentioned in original comment, but I think this could use refactoring in near future. 

I will try to explain it again, because it was vague for you. Tho would be great to know what part was vague.

In this file there is 
```  
substituteDaySettingsPage.observationPeriodForm.setObservationPeriod('2024-01-01', '2024-12-31');
substituteDaySettingsPage.commonSubstitutePeriodForm.editCommonSubstitutePeriod({
  periodName: 'Tapaninpäivä 2024',
  substituteDay: 'Lauantai',
  lineType: 'Peruslinja',
});
```
and this

```
route1231InboundThursdayVehicleService
  .get()
  .should('contain', '26.12.2024 - 26.12.2024')
  .and('contain', '2 lähtöä')
  .and('contain', '07:05 ... 08:20');
route1231InboundSaturdayVehicleService
  .get()
  .should('contain', '1.1.2024 - 31.12.2024')
  .and('contain', '2 lähtöä')
  .and('contain', '07:05 ... 08:20');
```
For me there is clearly two levels of abstraction there, `substituteDaySettingsPage` abstracts nicely Cypress things to functions and if we use those functions there is no need to know Cypress stuff. Second example has some abstraction but it still brings all the implementation details to high level. 

Do you now understand why I wrote that comment? Any other thoughts ?
</blockquote></details>

I think I understand you comment. Is it any better now?
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NjgZ1sWC4QzoDf7SRkc:-NkU1aMxDya2J02XS0mV:bbg5dpk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cfe6552ae428d030f6e2bccf5e378068bb9a48b9/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L43)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Hmm, so the functionality is stable in `OccasionalSubstitutePeriodForm>selectLineTypes` but not here? If this is the case I would argue that something needs to be done.

How I can reproduce flakiness? I would like to check why there is this behavior.
</blockquote></details>

It is not stable in either one.

You can see the behavior when you just run the tests with the Cypress test runner open, using yarn test:e2e:open. If you remove the check for checked checkboxes, the tests will sometimes have all line types selected.
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 41 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-8ey24qfM5pqYHy3D:-NkTz1J-5nKZOB9GvqDv:b-eppbcm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L41)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I'm fine with this. I hope this gets priority because now it's only three page objects, when time passes it can be more work..
</blockquote></details>

I think there is time for this before we start needing tests for stop registry functionality. I created an issue for this now. https://github.com/HSLdevcom/jore4/issues/1620
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 47 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-C2MV5PQEAJAELfks:-NkU3Gws5-p4cX-Wse9Q:bjy9ie8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L47)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

How does the function caller know that this function has behavior that clears selections that have been made? If I call function `selectLinetypes` I cant know that first it will clear selection and then choose those.

If you want this to be a simple, create a function that clears the checkboxes eg `clearLinetypes()` and then `selectLinetypes` truly only selects linetypes 

But this doesn't solve the problem with unclear behavior...
</blockquote></details>

Added a jsdoc comment for the behavior.


<!-- Sent from Reviewable.io -->

2023-12-01 06:52 UTC, Perholehto requested changes
> Reviewed 3 of 6 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @sr-vala)

___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 487 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-Gs9_8F8z3iGoGCRi:-NkZ8YA39X_XtjsfINaB:b-lrkmlt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/e2e/commonSubstituteDays.cy.ts#L487)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

I think I understand you comment. Is it any better now?
</blockquote></details>

Do you think it is better?
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NjgZ1sWC4QzoDf7SRkc:-NkZ7sPe4xmc3MopAjj4:b-l9jmih) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cfe6552ae428d030f6e2bccf5e378068bb9a48b9/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L43)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

It is not stable in either one.

You can see the behavior when you just run the tests with the Cypress test runner open, using yarn test:e2e:open. If you remove the check for checked checkboxes, the tests will sometimes have all line types selected.
</blockquote></details>

I removed the part where checkboxes are clicked and ran 'Should create and delete a common substitute operating period successfully' test 10 times. Every time I manually checked that there wasn't initially any boxes checked and test succeeded every time. Are you sure that there is this behavior ? 
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 47 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-C2MV5PQEAJAELfks:-NkZ7KNu6JnYamOH6_j9:b7cg63f) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L47)):*
<details><summary><i>Previously, sr-vala (Samuli Rasi) wrote…</i></summary><blockquote>

Added a jsdoc comment for the behavior.
</blockquote></details>

For comment to show when hovering over a function, it should be before functions signature



_Code snippet:_
```XML
  /**
  * Unchecks all line type checkboxes if any are checked
  * and then checks the checkboxes for the line types that
  * are provided as arguments. Checkbox unchecking is needed
  * because the element functionality is unstable in Cypress and
  * sometimes checkboxes are all checked and sometimes none are checked
  * initially.
  */
  selectLineTypes(lineTypes: string[]) {
    ....}
```


<!-- Sent from Reviewable.io -->

2023-12-04 06:26 UTC, sr-vala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725)* status: 9 of 15 files reviewed, 3 unresolved discussions (waiting on @Perholehto)

___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 487 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-Gs9_8F8z3iGoGCRi:-NknThtG1303mfR6P_65:b-mkvzae) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/e2e/commonSubstituteDays.cy.ts#L487)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Do you think it is better?
</blockquote></details>

I must have changed the wrong spot in the code. Made the changes to each part where this .get() was used.
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 43 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NjgZ1sWC4QzoDf7SRkc:-NknUESAAtAd2acRlkC7:bd2w59m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/cfe6552ae428d030f6e2bccf5e378068bb9a48b9/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L43)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I removed the part where checkboxes are clicked and ran 'Should create and delete a common substitute operating period successfully' test 10 times. Every time I manually checked that there wasn't initially any boxes checked and test succeeded every time. Are you sure that there is this behavior ?
</blockquote></details>

If the checkbox workaround is removed the tests do not behave as they should, for me locally and in the CI.
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 47 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-Nk-C2MV5PQEAJAELfks:-NknVTB84TxaqBnRbm9G:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/358e31c891148f90d6a1ec94fd0fc25643faee41/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L47)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

For comment to show when hovering over a function, it should be before functions signature
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-11 13:59 UTC, HenrikHartiala reviewed
> Reviewed 1 of 7 files at r1, 1 of 3 files at r10, 5 of 14 files at r12, 2 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725)* status: all files reviewed, 7 unresolved discussions (waiting on @Leitsi and @Perholehto)

___
*[`-- commits` line 17 at r13](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NshUA5J4wD1IcDSMPcq):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Not sure which commit `ffb16f2c` references since it doesn't seem to exist.
</blockquote></details>

Hmm, thought that reflog would find it, but cant. Maybe I'll just remove tha hash. Also the message was outdated also, already fixed many TODO's.
___
*[`-- commits` line 18 at r13](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NshUM9X5qhX0O5-TUcw):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

> functios
</blockquote></details>

Reworded all commits.
___
*[`-- commits` line 19 at r13](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NshUUdSAWmPQmyxHYqp):*
Reworded all commits.
___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 611 at r13](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NshWZ1t8fKyxVHu3uJs:-Nsh_WvB950ZjXjnKlT2:b-yj644q) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f6e95c75a2dc8ef09945788e9da3936982b5e49f/cypress/e2e/commonSubstituteDays.cy.ts#L611)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This current approach of adding via UI doesn't seem too bad either, since it's just one form fill.
</blockquote></details>

Yeah, probably not. I think it doesn't take that much time either. I just don't like to have the setup done with the UI and thought that it would be more clear if we separate UI-actions and base data completely. But yeah I can take the TODO out, its not that big of a deal here.
___
*[`cypress/e2e/commonSubstituteDays.cy.ts` line 657 at r13](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NshWqI6446tbrOekUnb:-NshlZgsEnn3KpbrOrfb:bel2am4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f6e95c75a2dc8ef09945788e9da3936982b5e49f/cypress/e2e/commonSubstituteDays.cy.ts#L657)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Guess we didn't have any more detailed error messages in this case? Or any other way for the user to know what went wrong. Seems like it could be a bit cryptic without any more info.
</blockquote></details>

Good one! Had to check, but there actually _is_ more to it in the toast message. Added the whole message to this assert.
___
*[`cypress/pageObjects/CommonSubstitutePeriodItem.ts` line 1 at r13](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-NshXjj96l1Duu6eP0t1:-NshmKCbBz5t4mWIK5Dn:b-ps5nf1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f6e95c75a2dc8ef09945788e9da3936982b5e49f/cypress/pageObjects/CommonSubstitutePeriodItem.ts#L1)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This is only used from `CommonSubstitutePeriodForm`, so should it be there? Maybe even just inline the type to the one function where it is used.
</blockquote></details>

Yeah, that sounds better I'll remove the interface. Good one, missed this completely.


<!-- Sent from Reviewable.io -->

2024-03-13 06:42 UTC, Leitsi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/725#-:-NsqY1JmCxYqAJe8Zenx:bnfp4nl)* status: 21 of 25 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala and @Perholehto)



<!-- Sent from Reviewable.io -->

2024-03-13 08:11 UTC, merged