Add import loading indicators
HSLdevcom/jore4-ui pull request #729
Opened 2023-11-24 11:55 UTC by HenrikHartiala

Note to reviewer: the two renaming commits have a small overlap, but since they are conceptually different renames, it is better to have them in their own commits.

Commits:
* Rename isModalOpen variables
Just to clarify that these are flags for modal being open or closed. `IsSaving` points towards something
actively happening while this is true, but that is a bit misleading. Also the onClick handlers
are renamed with the same reason.
* Rename cancel import to abort import
Abort implies towards some process that has already been started and requires revert actions.
Cancel implies more towards clearing something that has not yet been done. The finnish equivalents are
"Keskeytä" and "Peruuta"
* Add LoadingOverlay to import actions
Also disable save and close buttons on preview whilst loading.
Resolves https://github.com/HSLdevcom/jore4/issues/1605

2023-11-28 06:33 UTC, Perholehto requested changes
> Reviewed 1 of 1 files at r1, 6 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729)* status: all files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 15 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729#-NkJaK-D6NukdrD7M9im):*
I think it would be a good addition to have  guidelines(?) in Readme about `useLoader` and `loader` selector and slice?
___
*[`ui/src/components/timetables/import/ImportTimetablesPage.tsx` line 139 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729#-NkJbklSEEDbtsB_Ney1:-NkJbklSEEDbtsB_Ney2:bz6i6vl) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84c28a6d2eff3e107018b605a76a17921692175e/ui/src/components/timetables/import/ImportTimetablesPage.tsx#L139)):*
> ```XML
>         }}
>       />
>       <LoadingOverlay testId={testIds.loading} visible={isLoading} />
> ```

Hmm, I need to reminded about this decision. Didn't we decide that this should be "global"? Also might be that I mix up discussion and decisions :D


<!-- Sent from Reviewable.io -->

2023-11-28 08:14 UTC, Perholehto requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729)* status: all files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/hooks/timetables-import/useTimetablesImport.ts` line 185 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729#-NkJz6Oh8EbC4ppbHBnA:-NkJz6OiAHvytDcpK4yr:bplkd0k) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84c28a6d2eff3e107018b605a76a17921692175e/ui/src/hooks/timetables-import/useTimetablesImport.ts#L185)):*
> ```XML
>     priority: TimetablePriority,
>   ) => {
>     setIsImportLoading(true);
> ```

Would it make sense to use `loading` from mutation hooks when its possible? Then we can set `useEffect` and no need to set loading inside those functions. This occurred to me when I wrote delete timetable implementation...
```
useEffect(() => {
setIsLoading(loading);
}, [loading, setIsLoading]);
```


<!-- Sent from Reviewable.io -->

2023-11-28 11:07 UTC, Perholehto requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729)* status: all files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/hooks/timetables-import/useTimetablesImport.ts` line 185 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729#-NkJz6Oh8EbC4ppbHBnA:-NkKb2iS0BxT4MaolEOq:b-mlg35g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84c28a6d2eff3e107018b605a76a17921692175e/ui/src/hooks/timetables-import/useTimetablesImport.ts#L185)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Would it make sense to use `loading` from mutation hooks when its possible? Then we can set `useEffect` and no need to set loading inside those functions. This occurred to me when I wrote delete timetable implementation...
```
useEffect(() => {
setIsLoading(loading);
}, [loading, setIsLoading]);
```
</blockquote></details>

After testing this more, it's not robust. So you can skip this comment...


<!-- Sent from Reviewable.io -->

2023-11-29 08:39 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @Perholehto)

___
*[`-- commits` line 15 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729#-NkJaK-D6NukdrD7M9im):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

I think it would be a good addition to have  guidelines(?) in Readme about `useLoader` and `loader` selector and slice?
</blockquote></details>

Yes good point, I'll add some guidelines / instructions for this.
___
*[`ui/src/components/timetables/import/ImportTimetablesPage.tsx` line 139 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729#-NkJbklSEEDbtsB_Ney1:-NkLM5OT9Q6GzTyzcyAf:b9z8yxj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84c28a6d2eff3e107018b605a76a17921692175e/ui/src/components/timetables/import/ImportTimetablesPage.tsx#L139)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

Hmm, I need to reminded about this decision. Didn't we decide that this should be "global"? Also might be that I mix up discussion and decisions :D
</blockquote></details>

Yes, I also got confused and then I think that my thought process went towards this when I realised that I need the isLoading to disable the buttons as well. But I think we can still use the Global loader for this and if we get in to problems with that, then change it to something like this.
___
*[`ui/src/hooks/timetables-import/useTimetablesImport.ts` line 185 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729#-NkJz6Oh8EbC4ppbHBnA:-NkLM27O9lGUderQzBdd:b4bb46b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/84c28a6d2eff3e107018b605a76a17921692175e/ui/src/hooks/timetables-import/useTimetablesImport.ts#L185)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

After testing this more, it's not robust. So you can skip this comment...
</blockquote></details>

Cheeeck


<!-- Sent from Reviewable.io -->

2023-11-29 09:39 UTC, Perholehto approved these changes
> Reviewed 4 of 6 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/729)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @HenrikHartiala)



<!-- Sent from Reviewable.io -->

2023-11-29 10:42 UTC, merged