Timetables version details sidepanel
HSLdevcom/jore4-ui pull request #769
Opened 2024-02-20 12:19 UTC by HenrikHartiala

Commits: 
* Refactor VehicleJourneyGroupInfo parameters to require only necessary
This component had unnecessary requirements for parameters. It required `VehicleJourneyGroup`
as parameter, even though it did not need all attributes within that type.
Also the VehicleJourneyGroup made the requirements to be so that vehicleJourney's had to be
type `VehicleJourneyWithService` which reduced the reusability greatly or forced to use that fragment.
Only the start_time's are required for this component which is now the only required attribute. (<Pick..>)

* Add timetable version details panel functionality
This version details will open the timetable schedules of the selected version, which corresponds to the selected
versions vehicleScheduleFrame's schedules. This view is now currently the only way you can view all the timetables
within one vehileScheduleFrame, which is crucial if the user wants to change the validity of a timetable, because
it affects the validity period of the whole vehicle schedule frame.
This is pretty big commit and it has some overlapping components with existing code, and the existing code can be also refactored
to use some of the new components. For example `TimetableHeading` can be relocated and used with the existing
  * Added a optional `onChange` callback function to `ChangeTimetablesValidityModal`, so that we add custom
functionality in case of change e.g. re-fetching some view data.

2024-02-21 12:00 UTC, Leitsi requested changes
> Reviewed 4 of 4 files at r1, 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: all files reviewed, 15 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/timetables/versions/index.ts` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA55AyDWinbAUXtHGg:-NrA55AyDWinbAUXtHGh:b-nluoem) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/index.ts#L4)):*
> ```XML
> export * from './TimetableVersionTableRow';
> export * from './TimetableVersionsPage';
> export * from './timetable-version-details-panel/TimetableVersionDetailsPanel';
> ```

Shouldn't this just export the whole folder, `export * from './timetable-version-details-panel;`
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 116 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAEhGA9slc0Hhuxl2B:-NrAEhGA9slc0Hhuxl2C:b-n99v8p) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L116)):*
> ```XML
>       <td className={statusClassName}>{statusText}</td>
>       <td className={dayTypeClassName}>
>         {parseI18nField(data.dayType.nameI18n)}
> ```

Could just use the `dayType` variable here since it is already parsed above.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 117 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA7F-k1cIiQ9rhqCbx:-NrA7F-l0iPVitvG50B9:blf1u7m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L117)):*
> ```XML
>       <td className={dayTypeClassName}>
>         {parseI18nField(data.dayType.nameI18n)}
>         {/* TODO: <Visible> component was changed so can't be used here as it is, since it currently
> ```

Think I saw this exact error on some other table. Am in favor of reverting, I don't see why the id couldn't just be added to some separate div wrapper. FYI @niknii-vincit 
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 122 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA6ehfDK7hAQiHvy2Z:-NrA6ehgED4auM2INeD2:b-a5w3q) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L122)):*
> ```XML
>           <IconButton
>             onClick={openVersionPanel}
>             icon={<i className="icon-calendar" />}
> ```

This icon could use some tooltip text.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 145 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAEYHa2g4Yz_rmutQr:-NrAEYHa2g4Yz_rmutQs:b7ppq67) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L145)):*
> ```XML
>               status: statusText,
>               schedule: vehicleScheduleFrameName,
>               dayType: parseI18nField(dayType),
> ```

dayType is already parsed above, `const dayType = parseI18nField(data.dayType.nameI18n);`.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx` line 37 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrANN0jDLXaIc-XvX0T:-NrANN0jDLXaIc-XvX0U:b-2vxkns) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx#L37)):*
> ```XML
>             direction={direction}
>             className="my-5 ml-12"
>             titleName={t(`directionEnum.${direction}`)}
> ```

In every instance where this `DirectionBadge` is used, there's always `titleName={t(`directionEnum.${direction}`)}` Since `direction? is passed as parameter as well, this could/should probably be handled inside the `DirectionBadge` component.
Not an issue of this PR, but could maybe refactor here all the same, or just kick the can down the road.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAOtpm3vQoMxBF-4mn:-NrAOtpm3vQoMxBF-4mo:bhrndg2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx#L40)):*
> ```XML
>           />
>           <div className="ml-3.5 mt-1">
>             <span className="block font-bold">{routeLabel}</span>
> ```

Could be a `h3`?
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/index.ts` line 2 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA5Mbk5v2Ni6SIKkG9:-NrA5Mbk5v2Ni6SIKkGA:b-g9f0qn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/index.ts#L2)):*
> ```XML
> export * from './ExpandableRouteTimetableRow';
> export * from './TimetableHeading';
> ```

`RouteTimetableCard` missing here.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA5dOhEbR2igeJN0dA:-NrA5dOhEbR2igeJN0dB:bk2ow06) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx#L16)):*
> ```XML
> }
> 
> const getOddRowColor = (key: TimetablePriority) => {
> ```

This seems to be copypasted from `VehicleServiceTable`. Also both of these are only passed as parameter to `VehicleServiceRow`.
I think I would maybe remove this whole getter from this file. It doesn't make much sense since we use a hardcoded priority here. Maybe add `bg-hsl-neutral-blue` as default for the `oddRowColor` parameter in `VehicleServiceRow`.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx` line 43 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAJ2Ix1SeZFk9VKiEQ:-NrAJ2Ix1SeZFk9VKiER:b-c21nu7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx#L43)):*
> ```XML
>       sectionIdentifier={sectionIdentifier}
>     >
>       <div className="space-y-2" id={sectionIdentifier}>
> ```

Top margin missing here, looks about `mt-4`
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableHeading.tsx` line 10 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAKkDuBrsQbF4ZEp8a:-NrAKkDuBrsQbF4ZEp8b:bapcv8h) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableHeading.tsx#L10)):*
> ```XML
> import { getTimetableHeadingBgColor } from '../../vehicle-schedule-details';
> 
> export const TimetableHeading: React.FC<{
> ```

This looks quite like the `timetableHeadingButton` in `VehicleServiceTable` (where it is clickable, though). Could be an opportunity for refactoring.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.tsx` line 37 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAGmnpAsZND4iX8WSq:-NrAGmnpAsZND4iX8WSr:bny5kr9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.tsx#L37)):*
> ```XML
>   }, [...]

2024-02-26 10:59 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 4 of 28 files reviewed, 15 unresolved discussions (waiting on @Leitsi and @niknii-vincit)

___
*[`ui/src/components/timetables/versions/index.ts` line 4 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA55AyDWinbAUXtHGg:-NrZGf_D8c9hDQfHeIdr:b-oidhef) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/index.ts#L4)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Shouldn't this just export the whole folder, `export * from './timetable-version-details-panel;`
</blockquote></details>

yes, good one. I might have moved this in to a folder afterwards and then VS code has autochanged this path and I did not notice it.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 116 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAEhGA9slc0Hhuxl2B:-NrZHDeM8_92b4E8bdX5:b9u7bpw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L116)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could just use the `dayType` variable here since it is already parsed above.
</blockquote></details>

Yes. Also noticed these when we went through some of the existing code with Niki on Thursday. For me these were broken for a while and I probably "fixed" things after the rebase. But yeah, everything were fine in the existing code so I'll just revert tthese
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 117 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA7F-k1cIiQ9rhqCbx:-NrZHcRM7kg9vZd8j0D5:by9oetq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L117)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Think I saw this exact error on some other table. Am in favor of reverting, I don't see why the id couldn't just be added to some separate div wrapper. FYI @niknii-vincit
</blockquote></details>

Yep, discussed this with Niki on Thursday.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 122 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA6ehfDK7hAQiHvy2Z:-NrZIU0b6SIsMSM9yFtE:b12vxgf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L122)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This icon could use some tooltip text.
</blockquote></details>

:+1: Added
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 145 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAEYHa2g4Yz_rmutQr:-NrZL5qyCxYjaxHa54bu:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L145)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

dayType is already parsed above, `const dayType = parseI18nField(data.dayType.nameI18n);`.
</blockquote></details>

:+1: 
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx` line 37 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrANN0jDLXaIc-XvX0T:-NrZMkQv2eX__PJ3X3qA:b-cx14ei) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx#L37)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

In every instance where this `DirectionBadge` is used, there's always `titleName={t(`directionEnum.${direction}`)}` Since `direction? is passed as parameter as well, this could/should probably be handled inside the `DirectionBadge` component.
Not an issue of this PR, but could maybe refactor here all the same, or just kick the can down the road.
</blockquote></details>

Good one, I'll keep this in mind and will try to remember to add a refactor commit after this.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAOtpm3vQoMxBF-4mn:-NrZMS-qBIbcSndZO037:bw4wt6d) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx#L40)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Could be a `h3`?
</blockquote></details>

Hmm, not sure if that is the correct one from e.g. accessibility point of view. This is a list element, and the label is just bolded. I think we should not use heading here. What does @niknii-vincit think?
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/index.ts` line 2 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA5Mbk5v2Ni6SIKkG9:-NrZNLW04mrtL5_xJWWe:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/index.ts#L2)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

`RouteTimetableCard` missing here.
</blockquote></details>

:+1: 
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA5dOhEbR2igeJN0dA:-NrZOM_l1dndCt26Lek0:b7sm1f0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx#L16)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This seems to be copypasted from `VehicleServiceTable`. Also both of these are only passed as parameter to `VehicleServiceRow`.
I think I would maybe remove this whole getter from this file. It doesn't make much sense since we use a hardcoded priority here. Maybe add `bg-hsl-neutral-blue` as default for the `oddRowColor` parameter in `VehicleServiceRow`.
</blockquote></details>

Good one! Like you said, it's just copy pasted. Now that I look at it, it really doesn't make much sense. I think the VehicleServiceRow code could be implemented with a bit different way, but that is for the future. I'll now put it as default parameter as you said :ok_hand: 
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx` line 43 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAJ2Ix1SeZFk9VKiEQ:-NrZSO0mCJWzDRZLjVgJ:b4putsz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx#L43)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Top margin missing here, looks about `mt-4`
</blockquote></details>

:ok_hand: 
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableHeading.tsx` line 10 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAKkDuBrsQbF4ZEp8a:-NrZSRvC5fWlEt4XdXBv:bqkbzno) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableHeading.tsx#L10)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrot [...]

2024-02-26 11:08 UTC, niknii-vincit commented
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 117 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA7F-k1cIiQ9rhqCbx:-Nr_4zz31WQeR_EoGkF1:b-qdaepd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L117)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yep, discussed this with Niki on Thursday.
</blockquote></details>

Yup! I reverted the div wrapping and the id's have been changed to the childrens' pre-existing wrapping divs :ok_hand: 


<!-- Sent from Reviewable.io -->

2024-02-26 11:50 UTC, niknii-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 17 of 28 files reviewed, 15 unresolved discussions (waiting on @Leitsi)

___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAOtpm3vQoMxBF-4mn:-Nr_EbheBGoq5Znxot_i:b708ghv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx#L40)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, not sure if that is the correct one from e.g. accessibility point of view. This is a list element, and the label is just bolded. I think we should not use heading here. What does @niknii-vincit think?
</blockquote></details>

I agree that this should be a heading, but `h4`, because the entire section should have a `h3` above (as mentioned in another comment). They are list items sure, but they are the headings for the expandable section below them.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx` line 18 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAMQEyC3G2ramvsRy6:-Nr_DpF3-jZcm2MFmN6r:b-3b9qlo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx#L18)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Well I think yes and now. Semantically they are different and probably accessibility-wise we should use span here. The "block" classname is just for the layout, but we still want it to be a span. At least thats how I understand it. What do you think @niknii-vincit
</blockquote></details>

I think this should be a heading. The heading level is defined by the location we open the dialog in, so in this case (if the heading levels in the main page would correctly start from `h1`, instead of `h2`), it would be `h3`. I think the same style can be kept with spans within the `h3` element, but it being a header, makes it more scannable.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx` line 19 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAMH1w-baU0kyAN0ls:-Nr_ERfDCH0Xom9XqwAV:b-xuzoc6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx#L19)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yeah, this is the heading of the panel, so these could probably be headings then :D 
What does @niknii-vincit think?
</blockquote></details>

Same here as above


<!-- Sent from Reviewable.io -->

2024-02-26 14:54 UTC, niknii-vincit commented
*[`ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAOtpm3vQoMxBF-4mn:-Nr_tpgpDMSeMNfmPyBw:bdzsldp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx#L40)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

I agree that this should be a heading, but `h4`, because the entire section should have a `h3` above (as mentioned in another comment). They are list items sure, but they are the headings for the expandable section below them.
</blockquote></details>

Consulted Accessibility expert, and they said that the modal should start with a `h2`, because it's basically a new document for screen readers.


<!-- Sent from Reviewable.io -->

2024-02-26 15:00 UTC, niknii-vincit commented
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.tsx` line 50 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-Nr_ud993h078Fhmhls0:-Nr_ud993h078Fhmhls1:b-rullhj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a467d0457126de369d95ac48815c0959faa1bfd8/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.tsx#L50)):*
> ```XML
>   return (
>     <Visible visible={isOpen}>
>       <div className="fixed top-0 right-0 mt-20 mr-4 h-[90%] w-1/3 overflow-scroll rounded-md bg-white p-4 shadow-[0_3px_10px_rgb(0,0,0,0.2)] shadow-slate-500">
> ```

This might need the `aria-modal=true` and `role=dialog` attributes. 

Here's something to read on this: https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/, which is pretty hard to read for some reason (ironic), anyway there is the codepen example, which was way easier to read and understand from (at least for me)


<!-- Sent from Reviewable.io -->

2024-02-27 06:28 UTC, Leitsi requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 17 of 28 files reviewed, 7 unresolved discussions (waiting on @HenrikHartiala and @niknii-vincit)

___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAOtpm3vQoMxBF-4mn:-Nrd9juT0fc8jDEQKQRr:bao76de) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx#L40)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Consulted Accessibility expert, and they said that the modal should start with a `h2`, because it's basically a new document for screen readers.
</blockquote></details>

Roger. Could still be some header instead of a span though. Too bad tailwind doesn't have any classes for applying all text styles at once to make it look like a specific header element... Even if its just font size and weight.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA5dOhEbR2igeJN0dA:-NrdBERR6o0Ew3vBzgq5:bhp2zfd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx#L16)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Good one! Like you said, it's just copy pasted. Now that I look at it, it really doesn't make much sense. I think the VehicleServiceRow code could be implemented with a bit different way, but that is for the future. I'll now put it as default parameter as you said :ok_hand:
</blockquote></details>

Is not a default parameter now though, after all. But is fine like this as well. :heavy_check_mark: 
___
*[`ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFrameSchedules.ts` line 99 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrdD0SbABCBGJjHGrxF:-NrdD0SbABCBGJjHGrxG:b-mrxxsv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a467d0457126de369d95ac48815c0959faa1bfd8/ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFrameSchedules.ts#L99)):*
> ```XML
>     const updatedAcc = { ...acc };
> 
>     if (label && direction) {
> ```

I think this could be simplified as well with an early return. Since label and direction are both required for a route, you could just add an early return if `journey_pattern_route` is not set (can this even happen? oh well). So something like:

```
const updatedAcc = { ...acc };

const route = item.journey_pattern_ref.journey_pattern_instance?.journey_pattern_route
if (!route) { return updatedAcc; }

const label = route.unique_label;
const direction = route.direction;
const nameI18n = route.name_i18n;
```


<!-- Sent from Reviewable.io -->

2024-02-29 09:52 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 13 of 30 files reviewed, 7 unresolved discussions (waiting on @Leitsi and @niknii-vincit)

___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAOtpm3vQoMxBF-4mn:-Nro8CnF1poI1IA5YAlr:baip8o4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx#L40)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Roger. Could still be some header instead of a span though. Too bad tailwind doesn't have any classes for applying all text styles at once to make it look like a specific header element... Even if its just font size and weight.
</blockquote></details>

I'll put this as h3 (since the modal heading is h2 and these are childs of that), but still raises some questions, if the heading size for this list item is based on what are the parent headings. What if this component was to be used in somewhere else, where it is under h3? Wouldn't we need two different heading sizes for this at that point? For us this is probably enough, but should we at the given scenario somehow dynamically determine the heading?
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx` line 16 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrA5dOhEbR2igeJN0dA:-Nrnsw5rAXSu9vXVRTEH:b-9pck0q) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/RouteTimetableCard.tsx#L16)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Is not a default parameter now though, after all. But is fine like this as well. :heavy_check_mark:
</blockquote></details>

Ah pfft. true, should be fixed now as default parameter in VehicleServiceRow.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.tsx` line 50 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-Nr_ud993h078Fhmhls0:-NrntV3uBflXz1GmLk1j:b-tpv8yp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a467d0457126de369d95ac48815c0959faa1bfd8/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.tsx#L50)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

This might need the `aria-modal=true` and `role=dialog` attributes. 

Here's something to read on this: https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/, which is pretty hard to read for some reason (ironic), anyway there is the codepen example, which was way easier to read and understand from (at least for me)
</blockquote></details>

Hmm. But this is **not** a modal. It's more like a dialog/panel. (Modal = block interaction with the rest of the page)
This is what the link also says: "Tells assistive technologies that the windows underneath the current dialog are not available for interaction (inert)."
But in this case they are available for interaction. 
And by my understanding the role=dialog does not change this fact. 

Correct me if I understood something wrong, but otherwise: 
should we still add "role=dialog" for this and not the aria-modal=true?
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx` line 18 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAMQEyC3G2ramvsRy6:-Nro77gI7HZ_3JNNoQ-k:bjzujj7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx#L18)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

I think this should be a heading. The heading level is defined by the location we open the dialog in, so in this case (if the heading levels in the main page would correctly start from `h1`, instead of `h2`), it would be `h3`. I think the same style can be kept with spans within the `h3` element, but it being a header, makes it more scannable.
</blockquote></details>

Okay, so I now modified this that the wrapping div is the h2 (this was the suggested one from the other comment: ` Consulted Accessibility expert, and they said that the modal should start with a `h2`, because it's basically a new document for screen readers.`)
And also changed the classNames of the spans to better match figma.
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx` line 19 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAMH1w-baU0kyAN0ls:-Nro7abi0vEVUEeVlFVP:bz8d4eh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx#L19)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Same here as above
</blockquote></details>

So now the surrounding div is the h2, and these two remained as spans for different stylings. They both are part of the same heading.
___
*[`ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFrameSchedules.ts` line 99 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrdD0SbABCBGJjHGrxF:-NrnyBW36ULHm5KiEckp:bwfpgvy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a467d0457126de369d95ac48815c0959faa1bfd8/ui/src/hooks/vehicle-schedule-frame/useVehicleScheduleFrameSchedules.ts#L99)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I think this could be simplified as well with an early return. Since label and direction are both required for a route, you could just add an early return if `journey_pattern_route` is not set (can this even happen? oh well). So something like:

```
const updatedAcc = { ...acc };

const route = item.journey_pattern_ref.journey_pattern_instance?.journey_pattern_route
if (!route) { return updatedAcc; }

const label = route.unique_label;
const direction = route.direction;
const nameI18n = route.name_i18n;
```
</blockquote></details>

Good one!
I think at some point I've learnt to avoid early returns, but for example here it simplifies the code and readability so much that it is definitely beneficial. Thanks


<!-- Sent from Reviewable.io -->

2024-02-29 13:01 UTC, niknii-vincit requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 13 of 30 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala and @Leitsi)

___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAOtpm3vQoMxBF-4mn:-Nrov9z05vx2MNYGItw-:bix5hu8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx#L40)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

I'll put this as h3 (since the modal heading is h2 and these are childs of that), but still raises some questions, if the heading size for this list item is based on what are the parent headings. What if this component was to be used in somewhere else, where it is under h3? Wouldn't we need two different heading sizes for this at that point? For us this is probably enough, but should we at the given scenario somehow dynamically determine the heading?
</blockquote></details>

Yes! Absolutely `h3` for these child elements, I should have written the `h2` part in the correct modal "title" spot, but alas :shrug:  

I think once this is used elsewhere and if it's heading doesn't match there, it could be parametrised as an attribute perhaps? I don't think we need to solve that issue now "for the future".
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.tsx` line 50 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-Nr_ud993h078Fhmhls0:-Nrowe814xORhnP5zu7_:boe6npc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a467d0457126de369d95ac48815c0959faa1bfd8/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.tsx#L50)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm. But this is **not** a modal. It's more like a dialog/panel. (Modal = block interaction with the rest of the page)
This is what the link also says: "Tells assistive technologies that the windows underneath the current dialog are not available for interaction (inert)."
But in this case they are available for interaction. 
And by my understanding the role=dialog does not change this fact. 

Correct me if I understood something wrong, but otherwise: 
should we still add "role=dialog" for this and not the aria-modal=true?
</blockquote></details>

Ah I misunderstood, I somehow thought it's a "lite" modal, because it covers some of the pre-existing UI. Yes the correct way would be to add `role=dialog` here. :ok_hand:  Good job staying vigilant, I'm a little scatterbrained at the moment.


<!-- Sent from Reviewable.io -->

2024-02-29 13:05 UTC, niknii-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 13 of 30 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala and @Leitsi)

___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx` line 18 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAMQEyC3G2ramvsRy6:-NroxAiM54tPEbJa_Ypd:b4u9lob) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx#L18)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Okay, so I now modified this that the wrapping div is the h2 (this was the suggested one from the other comment: ` Consulted Accessibility expert, and they said that the modal should start with a `h2`, because it's basically a new document for screen readers.`)
And also changed the classNames of the spans to better match figma.
</blockquote></details>

Looks great! 
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx` line 19 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAMH1w-baU0kyAN0ls:-NroxubDCbYFFQkqAwnQ:beex6gu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx#L19)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

So now the surrounding div is the h2, and these two remained as spans for different stylings. They both are part of the same heading.
</blockquote></details>

Imo it looks great :thumbsup: 


<!-- Sent from Reviewable.io -->

2024-03-05 11:14 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 13 of 30 files reviewed, 6 unresolved discussions (waiting on @Leitsi and @niknii-vincit)

___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx` line 40 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAOtpm3vQoMxBF-4mn:-NsDIxzr7RoeMGUUo0SK:b-owz02y) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/ExpandableRouteTimetableRow.tsx#L40)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Yes! Absolutely `h3` for these child elements, I should have written the `h2` part in the correct modal "title" spot, but alas :shrug:  

I think once this is used elsewhere and if it's heading doesn't match there, it could be parametrised as an attribute perhaps? I don't think we need to solve that issue now "for the future".
</blockquote></details>

Yep lets go with that :+1: 
___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.tsx` line 50 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-Nr_ud993h078Fhmhls0:-NsDJDIT63kJmEA5Ouz0:b-p768g3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a467d0457126de369d95ac48815c0959faa1bfd8/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.tsx#L50)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Ah I misunderstood, I somehow thought it's a "lite" modal, because it covers some of the pre-existing UI. Yes the correct way would be to add `role=dialog` here. :ok_hand:  Good job staying vigilant, I'm a little scatterbrained at the moment.
</blockquote></details>

Added the `role=dialog`


<!-- Sent from Reviewable.io -->

2024-03-07 13:46 UTC, Leitsi requested changes
> Reviewed 6 of 20 files at r6.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 18 of 44 files reviewed, 9 unresolved discussions (waiting on @HenrikHartiala and @niknii-vincit)

___
*[`cypress/e2e/timetableVersionDetailsPanel.cy.ts` line 36 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO4YKpDD66cNXn0xmh:-NsO4YKpDD66cNXn0xmi:b-j5wj0f) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/e2e/timetableVersionDetailsPanel.cy.ts#L36)):*
> ```XML
> 
> // TODO: Extract the basedata somewhere, so that it can be used in multiple tests. No need
> // to copy paste 400+ lines in front of every test.
> ```

Yep, :TLDR:.
___
*[`cypress/e2e/timetableVersionDetailsPanel.cy.ts` line 446 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO4gpL1qieAdr4vbhy:-NsO4gpL1qieAdr4vbhz:b7qf4mc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/e2e/timetableVersionDetailsPanel.cy.ts#L446)):*
> ```XML
> 
> describe('Timetable version details panel', () => {
>   // let vehicleScheduleDetailsPage: VehicleScheduleDetailsPage;
> ```

This was forgotten here.
___
*[`cypress/e2e/timetableVersionDetailsPanel.cy.ts` line 501 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO5Aqa2wCiXoM1WKHD:-NsO5Aqa2wCiXoM1WKHE:bwn7lwk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/e2e/timetableVersionDetailsPanel.cy.ts#L501)):*
> ```XML
> 
>   afterEach(() => {
>     cy.task('emptyDownloadsFolder');
> ```

Are we actually downloading something here though?
___
*[`cypress/e2e/timetableVersionDetailsPanel.cy.ts` line 613 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO7_MV2vMuTJ6LV2xs:-NsO7_MV2vMuTJ6LV2xt:bisrvyx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/e2e/timetableVersionDetailsPanel.cy.ts#L613)):*
> ```XML
>       .getRows()
>       .eq(0)
>       .findByTestId('TimetableVersionTableRow::row::validityEnd')
> ```

Slightly bothers me that the test ids leak to tests. Should we add `findNthRowValidityEnd`?

Though, there's quite a few `findByTestId` calls earlier in this file and that solution wouldn't really work for them...
___
*[`cypress/pageObjects/TimetableVersionTableRow.ts` line 6 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO5MdYDGIoQHwHXn5b:-NsO5MdYDGIoQHwHXn5c:bhx4sfu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/pageObjects/TimetableVersionTableRow.ts#L6)):*
> ```XML
>   }
> 
>   openNthRowVersionDetailsPanel({ rowNumber }: { rowNumber: number }) {
> ```

This would be just fine as `(rowNumber: number)` as well, in my opinion. The `Nth` in function title already tells what that means.
___
*[`cypress/pageObjects/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.ts` line 14 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO4J4h79IT_Ocb279R:-NsO4J4i6QjJCYURAVRl:bwgjegg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/pageObjects/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.ts#L14)):*
> ```XML
>   };
> 
>   expandNthRow = ({ rowNumber }: { rowNumber: number }) => {
> ```

Nit: To be precise, this _toggles_, right? Just happens to expand since it's closed by default.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 28 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO2JcdDB75pjt9QGyP:-NsO2JcdDB75pjt9QGyQ:bk0qe63) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L28)):*
> ```XML
>     'TimetableVersionTableRow::row::validityStart',
>   timetableVersionTableRowValidityEnd:
>     'TimetableVersionTableRow::row::validityEnd',
> ```

Nit: don't think we need the `::row::` on these validity testids here.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 31 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO35R72K9IuiakaUi_:-NsO35R72K9IuiakaUia:b-4hwbwa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L31)):*
> ```XML
>   timetableVersionTableRowActions: 'TimetableVersionTableRow::actions',
>   deleteTimetableMenuItem: 'TimetableVersionTableRow::deleteTimetableMenuItem',
>   versionPanelMenuItem: 'TimetableVersionTableRow:versionPanelMenuItem',
> ```

Some inconsistency, some test ids use `:` as separator and some `::`. Hardly matters though.


<!-- Sent from Reviewable.io -->

2024-03-08 08:24 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 17 of 44 files reviewed, 8 unresolved discussions (waiting on @Leitsi and @niknii-vincit)

___
*[`cypress/e2e/timetableVersionDetailsPanel.cy.ts` line 446 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO4gpL1qieAdr4vbhy:-NsOAy0I8x4jZ5-pH9Wz:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/e2e/timetableVersionDetailsPanel.cy.ts#L446)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This was forgotten here.
</blockquote></details>

:+1: 
___
*[`cypress/e2e/timetableVersionDetailsPanel.cy.ts` line 501 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO5Aqa2wCiXoM1WKHD:-NsRtXi97I4iY7Qeg-KP:b-d34222) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/e2e/timetableVersionDetailsPanel.cy.ts#L501)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Are we actually downloading something here though?
</blockquote></details>

Good catch and nope, probably copypaste leftover. 
___
*[`cypress/e2e/timetableVersionDetailsPanel.cy.ts` line 613 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO7_MV2vMuTJ6LV2xs:-NsS1jWHB_fASshkkbBC:b6hxwyj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/e2e/timetableVersionDetailsPanel.cy.ts#L613)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Slightly bothers me that the test ids leak to tests. Should we add `findNthRowValidityEnd`?

Though, there's quite a few `findByTestId` calls earlier in this file and that solution wouldn't really work for them...
</blockquote></details>

Yep, I do think that we need to think of some guidelines for how we create these tests and create/use pageObjects, and because of that I did not want to invest time to these yet. That said, I did make some changes to these. (e.g. in some places the .getRows wasn't used)
Also hmm.. probably should use wihtin here, instead of multiple findBy's.. Well, like said, I'd rather do these refactors in another PR, where I can go through these with more focus on just the pageObjects. I do have some ideas for the pageObjects.
___
*[`cypress/pageObjects/TimetableVersionTableRow.ts` line 6 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO5MdYDGIoQHwHXn5b:-NsRtn0PBINNG93_3Akz:bu21deh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/pageObjects/TimetableVersionTableRow.ts#L6)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This would be just fine as `(rowNumber: number)` as well, in my opinion. The `Nth` in function title already tells what that means.
</blockquote></details>

True :+1: 
___
*[`cypress/pageObjects/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.ts` line 14 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO4J4h79IT_Ocb279R:-NsRuobrDqd1BdAB2Di2:bk8akgr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/cypress/pageObjects/timetables/versions/timetable-version-details-panel/TimetableVersionDetailsPanel.ts#L14)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Nit: To be precise, this _toggles_, right? Just happens to expand since it's closed by default.
</blockquote></details>

Good one! I'll change this to toggleExpandNthRow probably could also be `toggleNthRow`, but maybe this is more clear.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 28 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO2JcdDB75pjt9QGyP:-NsRvGd-6rFtxDJ7WWyo:bylloie) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L28)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Nit: don't think we need the `::row::` on these validity testids here.
</blockquote></details>

Thanks, yeah now that I look at it,  it's clearly redundant.
___
*[`ui/src/components/timetables/versions/TimetableVersionTableRow.tsx` line 31 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsO35R72K9IuiakaUi_:-NsRvjwTCTb--spnmdf-:b-fyeaxv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/ui/src/components/timetables/versions/TimetableVersionTableRow.tsx#L31)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Some inconsistency, some test ids use `:` as separator and some `::`. Hardly matters though.
</blockquote></details>

We do have a guideline in readme to use double colons, so you are correct. This was a pure negligent error. Quickly skimmed through the changes and I believe this was the only one with single colon.


<!-- Sent from Reviewable.io -->

2024-03-08 09:53 UTC, Leitsi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-:-NsSTjU10bohnizMof8m:bnfp4nl)* status: 17 of 44 files reviewed, 5 unresolved discussions (waiting on @niknii-vincit)



<!-- Sent from Reviewable.io -->

2024-03-08 09:54 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 17 of 44 files reviewed, 4 unresolved discussions (waiting on @niknii-vincit)

___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableHeading.tsx` line 10 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NrAKkDuBrsQbF4ZEp8a:-NsSTzqL5kORDgBIP2sc:b-1h6pa1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90cd3711726f37c80988be0cb0dda8e3e30a6899/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableHeading.tsx#L10)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Yep, like mentioned these can probably be combined with the clickability as parameterized. Will look in to this after.
</blockquote></details>

:heavy_check_mark:  let's check this separately from this PR then.


<!-- Sent from Reviewable.io -->

2024-03-08 12:11 UTC, niknii-vincit commented
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx` line 24 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsSw9Vw0i7T07zHGWhn:-NsSw9Vw0i7T07zHGWho:b-ypyz36) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx#L24)):*
> ```XML
>       )} - ${mapToShortDate(validityEnd)}`}</span>
>     </h2>
>     <CloseIconButton
> ```

Because there is a close button here, I think the dialog should be able to be closed with the press of "Esc", so maybe you could use this code from `Modal.tsx`(rows 57-67):



_Code snippet:_
```XML
  const closeOnEscape = (e: KeyboardEvent) => {
    if (e.key === 'Escape') {
      e.preventDefault();
      onClose();
    }
  };

  useEffect(() => {
    document.addEventListener('keydown', closeOnEscape, true);
    return () => document.removeEventListener('keydown', closeOnEscape, true);
  });
```


<!-- Sent from Reviewable.io -->

2024-03-11 07:53 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 17 of 48 files reviewed, 2 unresolved discussions (waiting on @Leitsi and @niknii-vincit)

___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx` line 24 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsSw9Vw0i7T07zHGWhn:-NsgV3AE9np8rr92CBAr:b-q63gtg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx#L24)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Because there is a close button here, I think the dialog should be able to be closed with the press of "Esc", so maybe you could use this code from `Modal.tsx`(rows 57-67):
</blockquote></details>

Created a hook for this :+1: 


<!-- Sent from Reviewable.io -->

2024-03-11 08:10 UTC, niknii-vincit commented
*[`ui/src/hooks/useCallbackOnKeyEscape.ts` line 12 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsgYd5w7fwgjBvrso2Y:-NsgYd5w7fwgjBvrso2Z:b-s4ixx6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90d2e18d0102118e6d50551f1116f771c44c8b84/ui/src/hooks/useCallbackOnKeyEscape.ts#L12)):*
> ```XML
>     };
> 
>     document.addEventListener('keydown', onKeyEscape, true);
> ```

Should this be keyup instead? So it doesn't happen INSTANTLY if someone presses the wrong button? At least I have the tendency to keep pressing the button and going elsewhere to stop the button action from happening :sweat_smile: 


<!-- Sent from Reviewable.io -->

2024-03-11 08:10 UTC, niknii-vincit reviewed
> Reviewed 2 of 11 files at r3, 9 of 14 files at r4, 1 of 1 files at r5, 17 of 20 files at r6, 2 of 4 files at r7, 2 of 2 files at r8, 4 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala and @Leitsi)

___
*[`ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx` line 24 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsSw9Vw0i7T07zHGWhn:-NsgYKg26lhULT5eCUry:bccpe83) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9a8ef330db1953ff20fe34dce69cf86337621a95/ui/src/components/timetables/versions/timetable-version-details-panel/TimetableVersionPanelHeading.tsx#L24)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Created a hook for this :+1:
</blockquote></details>

Awesome!


<!-- Sent from Reviewable.io -->

2024-03-11 08:17 UTC, niknii-vincit commented
:shipit: 





<!-- Sent from Reviewable.io -->

2024-03-11 08:18 UTC, niknii-vincit reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769)* status: 47 of 48 files reviewed, all discussions resolved (waiting on @Leitsi)

___
*[`ui/src/hooks/useCallbackOnKeyEscape.ts` line 12 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-NsgYd5w7fwgjBvrso2Y:-Nsg_fh2Efgyio0-NKWy:b-gsb174) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/90d2e18d0102118e6d50551f1116f771c44c8b84/ui/src/hooks/useCallbackOnKeyEscape.ts#L12)):*
<details><summary><i>Previously, niknii-vincit (Niki Niittymäki) wrote…</i></summary><blockquote>

Should this be keyup instead? So it doesn't happen INSTANTLY if someone presses the wrong button? At least I have the tendency to keep pressing the button and going elsewhere to stop the button action from happening :sweat_smile:
</blockquote></details>

Let's fix it later on if it's a problem, so :shipit: 


<!-- Sent from Reviewable.io -->

2024-03-11 08:18 UTC, niknii-vincit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/769#-:-Nsg_rqh75IGePExuF6Q:bnfp4nl)* status: 47 of 48 files reviewed, all discussions resolved (waiting on @Leitsi)



<!-- Sent from Reviewable.io -->

2024-03-11 08:25 UTC, merged