Stop basic info edit
HSLdevcom/jore4-ui pull request #799
Opened 2024-04-03 16:39 UTC by HenrikHartiala

2024-04-05 09:23 UTC, Leitsi reviewed
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799)* status: 15 of 24 files reviewed, 7 unresolved discussions (waiting on @HenrikHartiala)

___
*[`-- commits` line 41 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh5fkmB0yVpCXDROV0):*
This could just as well be squashed to the actual commit where this is used. All the code here is in separate files and there's not that much of it, so doesn't really clarify much having it separate. In fact, I think it's more confusing having it separate, it is very unclear at this moment how this will be used, or why.
___
*[`ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx` line 27 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh83iE6FCrvgseqz22:-Nuh83iE6FCrvgseqz23:btqtcwu) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c1195b994e2c23532e6c65b7768a18bf2c592da1/ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx#L27)):*
> ```XML
> };
> 
> export const ExpandableInfoContainer: React.FC<Props> = ({
> ```

Thinking if this should be renamed now that it does more than expand, that is, edit mode is part of this. No good suggestions to give at the moment though. :shrug: 
___
*[`ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx` line 85 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh8UKFADR2SiGFGYg5:-Nuh8UKFADR2SiGFGYg6:banypxd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c1195b994e2c23532e6c65b7768a18bf2c592da1/ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx#L85)):*
> ```XML
>           flex items-center justify-end space-x-2 rounded-b-lg
>           border
>           bg-hsl-neutral-blue px-4 py-2 ${isExpanded ? '' : 'rounded-b-lg'}
> ```

`rounded-b-lg` is already set two lines above.
___
*[`ui/src/components/stop-registry/stops/stop-details/utils.ts` line 29 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh44DT0DG_8bffS7-E:-Nuh44DU2jSIOIAJKfHh:bkjfcjw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/95695da097b266d6f203585ad0901ac871c27453/ui/src/components/stop-registry/stops/stop-details/utils.ts#L29)):*
> ```XML
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> export const deepStripTypename = (obj: any) => {
>   // TODO: is this safe enough?
> ```

One fun case I can think of: `typeof null === 'object'`.

There's `hasTypeName` in `ui/src/graphql/types.ts`, which uses `lodash/isObject` which seems to handle that case at least.
___
*[`ui/src/components/stop-registry/stops/stop-details/utils.spec.ts` line 66 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh6fetEviI6jzQpyaC:-Nuh6fetEviI6jzQpyaD:borbzvm) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/95695da097b266d6f203585ad0901ac871c27453/ui/src/components/stop-registry/stops/stop-details/utils.spec.ts#L66)):*
> ```XML
>     });
> 
>     it('does not crash if object doesnt have typename', () => {
> ```

Or, `if object has no typename` if repetition starts to bother.



_Suggestion:_
```XML
does not
```
___
*[`ui/src/i18n/uiNameMappings.ts` line 93 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh3AmiDCn8FG99Q36P:-Nuh3AmiDCn8FG99Q36Q:bguv7b7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/efb630dd02458d39a510a847b232542491c4ecb5/ui/src/i18n/uiNameMappings.ts#L93)):*
> ```XML
> };
> 
> export const mapStopRegistryTransportModeSubsetToUiName = (
> ```

There's already `mapStopRegistryTransportModeTypeToUiName` above (which actually only handles this same subset).
___
*[`ui/src/types/enums.ts` line 72 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh2IHX8nhT8JLwek9j:-Nuh2IHX8nhT8JLwek9k:b-rlg40) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/efb630dd02458d39a510a847b232542491c4ecb5/ui/src/types/enums.ts#L72)):*
> ```XML
> 
> /**
>  * Subset of @StopRegistryTransportModeType, which is a generated enum from tiamat
> ```

Thinking if `subset` is a bit vague. How about `JoreStopRegistryTransportModeType` or something?
___
*[`ui/src/types/enums.ts` line 75 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh1x7uAzJ8zb35LXRr:-Nuh1x7uAzJ8zb35LXRs:b-bqzwdq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/efb630dd02458d39a510a847b232542491c4ecb5/ui/src/types/enums.ts#L75)):*
> ```XML
>  * and we do not use all of the types
>  */
> export enum StopRegistryTransportModeTypeSubset {
> ```

Should this rather be in `ui/src/types/stop-registry.ts` where we have other stop registry specific enums?
___
*[`ui/src/types/enums.ts` line 80 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh2cK68DLQGPh2bSET:-Nuh2cK7-H6A7jV0yvrY:b-sbahqa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/efb630dd02458d39a510a847b232542491c4ecb5/ui/src/types/enums.ts#L80)):*
> ```XML
>   Metro = 'metro',
>   Rail = 'rail',
>   Water = 'water',
> ```

I would rather use the base enum values instead of copypaste.



_Suggestion:_
```XML
  Bus = StopRegistryTransportModeType.Bus,
  Tram = StopRegistryTransportModeType.Tram,
  Metro = StopRegistryTransportModeType.Metro,
  Rail = StopRegistryTransportModeType.Rail,
  Water = StopRegistryTransportModeType.Water,
```


<!-- Sent from Reviewable.io -->

2024-04-05 12:07 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799)* status: 0 of 27 files reviewed, 20 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/hooks/stop-registry/useEditStopBasicInformation.ts` line 28 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nui6T7u0IYk7fOzD2Ii:-Nui6T7u0IYk7fOzD2Ij:bp9dpmh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/hooks/stop-registry/useEditStopBasicInformation.ts#L28)):*
> ```XML
>   showDangerToast,
> } from '../../utils';
> import { EditChanges } from '../stops/useEditStop';
> ```

I'd rather not use this from another hook. Feels like it's quite tightly coupled to the internal implementation of that hook. Also it has some properities that we don't need and just have to unnecessarily declare here because of this type. Maybe rather create a new type just for this hook.
___
*[`ui/src/hooks/stop-registry/useEditStopBasicInformation.ts` line 64 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nui4_32DVe8V5wnrrbh:-Nui4_32DVe8V5wnrrbi:b-8pjvz9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/hooks/stop-registry/useEditStopBasicInformation.ts#L64)):*
> ```XML
>   const [validateTimingSettings] = useValidateTimingSettings();
>   const dispatch = useDispatch();
> ```

I think it would help readability if you reorganize the functions here (would be even better if we could use hoisting, but oh well..). At least grouping all route db methods and then all tiamat methods together, now they're a bit mixed. So maybe like this:
```
  const mapFormStateToRoutesAndLinesDbInput = (
  const prepareEditForRoutesAndLinesDb = async ({
  const mapEditChangesToRoutesAndLinesDbVariables = (changes: EditChanges) => {
  const updateRoutesAndLinesStop = async (
  const mapStopEditChangesToTiamatDbInput = (
  const prepareEditForTiamatDb = ({
  const updateTiamatStopPlace = async (editParams: EditTiamatParams) => {
  const defaultErrorHandler = (err: Error) => {
```
___
*[`ui/src/hooks/stop-registry/useEditStopBasicInformation.ts` line 75 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nui7_Ld6n231UqxKRzB:-Nui7_Le30tD-nZyQXoN:b-7fiz67) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/hooks/stop-registry/useEditStopBasicInformation.ts#L75)):*
> ```XML
>   };
> 
>   const mapStopEditChangesToTiamatDbInput = (
> ```

Feels like things might get simplified if you just pass the stop / stopPlace here instead of n individual parameters.
___
*[`ui/src/hooks/stop-registry/useEditStopBasicInformation.ts` line 184 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nui64PbAZFEbT84Cle1:-Nui64PbAZFEbT84Cle2:bsu5om) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/hooks/stop-registry/useEditStopBasicInformation.ts#L184)):*
> ```XML
> 
>     // changes that will always be applied
>     const defaultChanges = {
> ```

This is not used before `mergedChanges` is declared, so maybe move right before that.
___
*[`ui/src/hooks/stop-registry/useEditStopBasicInformation.ts` line 207 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nui5vi49081RkWE8-oW:-Nui5vi49081RkWE8-oX:b-ouhkd8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/hooks/stop-registry/useEditStopBasicInformation.ts#L207)):*
> ```XML
>     }
> 
>     const mergedChanges = merge({}, defaultChanges);
> ```

Doesn't look like this actually does anything?
___
*[`ui/src/hooks/stop-registry/useEditStopBasicInformation.ts` line 242 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nui3DlfDKDhU59vq_48:-Nui3DlfDKDhU59vq_49:bczn0wd) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/hooks/stop-registry/useEditStopBasicInformation.ts#L242)):*
> ```XML
>       stop_label: changes.stopLabel,
>       stop_patch: changes.patch,
>       // TODO: should this be copypasted with the delete? Basic information changes is not changing the location of the stop
> ```

The mutation is on "common" side so I don't see an issue reusing that here. Even if there's some features we don't need in this case.
___
*[`ui/src/hooks/stop-registry/useEditStopBasicInformation.ts` line 253 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nui3Yd21-37z8-XlL8t:-Nui3Yd21-37z8-XlL8u:b-npzf9w) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/hooks/stop-registry/useEditStopBasicInformation.ts#L253)):*
> ```XML
>   const defaultErrorHandler = (err: Error) => {
>     if (err instanceof TimingPlaceRequiredError) {
>       dispatch(setIsMoveStopModeEnabledAction(false));
> ```

This action does not seem suitable for our case here. Unintentionally left here when copypasted?


<!-- Sent from Reviewable.io -->

2024-04-08 11:11 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799)* status: 0 of 36 files reviewed, 20 unresolved discussions (waiting on @Leitsi)

___
*[`-- commits` line 41 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh5fkmB0yVpCXDROV0):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This could just as well be squashed to the actual commit where this is used. All the code here is in separate files and there's not that much of it, so doesn't really clarify much having it separate. In fact, I think it's more confusing having it separate, it is very unclear at this moment how this will be used, or why.
</blockquote></details>

Good point, although this is now removed completely, and used the apollo's removeTypenameFromVariables.
___
*[`ui/src/components/stop-registry/stops/stop-details/BasicDetailsSection.tsx` line 68 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-NuhgHoH5G1DTpMol13a:-Nun0Sjo70dTU7GJgnqL:b2shbek) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/components/stop-registry/stops/stop-details/BasicDetailsSection.tsx#L68)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

If we have to do something like this, I would maybe rather move it to the hook. Just pass the whole stop / stop_place as parameter. That would also remove th need to pass id and stopPlaceQuayId as separate parameters.
</blockquote></details>

moved to hook :+1: 
___
*[`ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx` line 27 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh83iE6FCrvgseqz22:-NuwMkVZ3vzC-CGO6Rgj:b-iab3c9) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c1195b994e2c23532e6c65b7768a18bf2c592da1/ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx#L27)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Thinking if this should be renamed now that it does more than expand, that is, edit mode is part of this. No good suggestions to give at the moment though. :shrug:
</blockquote></details>

Yeah, probably. But can't think of one right now either. Maybe we'll come up with one later.
___
*[`ui/src/i18n/uiNameMappings.ts` line 93 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh3AmiDCn8FG99Q36P:-NuwNYf6BegXfFfGzogS:b-nqywgc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/efb630dd02458d39a510a847b232542491c4ecb5/ui/src/i18n/uiNameMappings.ts#L93)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

There's already `mapStopRegistryTransportModeTypeToUiName` above (which actually only handles this same subset).
</blockquote></details>

I suppose I can just add the subset type to that one as option. ( The types need to match, and at least I didn't find a way to create an actual subset enum )
___
*[`ui/src/types/enums.ts` line 80 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh2cK68DLQGPh2bSET:-NuwOSGh7MGbm8RkIWxc:b-b69c3x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/efb630dd02458d39a510a847b232542491c4ecb5/ui/src/types/enums.ts#L80)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I would rather use the base enum values instead of copypaste.
</blockquote></details>

That was my first code, but for some random reason it ends up being wrong. (Has everything doubled)
```
{
  Bus: 'bus',
  Metro: 'metro',
  Rail: 'rail',
  Tram: 'tram',
  Water: 'water',
  bus: 'Bus',
  metro: 'Metro',
  rail: 'Rail',
  tram: 'Tram',
  water: 'Water',
};
```
I dont know why this happens, 
If I do this in ts playground https://www.typescriptlang.org/play?#code/KYOwrgtgBAygLgewA4CVgHMCWBnOAnATwBU8BDEbJBPOAWQQBNgiClgoBvAKCigEFMeKAF4oAclKCxAGh5QAQmGwjxAIyUy5AYVKqANsADupAirEBjXQeMFNvAGJgQmc2D2khosQDMnLtx52ULTA+AhmEKF4CEEoknpmZJh6QSSk0F746UEA6qRwwJ7ixgV4mgC+XFWgkLCIqBg4+MRkFFQ09EwsbDBgqtihnHKKyqLwyGhYuIRpbdR0jMyswAB0I7K8aRl1E43TLeSU851LbCtbG8FR4WP1k00zrUcdi92rIWGXcckq4w1TzVmzwWXWWK2+ekueVKvzue0BT3aINOq2hhVklXMCAoCAMKz0CHQAAo-vd9kCkSc3r1+qEAJRAA

Everyhtings fine, also If I define these enums in a file and console log them there, everything is OK. But if I use the StopREgistryTransportMOdeType, it doubles it up :shrug:
___
*[`ui/src/components/forms/stop-registry/stop-place/basic-information/StopBasicInformationForm.tsx` line 42 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuher2F0RBYW_w_pOyb:-Nun-R1X3KGFurrOHSbd:b-cqd8vy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/components/forms/stop-registry/stop-place/basic-information/StopBasicInformationForm.tsx#L42)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

This is implemented in two places now.
</blockquote></details>

Removed from here. Was leftover, but this shouldn't be coupled to StopWithDetails.
___
*[`ui/src/components/forms/stop-registry/stop-place/basic-information/StopBasicInformationForm.tsx` line 45 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-NuhdAS38a6LO5V2hy3u:-NumHul548X19D7eJdOr:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/components/forms/stop-registry/stop-place/basic-information/StopBasicInformationForm.tsx#L45)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Slightly bothers me that these initial values and actual schema are defined in different places. Having whole schema in one file like you mentioned in commit message might help.
</blockquote></details>

:+1: 
___
*[`ui/src/components/forms/stop-registry/stop-place/basic-information/StopBasicInformationForm.tsx` line 100 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-NuhcKU30CBCorGuFMZS:-Nun04iUEq4KLnDf6DPG:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/components/forms/stop-registry/stop-place/basic-information/StopBasicInformationForm.tsx#L100)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

If we keep these, should we maybe name them `FormRow` instead? Since they just implement a single row and can not be used as standalone form.
</blockquote></details>

:+1: 
___
*[`ui/src/components/forms/stop-registry/stop-place/basic-information/StopLocationAndAbbreviationsForm.tsx` line 64 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-NuhZb9n676pgYpMrqLF:-Nun0KJI9N9ZGSr752Hq:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/components/forms/stop-registry/stop-place/basic-information/StopLocationAndAbbreviationsForm.tsx#L64)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Wrong testid.
</blockquote></details>

:+1: 
___
*[`ui/src/components/stop-registry/stops/stop-details/utils.ts` line 29 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh44DT0DG_8bffS7-E:-NuxOypX43lxzYVD8gEw:b-b5xk0b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/95695da097b266d6f203585ad0901ac871c27453/ui/src/components/stop-registry/stops/stop-details/utils.ts#L29)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

One fun case I can think of: `typeof null === 'object'`.

There's `hasTypeName` in `ui/src/graphql/types.ts`, which uses `lodash/isObject` which seems to handle that case at least.
</blockquote></details>

removed completely 
___
*[`ui/src/components/stop-registry/stops/stop-details/utils.spec.ts` line 66 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh6fetEviI6jzQpyaC:-NuxOvzGBIc6wji9A7sZ:b-hfpv0l) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/95695da097b266d6f203585ad0901ac871c27453/ui/src/component [...]

2024-04-10 07:16 UTC, Leitsi reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799)* status: 0 of 36 files reviewed, 6 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/stop-registry/stops/stop-details/BasicDetailsSection.tsx` line 68 at r11](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-NuhgHoH5G1DTpMol13a:-Nv5o5uk5TP9Gt9WAJpt:bwje1c2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c2a0ea853cc3b9d6542205b63d0e2b5bb1534643/ui/src/components/stop-registry/stops/stop-details/BasicDetailsSection.tsx#L68)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

moved to hook :+1:
</blockquote></details>

:thumbsup:  now this component is very neat.
___
*[`ui/src/components/stop-registry/stops/stop-details/BasicDetailsSection.tsx` line 66 at r34](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv5oPV7-SyNf7TiIVrw:-Nv5oPV7-SyNf7TiIVrx:b4beg6g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3e55b4c0139ebc6f72662862e041817de3506dd0/ui/src/components/stop-registry/stops/stop-details/BasicDetailsSection.tsx#L66)):*
> ```XML
>   };
> 
>   const defaultValues = mapStopBasicDetailsDataToFormState(stop);
> ```

Still thinking though if this should be inside the detailsform component :thinking:  We don't do anything with the defaultValues here, just passing them through.
___
*[`ui/src/hooks/stop-registry/useEditStopBasicDetails.ts` line 35 at r34](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv5q4V_ApzyuGlqY9E3:-Nv5q4V_ApzyuGlqY9E4:b9ohko3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/3e55b4c0139ebc6f72662862e041817de3506dd0/ui/src/hooks/stop-registry/useEditStopBasicDetails.ts#L35)):*
> ```XML
> }
> 
> // TODO: Go through this. Some of it can be deleted, but realised that the label name change conflicts are currently
> ```

Yep, at least `deleteStopFromRoutes` and `deleteStopFromJourneyPatternIds` look unnecessary to me (one reason why I suggested separating this from the other hook type in the first place). Maybe indeed check again when dealing with label.
___
*[`ui/src/types/enums.ts` line 80 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nuh2cK68DLQGPh2bSET:-Nv5oiH02u9pAvJ7gk_X:b-e2rqjk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/efb630dd02458d39a510a847b232542491c4ecb5/ui/src/types/enums.ts#L80)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

That was my first code, but for some random reason it ends up being wrong. (Has everything doubled)
```
{
  Bus: 'bus',
  Metro: 'metro',
  Rail: 'rail',
  Tram: 'tram',
  Water: 'water',
  bus: 'Bus',
  metro: 'Metro',
  rail: 'Rail',
  tram: 'Tram',
  water: 'Water',
};
```
I dont know why this happens, 
If I do this in ts playground https://www.typescriptlang.org/play?#code/KYOwrgtgBAygLgewA4CVgHMCWBnOAnATwBU8BDEbJBPOAWQQBNgiClgoBvAKCigEFMeKAF4oAclKCxAGh5QAQmGwjxAIyUy5AYVKqANsADupAirEBjXQeMFNvAGJgQmc2D2khosQDMnLtx52ULTA+AhmEKF4CEEoknpmZJh6QSSk0F746UEA6qRwwJ7ixgV4mgC+XFWgkLCIqBg4+MRkFFQ09EwsbDBgqtihnHKKyqLwyGhYuIRpbdR0jMyswAB0I7K8aRl1E43TLeSU851LbCtbG8FR4WP1k00zrUcdi92rIWGXcckq4w1TzVmzwWXWWK2+ekueVKvzue0BT3aINOq2hhVklXMCAoCAMKz0CHQAAo-vd9kCkSc3r1+qEAJRAA

Everyhtings fine, also If I define these enums in a file and console log them there, everything is OK. But if I use the StopREgistryTransportMOdeType, it doubles it up :shrug:
</blockquote></details>

:shrug: oh well, let's leave it as is.


<!-- Sent from Reviewable.io -->

2024-04-10 09:21 UTC, Leitsi requested changes
> Reviewed 6 of 6 files at r45.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799)* status: 6 of 43 files reviewed, 4 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 167 at r45](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv6Id3Q2_K8a9XduUWK:-Nv6Id3Q2_K8a9XduUWL:b-kwzv8a) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eccabbf822a560e5dd25e2a2787e9c01909c2f61/cypress/e2e/stop-registry/stopDetails.cy.ts#L167)):*
> ```XML
>     beforeEach(() => {
>       bdView = stopDetailsPage.basicDetails.basicDetailsViewCard;
>       bdForm = stopDetailsPage.basicDetails.basicDetailsForm;
> ```

Thinking if it would make sense to eliminate some repetition in names here. :shrug: 



_Suggestion:_
```XML
      bdView = stopDetailsPage.basicDetails.viewCard;
      bdForm = stopDetailsPage.basicDetails.form;
```
___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 243 at r45](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv6FtXmDPbbIgbdjm6b:-Nv6FtXmDPbbIgbdjm6c:b-v9geo6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eccabbf822a560e5dd25e2a2787e9c01909c2f61/cypress/e2e/stop-registry/stopDetails.cy.ts#L243)):*
> ```XML
>         bdView.getContent().shouldBeVisible();
> 
>         bdView.getLabel().shouldHaveText('H2003');
> ```

These shouldHaveText expects now exist in 3 tests., twice in each. On the `view and edit basic details text field` test this is fine since that's the purpose of the test, but on the rest of these I think they clutter the test unnecessarily, could tidy up a little.

Eg. here I would maybe only leave:
```
bdView.getLabel().shouldHaveText('H2003'); // sanity check that we are actually in correct stops page (though of course these never break, right?)
bdView.getTransportMode().shouldHaveText('Bussi');
bdView.getStopType().shouldHaveText('Runkolinja, vaihtopysäkki'); // since this is changed in the test, same for others below
bdView.getStopState().shouldHaveText('Pois käytöstä');
```
and just the `getStopType`, `getStopState` and `getTransportMode` expects after modifying.
___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 351 at r45](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv6Gj5z-SbDWBcCacva:-Nv6Gj6-5sATlVosqe8f:bys452a) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eccabbf822a560e5dd25e2a2787e9c01909c2f61/cypress/e2e/stop-registry/stopDetails.cy.ts#L351)):*
> ```XML
>           bdView.getAbbreviation5CharSwe().shouldHaveText('N.Esp');
>           bdView.getTransportMode().shouldHaveText('Bussi');
>           bdView.getTimingPlaceId().shouldHaveText('1AURLA');
> ```

Same here, I don't think it's quite necessary to check much else than `getTimingPlaceId`
___
*[`cypress/support/index.d.ts` line 21 at r45](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv6EWah87c5HtJ-zDqc:-Nv6EWah87c5HtJ-zDqd:brzvuwh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eccabbf822a560e5dd25e2a2787e9c01909c2f61/cypress/support/index.d.ts#L21)):*
> ```XML
> 
>     /**
>      * Custom command to click input field, clear it and type value
> ```

There does not seem to be a click though.
___
*[`ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx` line 50 at r9](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-NuhbNcl3jy0rwRkNdZ9:-Nv6C14a2DPRXq8JbDFs:bgjnkd1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c1195b994e2c23532e6c65b7768a18bf2c592da1/ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx#L50)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Clicking edit now hides the expand button as well and expands the card if it was shrunk.
Also added a stupid pixelplacement h-14 (which I hate) to the header div, so that it does not change size when the buttons are hidden / visible. There has to be a better solution to this as well but Im a bit tired of this PR already and don't have the energy to solve this any further now :D
</blockquote></details>

:thumbsup:  let's tinker with the buttons more later when we need to add more of them. At least it doesn't look broken now.
___
*[`ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx` line 80 at r45](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv6D94F2JbjqdbGVSQv:-Nv6D94F2JbjqdbGVSQw:b-7w9gt3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eccabbf822a560e5dd25e2a2787e9c01909c2f61/ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx#L80)):*
> ```XML
>               )}
>             </SlimSimpleButton>
>           )}
> ```

You can get rid of the `h-14` above if instead you just hide this button when not needed (so the height is maintained), instead of omitting completely.



_Suggestion:_
```XML
            <SlimSimpleButton
              onClick={onToggle}
              inverted={!isExpanded}
              className={isEditMode ? 'invisible' : ''}
              testId={testIds.toggle(testIdPrefix)}
            >
              {isExpanded ? (
                <FaChevronUp className="text-white" aria-hidden />
              ) : (
                <FaChevronDown className="text-tweaked-brand" aria-hidden />
              )}
            </SlimSimpleButton>
```


<!-- Sent from Reviewable.io -->

2024-04-10 11:05 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799)* status: 0 of 43 files reviewed, 4 unresolved discussions (waiting on @Leitsi)

___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 243 at r45](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv6FtXmDPbbIgbdjm6b:-Nv6eqIh02_JzqxU6zT4:b-lu6mo2) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eccabbf822a560e5dd25e2a2787e9c01909c2f61/cypress/e2e/stop-registry/stopDetails.cy.ts#L243)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

These shouldHaveText expects now exist in 3 tests., twice in each. On the `view and edit basic details text field` test this is fine since that's the purpose of the test, but on the rest of these I think they clutter the test unnecessarily, could tidy up a little.

Eg. here I would maybe only leave:
```
bdView.getLabel().shouldHaveText('H2003'); // sanity check that we are actually in correct stops page (though of course these never break, right?)
bdView.getTransportMode().shouldHaveText('Bussi');
bdView.getStopType().shouldHaveText('Runkolinja, vaihtopysäkki'); // since this is changed in the test, same for others below
bdView.getStopState().shouldHaveText('Pois käytöstä');
```
and just the `getStopType`, `getStopState` and `getTransportMode` expects after modifying.
</blockquote></details>

I cleared some of these up and left a comment in one place where we doublecheck all the fields.
___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 351 at r45](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv6Gj5z-SbDWBcCacva:-Nv6fiho8zZTeQpW0UrE:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eccabbf822a560e5dd25e2a2787e9c01909c2f61/cypress/e2e/stop-registry/stopDetails.cy.ts#L351)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Same here, I don't think it's quite necessary to check much else than `getTimingPlaceId`
</blockquote></details>

:+1: 
___
*[`cypress/support/index.d.ts` line 21 at r45](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv6EWah87c5HtJ-zDqc:-Nv6WQo80k_dCV9RBirW:b-4vziin) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eccabbf822a560e5dd25e2a2787e9c01909c2f61/cypress/support/index.d.ts#L21)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

There does not seem to be a click though.
</blockquote></details>

Ah, good one. I think there actually was a click at first, but then I tested if it works without the click and it did. Probably forgot to update the comment (classic)
___
*[`ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx` line 80 at r45](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-Nv6D94F2JbjqdbGVSQv:-Nv6XiR7AQ6Z3H9dMB4w:b-ukma9s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/eccabbf822a560e5dd25e2a2787e9c01909c2f61/ui/src/components/stop-registry/stops/stop-details/ExpandableInfoContainer.tsx#L80)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

You can get rid of the `h-14` above if instead you just hide this button when not needed (so the height is maintained), instead of omitting completely.
</blockquote></details>

That is true, but I think we stopped using 'invisible' classname, because it has its issues with accessibility (screen reader still sees it or something).


<!-- Sent from Reviewable.io -->

2024-04-10 13:02 UTC, Leitsi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/799#-:-Nv75Wzg2EuGz83KXV7m:bnfp4nl)* status: 0 of 43 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-11 05:58 UTC, merged