E2e test renovation 2
HSLdevcom/jore4-ui pull request #827
Opened 2024-05-30 13:59 UTC by HenrikHartiala

Create base dataset for timetables. This currently consists of two vehicle services, which each has 3 round trips. So total 6 departures per direction. These timetables are constructed to work with the base dataset route 901.

Also some refactoring and adding / enhancing tests. More info on commit messages.

2024-05-31 05:59 UTC, Leitsi requested changes
> Reviewed 3 of 3 files at r1, 5 of 5 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827)* status: all files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/datasets/timetables.ts` line 15 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzC25-o4d1785cdxEQP:-NzC25-o4d1785cdxEQQ:b-rljlvi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f784ff7d6901f507a6fc526ff701de7a5dcce862/cypress/datasets/timetables.ts#L15)):*
> ```XML
> const baseTimetableDataInput = {
>   _journey_pattern_refs: {
>     route901inbound: {
> ```

Should all of these be outbound first and inbound second, like in routes base dataset?
Not that it matters in an object.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 96 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzC4kAJ-VftVMMlyKNE:-NzC4kAJ-VftVMMlyKNF:b-h8rlyo) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d9d987bdf39241293f0d87967c0912ef8885aa33/cypress/e2e/timetablePassingTimes.cy.ts#L96)):*
> ```XML
>         .getRouteSection('901', RouteDirectionEnum.Outbound)
>         .within(() => {
>           // Click one passing time to hilight the journey
> ```

Nit, using a both `hilight` and `highlight` here.
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 172 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzCAq8C7mCQEeG6V1En:-NzCAq8C7mCQEeG6V1Eo:b3kruji) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d9d987bdf39241293f0d87967c0912ef8885aa33/cypress/e2e/timetablePassingTimes.cy.ts#L172)):*
> ```XML
>         .within(() => {
>           // E2E007
>           // Hour 07
> ```

Would be neat if we could check the hour in code as well, instead of just comments.
Would need some refactoring though. Should be doable since all passing times under a specific hour are inside the same parent element (PassingTimesByStopTableRowPassingTime).
Current page objects have this kind of structure that enables this:
```
      this.passingTimesByStopTableRowPassingTime
        .getTimeContainerByHour(passingTimeInfo.hour)
        .within(() => {
```
___
*[`cypress/e2e/timetableVersionDetailsPanel.cy.ts` line 111 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzC3Tb_1wgjAsqWpgrg:-NzC3Tb_1wgjAsqWpgrh:b-lqrif8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f784ff7d6901f507a6fc526ff701de7a5dcce862/cypress/e2e/timetableVersionDetailsPanel.cy.ts#L111)):*
> ```XML
>             vehicleServiceRow.getHour().should('contain', '07');
>             vehicleServiceRow.getMinute().eq(0).should('contain', '30');
>             vehicleServiceRow.getMinute().eq(1).should('contain', '40');
> ```

Would be good to check that there's no extra elements.
Does `vehicleServiceRow.getMinute().should('have.length', 2)` or something work?
___
*[`cypress/e2e/timetableVersionDetailsPanel.cy.ts` line 131 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzC49sL8SmpuR3Tcalm:-NzC49sL8SmpuR3Tcaln:undefined) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f784ff7d6901f507a6fc526ff701de7a5dcce862/cypress/e2e/timetableVersionDetailsPanel.cy.ts#L131)):*
> ```XML
>           });
>         // hour 10 departures
>         cy.wrap(rows)
> ```





_Suggestion:_
```XML
          });

        // hour 10 departures
        cy.wrap(rows)
```


<!-- Sent from Reviewable.io -->

2024-05-31 07:39 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827)* status: all files reviewed, 2 unresolved discussions (waiting on @Leitsi)

___
*[`cypress/datasets/timetables.ts` line 15 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzC25-o4d1785cdxEQP:-NzCZhW3Dk3VrKPQnOCX:b-4n61ay) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f784ff7d6901f507a6fc526ff701de7a5dcce862/cypress/datasets/timetables.ts#L15)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Should all of these be outbound first and inbound second, like in routes base dataset?
Not that it matters in an object.
</blockquote></details>

Yeah good one, and also like discussed in slack, I actually exchanged the outbound and inbound timetables so that the trip actually starts from outbound and the "trip back" will be inbound. This way the full journey will be E2E001 -> E2E009 instead of E2E005 -> E2E009 -> E2E001 -> E2E005
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 96 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzC4kAJ-VftVMMlyKNE:-NzCEirC9Dpup6zGPWOp:bnwetfr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d9d987bdf39241293f0d87967c0912ef8885aa33/cypress/e2e/timetablePassingTimes.cy.ts#L96)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Nit, using a both `hilight` and `highlight` here.
</blockquote></details>

:+1: I'll change it to highlight. 
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 172 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzCAq8C7mCQEeG6V1En:-NzCRqUz6s7ND1aXwDfB:b6i6mz8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d9d987bdf39241293f0d87967c0912ef8885aa33/cypress/e2e/timetablePassingTimes.cy.ts#L172)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Would be neat if we could check the hour in code as well, instead of just comments.
Would need some refactoring though. Should be doable since all passing times under a specific hour are inside the same parent element (PassingTimesByStopTableRowPassingTime).
Current page objects have this kind of structure that enables this:
```
      this.passingTimesByStopTableRowPassingTime
        .getTimeContainerByHour(passingTimeInfo.hour)
        .within(() => {
```
</blockquote></details>

Ah right, forgot about that one.
As a solution, I added another pageObject `PassingTimesByStopTableRow` and copypasted the methods there, since I think that is the correct place to search for time containers. And then we dig deeper with the within() methods in the test.

How does it look now?
___
*[`cypress/e2e/timetableVersionDetailsPanel.cy.ts` line 111 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzC3Tb_1wgjAsqWpgrg:-NzCSrF57fEx00q9Sp3b:b-r8k9kt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f784ff7d6901f507a6fc526ff701de7a5dcce862/cypress/e2e/timetableVersionDetailsPanel.cy.ts#L111)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Would be good to check that there's no extra elements.
Does `vehicleServiceRow.getMinute().should('have.length', 2)` or something work?
</blockquote></details>

Yes great one! Thanks :+1: 


<!-- Sent from Reviewable.io -->

2024-05-31 10:45 UTC, Leitsi requested changes
> Reviewed 1 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827)* status: 2 of 16 files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 172 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzCAq8C7mCQEeG6V1En:-NzDDaQ01RhTLOCJKPhO:b-9rzfho) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d9d987bdf39241293f0d87967c0912ef8885aa33/cypress/e2e/timetablePassingTimes.cy.ts#L172)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Ah right, forgot about that one.
As a solution, I added another pageObject `PassingTimesByStopTableRow` and copypasted the methods there, since I think that is the correct place to search for time containers. And then we dig deeper with the within() methods in the test.

How does it look now?
</blockquote></details>

Now feels like there's two ways of doing stuff:
- find the hour container, deal with minutes inside it
- find all minutes in the view and access by index

Would it be neat to force everything to use the first method?
So something like:
- remove `getStopNthPassingTimesArrivalTime` (unused)
- move `assertStopNthPassingTimeShouldBeHighlighted` to `PassingTimesByStopTableRowPassingMinute`

This will make the tests slightly more verbose maybe.

`getAllStopPassingTimesMinuteButtons` and `getAllPassingTimeArrivalTimes` and `getHighlightedElements` in  StopTable page object are possibly still useful for doing assertions for total amount of times in the view. If not intended to be used for anything else, opportunity for refactoring to `assertTotalMinuteButtons` and `assertTotalArrivalTimes` or something?
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 177 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzDFAjI2O054DN7BGLB:-NzDFAjI2O054DN7BGLC:bn7t49x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b20d9bfed194209096d153c7be115fdfa5f63d3f/cypress/e2e/timetablePassingTimes.cy.ts#L177)):*
> ```XML
>               .getTimeContainerByHour('7')
>               .within(() => {
>                 passingTimesByStopTable.row.passingTime
> ```

If the intent is to check all minutes within the hour, these should also include a check that there are no additional minutes. Probably needs some new page object method.
___
*[`cypress/pageObjects/timetables/PassingTimesByStopTableRow.ts` line 12 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzDALo_7VHvw56AVQqT:-NzDALo_7VHvw56AVQqU:b-o9b9us) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b20d9bfed194209096d153c7be115fdfa5f63d3f/cypress/pageObjects/timetables/PassingTimesByStopTableRow.ts#L12)):*
> ```XML
>   }
> 
>   getHour() {
> ```

I think this method could be a bit misleading now, since there can be (and with base data set, is) multiple time containers = hours on the row. Since this currently isn't used outside this page object, I would maybe just inline it to ` getTimeContainerByHour`.


<!-- Sent from Reviewable.io -->

2024-06-03 11:05 UTC, Leitsi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-:-NzSlcvo5RgnL8Zvo6nj:bnfp4nl)* status: 2 of 19 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 200 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzSlFRX0dQbRMN_9YuY:-NzSlFRX0dQbRMN_9YuZ:b-2i92yg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/db7a60fd51369c10ef58cd160fed9f54cef36ce8/cypress/e2e/timetablePassingTimes.cy.ts#L200)):*
> ```XML
>               passingTime.assertNthArrivalTime(0, '42');
> 
>               passingTime.assertNthArrivalTime(1, '52');
> ```

Don't think these would necessarily need to have empty lines at all.



_Suggestion:_
```XML
              passingTime.assertTotalMinuteCount(2);
              passingTime.assertNthArrivalTime(0, '42');
              passingTime.assertNthArrivalTime(1, '52');
```


<!-- Sent from Reviewable.io -->

2024-06-03 11:44 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827)* status: 2 of 19 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 172 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzCAq8C7mCQEeG6V1En:-NzStYnpEi1UzOPZ1dMo:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/d9d987bdf39241293f0d87967c0912ef8885aa33/cypress/e2e/timetablePassingTimes.cy.ts#L172)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Now feels like there's two ways of doing stuff:
- find the hour container, deal with minutes inside it
- find all minutes in the view and access by index

Would it be neat to force everything to use the first method?
So something like:
- remove `getStopNthPassingTimesArrivalTime` (unused)
- move `assertStopNthPassingTimeShouldBeHighlighted` to `PassingTimesByStopTableRowPassingMinute`

This will make the tests slightly more verbose maybe.

`getAllStopPassingTimesMinuteButtons` and `getAllPassingTimeArrivalTimes` and `getHighlightedElements` in  StopTable page object are possibly still useful for doing assertions for total amount of times in the view. If not intended to be used for anything else, opportunity for refactoring to `assertTotalMinuteButtons` and `assertTotalArrivalTimes` or something?
</blockquote></details>

:+1: 
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 177 at r6](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzDFAjI2O054DN7BGLB:-NzStXtG2qI92DRHi6Zb:b-8fx2u7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/b20d9bfed194209096d153c7be115fdfa5f63d3f/cypress/e2e/timetablePassingTimes.cy.ts#L177)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

If the intent is to check all minutes within the hour, these should also include a check that there are no additional minutes. Probably needs some new page object method.
</blockquote></details>

:+1: 
___
*[`cypress/e2e/timetablePassingTimes.cy.ts` line 200 at r8](https://reviewable.io/reviews/HSLdevcom/jore4-ui/827#-NzSlFRX0dQbRMN_9YuY:-NzStCxp0BJBAMIh3W9H:b-mmilwa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/db7a60fd51369c10ef58cd160fed9f54cef36ce8/cypress/e2e/timetablePassingTimes.cy.ts#L200)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

Don't think these would necessarily need to have empty lines at all.
</blockquote></details>

True, especially now that they are oneliners. :+1: 


<!-- Sent from Reviewable.io -->

2024-06-03 12:00 UTC, merged