Map ci fix
HSLdevcom/jore4-ui pull request #834
Opened 2024-06-04 05:42 UTC by Perholehto

2024-06-07 09:19 UTC, Huulivoide requested changes

2024-06-07 09:19 UTC, Huulivoide commented on ui/src/components/map/DrawRouteLayer.tsx
Tässä kun on nyt aika paljon tätä komponenttia tunkattu, niin saiskos tätä samalla refaktoroitua vähän pienempiin osiin? Tässä on kuitenkin nyt 300 rivi pitkä funkkari. Tyyliin jotain `useEffect` tai `useCallback` kutsuja eroteltua omiks `useMySpecialEffect(a,b,c)` ylätason funkkareiks.

2024-06-07 09:19 UTC, Huulivoide commented on ui/src/components/map/Map.tsx
> +  const editorLayerRef = useRef<ExplicitAny>(null);
Eiks näille pysty kertoon oikeeta tyyppiä?

2024-06-07 09:19 UTC, Huulivoide commented on ui/src/components/map/routes/ArrowRenderLayer.tsx
> +export interface ArrowLayout {
Uff, `no-use-before-define` eslint sääntö ei selvästikkään oo päällä

2024-06-07 09:19 UTC, Huulivoide commented on ui/src/utils/map/lineFromStopToInfraLink.ts
> +  if (map) {
Ite tykkään aina käyttää early-return tyyliä, jos vaan mahdollista.
Nyt jäin hetkeksi ettiin tän if-lauseen else-osiota, mutta eihän sitä ollutkaan olemassa, ja kuitnekin aika pitkä funkkari, niin hetken sai silmäillä kaikkiä näitä if-tasoja.

```typescript
if (!map) {
  return;
}

...
```

2024-06-07 09:19 UTC, Huulivoide commented on ui/src/utils/map/lineFromStopToInfraLink.ts
> +        data: { type: 'Feature', properties: {}, geometry },
Tässä on nyt duplikoituna tää data kahdelle riville. Tän vois ottaa ulos erillisene muuttujaan `const data = { … }` ja sit täällä if-else osiossa siihen viitata.

2024-06-07 09:19 UTC, Huulivoide commented on ui/src/utils/map/lineFromStopToInfraLink.ts
> +  if (map) {
Alemmassa funkkarissa tohon tyyliin onkin jo tehty

2024-06-13 10:33 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834)* status: 0 of 40 files reviewed, 7 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/components/map/CustomOverlay.tsx` line 15 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#gh-1630867451:-O-G8Njx51BPTvkGPpLk:b-etg4np) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f3f349919cbea156ce5d42fe23bb941da227d3c/ui/src/components/map/CustomOverlay.tsx#L15)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tässä ei nyt ihan kauheena oo koodia, niin eikö tää olis sama kirjottaa vaan meille parempammin sopivaan muotoon, että tarvi eslint sääntöjä pistää pois päältä. Ja muutenkin kirjottaa noi private jutut oikeesti privoina, eikä tolleen alaviivalla höpöhöpö tyyliin. Mielellään varmaan ihan jopa perus JS priva syntaksilla, joka on ollut tuettuna jo iät ja ajat.
</blockquote></details>

I didn't write this from scratch now nor before... Removed eslint disables and changed properties to private.
___
*[`ui/src/components/map/DrawRouteLayer.tsx` line 0 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#gh-1630888740:-O-G8cKh3HUj-5YrB4Ca:b-9k26p3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f3f349919cbea156ce5d42fe23bb941da227d3c/ui/src/components/map/DrawRouteLayer.tsx#L0)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tässä kun on nyt aika paljon tätä komponenttia tunkattu, niin saiskos tätä samalla refaktoroitua vähän pienempiin osiin? Tässä on kuitenkin nyt 300 rivi pitkä funkkari. Tyyliin jotain `useEffect` tai `useCallback` kutsuja eroteltua omiks `useMySpecialEffect(a,b,c)` ylätason funkkareiks.
</blockquote></details>

I refactored this to smaller pieces. `useSnappingLine` is still kind of big...
___
*[`ui/src/components/map/DrawRouteLayer.tsx` line 65 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#gh-1630887032:-O-G8wVC7CoYPKooF_kX:bb7f2mf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f3f349919cbea156ce5d42fe23bb941da227d3c/ui/src/components/map/DrawRouteLayer.tsx#L65)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Esim tästähän sais helposti pätkästyy funktion `setCursor(mapRef, drawingMode)`
</blockquote></details>

done
___
*[`ui/src/components/map/Map.tsx` line 53 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#gh-1630890380:-O-G8xhm3XW_uOrtantq:b-hc7hm4) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f3f349919cbea156ce5d42fe23bb941da227d3c/ui/src/components/map/Map.tsx#L53)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Eiks näille pysty kertoon oikeeta tyyppiä?
</blockquote></details>

Added types
___
*[`ui/src/components/map/routes/ArrowRenderLayer.tsx` line 13 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#gh-1630901301:-O-G926rB5__OAX-tt_0:bfcq93s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f3f349919cbea156ce5d42fe23bb941da227d3c/ui/src/components/map/routes/ArrowRenderLayer.tsx#L13)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Uff, `no-use-before-define` eslint sääntö ei selvästikkään oo päällä
</blockquote></details>

Moved interface initialization before usage. Seems like we don't have that rule.
___
*[`ui/src/utils/map/lineFromStopToInfraLink.ts` line 77 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#gh-1630916518:-O-G9DNmEAv08RTQ92wC:bb7f2mf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f3f349919cbea156ce5d42fe23bb941da227d3c/ui/src/utils/map/lineFromStopToInfraLink.ts#L77)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Alemmassa funkkarissa tohon tyyliin onkin jo tehty
</blockquote></details>

done
___
*[`ui/src/utils/map/lineFromStopToInfraLink.ts` line 82 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#gh-1630917986:-O-G9EK-8YPybufcefE7:bb7f2mf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f3f349919cbea156ce5d42fe23bb941da227d3c/ui/src/utils/map/lineFromStopToInfraLink.ts#L82)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tässä on nyt duplikoituna tää data kahdelle riville. Tän vois ottaa ulos erillisene muuttujaan `const data = { … }` ja sit täällä if-else osiossa siihen viitata.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-06-14 08:25 UTC, Huulivoide requested changes
> Reviewed 21 of 31 files at r1, 13 of 16 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834)* status: all files reviewed, 3 unresolved discussions (waiting on @Perholehto)

___
*[`ui/src/hooks/map/useSnappingLine.ts` line 14 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#-O-KpYP29LslHL2CY4nv:-O-KpYP29LslHL2CY4nw:b-whnjbl) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a550c48d4f9b960e1da5fca72acaf3de2dd1e2d4/ui/src/hooks/map/useSnappingLine.ts#L14)):*
> ```XML
> export const useSnappingLine = (map: MapRef<Map> | undefined) => {
>   const dispatch = useAppDispatch();
>   const [snappingLine, setSnappingLine] = useState<LineStringFeature>();
> ```

Tän vois tyypittää mielummin
```typescript
 const [snappingLine, setSnappingLine] = useState<LineStringFeature | null>(null);
```

Koska toi null kuvastaa paljon paremmin tilannetta, jossa arvoa ei ole, toisin kun undefined, joka voi johtua monesta syystä. Tässsähän ei tilannen ole (ainakaan en oleta niin), että snappingLineä ei vaan ole löytynyt, vaikka niin on oletetty, vaan sen sijaan se on tarkoituksellisesti tyhjä.
___
*[`ui/src/hooks/map/useSnappingLine.ts` line 16 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#-O-KoH6sDoriGW1sOkOm:-O-KoH6sDoriGW1sOkOn:b-3bch0z) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a550c48d4f9b960e1da5fca72acaf3de2dd1e2d4/ui/src/hooks/map/useSnappingLine.ts#L16)):*
> ```XML
>   const [snappingLine, setSnappingLine] = useState<LineStringFeature>();
> 
>   const onDelete = useCallback(() => {
> ```

Tää on nyt vähän huono. Ku täältä hookista kuitenkin palautetaan suoraan muös setSnappingLine ulos. Jos sitä joku menee kutsumaan ulkopuolelta `setSnappingLine(undefined)` niin sitten sitä ei poisteta kartalta.

Tässä pitäs varmaan olla mielummin:
```typescript
useEffect(() => {
  if (!snappingLine) {
    removeRoute(map.getMap(), SNAPPING_LINE_LAYER_ID);
    dispatch(resetDraftRouteGeometryAction());
  }
  firstCall.current = false;
}, [snappingLine]);
```

Ja sitten ei tarvis välttämättä olla erillistä onDelete funktiota ollenkaan, taikka sitten se vois olla suoraan vaan `onDelete = setSnappingLine(tyyhjä arvo)`
___
*[`ui/src/utils/map/lineFromStopToInfraLink.ts` line 77 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#gh-1630916518:-O-KqEY--1Yq7D_yIMUr:bw32d7g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f3f349919cbea156ce5d42fe23bb941da227d3c/ui/src/utils/map/lineFromStopToInfraLink.ts#L77)):*
<details><summary><i>Previously, Perholehto (Jarno) wrote…</i></summary><blockquote>

done
</blockquote></details>

Lukee Done, mutta ei kuitenkaan ole muutosta :)


<!-- Sent from Reviewable.io -->

2024-06-14 10:55 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834)* status: 36 of 40 files reviewed, 3 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/hooks/map/useSnappingLine.ts` line 14 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#-O-KpYP29LslHL2CY4nv:-O-LNPMI8T7jf95ifGPD:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a550c48d4f9b960e1da5fca72acaf3de2dd1e2d4/ui/src/hooks/map/useSnappingLine.ts#L14)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tän vois tyypittää mielummin
```typescript
 const [snappingLine, setSnappingLine] = useState<LineStringFeature | null>(null);
```

Koska toi null kuvastaa paljon paremmin tilannetta, jossa arvoa ei ole, toisin kun undefined, joka voi johtua monesta syystä. Tässsähän ei tilannen ole (ainakaan en oleta niin), että snappingLineä ei vaan ole löytynyt, vaikka niin on oletetty, vaan sen sijaan se on tarkoituksellisesti tyhjä.
</blockquote></details>

Done.
___
*[`ui/src/hooks/map/useSnappingLine.ts` line 16 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#-O-KoH6sDoriGW1sOkOm:-O-LNPiUAZJemrQ4YRPG:b-xv9f8k) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a550c48d4f9b960e1da5fca72acaf3de2dd1e2d4/ui/src/hooks/map/useSnappingLine.ts#L16)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tää on nyt vähän huono. Ku täältä hookista kuitenkin palautetaan suoraan muös setSnappingLine ulos. Jos sitä joku menee kutsumaan ulkopuolelta `setSnappingLine(undefined)` niin sitten sitä ei poisteta kartalta.

Tässä pitäs varmaan olla mielummin:
```typescript
useEffect(() => {
  if (!snappingLine) {
    removeRoute(map.getMap(), SNAPPING_LINE_LAYER_ID);
    dispatch(resetDraftRouteGeometryAction());
  }
  firstCall.current = false;
}, [snappingLine]);
```

Ja sitten ei tarvis välttämättä olla erillistä onDelete funktiota ollenkaan, taikka sitten se vois olla suoraan vaan `onDelete = setSnappingLine(tyyhjä arvo)`
</blockquote></details>

Made alternative changes. We don't expose `setSnappingLine` directly because it's not necessary. Instead use wrapper and no need to add more effects
___
*[`ui/src/utils/map/lineFromStopToInfraLink.ts` line 77 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#gh-1630916518:-O-LNJMvC1G25t6dxHpY:b-jd65m0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/9f3f349919cbea156ce5d42fe23bb941da227d3c/ui/src/utils/map/lineFromStopToInfraLink.ts#L77)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Lukee Done, mutta ei kuitenkaan ole muutosta :)
</blockquote></details>

This was in my stash :grin: 


<!-- Sent from Reviewable.io -->

2024-06-14 12:11 UTC, Huulivoide approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Perholehto)



<!-- Sent from Reviewable.io -->

2024-06-17 08:22 UTC, HenrikHartiala reviewed
> Reviewed 5 of 31 files at r1, 1 of 16 files at r2, 3 of 6 files at r3, 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834)* status: 39 of 40 files reviewed, 1 unresolved discussion (waiting on @Huulivoide and @Perholehto)

___
*[`cypress/e2e/editStop.cy.ts` line 123 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#-O-_E9JWDQP1Qu-gNoSA:-O-_E9JWDQP1Qu-gNoSB:b7u8lu1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a46eb43e4260f628cb9414828250cd09676e7b89/cypress/e2e/editStop.cy.ts#L123)):*
> ```XML
>       // Coordinates for the point where the stop is moved in the test.
>       const endCoordinates = {
>         lng: 24.923290685436285,
> ```

Just making sure that these coordinate changes were intended?


<!-- Sent from Reviewable.io -->

2024-06-17 09:24 UTC, Perholehto reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834)* status: 39 of 40 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala and @Huulivoide)

___
*[`cypress/e2e/editStop.cy.ts` line 123 at r5](https://reviewable.io/reviews/HSLdevcom/jore4-ui/834#-O-_E9JWDQP1Qu-gNoSA:-O-_TRl-1_8Ll57RoHiv:b710qfn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a46eb43e4260f628cb9414828250cd09676e7b89/cypress/e2e/editStop.cy.ts#L123)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Just making sure that these coordinate changes were intended?
</blockquote></details>

Yes, they are intended and needed, tested without these and test fails.


<!-- Sent from Reviewable.io -->

2024-06-17 12:27 UTC, merged