Insert stop place on create
HSLdevcom/jore4-ui pull request #844
Opened 2024-06-24 06:29 UTC by HenrikHartiala

Add stop place insert when creating stop on map

Earlier when we created a stop, we only created the scheduled_stop_point to
routes and lines database, but we need to also add an stop place entry to tiamat.
After that we need to update the newly created scheduled_stop_point's stop_place_ref
to point to the newly created stopPlace.
NOTE: These three queries are needed, but they are not in a transaction yet. So if one of the latter
queries fail, there is no rollbacks. This could've been all in one "mutation" instead of three separate, but
I think that could give the impression that they are done in a transaction which it isn't since they are actually
in different databases and GQL does not support transactions between multiple databases.
Also a minor thing but moved GQL_INSERT_STOP to useCreateStop.ts.

2024-06-24 09:04 UTC, Leitsi requested changes
> Reviewed 4 of 4 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844)* status: all files reviewed, 3 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/e2e/createStop.cy.ts` line 215 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-O08Tp_DDzqXjQZJWuN2:-O08Tp_DDzqXjQZJWuN3:bspebmn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c1298894d1f5da94e68135d3f4a6e05251b5e7f5/cypress/e2e/createStop.cy.ts#L215)):*
> ```XML
>   it(
>     'Should create stop and have its stop registry details correctly',
>     { tags: [Tag.Map, Tag.Stops], scrollBehavior: 'bottom' },
> ```

Could maybe add `Tag.StopRegistry` here as well, since we're dealing with creating stop registry entities.
___
*[`cypress/e2e/createStop.cy.ts` line 233 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-O08TdoD-We0sJClF4Eq:-O08TdoD-We0sJClF4Er:b-f5g82z) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/c1298894d1f5da94e68135d3f4a6e05251b5e7f5/cypress/e2e/createStop.cy.ts#L233)):*
> ```XML
>       navbar.getStopsLink().click();
>       stopSearchBar.getSearchInput().type('T0001{enter}');
>       stopSearchResultsPage.getRowLinkByLabel('T0001').click();
> ```

Nit, would make more sense to me to put newlines like this, maybe.



_Suggestion:_
```XML
      mapModal.checkStopSubmitSuccessToast();
      mapModal.getCloseButton().click();

      navbar.getStopsLink().click();

      stopSearchBar.getSearchInput().type('T0001{enter}');
      stopSearchResultsPage.getRowLinkByLabel('T0001').click();
```
___
*[`ui/src/components/map/stops/EditStopLayer.tsx` line 215 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-O08BBirAYy__oi8R94K:-O08BBirAYy__oi8R94L:brf5l1f) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6c67c75da1c80af822aaf10c35f77a2ed49d2b0b/ui/src/components/map/stops/EditStopLayer.tsx#L215)):*
> ```XML
>             ?.scheduled_stop_point_id
>         ) {
>           return;
> ```

What is this situation exactly? Insert failed?
___
*[`ui/src/components/map/stops/EditStopLayer.tsx` line 220 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-O08BLGc3A3QHkUDVkYK:-O08BLGc3A3QHkUDVkYL:b2nhkus) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6c67c75da1c80af822aaf10c35f77a2ed49d2b0b/ui/src/components/map/stops/EditStopLayer.tsx#L220)):*
> ```XML
>         const tiamatVariables = mapCreateChangesToTiamatVariables(changes);
> 
>         const stopPlaceResult = await insertStopPlaceMutation(tiamatVariables);
> ```

Nit



_Suggestion:_
```XML
        const tiamatVariables = mapCreateChangesToTiamatVariables(changes);
        const stopPlaceResult = await insertStopPlaceMutation(tiamatVariables);
```
___
*[`ui/src/components/map/stops/EditStopLayer.tsx` line 226 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-O08SKPD6sgEX7N8LH68:-O08SKPEBp13wQZMkDO0:b-6j5xa6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6c67c75da1c80af822aaf10c35f77a2ed49d2b0b/ui/src/components/map/stops/EditStopLayer.tsx#L226)):*
> ```XML
>             scheduled_stop_point_id:
>               stopResult.data?.insert_service_pattern_scheduled_stop_point_one
>                 ?.scheduled_stop_point_id,
> ```

No optional chaining needed here since the id is checked earlier.
Or could just stick it to a variable to begin with to shorten this even further.



_Suggestion:_
```XML
            scheduled_stop_point_id:
              stopResult.data.insert_service_pattern_scheduled_stop_point_one
                .scheduled_stop_point_id,
```
___
*[`ui/src/components/map/stops/EditStopLayer.tsx` line 229 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-O08Rn6P5VtebgTJWltl:-O08Rn6P5VtebgTJWltm:b-4lv516) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6c67c75da1c80af822aaf10c35f77a2ed49d2b0b/ui/src/components/map/stops/EditStopLayer.tsx#L229)):*
> ```XML
>             stop_place_ref:
>               stopPlaceResult?.data?.stop_registry?.mutateStopPlace &&
>               stopPlaceResult?.data?.stop_registry?.mutateStopPlace[0]?.id,
> ```

This can be simplified.



_Suggestion:_
```XML
            stop_place_ref:
              stopPlaceResult?.data?.stop_registry?.mutateStopPlace?.[0]?.id,
```
___
*[`ui/src/hooks/stops/useCreateStop.ts` line 41 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-O08AyL08A7DQ9vp3L-q:-O08AyL08A7DQ9vp3L-r:bpoq1od) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6c67c75da1c80af822aaf10c35f77a2ed49d2b0b/ui/src/hooks/stops/useCreateStop.ts#L41)):*
> ```XML
>     $object: service_pattern_scheduled_stop_point_insert_input!
>   ) {
>     insert_service_pattern_scheduled_stop_point_one(object: $object) {
> ```

Was not added in this PR, but anyway: what does this `_one` mean here :thinking: 
___
*[`ui/src/hooks/stops/useCreateStop.ts` line 54 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-O08R8e-0GdVFqr-nqRr:-O08R8e-0GdVFqr-nqRs:bxsut3s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6c67c75da1c80af822aaf10c35f77a2ed49d2b0b/ui/src/hooks/stops/useCreateStop.ts#L54)):*
> ```XML
> `;
> 
> const GQL_INSERT_STOP_PLACE = gql`
> ```

I would maybe like to move everything stop place related (so, this `GQL_INSERT_STOP_PLACE` and `mapCreateChangesToTiamatVariables`) from this hook to eg. `hooks/stop-registry/createStopPlace`, to keep all Tiamat modifying operations in one place. What do you think?


<!-- Sent from Reviewable.io -->

2024-06-24 12:46 UTC, Leitsi requested changes
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @HenrikHartiala)

___
*[`ui/src/hooks/stop-registry/useCreateStopPlace.ts` line 8 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-O09EtnR66kuDIzEPuYE:-O09EtnS93BtysGUEPu7:b2se2ep) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/875a11084e6cd164926fbc753ff0c1c7fe67451e/ui/src/hooks/stop-registry/useCreateStopPlace.ts#L8)):*
> ```XML
> } from '../../generated/graphql';
> 
> export interface CreateTiamatChanges {
> ```

I would like to avoid mentioning Tiamat too much whenever we can. Rather refer to is as "stop registry" if needed, like we've done with eg. the folder structure etc. Could just avoid this whole issue here with couple renamings, and I feel that these would improve the names anyway:
- `CreateTiamatChanges` -> `InsertStopPlaceInput`
- `mapCreateChangesToTiamatVariables` -> `mapToInsertStopPlaceVariables`


<!-- Sent from Reviewable.io -->

2024-06-25 11:01 UTC, HenrikHartiala reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @Leitsi)

___
*[`ui/src/hooks/stop-registry/useCreateStopPlace.ts` line 8 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-O09EtnR66kuDIzEPuYE:-O0E2Es0CR3UcYwzJUIP:bank54u) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/875a11084e6cd164926fbc753ff0c1c7fe67451e/ui/src/hooks/stop-registry/useCreateStopPlace.ts#L8)):*
<details><summary><i>Previously, Leitsi (Tommi Leinamo) wrote…</i></summary><blockquote>

I would like to avoid mentioning Tiamat too much whenever we can. Rather refer to is as "stop registry" if needed, like we've done with eg. the folder structure etc. Could just avoid this whole issue here with couple renamings, and I feel that these would improve the names anyway:
- `CreateTiamatChanges` -> `InsertStopPlaceInput`
- `mapCreateChangesToTiamatVariables` -> `mapToInsertStopPlaceVariables`
</blockquote></details>

Good point, made changes


<!-- Sent from Reviewable.io -->

2024-06-25 11:56 UTC, Leitsi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/844#-:-O0EFI0AAt8j9PNBBj0W:bnfp4nl)* status: 1 of 12 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-25 12:04 UTC, merged