Improve Map LoadingOverlay
HSLdevcom/jore4-ui pull request #868
Opened 2024-07-12 12:55 UTC by Huulivoide

### Rework Loader: Add Priority & allow LoadingOverlay to make use of them

* Instead of having booleans for the different Loader Operators, use a
  priority system for them:
  - NotLoading:Don't show LoadingOverlay
  - LowPriority: Not important & prefer not to show LoadingOverlay at all.
  - MediumPriority: No need to block further user input, but might confuse user of the network request is not immediate.
  - HighPriority: Immediately show LoadingOverlay

* Old Boolean based API kept in place with mapping:
  - false: NotLoading
  - true: HighPriority

* Update Map data features to use the new priority API.

* Updated LoadingOverlay to work with the Priority system.
  - Avoid Loader flashing the screen by always making sure that the loader is never just spawned in then hidden again on next frame.
  - If the loader is on screen, hiding it will happen on a timeout, making sure the loader stays on screen for at least 200ms.
  - Timeout for showing the loader on Medium prio is 300m.
  - Timeout for showing the loader on Low prio is 500ms.

* MapLoader:
  - Works with the new prio API.
  - Uses highest prio Map Operation as the prio.

* JoreLoader: Works with the old Boolean API.

### Add custom loader Operation for Infra Link fetching

Previously the Infra Link fetch was using the same loader Operation with the base Map, creating a potential conflict between them.

### Show single consistent loader when opening the map

Make sure all data fetches are synchronized and that we don't get multiple flashy loaders, from the multiple data layer fetch operations.

2024-07-15 11:15 UTC, HenrikHartiala requested changes
> Reviewed 12 of 12 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868)* status: all files reviewed, 5 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/components/map/Maplibre.tsx` line 67 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1ptYY2C_5Q4XY34RiD:-O1ptYY2C_5Q4XY34RiE:b72jeyy) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/components/map/Maplibre.tsx#L67)):*
> ```XML
>   const dispatch = useAppDispatch();
>   const { setLoadingState } = useLoader(Operation.LoadMap, {
>     immediatelyOn: LoadingState.HighPriority,
> ```

It seems that we already handle boolean values for _immediatelyOn_ in useLoader, so should this rather be just `true` instead of `LoadingState.HighPriority` for readability.
___
*[`ui/src/components/map/stop-areas/StopAreas.tsx` line 33 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1q4EcI2vRCL1ClGl3A:-O1q4EcI2vRCL1ClGl3B:b4putsz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8df75011e3a4ec4cf9621b3273c16a4813d489f9/ui/src/components/map/stop-areas/StopAreas.tsx#L33)):*
> ```XML
>       measured_location_filter: buildWithinViewportGqlGeometryFilter(viewport),
>     },
>     // Skip initial 0 radius fetch and wait for the map to get loaded,
> ```

:ok_hand: 
___
*[`ui/src/hooks/ui/useLoader.ts` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1pv3sq0Nlh6P-jCqrn:-O1pv3sq0Nlh6P-jCqro:bcfe2p) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/hooks/ui/useLoader.ts#L11)):*
> ```XML
> 
> interface LoaderOptions {
>   immediatelyOn?: boolean | LoadingState;
> ```

Like said in the other comment, we seem to have the boolean handling in the useEffect, so I think the LoadingState alternative type here is extra.
___
*[`ui/src/hooks/ui/useLoader.ts` line 55 at r3](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1q4_K-9J1WsFkMPAsR:-O1q4_K01aft-TQKqXrb:b-in7tp6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8df75011e3a4ec4cf9621b3273c16a4813d489f9/ui/src/hooks/ui/useLoader.ts#L55)):*
> ```XML
> }
> 
> export function useMapDataLayerLoader(
> ```

We've had only one hook per file, but since these are neat inherited hooks, I think its OK and probably better this way
___
*[`ui/src/redux/slices/loader.ts` line 22 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1pwuPi7eTqjwLNYdMv:-O1pwuPi7eTqjwLNYdMw:bjgps60) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/redux/slices/loader.ts#L22)):*
> ```XML
> }
> 
> export enum LoadingState {
> ```

This could benefit from a short JSDoc description about the different loading priorities
___
*[`ui/src/redux/slices/loader.ts` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1pxTCY2eFZXFkxScGT:-O1pxTCY2eFZXFkxScGU:b-rliyrt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/redux/slices/loader.ts#L23)):*
> ```XML
> 
> export enum LoadingState {
>   NotLoading = 'notLoading',
> ```

Also was thinking, that could we use integers for the enum values and then just return `Math.max(...loadingStates)` in getHighestLoadingState
___
*[`ui/src/redux/slices/loader.ts` line 35 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1pyBse7IasvZceQ186:-O1pyBse7IasvZceQ187:b6cxzau) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/redux/slices/loader.ts#L35)):*
> ```XML
>     return LoadingState.HighPriority;
>   }
> ```

Is medium priority currently skipped on purpose?
___
*[`ui/src/uiComponents/LoadingOverlay.tsx` line 62 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1q2BDcDUP1lJ2fXT1U:-O1q2BDcDUP1lJ2fXT1V:b-3k5wy1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/uiComponents/LoadingOverlay.tsx#L62)):*
> ```XML
> }
> 
> function useIsVisible(
> ```

At some point we decided to have all the business logic of the components to be separated in custom hooks in their own files, so all this should probably also be in its own hook file. Debatable of course (as everything is) if there is a valid reason to keep it this way.


<!-- Sent from Reviewable.io -->

2024-08-13 07:04 UTC, Huulivoide reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/uiComponents/LoadingOverlay.tsx` line 62 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1q2BDcDUP1lJ2fXT1U:-O49Y0hh7HYXrghs5p2_:b4462j) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/uiComponents/LoadingOverlay.tsx#L62)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

At some point we decided to have all the business logic of the components to be separated in custom hooks in their own files, so all this should probably also be in its own hook file. Debatable of course (as everything is) if there is a valid reason to keep it this way.
</blockquote></details>

Well previously this was inlined within the component body. Seems silly that if you want to extract a piece of code out of the function body to make it more readable that you would have to hide the extracted section in another file.


<!-- Sent from Reviewable.io -->

2024-08-13 08:27 UTC, Huulivoide reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868)* status: 8 of 14 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/redux/slices/loader.ts` line 22 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1pwuPi7eTqjwLNYdMv:-O49pssA6X8XdAKFuZCS:b-ejwm1u) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/redux/slices/loader.ts#L22)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

This could benefit from a short JSDoc description about the different loading priorities
</blockquote></details>

Doned ✔️
___
*[`ui/src/redux/slices/loader.ts` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1pxTCY2eFZXFkxScGT:-O49YRTn8y7FYUXup4oQ:b-umirjn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/redux/slices/loader.ts#L23)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Also was thinking, that could we use integers for the enum values and then just return `Math.max(...loadingStates)` in getHighestLoadingState
</blockquote></details>

I did consider doing that, but numeric enums are annoying to debug, because you can't see a human readable value for it when you console.log:it or see it redux tools or sumething.
___
*[`ui/src/redux/slices/loader.ts` line 35 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1pyBse7IasvZceQ186:-O49q9Nm6i26jG926HEW:b-aj3nzr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/redux/slices/loader.ts#L35)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Is medium priority currently skipped on purpose?
</blockquote></details>

Nope, fixed.


<!-- Sent from Reviewable.io -->

2024-08-16 12:18 UTC, Huulivoide reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868)* status: 1 of 17 files reviewed, 5 unresolved discussions (waiting on @HenrikHartiala)

___
*[`ui/src/components/map/Maplibre.tsx` line 67 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1ptYY2C_5Q4XY34RiD:-O4Q6FqO7czvwIIeDIr0:b-jqyk3x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/components/map/Maplibre.tsx#L67)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

It seems that we already handle boolean values for _immediatelyOn_ in useLoader, so should this rather be just `true` instead of `LoadingState.HighPriority` for readability.
</blockquote></details>

Boolean version is the old "comptabality" -API, that I left in place so that I didn't have to touch a million files in this PR. Specifying the actual loadstate we want, while being longer, is a clearer version, that does not require the reader to know that true maps to High.
___
*[`ui/src/hooks/ui/useLoader.ts` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1pv3sq0Nlh6P-jCqrn:-O4Q6oNfEMlLJurIl9rK:b-pf6enl) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/hooks/ui/useLoader.ts#L11)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Like said in the other comment, we seem to have the boolean handling in the useEffect, so I think the LoadingState alternative type here is extra.
</blockquote></details>

LoadingState is the new version and the actual type that we store in Redux. Boolean has simply been left in place compatability.


<!-- Sent from Reviewable.io -->

2024-08-19 08:45 UTC, HenrikHartiala requested changes
> Reviewed 13 of 13 files at r10, 2 of 2 files at r11, 4 of 4 files at r12, 4 of 4 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868)* status: all files reviewed, 2 unresolved discussions (waiting on @Huulivoide)

___
*[`cypress/pageObjects/Map.ts` line 20 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O4dQGww7DHR5ncTq_Ck:-O4dQGww7DHR5ncTq_Cl:bpnrfzr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e28fd8d94c6743815acfec9c24c56e95f53859db/cypress/pageObjects/Map.ts#L20)):*
> ```XML
>       if (iteration < n) {
>         // Panning and zoom events are debounced in the UI with delay of 800ms.
>         // Thus, we need to wait between the zooms, to allow the UI settle down
> ```

Hmm, yeah the debounce is not the issue. I think the 800ms debounce only affects how the UI state / urlQuery is updated but the map changes should be immediate.
I think that the issue is that the map zooms gradually and cypress sends another click before the earlier zoom is completely finished resulting that the last zoom starts at lets say 14.9xx and it adds 1 to that resulting that the final zoom level is 15.9xx instead of 16. (we start from zoom level 13 and 3 zooms should result in zoom level 16)

So I think it is okay to wait for 1000ms here (It should work with less wait time, but 1000ms ok to be sure). But I would at least adjust the comment (and commit message), because the issue is with the map, not with the debounce or cypress.
___
*[`ui/src/components/map/Maplibre.tsx` line 67 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1ptYY2C_5Q4XY34RiD:-O4dF8cJ-VX95Kllx5NI:b-vmsiyg) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/components/map/Maplibre.tsx#L67)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Boolean version is the old "comptabality" -API, that I left in place so that I didn't have to touch a million files in this PR. Specifying the actual loadstate we want, while being longer, is a clearer version, that does not require the reader to know that true maps to High.
</blockquote></details>

Hmm, I'm not completely sure if I follow. I mean it's ok if this solution greatly reduces the amount of changes, but my point was more likely that the `immediatelyOn` naming already indicates towards boolean value (Is the loader going to be visible immediately: yes/no*), so for me it is minorly confusing that it can get enum values as well. 
Maybe it could be renamed to `initialValue` or more like `immediateState` or something (?). 

*or maybe I've misunderstood something from the original purpose :D 

Well.. I'll put this comment as non-blocking as this it not a big deal anyways, but if any of this makes sense then feel free to make changes.
___
*[`ui/src/redux/slices/loader.ts` line 22 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1pwuPi7eTqjwLNYdMv:-O4dLmec95HHDPa6BZRt:b-ucfknh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/redux/slices/loader.ts#L22)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Doned ✔️
</blockquote></details>

Thanks!
___
*[`ui/src/redux/slices/loader.ts` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1pxTCY2eFZXFkxScGT:-O4dMC1-E5Xlr3C09J7Z:b-fc8stc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/redux/slices/loader.ts#L23)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

I did consider doing that, but numeric enums are annoying to debug, because you can't see a human readable value for it when you console.log:it or see it redux tools or sumething.
</blockquote></details>

Thats a very valid point :+1: 
___
*[`ui/src/uiComponents/LoadingOverlay.tsx` line 62 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1q2BDcDUP1lJ2fXT1U:-O4dO8ab4S_7zzR_V5NG:bwbmdun) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/uiComponents/LoadingOverlay.tsx#L62)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Well previously this was inlined within the component body. Seems silly that if you want to extract a piece of code out of the function body to make it more readable that you would have to hide the extracted section in another file.
</blockquote></details>

Yeah, maybe it is better with this kind of overlay components at least to have all the logic here next to the visuals :+1: 


<!-- Sent from Reviewable.io -->

2024-08-20 09:22 UTC, Huulivoide reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868)* status: 7 of 18 files reviewed, 2 unresolved discussions (waiting on @HenrikHartiala)

___
*[`cypress/pageObjects/Map.ts` line 20 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O4dQGww7DHR5ncTq_Ck:-O4j37yK0TtkOriO1WQL:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e28fd8d94c6743815acfec9c24c56e95f53859db/cypress/pageObjects/Map.ts#L20)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, yeah the debounce is not the issue. I think the 800ms debounce only affects how the UI state / urlQuery is updated but the map changes should be immediate.
I think that the issue is that the map zooms gradually and cypress sends another click before the earlier zoom is completely finished resulting that the last zoom starts at lets say 14.9xx and it adds 1 to that resulting that the final zoom level is 15.9xx instead of 16. (we start from zoom level 13 and 3 zooms should result in zoom level 16)

So I think it is okay to wait for 1000ms here (It should work with less wait time, but 1000ms ok to be sure). But I would at least adjust the comment (and commit message), because the issue is with the map, not with the debounce or cypress.
</blockquote></details>

Done.
___
*[`ui/src/components/map/Maplibre.tsx` line 67 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1ptYY2C_5Q4XY34RiD:-O4j38hzApiG8_cgj5lW:bn98ctt) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/components/map/Maplibre.tsx#L67)):*
<details><summary><i>Previously, HenrikHartiala wrote…</i></summary><blockquote>

Hmm, I'm not completely sure if I follow. I mean it's ok if this solution greatly reduces the amount of changes, but my point was more likely that the `immediatelyOn` naming already indicates towards boolean value (Is the loader going to be visible immediately: yes/no*), so for me it is minorly confusing that it can get enum values as well. 
Maybe it could be renamed to `initialValue` or more like `immediateState` or something (?). 

*or maybe I've misunderstood something from the original purpose :D 

Well.. I'll put this comment as non-blocking as this it not a big deal anyways, but if any of this makes sense then feel free to make changes.
</blockquote></details>

Final version named`initialState` and boolean support dropped, as there was only one place in the code that used the feature at all.


<!-- Sent from Reviewable.io -->

2024-08-21 08:47 UTC, HenrikHartiala approved these changes
> Reviewed 1 of 10 files at r15, 1 of 2 files at r16, 3 of 4 files at r17, 4 of 5 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Huulivoide)

___
*[`cypress/pageObjects/Map.ts` line 20 at r14](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O4dQGww7DHR5ncTq_Ck:-O4o58mc7CNVHxohfQ4B:bfnxrpj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/e28fd8d94c6743815acfec9c24c56e95f53859db/cypress/pageObjects/Map.ts#L20)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I didn't manage to get a complete ignore of a click, but not denying that it couldn't happen. So I think this is okay (and I'll also document this zoom thing in testing documentation). Thanks!
___
*[`ui/src/components/map/Maplibre.tsx` line 67 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/868#-O1ptYY2C_5Q4XY34RiD:-O4o69_F8EGGf_t_OVDu:b-wvx5j3) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/34a6e22b9657d92916bfa2c9b7b8bc0d2a2ff232/ui/src/components/map/Maplibre.tsx#L67)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Final version named`initialState` and boolean support dropped, as there was only one place in the code that used the feature at all.
</blockquote></details>

Thanks for the fix! I think it makes more sense this way :+1: 


<!-- Sent from Reviewable.io -->

2024-08-21 08:47 UTC, merged