DRAFT: Info spots edit view
HSLdevcom/jore4-ui pull request #930
Opened 2024-10-17 07:59 UTC by suvikankare

2024-10-30 10:27 UTC, Huulivoide requested changes
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930)* status: all files reviewed, 15 unresolved discussions (waiting on @suvikankare)

___
*[`ui/src/components/common/info-container/InfoContainer.tsx` line 68 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARgPZW226OLbwu6XZa:-OARgPZW226OLbwu6XZb:btmhnjn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/common/info-container/InfoContainer.tsx#L68)):*
> ```XML
>    */
>   readonly title: ReactNode;
>   readonly subTitle?: string;
> ```

Tää subTitle vielä vois ihan mennä,  mutta subTitleShelter type on jo liian spesifinen propsi tälle komponentille.

Ylipäätänsäkin sanosin, että rakennat vaan suoraan koko titlen tuolla kutsuvassa päässä:
```typescript
function InfoSpotTitle({ infoSpotCount, shelter, shelterIndex }) {
  return (
    <h4>
      <span>
        { infoSpotCount ? t('stopDetails.infoSpots.title') : t('stopDetails.infoSpots.titleNoInfoSpots') }
      </span>
      <span className="font-normal>
        { /* uus käännös stringi, tai sitten vaan palasista koosto täällä koodin puolella */ 
          t('stopDetails.infoSpots.shelterTypeSubtitle', {
             index: shelterIndex + 1,
             shelterType: mapStopRegistryShelterTypeEnumToUiName(shelter.shelterType ?? NullOptionEnum.Null)
          })
        }
      </span>
    <h4>
    );
}

// ... InfoSportSecion komponentti
return (
  <InfoContainer
     title={<InfoSpotTitle infospotCount=... />}

```
___
*[`ui/src/components/forms/common/InputField.tsx` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARjdlq8z3iMFZg5xkx:-OARjdlq8z3iMFZg5xky:bum4dnw) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/forms/common/InputField.tsx#L18)):*
> ```XML
>   fieldPath: Path<FormState>;
>   translationPrefix: TranslationKey;
>   customTitlePath?: string;
> ```

Tyypiks `TranslationKey` kuten translationPrefix:issäkin on
___
*[`ui/src/components/forms/common/InputLabel.tsx` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARjn-E7epjIB2jhUC2:-OARjn-E7epjIB2jhUC3:b9gqwem) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/forms/common/InputLabel.tsx#L11)):*
> ```XML
>   fieldPath: Path<FormState>;
>   translationPrefix: TranslationKey;
>   customTitlePath?: string;
> ```

Ja täällä sama
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 27 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARkWTi8oO0lZrqSUBw:-OARkWTi8oO0lZrqSUBx:bqoc9p5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L27)):*
> ```XML
> type Props = {
>   readonly stop: StopWithDetails;
>   readonly infoSpots: Array<InfoSpotDetailsFragment>;
> ```

Mielellään aina `ReadonlyArray`:nä kaikki data sisään kaikkialle. Ja samaten hook:eistä ois lähtökohtasesti aina hyvä palauttaa kaikki data immutablena. Datan mutatointi suoraan React kontekstissa kun on laitonta, niin saa minimoitua bugien syntymisen kun eksplisiittisti aina sanoo että ei saa muuttaa dataa. 
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARleYo7o3hRs4xCyzB:-OARleYo7o3hRs4xCyzC:b-gao2d0) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L34)):*
> ```XML
> function useInfoSpotFormDefaultValues(
>   infoSpots: ReadonlyArray<InfoSpotDetailsFragment>,
> ) {
> ```

Tää olis suotavaa wräpätät useMemo:oon, koska nyt nää default arvot "muuttuu" jok'ikisellä komponentin rendaus kerralla.

```typescript
return useMemo(() => {
  if (infoSpots.length) {
    return { infoSpots: infoSpots.map(mapInfoSpotDataToFormState) };
  }
 
  return { infospots: [mapInfoSpotDataToFormState({})];
}, [infoSpots]);
```
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 57 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARnNs02yuPAB_ZQNze:-OARnNs02yuPAB_ZQNzf:b-z1m2x7) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L57)):*
> ```XML
>     useEditStopInfoSpots();
> 
>   const [infoSpotCount, setInfoSpotCount] = useState(infoSpots.length);
> ```

Sen sijaan että ylläpidetään tämmöstä ""raskasta"" state muuttujaa, niin eikös tää menis myös (alempana koodissa)
```typescript
const infoSpotCount = infoSpots.lenght + (isInEditMode ? 1 : 0);
```
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 63 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARmku1EerU07-cBSoS:-OARmku1EerU07-cBSoT:b-h0cpqa) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L63)):*
> ```XML
>   const stopName = stop.label;
> 
>   const formRef = useRef<ExplicitAny>(null);
> ```

Any on lähtökohtasesti täysin kielletty tyyppi ku kirjotetaan Typescriptiä. Aiemmat debaajat vaan ei oo osanneet ts/react komboo kunnolla, eikä oo osanneet kirjottaa oikeita tyyppejä.

Tässä oikee tyyppi on `HTMLFormElement | null`
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARrx8MCRR5rdmUNVTd:-OARrx8MCRR5rdmUNVTe:b-2v7508) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx#L14)):*
> ```XML
> };
> 
> function useInfoSpots(stop: StopWithDetails): Array<InfoSpotDetailsFragment> {
> ```

Nää vois ihan vaan suoraan inlainata tonne varsinaiseen komponentitin, ku näissä ei oo mitään logiikkaa varsinaisesti.
Toiseks, jos hookki ei kutsu mitään toista hookkia, niin sitten se ei oo hookki, vaan sen pitäs olla ihan vaan tavallinen funktio,
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARsKx_8lOu-8w7uQKD:-OARonPN1VxbPT1_7yZR:b-qvko9b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx#L26)):*
> ```XML
> }
> 
> export const SheltersInfoSpotsSection: FC<Props> = ({ stop }) => {
> ```

Täällä vois myös harkita, että laskis noi shelter⋄infoSpot-listat vaan yhteen kertaan useMemo:n sisällä
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx` line 38 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARsUw73w7fQDLv1NdZ:-OARsUw73w7fQDLv1Nd_:b3hibsk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx#L38)):*
> ```XML
> 
>   return shelters.map((shelter, shelterIndex) => (
>     <React.Fragment key={shelter.id}>
> ```

Tarpeerton Fragment wräpperi
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsForm.tsx` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARsc4w9GQZ71CPsUro:-OARsc4w9GQZ71CPsUrp:bfka24d) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsForm.tsx#L23)):*
> ```XML
>  [...]

2024-10-31 12:42 UTC, Huulivoide requested changes
> Reviewed 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930)* status: 11 of 17 files reviewed, 6 unresolved discussions (waiting on @suvikankare)

___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARleYo7o3hRs4xCyzB:-OAXYbW_-PtZKqGoGnjw:b1pdi8a) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L34)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tää olis suotavaa wräpätät useMemo:oon, koska nyt nää default arvot "muuttuu" jok'ikisellä komponentin rendaus kerralla.

```typescript
return useMemo(() => {
  if (infoSpots.length) {
    return { infoSpots: infoSpots.map(mapInfoSpotDataToFormState) };
  }
 
  return { infospots: [mapInfoSpotDataToFormState({})];
}, [infoSpots]);
```
</blockquote></details>

Tänne on jäänyt näköjään vielä vanhatr koodit sekaan
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARsKx_8lOu-8w7uQKD:-OAXZBZ_7BxrwB1gqEoQ:b8tmhxk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx#L26)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Täällä vois myös harkita, että laskis noi shelter⋄infoSpot-listat vaan yhteen kertaan useMemo:n sisällä
</blockquote></details>

Compact kutsujen pitäs olla useMemon sisällä. Koska nyt toi kuitenkin lasketaan joka kerralla uudellen, koska infoSpots muuttuja on joka kerta uudelleen laskettu.

Myöskään, hookkia ei pitäs koskaan määritellä komponentin sisässä, eikä hookkeja saa muyskään kutsua loopissa.
https://react.dev/warnings/invalid-hook-call-warning

```typescript
type ShelterAndSpots = [ShelterEquipmentDetailsFragment, ReadonlyArray<InfoSpotDetailsFragment>];

const items: ReadonlyArray<ShelterAndSpots> = useMemo(() => {
  const infoSpots = compact(...)
  const shelters = compact(...)

  return shelters.map(shelter => {
    const shelterSpots = infoSpots.filter(belongsToShelter(shelter));
    return [shelter, shelterSpots]
  );
}, [stop]);

return items.map(([shelter, shelterInfoSpots]) => (<InfoSpotsSection ... />))
```
___
*[`ui/src/hooks/stop-registry/useEditStopInfoSpots.ts` line 87 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OAXa2jW-oDN4w1Iigld:-OAXa2jXDOaruyacPdUl:b-g7aiwc) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/60f2d38e6ebb03c7e8235e9c5499bd31ada5400b/ui/src/hooks/stop-registry/useEditStopInfoSpots.ts#L87)):*
> ```XML
>   };
> 
>   const saveStopPlaceInfoSpots = async ({
> ```

Tää kutsuu vaan tota yhtä funktiota `updateTiamatStopPlace` sen vois ehkä nimetä uudelleen `saveStopPlaceInfoSpots` funkkariks ja se vois suoraan ottaa ton staten parameterina.


<!-- Sent from Reviewable.io -->

2024-11-01 08:28 UTC, suvikankare reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930)* status: 10 of 17 files reviewed, 6 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/components/forms/common/InputField.tsx` line 18 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARjdlq8z3iMFZg5xkx:-OAX6igBAYzpswuRVpi0:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/forms/common/InputField.tsx#L18)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tyypiks `TranslationKey` kuten translationPrefix:issäkin on
</blockquote></details>

Done.
___
*[`ui/src/components/forms/common/InputLabel.tsx` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARjn-E7epjIB2jhUC2:-OAX6kte1kwxHF9GDGUI:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/forms/common/InputLabel.tsx#L11)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Ja täällä sama
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 27 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARkWTi8oO0lZrqSUBw:-OAX6njtAXVPFQlykEoi:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L27)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Mielellään aina `ReadonlyArray`:nä kaikki data sisään kaikkialle. Ja samaten hook:eistä ois lähtökohtasesti aina hyvä palauttaa kaikki data immutablena. Datan mutatointi suoraan React kontekstissa kun on laitonta, niin saa minimoitua bugien syntymisen kun eksplisiittisti aina sanoo että ei saa muuttaa dataa.
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARleYo7o3hRs4xCyzB:-OAX6oPsAcWEWfP358Fb:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L34)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tää olis suotavaa wräpätät useMemo:oon, koska nyt nää default arvot "muuttuu" jok'ikisellä komponentin rendaus kerralla.

```typescript
return useMemo(() => {
  if (infoSpots.length) {
    return { infoSpots: infoSpots.map(mapInfoSpotDataToFormState) };
  }
 
  return { infospots: [mapInfoSpotDataToFormState({})];
}, [infoSpots]);
```
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 57 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARnNs02yuPAB_ZQNze:-OAX6p1dDJs04z3wUkHE:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L57)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Sen sijaan että ylläpidetään tämmöstä ""raskasta"" state muuttujaa, niin eikös tää menis myös (alempana koodissa)
```typescript
const infoSpotCount = infoSpots.lenght + (isInEditMode ? 1 : 0);
```
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 63 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARmku1EerU07-cBSoS:-OAX6pcb5FrWlGFBS-yp:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L63)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Any on lähtökohtasesti täysin kielletty tyyppi ku kirjotetaan Typescriptiä. Aiemmat debaajat vaan ei oo osanneet ts/react komboo kunnolla, eikä oo osanneet kirjottaa oikeita tyyppejä.

Tässä oikee tyyppi on `HTMLFormElement | null`
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARrx8MCRR5rdmUNVTd:-OAX7y5ECGLwDVuqrA_N:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx#L14)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Nää vois ihan vaan suoraan inlainata tonne varsinaiseen komponentitin, ku näissä ei oo mitään logiikkaa varsinaisesti.
Toiseks, jos hookki ei kutsu mitään toista hookkia, niin sitten se ei oo hookki, vaan sen pitäs olla ihan vaan tavallinen funktio,
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARsKx_8lOu-8w7uQKD:-OAX6yfACyANEahgN-pd:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx#L26)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Täällä vois myös harkita, että laskis noi shelter⋄infoSpot-listat vaan yhteen kertaan useMemo:n sisällä
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx` line 38 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARsUw73w7fQDLv1NdZ:-OAX6zcR33_VHRo9nvvf:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/SheltersInfoSpots.tsx#L38)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tarpeerton Fragment wräpperi
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsForm.tsx` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARsc4w9GQZ71CPsUro:-OAX7Cui4_CUfOxWFkP-:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsForm.tsx#L23)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

```typescript
const InfoSpotsFormComponent: ForwardRefRenderFunction<HTMLFormComponent, Props> = ({
   classname,
   ...
}, ref) {
  const methods ....
```
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsForm.tsx` line 42 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARt7FPDsWyl_SEPs_P:-OAX7DDCCU2tXG-tS1kn:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/info-spots-form/InfoSpotsForm.tsx#L42)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

`twMerge(`space-y-4`, className)` ja className:sta voi pudottaa tuolta ylempää `= ''` osuuden pois.
</blockquote></details>

Done.
___
*[`ui/src/hooks/stop-registry/useEditStopInfoSpots.ts` line 66 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARvoGlAuFVeLBFM7KD:-OAX7H6V-nmPca3rdt56:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/hooks/stop-registry/useEditStopInfoSpots.ts#L66)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><b [...]

2024-11-01 09:14 UTC, Huulivoide requested changes
> Reviewed 4 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @suvikankare)

___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARleYo7o3hRs4xCyzB:-OAayqztEpQ4QCcC04fw:b-iirg65) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L34)):*
<details><summary><i>Previously, suvikankare wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Edelleen on 
```typescript
  const infoSpotFormDefaultValues = {
    infoSpots: infoSpots.map(mapInfoSpotDataToFormState),
  };

  if (!infoSpotFormDefaultValues.infoSpots.length) {
    infoSpotFormDefaultValues.infoSpots = [mapInfoSpotDataToFormState({})];
  }
```
tarpeettomana vanhasta koodista
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 54 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OAazIJ_0-0OLK5uT5gI:-OAazIJ_0-0OLK5uT5gJ:b-8cuhs8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6573c2cb2100dc5a721b18456d2856ad4c2d46e7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L54)):*
> ```XML
> 
> const InfoSpotTitle: FC<{
>   infoSpotCount: number;
> ```

readonly:t propseihin
___
*[`ui/src/i18n/uiNameMappings.ts` line 155 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARwGPn1_O7aULGBkQv:-OAazunsDL5kXWzMpsxt:b-qawemj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/i18n/uiNameMappings.ts#L155)):*
<details><summary><i>Previously, suvikankare wrote…</i></summary><blockquote>

Oisko tästä fiksumpi tehä kokonaan oma refaktorointitiketti, koska noita i18n käyttäviä on tuolla monta (joista itsekin sokeasti copypastesin) ja ehkä ne ois hyvä olla yhteneväiset?
</blockquote></details>

Vois oikeestaan tehdä joo


<!-- Sent from Reviewable.io -->

2024-11-01 10:49 UTC, suvikankare reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930)* status: 15 of 17 files reviewed, 3 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARleYo7o3hRs4xCyzB:-OAbL-Gm8v7vT7CJFjRv:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L34)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Edelleen on 
```typescript
  const infoSpotFormDefaultValues = {
    infoSpots: infoSpots.map(mapInfoSpotDataToFormState),
  };

  if (!infoSpotFormDefaultValues.infoSpots.length) {
    infoSpotFormDefaultValues.infoSpots = [mapInfoSpotDataToFormState({})];
  }
```
tarpeettomana vanhasta koodista
</blockquote></details>

Done.
___
*[`ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx` line 54 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OAazIJ_0-0OLK5uT5gI:-OAbL-et8vFpZPDaskBv:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/6573c2cb2100dc5a721b18456d2856ad4c2d46e7/ui/src/components/stop-registry/stops/stop-details/info-spots/InfoSpotsSection.tsx#L54)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

readonly:t propseihin
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-01 10:56 UTC, Huulivoide approved these changes
> Reviewed 1 of 6 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930)* status: all files reviewed, 1 unresolved discussion (waiting on @suvikankare)

___
*[`ui/src/hooks/stop-registry/useEditStopInfoSpots.ts` line 30 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OARw20o3g25xA-mLk5_:-OAbMOKPCtNrjr2oIUGB:b1iqydz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a8bd113b1945d72f86c145104e6d8fd910f2b5d7/ui/src/hooks/stop-registry/useEditStopInfoSpots.ts#L30)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tänne vois tyypitää funktion paluuarvon `StopRegistryInfoSpotInput`
</blockquote></details>

Tää täällä oli vielä teknisesti. Mutta voi mun puolesta jo painaa merge nappulaa


<!-- Sent from Reviewable.io -->

2024-11-01 11:07 UTC, Huulivoide commented
Paitsi että testit vielä vaatinee päivitystä. Menee vissiin nyt erijärjestykseen noi infopaikat taas.

2024-11-01 12:25 UTC, Huulivoide requested changes
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930)* status: all files reviewed, 2 unresolved discussions (waiting on @suvikankare)

___
*[`ui/src/locales/en-US/common.json` line 358 at r7](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-OAbfhbzAaMqR1D6IZ6U:-OAbfhbzAaMqR1D6IZ6V:b-338jsn) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/a11ea05d8ccfd11f3675d91eaa4dfb2597c079ad/ui/src/locales/en-US/common.json#L358)):*
> ```JSON
>       "displayTypes": {
>         "electricTft": "Electric TFT",
>         "electricTFT": "Electric TFT",
> ```

Auts, nyt on tupla käännös
`electricTft` ja
`electricTfT`


<!-- Sent from Reviewable.io -->

2024-11-01 13:49 UTC, Huulivoide approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/930#-:-OAbz5XbCu2c9M5Kejrf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @suvikankare)



<!-- Sent from Reviewable.io -->

2024-11-01 14:00 UTC, merged