Draft: 43662 - Added error handling hook to StopAreaDetailsEdit
HSLdevcom/jore4-ui pull request #931
Opened 2024-10-17 11:26 UTC by villepynttari

Testing:

- Go to: //stop-registry/stop-areas/HSL:GroupOfStopPlaces:2?observationDate=2024-10-16
- Change label and name values to existing values ( for example these - Go to: //stop-registry/stop-areas/HSL:GroupOfStopPlaces:1?observationDate=2024-10-16)
- Should print errors with correct texts

2024-10-17 12:39 UTC, Huulivoide requested changes
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @villepynttari)

___
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PNbmADuPG6HA-iz0m:-O9PNbmB555Y8S-SS5Tt:b3xs8te) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts#L7)):*
> ```XML
> import { StopAreaFormState } from '../stopAreaFormSchema';
> 
> const ERRORS: Readonly<Map<string, string>> = new Map([
> ```

Map luokan sijaan vois käyttää ihan vaan objektia. Ja en oo nyt vielä koko tietostoa lukenut, mutta oletan että tässä on Virhekoodi⋄käännösavain mäppäys → Käännös avain pitäs tyypittää oleen semmonen.
tyyppi `TranslationKey` ui/src/i18n.ts tiedostosta 
___
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts` line 24 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PSG1r7FopjrgManal:-O9PSG1r7FopjrgManam:b-4e3jlf) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts#L24)):*
> ```XML
>   const tryHandle = useCallback(
>     (error: ApolloError, details?: StopAreaFormState): boolean => {
>       const errorNames = Array.from(ERRORS.keys());
> ```

Tässä on mun mielestä tarpeettomasti looppausta, kun tän sais tehtyy myös toisinkin päin. Et etitään virheen potentiaalistta errorCodea tunnettujen listasta, sen sijaan että katotaan onko virheessä yhtään tunnettia koodia asetettuna.
___
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts` line 33 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PSbfPAAgKlVQ2VoxJ:-O9PSbfPAAgKlVQ2VoxK:buitl0m) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts#L33)):*
> ```XML
>         const knownErrorKey = ERRORS.get(knownError);
>         if (knownErrorKey) {
>           if (details) {
> ```

Tää on tarpeeton. Koska toi on TFunktiolla optionaalinen argumentti, niin siellä on jo sisällä käsittely tilanteellee että toka argumentti on undefined.
___
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts` line 45 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PSs3wE0UMyhKF6xDx:-O9PSs3wE0UMyhKF6xDy:b-1xry6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts#L45)):*
> ```XML
>     [t],
>   );
>   return { tryHandle };
> ```

Tarpeeton objekti wräppäys. Suoraan vaan funktio ulos.
___
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts` line 46 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PSxLaDqzedi_4ax0M:-O9PSxLaDqzedi_4ax0N:b7n7up5) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts#L46)):*
> ```XML
>   );
>   return { tryHandle };
> }
> ```

Ite sain muodon:
```typescript
import { ApolloError } from '@apollo/client';
import get from 'lodash/get';
import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { TranslationKey } from '../../../../i18n';
import { showDangerToast } from '../../../../utils';
import { StopAreaFormState } from '../stopAreaFormSchema';

const ERRORS: Readonly<Record<string, TranslationKey>> = {
  GROUP_OF_STOP_PLACES_UNIQUE_NAME:
    'stopAreaDetails.errors.groupOfStopPlacesUniqueName',

  GROUP_OF_STOP_PLACES_UNIQUE_DESCRIPTION:
    'stopAreaDetails.errors.groupOfStopPlacesUniqueDescription',
};

function mapApolloErrorToTranslationKey(
  error: ApolloError,
): TranslationKey | null {
  const errorCode: unknown = get(error, ['cause', 'extensions', 'errorCode']);
  if (typeof errorCode === 'string' && errorCode in ERRORS) {
    return ERRORS[errorCode];
  }

  return null;
}

export function useStopAreaDetailsApolloErrorHandler() {
  const { t } = useTranslation();

  return useCallback(
    (error: ApolloError, details?: StopAreaFormState): boolean => {
      const translationKey = mapApolloErrorToTranslationKey(error);

      if (translationKey) {
        showDangerToast(t(translationKey, details));
        return true;
      }

      return false;
    },
    [t],
  );
}
```
___
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.spec.ts` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PTmQs20n4rSr90b6K:-O9PTmQs20n4rSr90b6L:b-pa0n8j) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.spec.ts#L1)):*
> ```XML
> import { ApolloError } from '@apollo/client';
> ```

Tälle pitäs olla olemassa oikee E2E testi, ja sen jälkeen tää yksikkö testi jää tarpeettomaks.
Koska Tiamatin pään muutoksetkin voi tän toiminnalisuuden rikkoa, ku sieltä ne virheet loppupeleissä tulee.


<!-- Sent from Reviewable.io -->

2024-10-18 04:12 UTC, villepynttari commented
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts` line 46 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PSxLaDqzedi_4ax0M:-O9SnC855HA_V0zkOrNE:b4q9dxj) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts#L46)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Ite sain muodon:
```typescript
import { ApolloError } from '@apollo/client';
import get from 'lodash/get';
import { useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import { TranslationKey } from '../../../../i18n';
import { showDangerToast } from '../../../../utils';
import { StopAreaFormState } from '../stopAreaFormSchema';

const ERRORS: Readonly<Record<string, TranslationKey>> = {
  GROUP_OF_STOP_PLACES_UNIQUE_NAME:
    'stopAreaDetails.errors.groupOfStopPlacesUniqueName',

  GROUP_OF_STOP_PLACES_UNIQUE_DESCRIPTION:
    'stopAreaDetails.errors.groupOfStopPlacesUniqueDescription',
};

function mapApolloErrorToTranslationKey(
  error: ApolloError,
): TranslationKey | null {
  const errorCode: unknown = get(error, ['cause', 'extensions', 'errorCode']);
  if (typeof errorCode === 'string' && errorCode in ERRORS) {
    return ERRORS[errorCode];
  }

  return null;
}

export function useStopAreaDetailsApolloErrorHandler() {
  const { t } = useTranslation();

  return useCallback(
    (error: ApolloError, details?: StopAreaFormState): boolean => {
      const translationKey = mapApolloErrorToTranslationKey(error);

      if (translationKey) {
        showDangerToast(t(translationKey, details));
        return true;
      }

      return false;
    },
    [t],
  );
}
```
</blockquote></details>

Tää varmaan looppaa enemmän pellin alla. Mapin muunto objektiksi ja listoiksi on erittäin tehokasta, mutta eipä tän kokoisessa datamäärässä ole käytännössä mitään väliä. Tämä tekee riippuvuuden lodashiin. Onhan tämä siistimmän näköinen, niin mennään tällä.


<!-- Sent from Reviewable.io -->

2024-10-18 04:19 UTC, villepynttari commented
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.spec.ts` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PTmQs20n4rSr90b6K:-O9Sp-f1CV2DwswxrYJB:b-cbrq6s) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.spec.ts#L1)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tälle pitäs olla olemassa oikee E2E testi, ja sen jälkeen tää yksikkö testi jää tarpeettomaks.
Koska Tiamatin pään muutoksetkin voi tän toiminnalisuuden rikkoa, ku sieltä ne virheet loppupeleissä tulee.
</blockquote></details>

Yksikkötestit ei ole koskaan tarpeettomia monestakin syystä, vaikka olisikin integraatiotestejä. Lisään vielä sen e2e testin.


<!-- Sent from Reviewable.io -->

2024-10-28 06:40 UTC, villepynttari reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts` line 7 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PNbmADuPG6HA-iz0m:-OAGoZpqEZrxhwuRpskF:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts#L7)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Map luokan sijaan vois käyttää ihan vaan objektia. Ja en oo nyt vielä koko tietostoa lukenut, mutta oletan että tässä on Virhekoodi⋄käännösavain mäppäys → Käännös avain pitäs tyypittää oleen semmonen.
tyyppi `TranslationKey` ui/src/i18n.ts tiedostosta
</blockquote></details>

Done.
___
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts` line 24 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PSG1r7FopjrgManal:-OAGo_ATBwbaLHrxy020:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts#L24)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tässä on mun mielestä tarpeettomasti looppausta, kun tän sais tehtyy myös toisinkin päin. Et etitään virheen potentiaalistta errorCodea tunnettujen listasta, sen sijaan että katotaan onko virheessä yhtään tunnettia koodia asetettuna.
</blockquote></details>

Done.
___
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts` line 33 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PSbfPAAgKlVQ2VoxJ:-OAGqPOGEWdvFK1b0m6l:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts#L33)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tää on tarpeeton. Koska toi on TFunktiolla optionaalinen argumentti, niin siellä on jo sisällä käsittely tilanteellee että toka argumentti on undefined.
</blockquote></details>

Done.
___
*[`ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts` line 45 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-O9PSs3wE0UMyhKF6xDx:-OAGplqD7QCQIZq8cMTa:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/28925becae8f9310100124b691a00c0632e2b3fe/ui/src/components/forms/stop-area/util/stopAreaDetailsErrorHandler.ts#L45)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tarpeeton objekti wräppäys. Suoraan vaan funktio ulos.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-28 09:16 UTC, Huulivoide requested changes
> Reviewed 1 of 7 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931)* status: all files reviewed, 2 unresolved discussions (waiting on @villepynttari)

___
*[`cypress/e2e/stop-registry/stopAreaDetails.cy.ts` line 365 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-OAHOnnP5CXAQmWB0NFF:-OAHOnnP5CXAQmWB0NFG:b-mz7sqh) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/91348f23159e39a8b2be6d2c1dc41e9338bd7866/cypress/e2e/stop-registry/stopAreaDetails.cy.ts#L365)):*
> ```XML
>     it('should handle unique name exception', () => {
>       const existingLabel =
>         stopAreaData?.at(1)?.stopArea?.name?.value ?? 'noop';
> ```

Sen sijaan, että luottaa puhtaasti tohon testidatan insertointi järjestykseen, niin oisko parempi etsiä haluttu testientiteetti mielumiin, jonko ID:n perusteella. name/description kentät.
___
*[`cypress/e2e/stop-registry/stopAreaDetails.cy.ts` line 375 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-OAHLAJy9aQg9m393Tpd:-OAHLAJy9aQg9m393Tpe:b-plkzdx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/91348f23159e39a8b2be6d2c1dc41e9338bd7866/cypress/e2e/stop-registry/stopAreaDetails.cy.ts#L375)):*
> ```XML
>       inputBasicDetails(newBasicDetails);
>       stopAreaDetailsPage.details.edit.getSaveButton().click();
>       toast.checkDangerToastHasMessage(
> ```

Jokin aika sitten tein success tilanteeseen vähän tarkemman chekin näille paahtoleiville.
toast, `toast.expectSuccessToast("viesti")`.

checkDangerToastHasMessage implementaatio, ja sen muut vastineet on siitä mielestä huonoja, että ne jää pollaamaan DOM:ia ja odottaa timeouttia, kunne ne löytää sieltä "toastin, joka on tyyppiä ja sisältää viestin".

 `expectSuccessToast` taas alkaa pollaan DOM:sta `Ensimmäinen toast, joka tulee näkyviin` ` .then()` assertoi että se on tyyppiä `success` ja sitten vielä lopuksi, tarkasta että siinä on annettu viesti sisältönä.

Lyhyesti ongelma vanhassa:
Jos odotetaan onnistumista, mutta tuleekin virhe, tai jos odotetaan virhettä, ja tuleekin onnistuminen, niin: esiin tullut notifikaatio ehtii kadota ruudulta pois, kun testi koodi vielä pollaa kaikkiin hakuehtoihin sopivaa DOM elementtiä. Ja semmosta kun ei lopula löydy, niin Cypress ottaa ruutukaappauksen sivusta, jolla ei ole enää yhtään toastia näkyvissä → Kuvasta ei käy ilmi, miksi testiajo epäonnistui.

Eli: error versio `expectSuccessToast`:sta


<!-- Sent from Reviewable.io -->

2024-11-02 04:55 UTC, villepynttari reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @Huulivoide)

___
*[`cypress/e2e/stop-registry/stopAreaDetails.cy.ts` line 375 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931#-OAHLAJy9aQg9m393Tpd:-OAfDRH146yZHWIwe19R:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/91348f23159e39a8b2be6d2c1dc41e9338bd7866/cypress/e2e/stop-registry/stopAreaDetails.cy.ts#L375)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Jokin aika sitten tein success tilanteeseen vähän tarkemman chekin näille paahtoleiville.
toast, `toast.expectSuccessToast("viesti")`.

checkDangerToastHasMessage implementaatio, ja sen muut vastineet on siitä mielestä huonoja, että ne jää pollaamaan DOM:ia ja odottaa timeouttia, kunne ne löytää sieltä "toastin, joka on tyyppiä ja sisältää viestin".

 `expectSuccessToast` taas alkaa pollaan DOM:sta `Ensimmäinen toast, joka tulee näkyviin` ` .then()` assertoi että se on tyyppiä `success` ja sitten vielä lopuksi, tarkasta että siinä on annettu viesti sisältönä.

Lyhyesti ongelma vanhassa:
Jos odotetaan onnistumista, mutta tuleekin virhe, tai jos odotetaan virhettä, ja tuleekin onnistuminen, niin: esiin tullut notifikaatio ehtii kadota ruudulta pois, kun testi koodi vielä pollaa kaikkiin hakuehtoihin sopivaa DOM elementtiä. Ja semmosta kun ei lopula löydy, niin Cypress ottaa ruutukaappauksen sivusta, jolla ei ole enää yhtään toastia näkyvissä → Kuvasta ei käy ilmi, miksi testiajo epäonnistui.

Eli: error versio `expectSuccessToast`:sta
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-04 08:45 UTC, Huulivoide approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/931)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @villepynttari)



<!-- Sent from Reviewable.io -->

2024-11-06 08:43 UTC, merged