35325 - Line details observation date outside its validity period box
HSLdevcom/jore4-ui pull request #940
Opened 2024-11-07 13:24 UTC by villepynttari

Added box to line details to show information when observation date is outside its validity period.

Testing:

1. Go to Routes and lines (/routes)
2. Click line
3. Select line
4. Set observation date what is outside line's validity period
5. Should show info box with alert

2024-11-08 10:21 UTC, Huulivoide requested changes
Tuleekos nyt aina päivämäärävalitus ihan mistä tahansa syystä, jos linjaa ei vaan löydy.

Löysin tolta tietosivulta myös bugin, jota vois tutkia tarkemmin ja kirjata Azureen:
Jos yrittää avata linjan tietosivua ja asettaa URLiin muodollisesti validin UUID:n id:ks, mutta jonka mukasta linjaa ei oikeasti kannassa ole ja avaa tietosivun, niin se avaa linjan 201 tiedot. Esim linkki: http://localhost:3300/lines/00000000-0000-0000-0000-000000000000  

> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-:-OBACBLh1PAEMdjmOK5I:b4e6yqv)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @villepynttari)

___
*[`ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx` line 100 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OBAHc5jC3vHjs92RikR:-OBAHc5jC3vHjs92RikS:b-14gnil) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/162d86d96439a45ee54d2359523b1ea0102933ec/ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx#L100)):*
> ```XML
>           </>
>         ) : (
>           <LineNotValidForDayBox />
> ```

Figmassa on kartta placeholder tän laatikon vieressä.
___
*[`ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OBAFCOaDZmyYK_R273J:-OBAFCOaDZmyYK_R273K:bwux6z8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/162d86d96439a45ee54d2359523b1ea0102933ec/ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx#L10)):*
> ```XML
>   const { t } = useTranslation();
>   const { colors } = theme;
>   const grayBackground = `bg-[${colors.background.grey}]`;
> ```

Meillä in pieni epäsynkka teema tiedoston ja varsinaisen Tailwind confin välillä.
Teema tiedoston background/gray on Tailwindisssa background/DEFAULT, joka kääntyy Tailwind luokaks `bg-background`
___
*[`ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OBAFXk-Etu1CinaQTfA:-OBAFXk-Etu1CinaQTfB:butugrk) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/162d86d96439a45ee54d2359523b1ea0102933ec/ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx#L11)):*
> ```XML
>   const { colors } = theme;
>   const grayBackground = `bg-[${colors.background.grey}]`;
>   const redText = `text-[${colors.hslRed}]`;
> ```

Tän pitäs olla ihan vaan `text-hsl-red`
___
*[`ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OBAFZcT0nOcwABjxEbj:-OBAFZcU0dkHmZqz6wt_:beuty3g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/162d86d96439a45ee54d2359523b1ea0102933ec/ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx#L14)):*
> ```XML
>   return (
>     <div
>       className={`justify-center] flex h-[309px] w-[928px] items-center justify-center ${grayBackground}`}
> ```

Ei käytetä suoraan pikseli kokoja mielellään. Tähän löytyy varmasti joku parempi koko. Leveyden pitäs varmaan olla `w-full` ja sitten korkeamalla tasolla pitäs olla joku leveys määritettynä tyyliin `w-2/3` ylemälle kontainerille. Tai sit jos siellä ei semmosta ole, niin tän pitäs ottaa sisään className ja sieltä ylemmältä tasolta pässätä tänne toi `w-2/3`.

Ja korkeudeks vois laittaa jonkin `h-numero` luokan `h-72` tai  `h-80` esim. https://tailwindcss.com/docs/height

Sit tässä pitäs olla vielä border ja kulmien pitäs olla pyöristettyjä


<!-- Sent from Reviewable.io -->

2024-11-13 07:25 UTC, villepynttari commented
Lisätty oletusvirhe





<!-- Sent from Reviewable.io -->

2024-11-13 07:26 UTC, villepynttari commented
*[`ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx` line 14 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OBAFZcT0nOcwABjxEbj:-OBZPWDg08ZMUKwFbcU3:b-r7i159) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/162d86d96439a45ee54d2359523b1ea0102933ec/ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx#L14)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Ei käytetä suoraan pikseli kokoja mielellään. Tähän löytyy varmasti joku parempi koko. Leveyden pitäs varmaan olla `w-full` ja sitten korkeamalla tasolla pitäs olla joku leveys määritettynä tyyliin `w-2/3` ylemälle kontainerille. Tai sit jos siellä ei semmosta ole, niin tän pitäs ottaa sisään className ja sieltä ylemmältä tasolta pässätä tänne toi `w-2/3`.

Ja korkeudeks vois laittaa jonkin `h-numero` luokan `h-72` tai  `h-80` esim. https://tailwindcss.com/docs/height

Sit tässä pitäs olla vielä border ja kulmien pitäs olla pyöristettyjä
</blockquote></details>

Kulmien pyöristystä en löytänyt figmasta, mutta muuten aseteltu uusiksi


<!-- Sent from Reviewable.io -->

2024-11-13 07:27 UTC, villepynttari reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940)* status: 0 of 20 files reviewed, 4 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx` line 100 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OBAHc5jC3vHjs92RikR:-OBZP8j5-PurxV2PZeGS:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/162d86d96439a45ee54d2359523b1ea0102933ec/ui/src/components/routes-and-lines/line-details/LineDetailsPage.tsx#L100)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Figmassa on kartta placeholder tän laatikon vieressä.
</blockquote></details>

Done.
___
*[`ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OBAFCOaDZmyYK_R273J:-OBZPSoDDMcPmiVGu76D:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/162d86d96439a45ee54d2359523b1ea0102933ec/ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx#L10)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Meillä in pieni epäsynkka teema tiedoston ja varsinaisen Tailwind confin välillä.
Teema tiedoston background/gray on Tailwindisssa background/DEFAULT, joka kääntyy Tailwind luokaks `bg-background`
</blockquote></details>

Done.
___
*[`ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx` line 11 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OBAFXk-Etu1CinaQTfA:-OBZPTVn5L_hXX_mqbDH:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/162d86d96439a45ee54d2359523b1ea0102933ec/ui/src/components/routes-and-lines/line-details/LineNotValidForDayBox.tsx#L11)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tän pitäs olla ihan vaan `text-hsl-red`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-13 08:43 UTC, Huulivoide commented
![image](https://github.com/user-attachments/assets/c343aa9d-35c4-44c9-8016-0bd2a066ef84)

2024-11-13 10:29 UTC, Huulivoide requested changes
> Reviewed 20 of 20 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940)* status: all files reviewed, 4 unresolved discussions (waiting on @villepynttari)

___
*[`ui/src/hooks/line-details/useGetLineDetails.ts` line 167 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OB_2jTw9idL5hlthLNn:-OB_2jTw9idL5hlthLNo:b-oykzm1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f49f87a6dc85dc252d85230ad8e0e9c5f62f8148/ui/src/hooks/line-details/useGetLineDetails.ts#L167)):*
> ```XML
> 
> export enum LineFetchError {
>   'LINE_MISSING_DEFAULT' = 'lines.lineMissingDefault',
> ```

Mielipide kysymys, mutta itte en tykkää että koodissa on "tyypittämättömiä" / "piilotettuja" käännös stringejä. Tästä ei käy mitenkään ilmi että nää on käännös stringejä, ja käännöstiedoston kautta jos lähtee kattoo, niin kyseisiä käännökisä ei oo oikeesti käytetty missään.
___
*[`ui/src/components/routes-and-lines/line-details/LineMissingBox.tsx` line 9 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OB_2-af11M8YfiOSyY8:-OB_2-af11M8YfiOSyY9:bfb76bp) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f49f87a6dc85dc252d85230ad8e0e9c5f62f8148/ui/src/components/routes-and-lines/line-details/LineMissingBox.tsx#L9)):*
> ```XML
> };
> const { colors } = theme;
> const grayBackground = `bg-background`;
> ```

Nää vois ihan vaan inlainata suoraan tonne käyttöpaikkoihin.
___
*[`ui/src/components/routes-and-lines/line-details/LineMissingBox.tsx` line 11 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OB_2SGe4SLOoSOLgX6x:-OB_2SGe4SLOoSOLgX6y:bsownla) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f49f87a6dc85dc252d85230ad8e0e9c5f62f8148/ui/src/components/routes-and-lines/line-details/LineMissingBox.tsx#L11)):*
> ```XML
> const grayBackground = `bg-background`;
> const redText = `text-hsl-red`;
> const border = `border border-${colors.lightGrey}`;
> ```

`border-light-grey` ei tarvi hakee käsin teemasta väriä


<!-- Sent from Reviewable.io -->

2024-11-18 08:37 UTC, villepynttari commented
*[`ui/src/hooks/line-details/useGetLineDetails.ts` line 167 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OB_2jTw9idL5hlthLNn:-OByOyz_9qOYIO0nOhSu:boike5n) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/f49f87a6dc85dc252d85230ad8e0e9c5f62f8148/ui/src/hooks/line-details/useGetLineDetails.ts#L167)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Mielipide kysymys, mutta itte en tykkää että koodissa on "tyypittämättömiä" / "piilotettuja" käännös stringejä. Tästä ei käy mitenkään ilmi että nää on käännös stringejä, ja käännöstiedoston kautta jos lähtee kattoo, niin kyseisiä käännökisä ei oo oikeesti käytetty missään.
</blockquote></details>

Mulla ei tommosta plugaria ole, niin oon ettinyt ihan findillä. Voishan sitä tietysti tehdä jonkun geneerisen virheilmoitusenumin, mutta nyt siirretty käännösten päättely komponentin yhteyteen.


<!-- Sent from Reviewable.io -->

2024-11-18 09:08 UTC, Huulivoide requested changes
> Reviewed 6 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940)* status: 18 of 20 files reviewed, 4 unresolved discussions (waiting on @villepynttari)

___
*[`ui/src/components/routes-and-lines/line-details/LineDetailsEmptyMapPlaceholder.tsx` line 8 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OByWCSm325z5Dg7lmn3:-OByWCSm325z5Dg7lmn4:bz6su3x) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1514c5b819a3a2253bf1757b16ff5d35957f7051/ui/src/components/routes-and-lines/line-details/LineDetailsEmptyMapPlaceholder.tsx#L8)):*
> ```XML
> const { colors } = theme;
> 
> const border = `border border-${colors.lightGrey}`;
> ```

Täällä kanssa vaan `border-light-grey`
___
*[`ui/src/components/routes-and-lines/line-details/LineDetailsEmptyMapPlaceholder.tsx` line 18 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OByW6Ob1xMxPExGiBDd:-OByW6Ob1xMxPExGiBDe:bujrhnx) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1514c5b819a3a2253bf1757b16ff5d35957f7051/ui/src/components/routes-and-lines/line-details/LineDetailsEmptyMapPlaceholder.tsx#L18)):*
> ```XML
>     <div
>       data-testid={testIds.mapPlaceholder}
>       className={`justify-center] flex h-72 w-full flex-shrink-0 items-center justify-center ${border}`}
> ```

Tuolla on tommonen `]` merkki tuolla justify-center:in perässä
___
*[`ui/src/components/routes-and-lines/line-details/LineMissingBox.tsx` line 24 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OByWVpv7ehm1lfzrh9_:-OByWVpw0RblgxZDYgTZ:bycu2bz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1514c5b819a3a2253bf1757b16ff5d35957f7051/ui/src/components/routes-and-lines/line-details/LineMissingBox.tsx#L24)):*
> ```XML
> export const LineMissingBox = (props?: { error?: LineFetchError }) => {
>   return (
>     <div className="justify-center] flex h-72 w-full flex-shrink-0 items-center justify-center border-light-grey bg-background">
> ```

Täällä kanssa ylimääränen `]` justify-centerin perässä


<!-- Sent from Reviewable.io -->

2024-11-18 12:10 UTC, villepynttari reviewed
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940)* status: 14 of 20 files reviewed, 4 unresolved discussions (waiting on @Huulivoide)

___
*[`ui/src/components/routes-and-lines/line-details/LineDetailsEmptyMapPlaceholder.tsx` line 8 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OByWCSm325z5Dg7lmn3:-OBzAHNP3UdN1t_5OtLA:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1514c5b819a3a2253bf1757b16ff5d35957f7051/ui/src/components/routes-and-lines/line-details/LineDetailsEmptyMapPlaceholder.tsx#L8)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Täällä kanssa vaan `border-light-grey`
</blockquote></details>

Done.
___
*[`ui/src/components/routes-and-lines/line-details/LineDetailsEmptyMapPlaceholder.tsx` line 18 at r4](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940#-OByW6Ob1xMxPExGiBDd:-OBzAH8vAKdVHFId7ixp:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1514c5b819a3a2253bf1757b16ff5d35957f7051/ui/src/components/routes-and-lines/line-details/LineDetailsEmptyMapPlaceholder.tsx#L18)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tuolla on tommonen `]` merkki tuolla justify-center:in perässä
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-18 12:22 UTC, Huulivoide approved these changes
> Reviewed 2 of 8 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/940)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @villepynttari)



<!-- Sent from Reviewable.io -->

2024-11-18 13:20 UTC, merged