Draft: Create stop version init
HSLdevcom/jore4-ui pull request #960
Opened 2024-12-05 14:40 UTC by villepynttari

Initial version of copying stop to new version.

2024-12-10 10:21 UTC, Huulivoide requested changes
> Reviewed 10 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960)* status: 10 of 14 files reviewed, 26 unresolved discussions (waiting on @villepynttari)

___
*[`ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx` line 49 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODjzVxK0OpXipq8FWnw:-ODjzVxL96GdHUp0tNoW:bjk328) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/StopDetailsPage.tsx#L49)):*
> ```XML
>   const { label } = useRequiredParams<{ label: string }>();
> 
>   // TODO: Use appDispatch or simple useState?
> ```

Korvää koko tää redux hässäkkä vaan `const [isCreateVersionModalOpen, setCreateVersionModalOpen] = useState(false)` Ku siellä on vaan yks ainut muuttuja.
___
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx` line 26 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODjzyUd3yqMPv21bmMp:-ODjzyUd3yqMPv21bmMq:bswunv6) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx#L26)):*
> ```XML
> };
> 
> interface Props {
> ```

type ja reaonly
___
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx` line 33 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk-0HwDloo6lROjxNg:-ODk-0HwDloo6lROjxNh:b6svbwi) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx#L33)):*
> ```XML
> }
> 
> export const CreateStopVersionForm = ({
> ```

`Komponentti: FC<PropsiTyyppi> = ({ ... }) => {`
___
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx` line 41 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk-BAOAfozlZcZJEzq:-ODk-BAOAfozlZcZJEzr:b-fwtop) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx#L41)):*
> ```XML
>   const { t } = useTranslation();
> 
>   const formRef = useRef<ExplicitAny>(null);
> ```

Käytetään oikeita tyyppejä Any:n sijaan.
___
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx` line 54 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk-m3KAbSqzpbjY2bk:-ODk-m3KAbSqzpbjY2bl:bsw7w9r) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx#L54)):*
> ```XML
>         onSubmit={handleSubmit(onFormSubmit)}
>         ref={formRef}
>         className={`space-y-4 ${className}`}
> ```

`twMerge('space-y-4', className)`
___
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx` line 75 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk-ziZAPMbMgrUdMhQ:-ODk-ziZAPMbMgrUdMhR:b-qm98hv) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx#L75)):*
> ```XML
>           <PriorityForm />
>         </FormRow>
>         <FormRow mdColumns={2}>
> ```

Eiks tälle oo olemassa jo jotain `<PriorityForm />`:ia vastaavaa toteutusta? :thinking: 
___
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx` line 98 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk07XtEqn8TomNjruc:-ODk07XtEqn8TomNjrud:b-h5plsr) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/CreateStopVersionForm.tsx#L98)):*
> ```XML
>             {t('cancel')}
>           </SimpleButton>
>           <SimpleButton onClick={onSaved} testId={testIds.submitButton}>
> ```

onClick:in sijaan pitäs olla `type="submit"` ja antaa formin itse hoitaa submit eventti.
___
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/createStopVersionCommon.ts` line 1 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk1E1XBj534fAFATx6:-ODk1E1XBj534fAFATx7:bl0882q) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/createStopVersionCommon.ts#L1)):*
> ```XML
> import { gql } from '@apollo/client';
> ```

Tää tiedosto vois olla selkeemmin nimetty ja ehkä jakaa useempaan eri tiedostoon `types` alikansioon.
___
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/createStopVersionCommon.ts` line 30 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk0rm5-4v6C5J02-t7:-ODk0rm5-4v6C5J02-t8:b-hecuko) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/createStopVersionCommon.ts#L30)):*
> ```XML
> >;
> 
> export const GQL_UPSERT_STOP_PLACE_VERSION = gql`
> ```

Väittäsin että tää on väärässä tiedostossa. Samaan paikkaan ku missää tota kyselyä oikeesti käytetään.
___
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/createStopVersionCommon.ts` line 42 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk1Ovx4E0kuglZc1Td:-ODk1Ovx4E0kuglZc1Te:b4sisme) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/createStopVersionCommon.ts#L42)):*
> ```XML
> export type StopPlaceKeyValues = {
>   validityStart: DateTime;
>   validityEnd: DateTime<true> | undefined;
> ```

`<true>` on turha tossa end kentän tyypissä
___
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/createStopVersionCommon.ts` line 55 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk1nIACsftcCMEnJw4:-ODk1nIACsftcCMEnJw5:b-o1aynz) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/createStopVersionCommon.ts#L55)):*
> ```XML
> };
> 
> export type StopPointVersionInputFull = ScheduledStopPointSetInput & {
> ```

Miks tässä on käytännössä ylikirjotettu jokanen kenttä tosta tyypistä?
___
*[`ui/src/components/stop-registry/stops/stop-details/CalendarButton.tsx` line 2 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODjzDRu5h32owN5mcrO:-ODjzDRu5h32owN5mcrP:blux93b) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/CalendarButton.tsx#L2)):*
> ```XML
> export type CalendarButtonProps = {
>   name: string;
> ```

readonly
___
*[`ui/src/components/stop-registry/stops/stop-details/CalendarButton.tsx` line 6 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODjzEVC4r5Dhx0ZFjxf:-ODjzEVC4r5Dhx0ZFjxg:bt4w7jq) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/CalendarButton.tsx#L6)):*
> ```XML
> };
> 
> export const CalendarButton = (props: CalendarButtonProps) => {
> ```

`CalendarButton: FC<CalendarButtonProps> = ({ name, onClick }) => {...`
___
*[`ui/src/components/stop-registry/stops/stop-details/CalendarButton.tsx` line 10 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODjzOG9DCLFE9rHE-O1:-ODjzOG9DCLFE9rHE-O2:b-263su1) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/CalendarButton.tsx#L10)):*
> ```XML
>   return (
>     <div className="ml-3 rounded-[3px] border border-light-grey bg-w [...]

2024-12-12 06:52 UTC, villepynttari commented
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/createStopVersionCommon.ts` line 55 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk1nIACsftcCMEnJw4:-ODtbdL7BBfDpa8APzKP:b-6a803i) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/createStopVersionCommon.ts#L55)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Miks tässä on käytännössä ylikirjotettu jokanen kenttä tosta tyypistä?
</blockquote></details>

Nää on vähän kuin muistilappuna sille mitä ollaan varsinaisesti tallentamassa, että pysyin jotenkin kärryillä, kun vertailin olemassaolevia kilkkeitä. Lisäksi ylikirjoittaa joitain nullableja pakollisiksi. Ei ole välttämättä tarpeellisia lopullisessa versiossa.


<!-- Sent from Reviewable.io -->

2024-12-12 06:55 UTC, villepynttari commented
*[`ui/src/components/forms/common/customZodSchemas.ts` line 98 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODjz2lUDsYOXlV8oJCs:-ODtdWZn7_aJyDElzlEu:bta3k3f) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/forms/common/customZodSchemas.ts#L98)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Nyt on jännää koodia. En keksi pelkästään tätä lukemalla, että mitä tässä oln varsinaisesti yritetty saavuttaa :thinking:
</blockquote></details>

Liittyi jotenkin priorityyn, mutta löysinkin sille valmiin toteutuksen. Ei ole tosiaan käytössä ja vaan unohtui tänne.


<!-- Sent from Reviewable.io -->

2024-12-12 07:00 UTC, villepynttari commented
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/stopPlaceToInputMapperUtils.ts` line 27 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk2u26BUTepYtU3JJK:-ODteLl_17xhf4NdeN4A:b7slxz8) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/stopPlaceToInputMapperUtils.ts#L27)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Tarviiks näitä yksittäisiä apufunktioita exportata erikseen? Kutsutaanko näitä erikseen tiedoston ulkopuolelta?
</blockquote></details>

Ei kutsuta. Pidin vaan näitä vielä ns. liikuteltavassa muodossa, kun on toteutus vähän kokeilun asteella.


<!-- Sent from Reviewable.io -->

2024-12-12 07:04 UTC, villepynttari commented
*[`ui/src/components/stop-registry/stops/stop-details/stop-version/stopPlaceToInputMapperUtils.ts` line 112 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODk3CrF3ny95XReveir:-ODtf7654mHmM2KNmQDW:b9jnt3g) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/1f262bceb75c48116047cf4dbc01e0a3bada1cda/ui/src/components/stop-registry/stops/stop-details/stop-version/stopPlaceToInputMapperUtils.ts#L112)):*
<details><summary><i>Previously, Huulivoide (Jesse Jaara) wrote…</i></summary><blockquote>

Parametrit on vähän hassussa järjestyksessä, ja oli kiva jos funktio ottaa aina oletuksena readonlyna datan sisään.

ja voisko tän korvata kokonaan jo olemassa olevalla vastaavalla toteutuksella. En muista tarkalleen etät missä se on määritelty ja millä nimellä, mutta sitä on muissa pysäkin tallennuksissa käytetty.
</blockquote></details>

Varmaan voi. En vaan löytänyt valmista toteutusta äkkiseltään.


<!-- Sent from Reviewable.io -->

2024-12-12 12:48 UTC, Huulivoide requested changes
> Reviewed 1 of 14 files at r1, 4 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960)* status: 8 of 17 files reviewed, 26 unresolved discussions (waiting on @villepynttari)

___
*[`cypress/e2e/stop-registry/stopDetails.cy.ts` line 2292 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-ui/960#-ODutHx68xwsehaYClgU:-ODutHx68xwsehaYClgV:b5po3ve) ([raw file](https://github.com/HSLdevcom/jore4-ui/blob/8ab1bb9f21192c43ff6c866ceb4088385f17833d/cypress/e2e/stop-registry/stopDetails.cy.ts#L2292)):*
> ```XML
>   describe('Stop version', () => {
>     function initForm() {
>       return new CreateStopVersionFormWrapper();
> ```

Tää on vähän tarpeeton luoda jokasessa testissä uudelleen. Vois olla vaan yks initialisointi, ku ei tuossa luokassa kuitenkaan mitään tilaa ole.


<!-- Sent from Reviewable.io -->

2025-02-04 09:39 UTC, closed without merging